### ISSUE TITLE
Why use GCD queue but not recursive lock to protect sqlite operations?

### ISSUE THREAD

**Issue by alexlee002** [groue/GRDB.swift#1002]
I got 2 questions while reading the source code of GRDB:

1,  GRDB using SerializedDatabase in queue or pool,  but why it still need SchecdulingWatchdog?
2, Why using GCD queue to avoid a sqlite handler is used by multi-thread at a same time,  but why not using recursive lock?

**Comment by groue** [comment]
Hello @alexlee002,

GRDB intentionally restricts the ways to use a database, in order to provide its [concurrency guarantees](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency). Those guarantees [solve problems](https://github.com/groue/GRDB.swift/blob/master/Documentation/WhyAdoptGRDB.md) commonly found in other database libraries. Those guarantees make it possible to build useful features such as [Database Observation](https://github.com/groue/GRDB.swift/blob/master/README.md#database-changes-observation) that you do not find in other SQLite wrappers.

The first restriction is simple: one must access the database inside a database access method. The main ones are `read` or `write`. If you access the database outside of a database access method, the concurrency guarantees would become void. This is a programmer error, and the SchedulingWatchdog makes sure it triggers a fatal error:

```swift
// NOT ALLOWED: using the database outside of a database access method
let db = try dbQueue.read { db in return db }
let players = try Player.fetchAll(db)
```

The GCD queue could indeed be replaced with a lock. But DispatchQueue comes with `async` which is just too handy.

A recursive lock is out of question, and this brings us to the second restriction: one must not nest calls to database access methods:

```swift
// NOT ALLOWED: nesting calls to database access methods
try dbQueue.write { db in
    try dbQueue.write { db in
        ...
    }
}
```

The consequence of this restriction is easier reading and understanding of code that uses the database. It forces developers to write two kinds of functions:

1. Non-composable functions that perform transactions:

    ```swift
    func transfer(amount: Int, from source: Account, to destination: Account) throws {
        try dbQueue.write { db in
            guard try balance(db, source) >= amount else {
                throw AccountError.insufficientFunds
            }
            try addLine(db, amount: -amount, to: source)
            try addLine(db, amount: amount, to: destination)
        }
    }
    ```

    Those functions are typically used by other components of the application.

2. Composable functions that access the database:

    ```swift
    func balance(_ db: Database, _ account: Account) throws -> Int { ... }
    func addLine(_ db: Database, amount: Int, to account: Account) throws { ... }
    ```

    Many such functions are built-in GRDB: `insert`, `fetchAll`, etc. Apps can define their own.

**Comment by alexlee002** [comment]
Hi @groue , thanks very much!

I'm going to optimize my SQLite wrapper,  for some reason I can not migrate to GRDB (too much business code need to be modified).  I also read the code of another framework: WCDB, do you hear about it?

```swift
// NOT ALLOWED: using the database outside of a database access method
let db = try dbQueue.read { db in return db }
let players = try Player.fetchAll(db)
```
YES, this is great!  I need this restriction.

But the others, I'm not sure if I really need them.  I need to think more time...

Thanks again!

**Comment by groue** [comment]
I could not find an English version of the WCDB documentation, so no, I could not learn much about WCDB. I'm sure you'll write a marvelous application with it! 👍
