### ISSUE TITLE
dbPool.unsafeRead immediately after a dbPool.writeWithoutTransaction does not work at times

### ISSUE THREAD

**Issue by guidedways** [groue/GRDB.swift#1017]
### What did you do?

I've got the following configuration:

```
    let dbPool = try DatabasePool(path: "")
    
    // I wrote a small test to spawn off 100 or so writes / reads simultaneously:
    
    for 0..<100 {
      DispatchQueue.global().async {
        // I get the same result with dbPool.write
        try dbPool.writeWithoutTransaction { db in
          try db.execute("INSERT INTO ....")
        }
        
        try dbPool.unsafeRead { db in
          // select the same record inserted above
          try db.execute("SELECT ...")
        }
      }
    }
```
After about 12 to 20 or so iterations, the `unsafeRead` does not seem to find the entry inserted directly above. I tried with different configurations but I get the same result.

I then tried this with a `DatabaseQueue` instead, and that seems to work fine every time. I need to use a DatabasePool for concurrent reads (also since I need to share the database with other app extensions). What am I doing wrong?

### What did you expect to happen?

I expected to get the record inserted above. Both statements are run serially and any deferred transaction should (I assume) commit by the time it's read.

### What happened instead?

Random failures.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.8.0
**Installation method:** SPM
**Xcode version:** 12.5
**Swift version:** 5.4
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.4

**Comment by groue** [comment]
Hello @guidedways,

I do not see anything wrong in your setup. You are looking at SQLite concurrency straight in the eyes.

> Both statements are run serially

But SQLite does not know it. On top of that, *other statements* run concurrently.

DatabasePool uses one SQLite connection for all writes, and a pool of connection for reads. Your sample code (which I can't run) bombs a single database file with various statements from various connections, and happens to exercise SQLite's implementation of ACID and isolation levels. 

I will not investigate further, since your use of `writeWithoutTransaction` and `unsafeRead` guarantee the most genuine use of SQLite. You are describing a SQLite behavior, not a GRDB behavior.

For more information:

- See the [Guarantees and Rules](https://github.com/groue/GRDB.swift/blob/master/README.md#guarantees-and-rules) chapter, and especially the Rule 2 (which aims at avoiding your surprise).
- See https://sqlite.org/wal.html

**Comment by guidedways** [comment]
@groue thank you! Yes you're right, this is an SQLite issue. Is there a way to set WAL mode with `DatabaseQueue`?

**Comment by groue** [comment]
This is not an issue. This is a normal SQLite behavior.

If your application does not deal with it well, it is because your application code does not follow the rules I linked to in the above comment.

I feel a strong [XY problem](https://xyproblem.info) in this whole Github issue.

> Is there a way to set WAL mode with `DatabaseQueue`?

```swift
try dbQueue.writeWithoutTransaction { db in
    let journalMode = try String.fetchOne(db, sql: "PRAGMA journal_mode = WAL")
    guard journalMode == "wal" else {
        throw DatabaseError(message: "Could not activate WAL mode")
    }
}
```
