### ISSUE TITLE
Suggestion: provide a stable ABI for GRDB

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#1027]
### What did you do?

I upgraded Xcode.

### What did you expect to happen?

I expected my projects that use my binary build of the GRDB framework to compile.

### What happened instead?

Xcode complains that GRDB was built with an older version of the Swift compiler and needs to be rebuilt.

This is a common annoyance with Swift-based binary frameworks. I think the solution basically comes down to updating GRDB so that it builds with the "Build Libraries for Distribution" Xcode build option. If only it were that easy...

When I tried building GRDB with that option, I got stumped by a compiler error—probably the first of many. The fact is, writing code that allows for a stable ABI is not entirely trivial. This mode introduces some additional restrictions in Swift coding semantics. For example, ABI-stable Swift structs are more restrictive in their implementation.

In fact, I wouldn't even say that the idea of any or every Swift framework providing a stable ABI should be considered desirable for its own sake. For example, some Swift frameworks such as the gRPC integration have no intention of providing ABI stability because (I presume) it's based on code generation. However, I do think ABI stability for GRDB is worthwhile and desirable because

 * GRDB provides API stability via the semantic versioning paradigm
 * adding GRDB as a Swift source package implies compiling it every time you clean your project's build directory, and building GRDB is slow
 * other things I'm not thinking of right now

What do you think? Is this a worthwhile goal?

Thank you as always.

### Environment

**GRDB flavor(s):** GRDB with custom SQLite build
**GRDB version:** 5.8.0
**Installation method:** manual framework built with Xcode
**Xcode version:** 13.0 beta 4
**Swift version:** 5.5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.5

**Comment by Dark403969** [comment]
#1026

**Comment by groue** [comment]
Hello @mallman!

This question was already asked once: #964 (with multiple points of view).

To sum up:

- ABI stability is **much harder** than API stability.
- I support removing the compiler errors when building with BUILD_LIBRARY_FOR_DISTRIBUTION, though, because it will help some people caching and reusing GRDB binaries. #979 was a naive (and failed) attempt at removing those errors. Someone will have to audit existing ABI annotations, which I added without much thought, blindly aiming at runtime performance through generics specialization and inlining. This is messy, and I apologize because this topic isn't as easy to deal with as I wish it would.

**Comment by mallman** [comment]
I agree ABI stability is stronger than API stability, and verifying ABI compatibility across minor versions can be difficult. I don't know the state of the art for tools that could do this for Swift. The Java ecosystem has a build tool for this—the name escapes me at the moment—but it's far from perfect and has its own maintenance burden.

The more I've looked into the subject the more I feel I should just tolerate the recompilation issue. As mentioned above, I use my own GRDB binary framework, so I only recompile when I upgrade Xcode. Personally, it's not so much a problem as to be worth the effort and ongoing maintenance.

Thanks for considering!

**Comment by groue** [comment]
> I agree ABI stability is stronger than API stability, and verifying ABI compatibility across minor versions can be difficult. I don't know the state of the art for tools that could do this for Swift. The Java ecosystem has a build tool for this—the name escapes me at the moment—but it's far from perfect and has its own maintenance burden.

I happen to read in the [Swift Forums](https://forums.swift.org) about some tools used by the developers of the standard library, so I'd say we're not completely naked.

I also read about their great difficulties concerning evolution. Some very cool API-compatible changes are dismissed just because they would break ABI. Even with their serious training, and their rock-solid confidence about the design of the code that they ship, they put themselves into corners. Tools that prevent ABI breakage are a thing, but it is *designing a library that can evolve in such a mine field* that is really tough.

ABI stability would basically kill the evolution of GRDB.
