### ISSUE TITLE
Suggestion: Best practices to perform frequent read-write and upload to server

### ISSUE THREAD

**Issue by jbatra-umeey** [groue/GRDB.swift#1028]
### What did you do?

I have a requirement wherein I am supposed to do the following steps
1. After every 5mins write data to DB and then read it in slots of 30 (Repeat the read until all data has been synced)
2. Post this data via API, if Api is successfully deleting the entries from DB  
3. Repeat this activity after every 5 mins

Below is the approach I am planning to adopt

- Follow the steps mentioned `Start using the database in four easy steps` for initial integration
- Include https://github.com/groue/GRDB.swift#the-concurrentread-method to achieve step 1
- Post read, call the API to sync the fetched data, and then based on success, delete the ids from DB using https://github.com/groue/GRDB.swift#persistence-methods

Now, I have the following queries:

1. Is there a need to synchronize the API calls with DB queues or it can be run outside DB queues. Something like below

 Approach 1 : // Synchronized with read:
```
try dbQueue.read { db in
    let data = try JSON.fetchAll(db)
<<API call >>
}
```

 Approach 2 : // Outside Read queue:
```
try dbQueue.read { db in
    let data = try JSON.fetchAll(db)
}

<<API call >>
```

Will Approach 2 guarantee the read data to API call? 

2. Is there an option to bulk write the data in DB?. Perhaps, a way to achieve a bulk UPSERT would also be helpful
3. Can the delete call be added to the success of the network call?
4. How should I manage DB close operation ?
5. Can I create a singleton class something like `DBManager` as mentioned https://github.com/groue/GRDB.swift/issues/981#issue-907599658 

### What did you expect to happen?

Seamlessly perform write, read and delete operations without blocking the thread  and API calls

### Environment

**GRDB flavor(s):**  : GRDB
**GRDB version:** :  v5.8.0
**Installation method:** : Manual
**Xcode version:** : 12.5.1
**Swift version:** :  5.4.2
**Platform(s) running GRDB:** : iOS
**macOS version running Xcode:** : MacOS Big Sur (11.4)

Any examples from the production App will be helpful. Thanks in advance

**Comment by groue** [comment]
Hello @jbatra-umeey,

> Best practices to perform frequent read-write and upload to server

This question is not related to GRDB. You will figure out your favorite server syncing solution.

> Seamlessly perform write, read and delete operations without blocking the thread and API calls

The threading behavior of GRDB is fully described in the [Concurrency](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency) documentation chapter.

Your other questions:

1. It is not recommended to perform a blocking network call from a database access method like `read`, since it will prevent other threads from accessing the database.
2. For bulk inserts, write a loop. For bulk updates, see [Update Requests](https://github.com/groue/GRDB.swift/blob/master/README.md#update-requests). For UPSERT, see #315
3. You can do whatever you want.
4. There is a [FAQ](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-close-a-database-connection) for that
5. Of course you can. See [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md#how-to-design-database-managers) and the demo apps for some advice and sample code.

On a general note:

- It is considered good etiquette to search documentation and existing issues before opening a new one.
- GRDB support is free, but answering general programming questions about application or algorithm design is not. We can setup a regular business relationship and discuss pricing if you want.
