### ISSUE TITLE
defaults(to: make no sense

### ISSUE THREAD

**Issue by karthuszY** [groue/GRDB.swift#1030]
### What did you do?
`table.column("isCollected", .boolean).defaults(to: false)`

### What did you expect to happen?
isCollected should be false

### What happened instead?
![image](https://user-images.githubusercontent.com/13864988/129327102-35b145ba-6a8f-41dc-af02-55ad97816e20.png)

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:** (CocoaPods, SPM, manual?)
**Xcode version:** 12.4
**Swift version:** 5.0
**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
**macOS version running Xcode:** Big Sur 11.1

**Comment by groue** [comment]
Hello @karthuszY,

Default values do not prevent nulls. They just provide a default value when a value is not specified. Since NULLs are present in the database, something did insert NULLs:

```sql
-- inserts isCollected: default 
INSERT INTO player (name) VALUES ('Arthur');
-- inserts isCollected: true
INSERT INTO player (name, isCollected) VALUES ('Barbara', 1);
-- inserts isCollected: NULL
INSERT INTO player (name, isCollected) VALUES ('Craig', NULL);
```

It is rare that boolean columns are nullable, because you then have three values to deal with (true, false, and null). Most boolean columns are specified as `table.column("isCollected", .boolean).notNull`, without any default. This forces your app to insert the boolean value it intends to read later.
