### ISSUE TITLE
SqlCipher support for Swift PM

### ISSUE THREAD

**Issue by kmitj** [groue/GRDB.swift#1056]

**Comment by groue** [comment]
https://github.com/sqlcipher/sqlcipher/issues/371

**Comment by groue** [comment]
If you are looking for precise information, there's no better source than Apple documentation. https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files

**Comment by brunomunizaf** [comment]
I did and as it states: "If you do not specify a protection level when creating a file, iOS applies the default protection level automatically." But I was able to get the .sqlite file from the simulator. I believe that's technically impossible on production (?)

**Comment by groue** [comment]
> But I was able to get the .sqlite file from the simulator

Last time I checked, data protection was not available on simulators. This is understandable, since it is implemented at a very low level of the file system.

You'll be able to see its effects on a device.

BTW, don't miss the dedicated GRDB documentation about it, especially the advice to protect a _directory_, not only the main database file: [Data Protection ](https://github.com/groue/GRDB.swift/blob/master/README.md#data-protection) (grr, it contains outdated links to Apple documentation 💀😬)
