### ISSUE TITLE
Question: Database schema

### ISSUE THREAD

**Issue by corysullivan** [groue/GRDB.swift#1071]
I have a table that contains calendar events, populated from various APIs, and each event includes an organizer and attendees. Should I create one standard table representing a Person that the event can reference for the organizer and attendees?

![First](https://user-images.githubusercontent.com/1440684/135458153-94b23f15-ebc5-4ffc-991e-5cd74b498652.png)

 or flatten the organizer into event properties (name, email) and have a table specifically for attendees?

![second](https://user-images.githubusercontent.com/1440684/135458197-9aa802fd-a3d1-4743-8fb0-a8d15b608ed4.png)

or maybe another method I haven't considered. Regardless, is it ok to create duplicates in the attendee's table? Otherwise, for each added/updated event, I will need to check if that attendee exists. At the end of the day, I want to query events and get the organizer and attendees. I'm not interested in identifying which events a particular person is attending.

```
public struct EventInfo {
    public let event: Event
    public let organizer: Organizer
    public let attendees: [Attendee]
}
```
 
What is the recommeded way to acheive this?

**Comment by groue** [comment]
Hello @corysullivan,

This question is a question about database design, not GRDB: it falls out of the scope of the free support provided here.

I recommend learning about database design in general, and maybe ask on StackOverflow, so that you can make an educated opinion.

Another option is to pick one schema and start your app with it, YOLO mode. Later, in a future version of your app, whenever you have a better understanding of what you need, and some design flaws start to appear, you'll be able to fix this schema. It is recommended to consider the schema of your database as something that *will* evolve anyway. So don't miss [Migrations](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md).
