### ISSUE TITLE
2 CTEs in the same request

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#1080]
### What did you do?

I'd like to fetch Groups with the last message sent and its members. I thought about doing 2 common table expressions but it didn't work for some reason.

```swift
struct Group {
  var groupId: Data
}

struct GroupInformation: TableRecord {
  var grou: Group
   var members: [GroupMember]
   var lastMessage: GroupMessage?
}
...

let lastMessageRequest = GroupMessage
    .annotated(with: max(GroupMessage.Column.timestamp))
    .group(GroupMessage.Column.groupId)

let lastMessageCTE = CommonTableExpression<GroupMessage>(
    named: "lastMessage",
    request: lastMessageRequest
)

let lastMessage = Group.association(to: lastMessageCTE) { group, lastMessage in
    lastMessage[GroupMessage.Column.groupId] == group[Group.Column.groupId]
}.order(GroupMessage.Column.timestamp.desc)

let membersRequest = GroupMember
    .annotated(with: GroupMember.Column.userId)
    .group(GroupMember.Column.groupId)

let membersCTE = CommonTableExpression<GroupMember>(
    named: "members",
    request: membersRequest
)

let members = Group.association(to: membersCTE) { group, member in
   member[GroupMember.Column.groupId] == group[Group.Column.groupId]
}

return Group.with(lastMessageCTE)
    .including(optional: lastMessage)
    .with(membersCTE)
    .including(required: members)
    .asRequest(of: Self.self)

try db.create(table: Group.databaseTableName, ifNotExists: true) { table in
    table.autoIncrementedPrimaryKey(Group.Column.id.rawValue, onConflict: .replace)
    table.column(Group.Column.groupId.rawValue, .blob)
}

try db.create(table: GroupMember.databaseTableName, ifNotExists: true) { table in
    table.autoIncrementedPrimaryKey(GroupMember.Column.id.rawValue, onConflict: .replace)
    table.column(GroupMember.Column.groupId.rawValue, .blob).notNull()
    table.column(GroupMember.Column.userId.rawValue, .blob).notNull()
}

try db.create(table: GroupMessage.databaseTableName, ifNotExists: true) { table in
    table.autoIncrementedPrimaryKey(GroupMessage.Column.id.rawValue, onConflict: .replace)
    table.column(GroupMessage.Column.groupId.rawValue, .blob).notNull()
    table.column(GroupMessage.Column.payload.rawValue, .blob).notNull()
    table.column(GroupMessage.Column.timestamp.rawValue, .integer).notNull()
}

```

### What did you expect to happen?

the request would bring a list of all groupmembers w/ the id for each group

### What happened instead?

Only the latest messages come, nothing comes on the members array.

**Comment by groue** [comment]
Yes, define the `Group.members` hasMany association. Declare a foreign key in the database between the GroupMember table to the Group table, so that the association understands what's going on. The association documentation describes this in details.

And of course don't remove `members` GroupInformation if you want them! Again this is covered by the doc.

https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md

**Comment by brunomunizaf** [comment]
I figured out what is going on, I'm observing changes on the Group table, creating a Group triggers the observation and then it pulls the members but there's none yet and since its a non-optional property on my request, it crashes. I have to find a way to save both group and members in the same transaction in order to avoid this

**Comment by groue** [comment]
> `Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "members", intValue: nil)`

The `Group.members` association feeds from `GroupMember`. By default, GRDB, when decoding `Group...including(all: Group.members)...`, looks for a property which as the same name as the database table for `GroupMembers`.

This default can be overridden by specifying the key that an association should be decoded into.

Since you want to decode the `members` property of `GroupChatInfo, change:

```diff
-static let members = hasMany(GroupMember.self)
+static let members = hasMany(GroupMember.self).forKey("members")
```
