### ISSUE TITLE
Feature Request: Single Cross-Platform Target

### ISSUE THREAD

**Issue by WarWithinMe** [groue/GRDB.swift#1105]
When a workspace contains both iOS and macOS projects and uses GRDB, Xcode 13 will warn _Multiple targets match implicit dependency for product reference 'GRDB.framework'. Consider adding an explicit dependency on the intended target to resolve this ambiguity_

This can be solved by keeping only one build target in GRDB project and setting its `Supported Platforms` to `Any Platform` and `Allow Multi-Platform Builds` to `Yes`, as demonstrated by the screenshot below. **However, this feature requires XCode 13**

![image](https://user-images.githubusercontent.com/567110/144556910-a29f8c84-6b17-435e-81bc-29b67e158d53.png)

**Comment by groue** [comment]
Hello @WarWithinMe,

Thanks for telling your experience of a user who installs GRDB by dragging the GRDB project in your own project.

I'm not sure the modifications can be applied to the GRDB repo itself, since GRDB 5 supports Xcode version older than Xcode 13. But this is clearly something that we'll have to remember when the minimum Xcode version eventually reaches Xcode 13 👍

**Comment by groue** [comment]
No news is good news: closing.

**Comment by groue** [comment]
Hello @WarWithinMe,

GRDB now uses cross-platform targets in the `development` branch (this change will soon ship in GRDB 6 beta 4). You can give it a try!
