### ISSUE TITLE
Question: Is it possible to auto create tables from records?

### ISSUE THREAD

**Issue by hyouuu** [groue/GRDB.swift#1113]
Taking demo apps' `Player` struct as an example, it clearly defined each column and their type, so why can't we create tables automatically from a `PersistableRecord`? Looks like we need to manually create tables using literal names and specifying types, which seems unnecessary and prone to typos.

**Comment by groue** [comment]
Hello @hyouuu,

There are many frameworks out there, in many languages, that automatically create tables from the definition of their matching record type. So it is natural to think that this feature that can be expected from a database library.

But if you look better, you'll see many other frameworks out there, in many languages, which DO NOT automatically create tables from the definition of their matching record type. Instead they often provide a solution named "migrations". [See how migrations work in GRDB](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md).

The reason why GRDB prefers migrations over automatic table creation is that this library fosters the robustness of the database schema. It is impossible to infer, from a plain Swift type, the integrity checks and relational constraints that your database needs. It is also impossible to know if your `Date` should be stored as a numerical timestamp, or a ISO-8601 string, for that matter. Or if you want auto-incremented ids or not. Or the indexes you need. Or the foreign keys that support [Associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md).

> Looks like we need to manually create tables using literal names and specifying types, which seems unnecessary

Yes, you do need to create table using literal names and specifying types. It is necessary for people who care about their database schema, and plan early for the future evolutions of this schema. See the first chapter "Trust SQLite More Than Yourself" in [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md).

> and prone to typos.

If you do not ignore database errors, you'll quickly spot typos. Typos do happen indeed, so don't miss the [eraseDatabaseOnSchemaChange](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md#the-erasedatabaseonschemachange-option) option of DatabaseMigrator: it really speeds up your development when the database schema is still in flux.

**Comment by hyouuu** [comment]
Thanks for the quick and thorough response - it makes a lot of sense!  Still though, I think auto creating table would cover 80% of the use cases whereas users who care more than that could always create their tables in the current way. Regarding the counter points you had:
1. Core Data's `xcdatamodeld` is basically a table & data struct mix, and you don't need to define them in 2 separate places.
2. `Date` format standards are quite limited, and e.g. `Vapor`'s `Fluent` has a few enums you can specify using an annotation (https://docs.vapor.codes/4.0/fluent/model/#timestamp). Although their annotation requires repeated column names and introduces more complexity to the domain, it still feels less repetitive than creating the table manually elsewhere.
3. Similarly, auto-incremented id is a very specific thing that can be added as an option.
4. Indexes can also be specified with annotations in both `Fluent` and `Realm`(https://docs.mongodb.com/realm/sdk/swift/examples/define-a-realm-object-model/)

So the point is that, with the help of annotations, we still "Trust SQLite More Than Yourself", plus utilizing Swift more than using literals.

I'm not insisting on it, as the effort to create tables is low; it's just my gut feeling using GRDB the first time tells me that it shouldn't require writing the almost same thing in 2 different places, and want to help make GRDB even better ;)

**Comment by groue** [comment]
Thanks for challenging my first answer 😉

> 1. Core Data's `xcdatamodeld` is basically a table & data struct mix, and you don't need to define them in 2 separate places.

This is true. There is a cost, though: NSManagedObject and Objc runtime. This leads to a so-so Swift integration, and [performances that GRDB can improve in a significant way](https://github.com/groue/GRDB.swift/wiki/Performance).

Although, Core Data schema is not SQL schema: it is much more rich, which allows it to generate "well-typed" properties in managed objects. For the record, you can look at https://github.com/gotev/GRDB-Record-Generator. Also, generating both GRDB records and schema from an `xcdatamodeld` is an option that has never been explored, and could reveal fruitful. It's just not on my personal wishlist.

> 2. `Date` format standards are quite limited, and e.g. `Vapor`'s `Fluent` has a few enums you can specify using an annotation (https://docs.vapor.codes/4.0/fluent/model/#timestamp). Although their annotation requires repeated column names and introduces more complexity to the domain, it still feels less repetitive than creating the table manually elsewhere.
> 3. Similarly, auto-incremented id is a very specific thing that can be added as an option.
> 4. Indexes can also be specified with annotations in both `Fluent` and `Realm`(https://docs.mongodb.com/realm/sdk/swift/examples/define-a-realm-object-model/)

All those options have to be specified somewhere. And in GRDB, they are specified in the schema, because they are not specified in the record type.

The way users expect those options to be declared in a type are, as you say, annotations (property wrappers in Swift).

Well, GRDB records do not use any base class or property wrapper, and this is an achievement I'm quite happy with, and quite firmly intend to keep alive.

- See https://github.com/groue/GRDB.swift/issues/1081#issuecomment-948286846 for a discussion of some of the benefits of not having any base class or property wrapper.
- See https://github.com/groue/GRDB.swift/issues/1084#issuecomment-948880910 for a discussion of the undesired side effects of embedding associated records (with or without property wrappers), like Fluent does.
- See https://github.com/groue/GRDB.swift/issues/1084#issuecomment-948966623 for one reason why property wrappers, which the language _fundamentally ties to instances_, are unable to provide type-level information.

[Codable Records](https://github.com/groue/GRDB.swift/blob/master/README.md#codable-records) allow some customization, though.

> So the point is that, with the help of annotations, we still "Trust SQLite More Than Yourself", plus utilizing Swift more than using literals.

Did I mention that if _creating_ a table is a thing, _altering_ one is much less easy to do _reliably_, especially when some users declare indexes or SQL triggers that can not be trivially recreated after a schema change?

> I'm not insisting on it, as the effort to create tables is low; it's just my gut feeling using GRDB the first time tells me that it shouldn't require writing the almost same thing in 2 different places, and want to help make GRDB even better ;)

Thank you for your efforts, they are really well appreciated. This lib has very frequently been influenced by messages like yours 🙂 

I hope I was able to explain that the choice of GRDB to use migrations serves well users who don't know, don't care, don't have time to spend on crafting their schema, as well as experts who need a sharp tool. The first ones have to spend a little energy ("low effort", as you say), the second ones just do their job and move on.

This looks like a good balance to me, considering that auto-generated schemas require _a lot of efforts_, for _debatable benefits_.

**Comment by hyouuu** [comment]
Interesting discussions in #1084, and it's quite recent! I can definitely see that auto-generated schemas require a lot of efforts, and is hard to make it cover every use case correctly.

Case closed - thanks again for the in-depth explanation and this issue should also serve for others who search for this ;)

**Comment by groue** [comment]
> this issue should also serve for others who search for this ;)

Exactly 👍 There are few opportunities to explain design choices, so thank for that. Only this can help other users sharpen their arguments, and maybe come up with new ideas that we can turn into apis.

**Comment by alexlee002** [comment]
> I think auto creating table would cover 80% of the use cases

I agree with you! I think it is better to do it in a `semi-automatic` way.   e.g.:

```swift
protocol TableRecordMappable {
var customPropertyColumnMappings: [String /* CodingKey*/: String /* Column Name*/]? { get }
var customPropertyColumnDefinitions: [String /* CodingKey*/:   ColumnInfo]? { get }
}
