### ISSUE TITLE
Can we use arguments dictionary while inserting using db.execute(:sql:arguments)

### ISSUE THREAD

**Issue by SNNafi** [groue/GRDB.swift#1116]
Is it valid to use   VALUES (:id, :title, :type, :color) `, Please check the below code for details

```

                    try db.execute(sql: """
                     IF EXISTS(SELECT * FROM folders WHERE id = :id)
                        UPDATE folders SET title= :title, color = :color, type = :type WHERE id= :id
                     ELSE
                       INSERT INTO folders (id, title, type, color)
                       VALUES (:id, :title, :type, :color) //  is this valid to use ?

                    """, arguments: [
                        "id": $0.uuid, "title": $0.title, "type": $0.type.rawValue,
                        "color": $0.color
                    ])


```

**Comment by groue** [comment]
Hello @SNNafi,

You can use dictionary as query arguments, for sure:

```swift
try db.execute(
    sql: "UPDATE player SET name = :name WHERE id = :id",
    arguments: ["name": name, "id": id])
```

You can even reuse an argument key such as `:id` several times in one SQL query, if this was your question.

Now... `IF ... ELSE ...` is not valid SQL with SQLite.

Maybe you are looking for:

```swift
let arguments: StatementArguments = [
    "id": $0.uuid,
    "title": $0.title,
    "type": $0.type.rawValue,
    "color": $0.color,
]
if try Bool.fetchOne(db, sql: """
    SELECT EXISTS(SELECT * FROM folders WHERE id = :id)
    """, arguments: arguments)!
{
    try db.execute(sql: """
        UPDATE folders SET title= :title, color = :color, type = :type WHERE id= :id
        """, arguments: arguments)
} else {
    try db.execute(sql: """
        INSERT INTO folders (id, title, type, color) VALUES (:id, :title, :type, :color)
        """, arguments: arguments)
}
```

Note that GRDB [Record Types](https://github.com/groue/GRDB.swift/blob/master/README.md#records) could help a lot, since this whole code could be written as:

```swift
let folder = Folder(id: $0.id, title: $0.title, type: $0.type, color: $0.color)
try folder.save(db)
```

See `save(_:)` method is one of the [Persistence Methods](https://github.com/groue/GRDB.swift/blob/master/README.md#persistence-methods).

**Comment by SNNafi** [comment]
Thanks for the detailed answer. You are doing a great job I must say. I can't think of anything other than this awesome library when I need to work with SQLite in iOS.

**Comment by groue** [comment]
Thank you @SNNafi ❤️, this goes straight to my heart, and it's a joy to volunteer 😊
