### ISSUE TITLE
Would you consider dual-tagging GRDB releases until SPM supports your preferred tag format?

### ISSUE THREAD

**Issue by jackpal** [groue/GRDB.swift#1125]
As I understand it, Swift Package Manager requires tags to be in the format 1.0.0 (without any prefix), while GRDB strongly prefers the format v1.0.0.

I understand that you've filed a bug requesting that SPM be extended to support the GRDB project's preferred tag format.

But in the meantime, would you be willing to double-tag your releases, so that each release has both a v tag and a SPM-compatible tag?

As things currently stand, it's hard for people to write Swift Package Manager packages that depend on GRDB.

**Comment by groue** [comment]
Hello @jackpal,

> As things currently stand, it's hard for people to write Swift Package Manager packages that depend on GRDB.

I assume this issue is related to #1115. If it is not, please better describe your concern.

> Swift Package Manager requires tags to be in the format 1.0.0 (without any prefix)

This is not true. You can build an app or a package that depends on the GRDB SPM package today. SPM is one of the supported, documented, and tested installation methods of GRDB, since version 0.106.0 in April 2017.

> But in the meantime, would you be willing to double-tag your releases, so that each release has both a v tag and a SPM-compatible tag?

I know that SPM does not support dually tagged packages. I one mistakenly published a `3.0.0` tag without prefix, and this completely broke SPM support (#368). Admittedly, maybe this is different now.

> I understand that you've filed a bug requesting that SPM be extended to support the GRDB project's preferred tag format.

This is not a "preferred" tag format.

`v`-prefixed tags are a widely used convention, which predates SPM by several years. It is explicitly mentioned in https://semver.org:

> Is “v1.2.3” a semantic version?
> 
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

Finally, even when Apple eventually fixes this bug in the Swift Playgrounds on iPad application, this won't allow you to use GRDB there until system modules are supported (https://twitter.com/damienpetrilli/status/1472144736983134211).

All in all, I don't see any reason to do anything in the GRDB repo at the present time.

Let's wait for the Apple/SPM teams to fix their bugs and build the features requested by the community. You may want to let them know and express your wishes at https://feedbackassistant.apple.com

**Comment by jackpal** [comment]
Thanks for explaining! Seems like a tough situation.

My request is motivated by trying to create a Swift **library** package that depends upon GRDB. I guess #1115 is very similar. It's about an *executable* package, but the root cause is probably the same.

By the way, could you explain why GRDB is using "system" for it's C target? Shouldn't it be possible to have a C target without using "system"? Is "system" required to work around some other issue?

**Comment by JayToltTech** [comment]
FYI, failed to create a SPM library which has a dependency on GRDB due to this semver issue:

<img width="407" alt="Screen Shot 2022-01-05 at 8 12 58 AM" src="https://user-images.githubusercontent.com/69092530/148250688-fa0a95f3-1eaf-413d-8d51-ca5c3a2d8f34.png">

import PackageDescription

let package = Package(
    name: "...",
    products: [
        .library(
            name: "...",
            targets: ["...","..."]),
    ],
    dependencies: [
        .package(url: "https://github.com/stephencelis/SQLite.swift.git", from: "0.13.1"),
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "v5.17.0")
    ],
    targets: [
        .target(
            name: "...",
            dependencies: [
                .product(name: "SQLite", package: "SQLite.swift"),
                .product(name: "GRDB", package: "GRDB.swift")
            ])
    ]
)

**Comment by JayToltTech** [comment]
As a temporary workaround for anyone else who is caught in this thread, I forked/updated the tag so you don't have to:

.package(url: "https://github.com/JayToltTech/GRDB.swift.git", from: "5.17.0")

Note: temporary fork, not going to be updated, expect this to disappear once this issue is resolved one way or the other.

**Comment by jackpal** [comment]
Re "Failed to parse the manifest file" -- I think you can make this work by
using an alternate form of specifying the dependency on GRDB, which doesn't
use the "from:" argument. That has drawbacks like either requiring you to
stick with the head of a branch, or requiring you to pin to a specific
release, neither of which are appropriate for use as a library dependency.

**Comment by jackpal** [comment]
@JayToltTech - thanks for chiming in. I was wondering if doing a fork and tag rename would work.

I guess GRDB doesn't want to switch to SPM compatible tags because it would break any existing downstream dependencies that are depending on the old tags. (Presumably these are not SPM dependencies.)

GRDB could fork a GRDB-legacy-tags.git, then the update the mainline GRDB to use SPM-compatible tags. Any clients that depended on the legacy tag format would have to manually change their dependencies by changing which git repo they pulled from.

**Comment by JayToltTech** [comment]
Also, I didn't remove tag v5.17.0, I just added tag 5.17.0 pointing to the same commit and all worked fine with SPM, so #368 doesn't seem to be an issue at this point.

**Comment by groue** [comment]
> FYI, failed to create a SPM library which has a dependency on GRDB due to this semver issue with XCode Version 13.2.1 (13C100)

The issue is in your package file: `"v5.17.0"` is not a semantic version. You can fix your package as below:

```swift
import PackageDescription

let package = Package(
    ...
    dependencies: [
        .package(name: "GRDB", url: "https://github.com/groue/GRDB.swift.git", .upToNextMajor(from: "5.17.0")),
    ],
    targets: [
        .executableTarget(
            name: "...",
            dependencies: ["GRDB"]),
    ]
)
```

I deeply regret SPM is so immature, and that I have to answer this kind of issue. I'm not paid by Apple to provide support for their lacking environment. But please don't mismatch SPM issues and poor ergonomics with package issues.

Here the problem(s) are clearly on the SPM side. If you have concerns, do raise your voice at the [correct location](https://feedbackassistant.apple.com/), thank you.

**Comment by groue** [comment]
> I guess GRDB doesn't want to switch to SPM compatible tags because it would break every existing downstream dependency that is depending on the old tags. (Presumably these are not SPM dependencies.)

Yes. This is basic respect for the work of GRDB users.

> I see why GRDB is choosing to live with broken SPM support, in the hope that SPM is updated to support GRDB someday. But is sure is frustrating as someone trying to use GRDB as a dependency.

I fully agree. Frustrated users, please report their bugs to Apple. I can't do it for you.

**Comment by JayToltTech** [comment]
@groue reported to Apple as you requested.

From a pure practicality standpoint, assuming the responsible apple developer takes your viewpoint that "v*" is acceptable, it will be many months before XCode and the toolchain is released with a fix.  And as an impartial third party, I'm not certain your argument will be received as 'unquestionably correct'.  Is there a value in perhaps thinking that a Swift library should adapt itself to work with the Swift toolchain that Apple provides, as opposed to the other way around?

One of the reasons for the fork is that you can use that repo to test for other unintended consequences or breakages with the dual tag approach, if you were so inclined.

**Comment by groue** [comment]
You are not impartial, @JayToltTech, you are lost.

There is no problem with GRDB support for SPM with Xcode, as far as I know. [This](https://github.com/groue/GRDB.swift/issues/1125#issuecomment-1005866848) is not a problem, it is a buggy package definition that has to be [fixed](https://github.com/groue/GRDB.swift/issues/1125#issuecomment-1005913930).

There is a problem with Swift Playgrounds for iPad. This app is buggy. I won't create difficulties for other GRDB users who are working hard in order to satisfy the desire of a few people to fiddle with an immature application.

**Comment by JayToltTech** [comment]
Ouch!

Hey, thanks for all the great work here @groue, it's much appreciated.

I know open source development can feel like it's a lot of conflict and not a lot of gratitude.  Wasn't trying to be that person to you.

 - Jay

**Comment by groue** [comment]
Don't worry! I had to put an end to what looked like an endless argument 😅 For whoever read this discussion in the future, make sure you read the reasons why this request was rejected, all listed in the previous comments.

**Comment by JayToltTech** [comment]
FYI, in case you're waiting for Apple to change their mind @groue:

Jan 5, 2022 at 10:19 AM – FB9833870
SemVer issues with package dependencies in SPM

Recent Similar Reports:None
Resolution:Investigation complete - Works as currently designed

**Comment by groue** [comment]
Let me repeat the arguments I have above, @JayToltTech, because they still stand:

- "v..." tags are used by many other popular repositories https://github.com/realm/realm-swift/tags, https://github.com/kishikawakatsumi/KeychainAccess/tags (I let you search for other such repositories).
- "v..." tags are perfectly supported by all package managers, CocoaPods, SPM on the command line, SPM in Xcode, etc. Swift Playgrounds for iPad is the only environment that does not support such tags.
- "v..." tags are explicitly mentioned in https://semver.org
- SPM does not support dual tagging #368
- Retagging GRDB would break some existing user setups
- Even if GRDB was retagged, Swift Playgrounds for iPad would still be unable to deal with GRDB, due to its [lack of support for system modules](https://twitter.com/damienpetrilli/status/1472144736983134211).

Until each one of those arguments is addressed, I do not see any reason to change my decision, which is to keep tagging GRDB as I have always did.

Yet your energy is quite welcome! What about spending it on writing an answer to the Apple engineer, with all the reasons why Swift Playgrounds for iPad should support "v..." tags? _This_ would be a helpful contribution.

**Comment by groue** [comment]
Just in case it can help, [I reported the issue](https://forums.swift.org/t/support-for-v-prefixed-version-tags-in-spm-swift-playgrounds-for-ipad/54845) in the Swift forums as well.

**Comment by groue** [comment]
[It did help indeed](https://forums.swift.org/t/support-for-v-prefixed-version-tags-in-spm-swift-playgrounds-for-ipad/54845/4).

This definitely closes this issue. There is no debate: the bug is in Swift Playgrounds for iPad, and the tagging scheme of GRDB is totally legit.

Thanks to everyone!
