### ISSUE TITLE
FTS5 when installing via SPM

### ISSUE THREAD

**Issue by raphaelcruzeiro** [groue/GRDB.swift#1137]
I have a fairly large project which relies on GRDB for its data layer. I have full-text search for some of my entities. This was done by installing GRDB linked against SQLCipher using cocoa pods (i.e `pod 'GRDB.swift/SQLCipher'`). This works well, but I have now to migrate my project to SPM packages mainly due to some weird behaviours when installing dependencies through Cocoapods and running the app on the M1 iOS simulator.

I realise that installing SQLCipher via SPM I currently not possible due to SPM's lack of a preprocessing stage. I saw some guides online where people suggested manually cloning the SQLCipher repo and running some scripts to generate a C amalgamation and including said amalgamation on a fork of GRDB. I've tried several approached to this and even managed with a fork of GRDB that will compile just fine in isolation, but it will fail to compile if it's being linked against by an iOS app. 

Is there any way to currently achieve this? I don't mind maintaining this fork myself, but it's getting to a working solution which is killing me. I know some people online have managed to do this, but they haven't posted their code anywhere.

**Comment by groue** [comment]
Hello @raphaelcruzeiro,

I assume you only use SQLCipher for FTS5, and not for encryption.

What [other people](https://github.com/groue/GRDB.swift/network) do to enable FTS5 support via SPM is fork GRDB, and append `swiftSettings: [.define("SQLITE_ENABLE_PREUPDATE_HOOK")]` to the definition of the "GRDB" target in Package.swift: [example 1](https://github.com/rcasula/GRDB.swift/commit/1336a4191ff49dead272351028f9712ee7acddf4), [2](https://github.com/AndreiSava25/GRDB.swift/commit/9576c1fab6eecfa1d32622f99812e688f6de5b30).

This technique works, as far as I know, as long as you target iOS 11.4+ / macOS 10.13+ / tvOS 11.4+ / watchOS 4.3+.

**Comment by groue** [comment]
For information, there are multiple reasons why the main repo does not support FTS5 with SPM out of the box:

1. A SPM package can not specify multiple platform requirements. As long as GRDB supports operating systems that do not ship with FTS5, it's impossible to declare the FTS5 requirements at the level of the package.
2. The Swift language makes it very impractical to conditionally enable apis for 1. system SQLite (with `@available` checks), 2. custom SQLite builds (with `#if SQLITE_XXX` checks), and 3. SQLCipher (no way to access compilation options). Code duplication is required.

In the case of FTS5, the amount of code to duplicate is just too big to be practical. That's why I decided to guard FTS5 apis with `#if SQLITE_ENABLE_FTS5`. This requires the users to find a way to set this flag, and take care of not deploying this code to old operating systems.

**Comment by raphaelcruzeiro** [comment]
That did the trick @groue! Thank you very much for your explanation.

**Comment by groue** [comment]
Happy GRDB!
