### ISSUE TITLE
Why isn't there a way to delete columns?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1138]
I read the part of the documentation on migration, there are methods such as deleting tables and adding columns, but I don't see the method of deleting columns.

Is it forgotten, or will there be any sequelae after this drop column?

Shouldn't it be like this?

            try db.alter(table: *) { t in
                t.drop(column: "name")
            }

**Comment by groue** [comment]
Hello @SF-Simon,

The ability to drop columns was introduced quite recently, in [SQLite 3.35.0](https://www.sqlite.org/releaselog/3_35_0.html).

iOS 14.4, for example, ships with SQLite 3.23.3 ([reference](https://github.com/yapstudios/YapDatabase/wiki/SQLite-version-(bundled-with-OS))), and thus is unable to drop columns.

In order to enable such a Swift API, we need to know which exact versions of iOS, macOS, tvOS and watchOS come with SQLite >= 3.35.

A pull request would be quite appreciated!

**Comment by groue** [comment]
I guess the initial question was answered, actually. I'm closing this issue, but the discussion can of course continue :-)

**Comment by groue** [comment]
Fixed by #1144
