### ISSUE TITLE
SQLite error 10: disk I/O error

### ISSUE THREAD

**Issue by brunomunizaf** [groue/GRDB.swift#1153]
Bonjour @groue ! Hope you're safe and doing good...
```
Integration/Session.swift:255: Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 10: disk I/O error - while executing `PRAGMA main.table_xinfo("messages")` Integration/Session+Chat.swift:207: Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 10: disk I/O error - while executing `PRAGMA main.table_xinfo("messages")
```
Firebase reported this crash and the reason seems pretty clear to me: I did force-try on something that thew an exception. What I'm wondering is actually what is the exception that was thrown here. The error message points to two different places on my app, could it be a concurrency issue? I'm using DatabaseQueue and GRDB 5.3.0
```
let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0].appending("/db.sqlite")
databaseQueue = try DatabaseQueue(path: path)
try FileManager.default.setAttributes([.protectionKey : FileProtectionType.complete], ofItemAtPath: path)
```
Could it be because I did not follow your specs when you said "Don't set protection attributes to the file but instead to the folder"?

PS: Don't get me wrong, I did follow your instructions - this is somewhat a legacy code 😄 

Thanks in advance. Salut

**Comment by groue** [comment]
Hello again @brunomunizaf !

I/O error are, presumably, failures of SQLite to interact with the underlying file system, so we're visiting one deep underground of your app!

I have only one experience of such error so far: [SQLite error 10 "disk I/O error", SQLite error 23 "not authorized"](https://github.com/groue/GRDB.swift#sqlite-error-10-disk-io-error-sqlite-error-23-not-authorized). If the error happens on locked devices, you may have to think how your app is supposed to catch those errors and handle protected databases.

**Comment by groue** [comment]
> Don't set protection attributes to the file but instead to the folder

This advice is still quite relevant. Setting protection attributes on the database file only does not protect the (many) [temporary files](https://www.sqlite.org/tempfiles.html) created by SQLite. Inconsistent protection does not look like a sane setup. This problem is avoided when you store the database in its dedicated folder, and protect the folder.

**Comment by brunomunizaf** [comment]
First things first, you are probably the fastest engineer I've ever seen to reply issues reported on their repository 😂. Hors concours! haha...

> This advice is still quite relevant. Setting protection attributes on the database file only does not protect the (many) temporary files created by SQLite. Inconsistent protection does not look like a sane setup. This problem is avoided when you store the database in its dedicated folder, and protect the folder.

Got it, already separated everything onto a new folder and protected the folder itself. Thanks!

> I have only one experience of such error so far: SQLite error 10 "disk I/O error", SQLite error 23 "not authorized". If the error happens on locked devices, you may have to think how your app is supposed to catch those errors and handle protected databases.

That's interesting. In fact I do some database operations while the app is running on a background task, so that raises the question: is the database readonly while the app is in background by default? Cause I don't seem to be setting it as readonly anywhere in my codebase. Maybe using DatabasePool instead of DatabaseQueue here could give me a different result?

**Comment by groue** [comment]
> First things first, you are probably the fastest engineer I've ever seen to reply issues reported on their repository 😂. Hors concours! haha...

I do like it as well when repos maintainers are responsive 😉

> That's interesting. In fact I do some database operations while the app is running on a background task, so that raises the question: is the database readonly while the app is in background by default? Cause I don't seem to be setting it as readonly anywhere in my codebase.

A protected database is completely unavailable. [Data Protection](https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/encrypting_your_app_s_files) prevents all accesses, reads and writes.

> So maybe if I catch DatabaseError.SQLITE_IOERR I can 'fail' the operation and wait for the delegate method to be called announcing that the protected data is available. What do you think?

Basically, such errors are to be expected as soon as your app attempts at accessing a protected database in the background. So you'd better catch them, and do what your app needs in this case. You can also listen to OS notifications in order to restart failed operations (if this is what your app needs).

I recommend catching both SQLITE_IOERR and SQLITE_AUTH, since I could see them both in such a setup.

> Maybe using DatabasePool instead of DatabaseQueue here could give me a different result?

No, data protection is at a much lower level than GRDB and SQLite.

**Comment by brunomunizaf** [comment]
Thank you very much @groue . Feel free to close this issue - you got me the support I needed. Have a great weekend!

**Comment by groue** [comment]
Vive le week-end ! Merci 😊
