### ISSUE TITLE
Writing to a specific database table

### ISSUE THREAD

**Issue by rozmarica** [groue/GRDB.swift#1154]
### What did you do?

Hello!
I have two tables (example: Male and Female with the same columns. Please guide me how can I select a specific table when saving

simple example:

```
var dbQueue: DatabaseQueue!

class DatabaseManager {
    
    static var migrator: DatabaseMigrator {
        var migrator = DatabaseMigrator()
        
        migrator.registerMigration("first create") { db in
            try db.create(table: "Male", body: { table in
                table.column("dbID", .integer).primaryKey()
                table.column("id", .integer).notNull()
                table.column("name", .text).notNull()
                table.column("hobby", .text).notNull()
            })
        }
        
        migrator.registerMigration("second create") { db in
            try db.create(table: "Female", body: { table in
                table.column("dbID", .integer).primaryKey()
                table.column("id", .integer).notNull()
                table.column("name", .text).notNull()
                table.column("hobby", .text).notNull()
            })
        }
        
        return migrator
}

    static func save(_ human: Human) throws {
            try dbQueue.inTransaction { db in
                try human.insert(db)

                return .commit
            }
    }
}
```
### What did you expect to happen?

I was expecting the ability to select the table name in the save function

### What happened instead?

Data not saved. Data is saved only if there are tables with DIFFERENT columns. Tell me, tables with the same columns are impossible?

### Environment

**GRDB flavor(s):** (GRDB
**GRDB version:**  5.10
**Installation method:** CocoaPods
**Xcode version:** 13.0
**Swift version:** 5.5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.4

**Comment by groue** [comment]
Hello @rozmarica 

> I was expecting the ability to select the table name in the save function

Did you find something in the documentation that created such an assumption? If so, please tell me so that I can fix it.

> Tell me, tables with the same columns are impossible?

SQLite gladly accepts that two tables share the same columns.

What you won't find is any support for table inheritance, or the ability for one record type to write in two distinct tables.

You have to find another technique. Check the [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md) for inspiration.

**Comment by groue** [comment]
No news is good news. Happy GRDB!
