### ISSUE TITLE
DatabaseValueConversion.swift:168 Fatal error: could not convert database value "11457-11-02 19:03:27.000" to DatabaseDateComponents (column: `date`, column index: 3...

### ISSUE THREAD

**Issue by DomBabic** [groue/GRDB.swift#1168]
Hey 👋 ,
recently we had started receiving crashlytics reports pointing to `DatabaseValueConversion.swift`. Issue is related to `Date` conversion when attempting to insert a new `PersistableRecord` into the pool.

### What did you do?

We create `Date` object using default initializer, we pass this object to our custom class during object initialization. Upon object creation we attempt to insert it into the pool.

This issue occurs when `Date` has a year component greater than or equal to 10,000. Given how we use default `Date init` the year component should never be anything other than what the system returns. 

Initially we assumed that maybe users had their device date manually set, so I went on to test this issue by changing date on the device. On iPhone 12 running iOS15.2.1 I wasn't even allowed to change the year beyond 2038. Scrolling to any year beyond 2038 would revert back to that year.

### What did you expect to happen?

New `PersistableRecord` should have been inserted into the GRDB pool.

### What happened instead?

Crash occurs with the following message:
```
Fatal error: could not convert database value "11457-11-02 19:03:27.000" to DatabaseDateComponents...
```

Error message contains additional information on the object being inserted into the pool which is not relevant to the crash.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.3.0
**Installation method:** CocoaPods
**Xcode version:** Version 13.2.1 (13C100)
**Swift version:** 5
**Platform(s) running GRDB:** iOS (multiple device models, multiple OS versions)

### Demo Project

I don’t have the demo project but the issue can easily be reproduced by generating a `Date` from the `String` listed above.

**Comment by groue** [comment]
Hello @DomBabic,

Indeed the [GRDB support for Date and DateComponents](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-datecomponents) closely matches the [date formats supported by SQLite](https://www.sqlite.org/lang_datefunc.html). In these formats, the range of valid years is `0000-9999`.

In the current state of the library, your solutions are:

- If you use [Codable Records](https://github.com/groue/GRDB.swift/blob/master/README.md#codable-records), use a custom `databaseDateEncodingStrategy/DecodingStrategy`.
- Otherwise, stop encoding or decoding `Date` in the database, but deal with raw `String` instead (that you will format and parse). Not ideal, but workable.
- I could not quite understand if those years beyond 9999 are normal in your application, or not. If they are not, it might be interesting to massage the database content.

On a side note, the "could not convert database value" error only happens when _decoding_ (not during insertion, as far as I know). Anyway: decoding errors are currently fatal errors. I know this is a pain point, but fixing this will come with breaking changes: you'll get a regular error instead of a fatal error in GRDB 6, when it ships.

**Comment by DomBabic** [comment]
@groue Thanks for the quick reply!

Our current workaround is to check year component and filter out any object that has a value above the upper limit. 

Odd thing is that we are unable to reproduce this issue by generating the date using `Date()` init. I just wanted to check if this crash was expected behaviour or not. I am glad to see you are on top of this and that GRDB 6 will bring changes that allows us to handle this issue in a safer way 👍.

**Comment by groue** [comment]
All right, glad you already found your workaround :-)

This issue remains interesting, nevertheless.

The libray aims at supporting [SQLite date functions](https://www.sqlite.org/lang_datefunc.html) by default, so possible consequences of this issue are:

- The documentation should much better describe the default limitations of dates.
- The documentation should much better describe the ways to pick a different format.
- The default conversion Date/DateComponent storage should _enforce_ the 0000-9999 limit (it is quite inconsistent to store dates but fail to decode them).
- Today, only Codable Records make it easy to pick another format (and, say, switch to ISO-8601). We may try to make it easier for plain records, and generally for plain dates.

**Comment by groue** [comment]
> * The documentation should much better describe the default limitations of dates.
> * The documentation should much better describe the ways to pick a different format.

Done in https://github.com/groue/GRDB.swift/commit/9b0e41ad586d4a52d67143a73732e99e38c29d86

> * The default conversion Date/DateComponent storage should _enforce_ the 0000-9999 limit (it is quite inconsistent to store dates but fail to decode them).

This would require a breaking change, or a fatal error, because The `DatabaseValueConvertible` protocol does not support types with "unserializable" values. Maybe GRDB6 will allow this. I'd rather not do anything right now, but I flag this issue as "needs revisiting".

> * Today, only Codable Records make it easy to pick another format (and, say, switch to ISO-8601). We may try to make it easier for plain records, and generally for plain dates.

This wasn't quite accurate. One can also define a [Custom Value Type](https://github.com/groue/GRDB.swift/blob/master/README.md#custom-value-types) that wraps a Date and performs customised encoding.
