### ISSUE TITLE
Question: SQLite/GRDB performance in DEBUG / Attached to debugger

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1173]
Sorry for deleting all of the meta data, but this isn't really in the scope of a "bug" per-se, but a behavioral question.

We have a relatively large (possibly hundreds-of-thousands of records) database, and we notice that sometimes certain insertions can take a few whole seconds. 

We also noticed it happens only when attached to a debugger and works much quicker without a debugger attached. I looked around the repo and the only reference I found is this:

https://github.com/groue/GRDB.swift/blob/d63392799928d60679b90fbec6a7ecfde358cdf1/Tests/GRDBTests/ValueObservationRecorder.swift#L425-L430

If this is a known issue (could be), is there any way to avoid it or reduce the significance? It makes debugging almost impossible in some scenarios. 

If it's not expected to take this long (sometimes up to 10-20seconds), could you share some thoughts on how I could debug this? I know you don't have access to our code, but any tips would be greatly appreciated.

Thank you! 🙏

**Comment by groue** [comment]
Hello @freak4pc,

Tests have very large timeouts because CI environments can be astonishingly slow. The figures you have found in tests have no meaning in the context of your development setup.

Now, I only monitor the [performances](https://github.com/groue/GRDB.swift/wiki/Performance) of release builds. Debug builds are certainly slower, due to lack of compiler optimizations, but also due to the liberal use of assertions that makes me sure the library behaves as intented. Debug builds are there... to help debuggability.

> could you share some thoughts on how I could debug this?

Don't forget to wrap large numbers of statements in a *single transaction*, so that SQLite does not have to wait for the file system before it can guarantee that a write was duly completed:

```swift
// Slow
for record in records {
    try dbQueue.write { db in
        try record.save(db)
    } // wait N times
}

// Better
try dbQueue.write { db in 
    for record in records {
        try record.save(db)
    }
} // wait 1 time
```

Next, search for existing issues that look related to yours, such as #926.

Then instrument your application in Release configuration: Xcode > Product menu > Profile, then choose the "Time Profiler" instrument. Look where your application is spending time.

You can also instrument your application again, but in Debug configuration this time: Xcode > Product menu > Scheme > Edit Scheme… > Profile > Info > Build Configuration: Debug, then run the "Time Profiler" instrument again. Look where your application is spending time.

I'm of course open to look at the performances of some specific code paths in debug builds, but "specific" is the key word, here. Remember that performance of debug builds is not a major concern - you'll need substantiated arguments.

**Comment by freak4pc** [comment]
Thanks so much for the detailed response. You've given me a lot to investigate into. I'll try to get back to you with more concrete data.

> Remember that performance of debug builds is not a major concern 

Generally agreed, but if it's something consistent it makes it very hard to build things that depend on the database :) 

Thank you so much!
