### ISSUE TITLE
Is it possible to operate GRDB.swift in "simple" mode without taking TRANSACTION & PRAGMA query_only into consideration?

### ISSUE THREAD

**Issue by yccheok** [groue/GRDB.swift#1178]
### What did you do?

Thank you for providing ORM liked feature for GRDB.swift, so that we need not to write boilerplate code to map struct data structure to database model.

We try to understand what work behind the scene in the following code

    func count() -> Int? {
        do {
            let count = try dbQueue.read { db in
                try Backup.fetchCount(db)
            }
            
            return count
        } catch {
            error_log(error)
        }
        
        return nil
    }

We notice the following SQLite statement is executed when the above `count()` function is executed

    BEGIN DEFERRED TRANSACTION
    PRAGMA query_only = 1
    SELECT COUNT(*) FROM backup
    PRAGMA query_only = 0
    COMMIT TRANSACTION

Based on documentation, we can understand why it is so. GRDB.swift tend to provide a lot of effort to ensure "multi-thread data safety"

However, such mechanism is a bit over engineering for our case, because our code have already ensure serial access to the desired database (via serial DispatchQueue & NSLock)

I was wondering, is it possible to only execute the following single statement, without transaction and pragma?

    SELECT COUNT(*) FROM backup

### What did you expect to happen?

Expect only

    SELECT COUNT(*) FROM backup

printed when using

    var configuration = Configuration()
    configuration.prepareDatabase { db in
        db.trace { print($0) }
    }

### What happened instead?

    BEGIN DEFERRED TRANSACTION
    PRAGMA query_only = 1
    SELECT COUNT(*) FROM backup
    PRAGMA query_only = 0
    COMMIT TRANSACTION

when trying to perform a simple count operation.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.21.0
**Installation method:** SPM
**Xcode version:** 13.2.1
**Swift version:** 5
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) iOS
**macOS version running Xcode:** 12.2.1

**Comment by groue** [comment]
Hello @yccheok,

Indeed GRDB provides many [concurrency guarantees](https://github.com/groue/GRDB.swift/blob/master/Documentation/Concurrency.md) by default, and you witness two of them: [isolated reads](https://github.com/groue/GRDB.swift/blob/master/Documentation/Concurrency.md#guarantee-isolated-reads) and [forbidden writes](https://github.com/groue/GRDB.swift/blob/master/Documentation/Concurrency.md#guarantee-forbidden-writes):

```sql
BEGIN DEFERRED TRANSACTION -- Isolated Read
PRAGMA query_only = 1      -- Forbidden Writes
SELECT COUNT(*) FROM backup
PRAGMA query_only = 0
COMMIT TRANSACTION
```

If you use a DatabasePool, you should not opt out of concurrency protections, because DatabasePool performs concurrent accesses. This would just be begging for trouble.

If you use a DatabaseQueue, then serial accesses are already guaranteed: DatabaseQueue internally uses its own serial DispatchQueue. You can safely opt out of concurrency protections, as long as 1. your application creates a single DatabaseQueue instance, for the whole duration of all database accesses to a database file, and 2. no other process accesses your database.

You have two options. Either pick the [semantic unsafe database access method](https://github.com/groue/GRDB.swift/blob/master/Documentation/Concurrency.md#safe-and-unsafe-database-accesses) `unsafeRead`. You can also use `DatabaseQueue.inDatabase`:

```swift
// Pick one. Both will only execute
// SELECT COUNT(*) FROM backup
let count = try dbQueue.unsafeRead { db in
    try Backup.fetchCount(db)
}
let count = try dbQueue.inDatabase { db in
    try Backup.fetchCount(db)
}
```

**Reminder**

Using the **safe** database access methods `read` and `write` is strongly recommended. This fosters database integrity, has no performance hit, and can even help performances.

One should not opt out of [concurrency guarantees](https://github.com/groue/GRDB.swift/blob/master/Documentation/Concurrency.md#safe-and-unsafe-database-accesses) and perform unsafe database accesses without a total understanding of the consequences.

**Comment by yccheok** [comment]
Hello @groue 

After reading your pointed concurrency documentation, I can see the complexity of the problem, and appreciate the abstraction you are trying to build upon to remove burden from app developer. 

Thank you!

I will then start building by relying on you safe database access methods `read` and `write`

Previously, I am using Android Room and I am achieving "concurrency safety" by the adapting the simple rules.

- Write operation will always performed by a global one and only one single thread executor
- Always wrap multiple operations within a single transaction, if any of the operations is performing write
- Pure read operation is not within transaction
- Never use `PRAGMA query_only = 1` before

Although going forward, I will not be using unsafe methods in your library, but I am still curious to know, is there any differences among the methods you have pointed out - `unsafeRead` and `inDatabase`? 

I checked their code and they look almost the same.

    public func unsafeRead<T>(_ value: (Database) throws -> T) rethrows -> T {
        try writer.sync(value)
    }


    public func inDatabase<T>(_ updates: (Database) throws -> T) rethrows -> T {
        try writer.sync(updates)
    }

Thanks.

**Comment by groue** [comment]
All right, @yccheok 👍 Yes, GRDB takes care of most aspects of concurrency safety by default.

The concurrency-related concept that remains on your shoulders (with both GRDB and Room) is **transaction boundaries**. With GRDB, this means that you have to care about how you group your database statements together in order to preserve database integrity (writes), and access consistent database states (reads):

```swift
try dbQueue.write { db in
  // In transaction: do preserve database integrity
  // Here you group related database updates.
}

let value = try dbQueue.read { db in
  // In transaction: consistent database state guaranteed.
  // Here you group related fetches.
}
```

You'll have a longer discussion of transaction boundaries in the [How to Design Database Managers](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md#how-to-design-database-managers) chapter of the Good Practices for Designing Record Types guide.

> I am still curious to know, is there any differences among the methods you have pointed out - `unsafeRead` and `inDatabase`?

They are identical indeed!

`inDatabase` is barely mentioned in the documentation. It is the quick-and-dirty database access method of DatabaseQueue, inherited from the early inspiration of GRDB: the venerable [FMDB](https://github.com/ccgus/fmdb). I often wonder whether I should remove it, but it is handy in scripts, where thread-safety is not really a concern.

`unsafeRead` is the "semantic" database access method shared by DatabaseQueue and DatabasePool, declared by their common protocol `DatabaseReader`. For DatabaseQueue, `unsafeRead` and `inDatabase` are identical. For DatabasePool, `unsafeRead` uses a read-only connection. DatabasePool has no `inDatabase` method.

Both `inDatabase` and `unsafeRead` are concurrency-unsafe, since they do not provide any transaction boundary, and do not guarantee snapshot isolation. For DatabaseQueue, it is only dangerous if there exists external connections to the database. For DatabasePool, `unsafeRead` is always dangerous, since nothing prevents writes from running concurrently.
