### ISSUE TITLE
Publish only values that changed on an observation

### ISSUE THREAD

**Issue by tiagopigatto** [groue/GRDB.swift#1179]
Hi @groue , first of all thank you for the amazing library!

I'm trying to observe changes on a specific column on my database and react to those but I want my publisher to publish only the columns that were changed and not all the columns. I'm not really proficient in SQL so I was wondering if this could be done.

So far what have I done:

```
self.sessionPublisher = ValueObservation.tracking(region: User.select(Column("status")), fetch: { db in try User.fetchAll(db)})
           .publisher(in: AppDatabase.shared.databaseReader)
           .eraseToAnyPublisher()
```

This reacts to the changes on the status column but the fetch part retrieves all the records and not only the ones that actually changed.

Sorry if this is really simple, I just couldn't figure it out.

**Comment by groue** [comment]
Hello @tiagopigatto,

If you want to only fetch only one column, then do what you want, and fetch only one column:

```swift
// Fetch statuses
let statuses = try databaseReader.read { db in
    try String.fetchAll(db, User.select(Column("status")))
}

// Observe statuses
let observation = ValueObservation.tracking { db in
    try String.fetchAll(db, User.select(Column("status")))
}
```

In the above sample code, you'll replace String with the type of your `status` column. If it is a Swift enum, make sure it conforms to `DatabaseValueConvertible`, as documented in [Swift Enums](https://github.com/groue/GRDB.swift/blob/master/README.md#swift-enums).

Try to restrict yourself from using `ValueObservation.tracking(region:fetch:)`. Distinguishing the tracked region from the observed values can be useful, but it can also be confusing. Most applications only need `ValueObservation.tracking(_:)`, and only specify the values they want to observe, by fetching them, as in the example above. This is a much simpler world, because if you know how to fetch, then you know how to observe, and vice-versa.

Maybe get more familiar with the [Requests](https://github.com/groue/GRDB.swift/blob/master/README.md#requests) chapter, so that you become able to better control your database requests. You may even become more proficient in SQL, a skill that can't hurt.

**Comment by tiagopigatto** [comment]
@groue I actually meant to say that the publisher must only publish the rows that changed and not the column. Really sorry about that

**Comment by groue** [comment]
Oops, I misunderstood your request.

I'm afraid ValueObservation does not allow this out of the box. You'll need elbow grease, a custom low-level [TransactionObserver](https://github.com/groue/GRDB.swift#transactionobserver-protocol), and probably learn a thing or two about SQLite.

**Comment by tiagopigatto** [comment]
No problem, I actually mistyped it, so my bad.

Thank you for your help!

One last question, is there any way that ValueObservation only works for updates on the value instead of any changes?

**Comment by groue** [comment]
ValueObservation, a high-level tool, is triggered by all database updates that *may* impact the tracked value (or that *may* impact the explicitly tracked region).

To understand this "may", consider an observation of the maximum score of all players. All players insertions, all player deletions, and all player score updates trigger the observation. Even if the maximum score itself is not modified.

This is one of the reasons why ValueObservation is [documented](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservation-usage) to be able to "notify consecutive identical values". Check this doc, it explains the behavior of ValueObservation with plenty of useful details.

The finest possible grain of database observation allowed by SQLite itself is exposed by GRDB with the TransactionObserver protocol. As low-level as it can be, it supports more advanced use case. It allows you to observe only updates of the status column of your users' table, gather the rowids of updated players during each database transaction, and, after a transaction has been successfully committed on disk, fetch the players with those ids and notify them to your application.

**Comment by tiagopigatto** [comment]
Thank you very much for the detailed explanation!

**Comment by groue** [comment]
I hope you can achieve your needs. I updated the above comment with a few more details.

**Comment by groue** [comment]
All right, I close this issue. Please reopen if you need further assistance, or open a new issue if you have another question. Happy GRDB!
