### ISSUE TITLE
How to correctly fetch a non-stored property using fetchOne?

### ISSUE THREAD

**Issue by CoderJasonSu** [groue/GRDB.swift#1180]
### What did you do?

I want to fetch a non-stored property using fetchOne.
In fact, I want to quickly define a non-storage property, and then still use methods such as fetchAll() without affecting data migration, etc.
Is there an easy way?

I have this class:

...
class ContactModel: Codable  {
    var id: Int? 
    var user_id: Int?
    var name: String?
    // more property
    
    // non-stored,  somewhere may use
    var feture: Int = 0
}
...

extension ContactModel: TableRecord {
    static var databaseTableName: String {
        return MSTableName.contact_table
    }
    static var databaseSelection: [SQLSelectable] = [Columns.id, Columns.user_id, Columns.name]
}

### What did you expect to happen?

I want that when i do this, it fetch success:

    static func query(uid: Int) -> ContactModel? {
        return try! self.dbQueue.unsafeRead({ (db) -> MSContactModel? in
            return try MSContactModel.filter(Column(Columns.user_id.rawValue) == uid).fetchOne(db)
        })
    }

### What happened instead?

some error:
Fatal error: could not read Int from missing column `feture` ...

### Environment

**GRDB flavor(s):** (SQLCipher)
**GRDB version:**
**Installation method:** (CocoaPods)
 pod 'GRDB.swift/SQLCipher'
 pod 'SQLCipher', '~> 4.0'
**Xcode version:13.2.1
**Swift version:5.5
**Platform(s) running GRDB:iOS

**Comment by groue** [comment]
Hello @CoderJasonSu,

You're question is more about Codable than GRDB.

You have two options:

1. Follow instructions described in the "Choose Properties to Encode and Decode Using Coding Keys" chapter of the [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) article.
2. Make `feature` an optional `Int?` (so that it is decoded as nil from a missing column).
