### ISSUE TITLE
Is it possible to find all three tables in a single query?

### ISSUE THREAD

**Issue by YotrolZ** [groue/GRDB.swift#1182]
hi,  groue, I'm looking for your help with a question！

Table1: t_user
```
struct User {
    var id: Int64?
    var nickname: String
}

extension User {
    // hasMany
    static let books = hasMany(Notebook.self).forKey("books")
}
```

Table2: t_notebook
```
struct Notebook {
    var id: Int64?
    var bookname: String
}
extension Notebook {
    //  hasMany
    static let notes = hasMany(Note.self).forKey("notes")
}
```

Table3: t_note
```
struct Note {
    var id: Int64?
    var content: String
}

extension Note {
    // belongsTo
    static let notebook = belongsTo(Notebook.self).forKey("notebook")
}
```

Is it possible to find all three tables in **a single query**?  I expect the following results

```
{
   user: {
       nickname: ""
   },
    notebooks: [
        {
             bookname: "",
             notes: [
                 {
                     content: ""
                 }
             ]
        }
    ]
}
```

My current practice is to conduct two rounds of query requests. My question is whether I can directly find out all the results through one query request. 
I am looking forward to your reply, best regards!

**Comment by groue** [comment]
Hello @YotrolZ,

You have read the documentation, and you know you can:

- write a request that fetches users with their books :

    ```swift
    let request = User.including(all: User.books)
    ```

- write a request that fetches books with their notes:

    ```swift
    let request = Notebook.including(all: Notebook.notes)
    ```

**Do you want to fetch all books with their notes _for a single user_?**

If so, use `request(for:)` in order to grab a user's books, and include notes with `.including(all:)`:

```swift
struct BookInfo: Decodable, FetchableRecord {
    var book: Notebook
    var notes: [Note]
}

let user: User = ... // Your input user
let request = user.request(for: User.books).including(all: Notebook.notes)
let bookInfos: [BookInfo] = try request
    .asRequest(of: BookInfo.self)
    .fetchAll(db)
```

**Do you want to fetch all users, with their books, with their notes?**

If so, call `including(all:)` twice:

```swift
let request = User.including(all: User.books.including(all: Notebook.notes))
```

As all requests that involve associations, you need to define a dedicated record type for gathering the results (see the documentation of [`including(all:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingall) for a simpler example):

```swift
struct UserInfo: Decodable, FetchableRecord {
    struct BookInfo: Decodable {
        var book: Notebook
        var notes: [Note]
    }
    var user: User
    var books: [BookInfo]
}

let userInfos: [UserInfo] = try request
    .asRequest(of: UserInfo.self)
    .fetchAll(db)
```

As documented, the coding keys of the decoded type must match the association keys. That's why `UserInfo` above has a `books` property, which matches the association key of `User.books` (which is declared with `forKey("books")`).

You can rename it if you want:

```swift
struct UserInfo: Decodable, FetchableRecord {
    struct BookInfo: Decodable {
        var book: Notebook
        var notes: [Note]
    }
    var user: User
    var bookInfos: [BookInfo] // <- bookInfos
}

let bookInfos = User.books.forKey("bookInfos") // <- rekey to "bookInfos"
let request = User.including(all: bookInfos.including(all: Notebook.notes))
let userInfos = try request
    .asRequest(of: UserInfo.self)
    .fetchAll(db)
```

The fetched type `UserInfo` does not exactly match the structure of your expected results. For example, we fetch whole records (`User`, `Book`, `Note`) and not only a few columns of each.

Yet it is close enough, and should let you make progress towards your solution.

**Comment by YotrolZ** [comment]
@groue Thank you very much for the detailed explanation!
