### ISSUE TITLE
Database Value conversion question

### ISSUE THREAD

**Issue by hdlj** [groue/GRDB.swift#119]
Hello Groue!

In the DatabaseValue implementation of DatabaseValueConvertible protocol  , 

```
 /// Returns *databaseValue*, or nil for NULL input.
    public static func fromDatabaseValue(_ databaseValue: GRDBCustomSQLite.DatabaseValue) -> GRDBCustomSQLite.DatabaseValue?
```

why nil is returned for NULL input instead of `DatabaseValue.null`? 
nil should not be returned when a conversion error happened ?

Thanks!

**Comment by groue** [comment]
Hello @hdlj 

The source code reads:

```swift
extension DatabaseValue : DatabaseValueConvertible {
    public static func fromDatabaseValue(_ databaseValue: DatabaseValue) -> DatabaseValue? {
        // Follow protocol semantics: DatabaseValueConvertible types turn NULL
        // into nil:
        //
        //     DatabaseValue.fetchOne(db, "SELECT NULL") // nil
        return databaseValue.isNull ? nil : databaseValue
    }
}
```

**Context**

The *main intent* of DatabaseValueConvertible.fromDatabaseValue is indeed, as you say, to return nil if the input databaseValue can't be converted into the adopting type. This prevents data loss by raising a fatal error when a conversion from a non-null database value fails. It also provides a safe path for developers who are not sure of their database content:

```swift
// fatal error: could not convert "Mom's birthday" to Date.
let date: Date? = row.value(named: "date")

let dbv = row.databaseValue(named: "date")
if dbv.isNull {
    // Handle NULL
if let date = Date.fromDatabaseValue(dbv) {
    // Handle valid date
} else {
    // Handle invalid date
}
```

Since DatabaseValueConvertible.fromDatabaseValue returns nil if the input databaseValue can't be converted into the adopting type, nearly all types return nil for NULL (NULL is usually not convertible to any value).

Now DatabaseValue *has* a value that represents NULL, so NULL *can* be converted. It is the only type like that.

So what should I do? Apply the cold conversion rule blindly, with an exception, or make no exception, and have all types return nil for NULL?

I decided to make no exception, but I can not say that I explored all use cases of the DatabaseValueConvertible facet of DatabaseValue.

What do you think?

**Comment by groue** [comment]
Since you're asking, I guess you have some code that does not behave as expected. Will you please provide this piece of code, as evidence for any decision we eventually take?

**Comment by hdlj** [comment]
Thanks for the detailed explanation! 

Here is my situation:

```
let input: [DatabaseValue] = [
    1.databaseValue,
    2.databaseValue,
    3.databaseValue,
    DatabaseValue.null,
    5.databaseValue]

// 5 values

let output: [DatabaseValue] = input.flatMap { DatabaseValue.fromDatabaseValue($0) }
// 4 values

```
I was surprised that 

``` 
for value:
       DatabaseValue.fromDatabaseValue(value.databaseValue) == value
is not always true
```

**Comment by hdlj** [comment]
No exception seems good to me but when you want to use the Database.null explicitly we have to be more careful

**Comment by groue** [comment]
You know what? I think you're right, and that DatabaseValue should convert NULL to DatabaseValue.null.

I hope you're not stuck with Swift 2, are you? The change will ship for Swift 2.3 and Swift 3.

**Comment by groue** [comment]
@hdlj The change has shipped in v0.81.1 (Swift 2.3) and v0.83.0 (Swift 3). See [CHANGELOG](https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md#0830).

Thanks for this issue: it has brought the opportunity to turn DatabaseValue into a regular value, and remove the need for specific APIs when extracting DatabaseValue from rows. The `Row.databaseValue(...)` methods have been removed, and one should use `Row.value(...)` instead:

```diff
-let dbv = row.databaseValue(atIndex: 0)
-let dbv = row.databaseValue(named: "foo")
+let dbv: DatabaseValue = row.value(atIndex: 0)
+let dbv: DatabaseValue = row.value(named: "foo")
```

**Comment by hdlj** [comment]
Great! Thanks! 
Cool,  I have moved on Swift 3 :)

**Comment by groue** [comment]
De rien Hubert ;-)
