### ISSUE TITLE
Is DatabaseQueue.close will gurantee all database info is written into single SQLite flat file and no SHM & WAL files will be genereated?

### ISSUE THREAD

**Issue by yccheok** [groue/GRDB.swift#1197]
### What did you do?

Trying to use GRDB, to convert CoreData to SQLite flat file format, then export as zip file.

### What did you expect to happen?

I want to ensure only single SQLite flat file is generated, and no SHM & WAL files, before I am performing zip operation

### What happened instead?

Currently, to ensure there is no SHM & WAL files, before I am performing zip operation, I will execute

```
do {
    dbQueue = try DatabaseQueue(path: localBackupDatabaseExportFullPath.path, configuration: configuration)
} catch {
    ...
}

...

do {
    try dbQueue.close()
} catch {
    ...
}
```

My observation is, there is no SHM & WAL files generated. I just want to know, is `dbQueue.close()` sufficient enough, to guarantee all DB operations are committed into single SQLite file, and no SHM & WAL files will be generated?

Also, besides performing `dbQueue.close()`, is "going out of scope" good enough to ensure all DB operations are committed into single SQLite file, and no SHM & WAL files will be generated?

For instance,

```
private static func _importNow(_ url: URL) -> Bool {
    var dbQueue: DatabaseQueue!
    
    defer {    
        // To 100% ensure no SHM & WAL files will be generated?
        if dbQueue != nil {
            do {
                try dbQueue.close()
            } catch {
                error_log(error)
            }
        }
    }
```

Upon returning from `_importNow`, is SHM & WAL files gurantee will not be generated because `DatabaseQueue` is going out of scope? Or, we need to rely on `defer` block to perform explicit close?

This is because in the `deinit` function of `DatabaseQueue`, I do not see a "database close" operation being executed?

```
    deinit {
        // Undo job done in setupMemoryManagement()
        //
        // https://developer.apple.com/library/mac/releasenotes/Foundation/RN-Foundation/index.html#10_11Error
        // Explicit unregistration is required before OS X 10.11.
        NotificationCenter.default.removeObserver(self)
    }
```

Thank you for your support.

### Environment

**GRDB flavor(s):** GDRB
**GRDB version:** 5.21.0
**Installation method:** SPM
**Xcode version:** 13E113
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.2.1

**Comment by groue** [comment]
Hello @yccheok,

> Trying to use GRDB, to convert CoreData to SQLite flat file format, then export as zip file. [...] I want to ensure only single SQLite flat file is generated, and no SHM & WAL files, before I am performing zip operation.

Thanks for making your need very clear.

The technique I would chose would be to export the CoreData database into a non-WAL database, and zip this copy:

```swift
let dbQueue = try DatabaseQueue(path: "/path/to/coredata.sqlite")
try dbQueue.vacuum(into: "/path/to/exported.sqlite")
```

You'll gain another advantage: the exported database will have the minimal size (see [VACUUM](https://www.sqlite.org/lang_vacuum.html)).

Since `vacuum(into:)` has availability constraints, you may prefer the [backup](https://github.com/groue/GRDB.swift/blob/master/README.md#backup) api instead of the `VACUUM INTO` command.

---

Now, some general considerations.

- Please read the [How do I close a database connection?](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-close-a-database-connection) FAQ
- Please read the inline documentation of the GRDB `close()` method.

> is `dbQueue.close()` sufficient enough, to guarantee all DB operations are committed into single SQLite file, and no SHM & WAL files will be generated?

I assume `dbQueue` is not currently in use elsewhere in your app (otherwise `close()` will throw an error).

"guarantee all DB operations are committed": no, operations that you did not commit yourself will not be committed.

"guarantee no SHM & WAL files will be generated": The default SQLite behavior is to delete the -wal and -shm files when a database connection is closed. Unfortunately it is not the default behavior of SQLite that ships with our operating systems. To re-enable this behavior, you need to make sure [`SQLITE_FCNTL_PERSIST_WAL`](https://www.sqlite.org/c3ref/c_fcntl_begin_atomic_write.html#sqlitefcntlpersistwal) is zero.

Please read carefully the linked doc for `SQLITE_FCNTL_PERSIST_WAL`. You'll find a GRDB sample code in the [Sharing a Database](https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md) guide. This guide has the exact opposite goal (setting `SQLITE_FCNTL_PERSIST_WAL` to 1, in order to make sure the -wql and -shm files are present), but you should be able to get inspiration from it.

For even more context about closing SQLite connections, check the [Closing A Database Connection](https://www.sqlite.org/c3ref/close.html) SQLite documentation. Yeah, it's not as simple as one would want it to be.

**Comment by groue** [comment]
> This is because in the `deinit` function of `DatabaseQueue`, I do not see a "database close" operation being executed?

The `DatabaseQueue` accesses the database through its `SerializedDatabase` instance. This is the object that closes the db in [its deinitializer](https://github.com/groue/GRDB.swift/blob/v5.22.1/GRDB/Core/SerializedDatabase.swift#L72-L77).

**Comment by yccheok** [comment]
Thank you for your advice. This is what I did after reading your post.

- No explicit `dbQueue.close`. We rely on out of scope, auto database closing.

- Set SQLITE_FCNTL_PERSIST_WAL to 0, to delete the -wal and -shm files when a database connection is closed.

```
var dbQueue: DatabaseQueue!

// For debugging purpose.
var configuration = Configuration()
configuration.prepareDatabase { db in
    db.trace { print($0) }
    
    // https://github.com/groue/GRDB.swift/issues/1197
    var flag: CInt = 0
    let code = withUnsafeMutablePointer(to: &flag) { flagP in
        sqlite3_file_control(db.sqliteConnection, nil, SQLITE_FCNTL_PERSIST_WAL, flagP)
    }
    guard code == SQLITE_OK else {
        throw DatabaseError(resultCode: ResultCode(rawValue: code))
    }
}

do {
    dbQueue = try DatabaseQueue(path: localBackupDatabaseExportFullPath.path, configuration: configuration)
} catch {
    error_log(error)
}
```

> The technique I would chose would be to export the CoreData database into a fresh database file, and zip this copy:

We do not use this technique to export CoreData database into a fresh database file.

Reason is that, we need the database file to be a pre-defined schema, so that it can be shared with other non Mac platforms. The database schema in CoreData, is undocumented and is a black box. 

What we did is iteraing through every NSManagedObject (using offset and limit to prevent out of memory), then write their property to a pre-defined schema DB, via GRDB.

Thank you for your support.

**Comment by groue** [comment]
I'm glad you found a good solution. Happy GRDB!
