### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by AlexandreMinard** [groue/GRDB.swift#1205]
Hello,

Since yesterday, i'm facing this error when compiling my project for any simulator (for devices it's working fine):

Could not find module 'GRDB' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at:  /Users/alex/Library/Developer/Xcode/DerivedData/Project/....

My project was working fine before.

Any help would be appreciated.

Regards,

**Comment by groue** [comment]
Hello @AlexandreMinard,

I do not know what happened to your machine since yesterday 😬.

Try the regular Xcode troubleshooting steps:

- Clean the build folder (Xcode > Product > Clean Build Folder) and rebuild
- Quit Xcode, relaunch, and rebuild
- Quit Xcode, delete ~/Library/Developer/Xcode/DerivedData, relaunch, and rebuild
- Quit Xcode, delete all the xcuserdata directories in your project which may contain corrupted Xcode caches, relaunch, and rebuild
- Have a orange-banana smoothie while your Mac is rebooting

**Comment by JoeFerrucci** [comment]
Remove your target's "Excluded Architectures" if you are building on Apple Silicon. I had arm64 in my excluded archs and encountered your same issue, @AlexandreMinard, but once I removed it it worked fine (I had arm64 excluded from long ago; no longer needed).
