### ISSUE TITLE
Can we exclude DemoApps when including GRDB via SPM in the project?

### ISSUE THREAD

**Issue by yccheok** [groue/GRDB.swift#1211]
### What did you do?

We saw the code in DemoApps is included during development via SPM

### What did you expect to happen?

Do not see DemoApps related code when during development/ deployment via SPM

### What happened instead?

We include GRDB via SPM

During development, we notice XCode will recognize the DemoApps unwind segue

https://github.com/groue/GRDB.swift/blob/master/Documentation/DemoApps/GRDBDemoiOS/GRDBDemoiOS/ViewControllers/PlayerListViewController.swift

![Screenshot 2022-04-26 at 2 26 58 PM](https://user-images.githubusercontent.com/308276/165237268-3c4dab45-87be-4d5d-ab0a-873ec9f55828.png)

- cancelPlayerEdition
- commitPlayerEdition

We have a concern that, will unnecessary DemoApps' code included in our release build? How can we exclude DemoApps, during development and during performing release build?

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.21.0
**Installation method:** SPM
**Xcode version:** 13.3.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.3.1

**Comment by groue** [comment]
Hello @yccheok,

Thanks for reporting this Xcode issue. I'll close it as "won't fix", because this is not a problem with GRDB.

The GRDB repository indeed contains demo apps. The demo app tests are part of the full suite of GRDB tests. The demo app are also tests for various GRDB installation methods.

Extracting demo apps in a separate repository, so that they are not cloned as part of the GRDB SPM package, would make it difficult to run the GRDB tests suite.

That's why I suggest you report your issue to Apple, at http://feedbackassistant.apple.com. Explain to them that the Xcode heuristics for populating the unwind segue menu should be amended so that it stops embedding selectors that are not part of a Swift Package interface. Indeed the GRDB demo apps are not present in any target of `Package.swift`.

**Comment by yccheok** [comment]
Thank you. I am not familiar with how Package.swift work

What my main concern is, when we build the final binary file to be ready for App Store publishing, will GRDB's demo app code + GRDB library code be included in the final binary file? Or, only essential GRDB library code will be included?

Thanks.

**Comment by groue** [comment]
> What my main concern is, when we build the final binary file to be ready for App Store publishing, will GRDB's demo app code + GRDB library code be included in the final binary file? Or, only essential GRDB library code will be included?

No, GRDB demo apps won't be included in your application.
