### ISSUE TITLE
Availability checks on TableAlteration.rename(column:to:) and .drop(column:) seem unnecessary

### ISSUE THREAD

**Issue by seanmrich** [groue/GRDB.swift#1214]
### What did you do?

I'm trying to add a migration that includes dropping a column. However, my app supports macOS 11 while the `TableAlteration.drop(column:)` method requires macOS 12 via availability checks. The relevant lines are in `TableDefinition.swift` lines 778 and 791.

A look through the code didn't reveal any particular need for the availability checks so I forked the project and removed them. The project built successfully and passed all tests. There may be a nuance to the project I don't understand, but the availability checks seem to be artificially restricting access to these features.

### What did you expect to happen?

I expected to be able to use `TableAlteration.drop(column:)` on a previous release of macOS. `TableAlteration.rename(column:to:)` is in the same boat.

### What happened instead?

Availability checks prevent the use of dropping/renaming columns via the alter API without changing the supported macOS version.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24
**Installation method:** SPM
**Xcode version:** 13.3.1
**Swift version:** 5.6
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 12.3.1

### Demo Project

N/A

**Comment by groue** [comment]
Hello @seanmrich,

Support for `DROP COLUMN` was added fairly recently in SQLite ([version 3.35.0](https://www.sqlite.org/releaselog/3_35_0.html)), so it does need availability checks.

Now, in the pull request #1144 that added the matching Swift API, the availability check for macOS was indeed rushed. The PR conversation does not capture this, but I remember that discovering the SQLite version that ships with each macOS version is difficult: this explains why the minimum macOS version is probably too high. Yes, that was a lazy move.

But you can help, since you have access to older macOS versions!

On your macOS machines, you can run the `sqlite3` tool in the terminal. It will tell the SQLite version that ships with the OS. For example, my copy of macOS 12.3.1 runs SQLite 3.37.0:

```
% sqlite3                                                                                 
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> ^D
%
```

Please report the precise macOS and SQLite versions you can see on your macOS 11 machine: we'll upgrade the availability check accordingly :-)

**Comment by seanmrich** [comment]
Unfortunately I’ve recently upgraded to the latest hardware that only supports macOS 12. I don’t currently have a way to test under Big Sur, even though my app still deploys to it. Also can’t find a reference to it online. Perhaps someone else has access to a macOS 11 installation?

**Comment by groue** [comment]
All right. If I were you I'd figure this out, or your app will fail on macOS 11. Your other option is to assume DROP COLUMN is not available. Check the GRDB Migrations guide.

**Comment by seanmrich** [comment]
I’ve already worked around the issue. Just trying to offer a recommendation. Sorry I couldn’t be more helpful.
