### ISSUE TITLE
How to fetch grouped records, referencing another table records?

### ISSUE THREAD

**Issue by darrarski** [groue/GRDB.swift#1222]
Hello! In a chat-like application that uses GRDB for local persistence, I have a problem figuring out how to fetch a list of conversations grouped by contacts.

Could you give me some hints on how to implement it with GRDB, as I'm running out of ideas?

## Description

Given the following records (each persisted in its own table):

|`Contact`||
|:--|:--|
|**id**|unique primary key|
|**name**|string|

|`Message`||
|:--|:--|
|**id**|unique primary key|
|**senderId**|foreign key referecing `Contact.id`|
|**recipientId**|foreign key referening `Contact.id`|
|**text**|string|

I would like to fetch a "virtual" (non-persisted) record, which looks like this:

|`ContactChatInfo`||
|:--|:--|
|**contact**|`Contact`|
|**lastMessage**|latest `Message` sent to or received from the `Contact`|

I expect the fetch request to return `ContactChatInfo` models for every `Contact` that given `Contact` exchanged at least one message with.

I'm trying to use an association with a common table expression, unfortunately without luck.

```swift
let userId: Data = /* the ID of Contact for which I need to fetch the ContactChatInfo models */

let lastMessageRequest = Message
  .annotated(with: max(Message.Column.date))
  .group(Message.Column.senderId || Message.Column.recipientId)

let lastMessageExpression = CommonTableExpression<Message>(
  named: Column.lastMessage.rawValue,
  request: lastMessageRequest
)

let lastMessageAssociation = Contact
  .association(
    to: lastMessageExpression,
    on: { contactTable, messageTable in
      messageTable[Message.Column.senderId] == contactTable[Contact.Column.id] ||
      messageTable[Message.Column.recipientId] == contactTable[Contact.Column.id]
    }
  )
  .order(Message.Column.date.desc)

let request = Contact
  .filter(Contact.Column.id != userId)
  .with(lastMessageExpression)
  .including(required: lastMessageAssociation)
  .order(sql: "\(lastMessageExpression.tableName).\(Message.Column.date.rawValue) DESC")
  .asRequest(of: ContactChatInfo.self)
```

[Here](https://git.xx.network/elixxir/client-ios-db/-/blob/c372dc81804e12a14dbf672ed6da3ae60b542240/Sources/XXDatabase/ContactChatInfo+GRDB.swift) you can find the complete implementation.

I've created a test for the expected result, you can [check it here](https://git.xx.network/elixxir/client-ios-db/-/blob/c372dc81804e12a14dbf672ed6da3ae60b542240/Tests/XXDatabaseTests/ContactChatInfoTests.swift).

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24.0
**Installation method:** SPM
**Xcode version:** 13.4.0
**Swift version:** 5.6.1
**Platform(s) running GRDB:** iOS, macOS

## Demo Project

The code is available in [this repository](https://git.xx.network/elixxir/client-ios-db) on the [`feature/db-models-3`](https://git.xx.network/elixxir/client-ios-db/-/tree/feature/db-models-3)  branch. 

Here is a [direct link](https://git.xx.network/elixxir/client-ios-db/-/blob/feature/db-models-3/Sources/XXDatabase/ContactChatInfo%2BGRDB.swift) to the file where the fetch request is implemented.

The problem is showcased in [ContactChatInfoTests](https://git.xx.network/elixxir/client-ios-db/-/blob/feature/db-models-3/Tests/XXDatabaseTests/ContactChatInfoTests.swift) - the tests are failing, because fetch result does not match expectation.

**Comment by groue** [comment]
Hello @darrarski,

You're developing a chat app, and this use case is clearly identified.

Did you check the [CTE Association Example: a Chat App](https://github.com/groue/GRDB.swift/blob/v5.24.0/Documentation/CommonTableExpressions.md#cte-association-example-a-chat-app) chapter?

Did you also check #856? It has some relevance as well, and explores another SQLite technique, without any CTE.

**Comment by darrarski** [comment]
Hello @groue, 

Thank you for the quick reply! I checked both the CTE example for a Chat App and the issue #856. I see the solutions provided there assume persisting `Chat` records in a dedicated table. Do you think it's mandatory? I thought it could be derived from contacts and messages tables, by fetching all contacts joined with messages. What do you think about it?

**Comment by groue** [comment]
Ah, thank you. Now I see how you are talking about a variant indeed. Please hold on.

**Comment by darrarski** [comment]
Unfortunately, I don't know the raw SQL query I need, but I'll try to play around and let you know if I found something that brings us closer to the solution that uses GRDB.

The world would be definitely a better place if everyone was as committed as you are! ❤️
And yeah, it's a fun challenge indeed :-)

**Comment by groue** [comment]
It's always easier to help people who tried to help themselves first. And this lib is very lucky because it gets a lot of questions like yours: that's how it evolves 🙂 So thank YOU. Now we still don't have any solution, so please have a little more patience 😉

**Comment by darrarski** [comment]
Some kind person on [stackoverflow](https://stackoverflow.com/questions/72325022/fetch-contacts-with-last-message-from-sqlite-database) helped me with the SQL query. The solution is to use two inner-joins, like this:

```
SELECT c2.name, MAX(m.date) last_date, m.text
FROM messages m 
INNER JOIN contacts c1 ON c1.id IN (m.senderId, m.recipientId)
INNER JOIN contacts c2 ON c2.id IN (m.senderId, m.recipientId) AND c1.id <> c2.id
WHERE c1.name = ?
GROUP BY c2.id
ORDER BY last_date DESC;
```

Here is a working [demo on dbfiddle](https://dbfiddle.uk/?rdbms=sqlite_3.27&fiddle=b3f11852def26e5e78de95a5a1fde7cb).

Now I just need to figure it out how to generate such query using GRDB.

@groue let me know what do you think.

**Comment by groue** [comment]
Well done, @darrarski!

Good news: we have an SQL request.

Bad news: this SQL request is not expressible with the (limited) Swift query interface. We can spot this in the joins:

```sql
INNER JOIN contacts c1 ON c1.id IN (m.senderId, m.recipientId)
INNER JOIN contacts c2 ON c2.id IN (m.senderId, m.recipientId) AND c1.id <> c2.id
--                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Such join condition can not be built from the [associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md) BelongsTo, HasMany, etc. Those only support foreign key equality checks, such as `JOIN contacts ON contacts.id = messages.senderId` for example.

That's not really a problem - the query interface never had the goal to generate all possible SQL queries! And even if we eventually get support for the generation of such SQL, that's not a reason to remain stuck. Let's just use our raw SQL query!

---

The target type is `ContactChatInfo`:

```swift
struct ContactChatInfo: Decodable, FetchableRecord {
    var contact: Contact
    var lastMessage: Message
}
```

It conforms to Decodable and FetchableRecord so that it can decode database rows.

It is made of other records (`Contact` and `Message`), and this will make our life simpler.

So we need to run an SQL query, based on your stack overflow answer, that fetches all columns from contacts (for the `contact` property), and all columns from message (for the `lastMessage` property).

This gives:

```sql
SELECT
    -- All contact columns
    c2.*,
    -- All message columns
    m.id,
    m.senderId,
    m.recipientId,
    m.text,
    MAX(m.date) AS date
FROM message m
INNER JOIN contact c1 ON c1.id IN (m.senderId, m.recipientId)
INNER JOIN contact c2 ON c2.id IN (m.senderId, m.recipientId) AND c1.id <> c2.id
WHERE c1.id = ?
GROUP BY c2.id
ORDER BY date DESC;
```

You will add the missing message columns I'm not aware of.

Note how `last_date` was renamed to `date`, so that it matches the `Message.date` property name.

I replaced the `WHERE c1.name = ?` condition with `WHERE c1.id = ?`, assuming you want to fetch all chat infos for a given contact identified by its id.

---

Now that we have our SQL and target record, the tricky part is to let GRDB dispatch row columns in the proper records (`contact` and `lastMessage`).

The technique to do so is described in [Joined Queries Support](https://github.com/groue/GRDB.swift/blob/master/README.md#joined-queries-support). It gives:

```swift
extension ContactChatInfo {
    static func fetchAll(_ db: Database, forContactId contactId: String) throws -> [ContactChatInfo] {
        try SQLRequest<ContactChatInfo>("""
            SELECT
                c2.*,
                m.id,
                m.senderId,
                m.recipientId,
                m.text,
                MAX(m.date) AS date
            FROM message m
            INNER JOIN contact c1 ON c1.id IN (m.senderId, m.recipientId)
            INNER JOIN contact c2 ON c2.id IN (m.senderId, m.recipientId) AND c1.id <> c2.id
            WHERE c1.id = \(contactId)
            GROUP BY c2.id
            ORDER BY date DESC;
            """)
        .adapted { db in
            let adapters = try splittingRowAdapters(columnCounts: [Contact.numberOfSelectedColumns(db)])
            return ScopeAdapter([
                // First columns (c2.*) feeds the `contact` property
                "contact": adapters[0],
                // Subsequent columns (m.id, ...) feed the `lastMessage` property
                "lastMessage": adapters[1]])
        }
        .fetchAll(db)
    }
}
```

Find a complete sample code below:

<details><summary>Sample Code</summary>

```swift
import GRDB

struct Contact: Codable, Identifiable, FetchableRecord, PersistableRecord, CustomStringConvertible {
    var id: String
    var name: String
    
    var description: String { name }
}

struct Message: Codable, FetchableRecord, PersistableRecord, CustomStringConvertible {
    var id: String
    var senderId: String
    var recipientId: String
    var text: String
    var date: Date
    
    var description: String {
        "\(date): \(text)"
    }
}

let dbQueue = DatabaseQueue()
try dbQueue.write { db in
    try db.create(table: "contact") { t in
        t.column("id", .text).notNull().primaryKey()
        t.column("name", .text).notNull()
    }
    
    try db.create(table: "message") { t in
        t.column("id", .text).notNull().primaryKey()
        t.column("senderId", .text).notNull().references("contact")
        t.column("recipientId", .text).notNull().references("contact")
        t.column("text", .text).notNull()
        t.column("date", .datetime).notNull()
    }
    
    try Contact(id: "G", name: "Gwendal").insert(db)
    try Contact(id: "D", name: "Dariusz").insert(db)
    try Contact(id: "A", name: "Alice").insert(db)
    try Contact(id: "B", name: "Bob").insert(db)
    
    try Message(id: "1", senderId: "D", recipientId: "G", text: "D>G", date: Date()).insert(db)
    try Message(id: "2", senderId: "G", recipientId: "D", text: "G>D", date: Date().addingTimeInterval(1)).insert(db)
    try Message(id: "3", senderId: "D", recipientId: "G", text: "D>G", date: Date().addingTimeInterval(2)).insert(db)
    try Message(id: "4", senderId: "D", recipientId: "A", text: "D>A", date: Date().addingTimeInterval(3)).insert(db)
    try Message(id: "5", senderId: "A", recipientId: "B", text: "A>B", date: Date().addingTimeInterval(4)).insert(db)
}

// MARK: -

struct ContactChatInfo: Decodable, FetchableRecord {
    var contact: Contact
    var lastMessage: Message
}

extension ContactChatInfo {
    static func fetchAll(_ db: Database, forContactId contactId: String) throws -> [ContactChatInfo] {
        try SQLRequest<ContactChatInfo>("""
            SELECT
                c2.*,
                m.id,
                m.senderId,
                m.recipientId,
                m.text,
                MAX(m.date) AS date
            FROM message m
            INNER JOIN contact c1 ON c1.id IN (m.senderId, m.recipientId)
            INNER JOIN contact c2 ON c2.id IN (m.senderId, m.recipientId) AND c1.id <> c2.id
            WHERE c1.id = \(contactId)
            GROUP BY c2.id
            ORDER BY date DESC;
            """)
        .adapted { db in
            let adapters = try splittingRowAdapters(columnCounts: [Contact.numberOfSelectedColumns(db)])
            return ScopeAdapter([
                "contact": adapters[0],
                "lastMessage": adapters[1]])
        }
        .fetchAll(db)
    }
}

try dbQueue.read { db in
    for contact in try Contact.fetchAll(db) {
        print(contact)
        for info in try ContactChatInfo.fetchAll(db, forContactId: contact.id) {
            print("-", info)
        }
    }
}
```

</details>

**Comment by darrarski** [comment]
Wow, that looks great. Thanks @groue!

I need to learn more about scope adapters in GRDB for sure. One more thing I'm missing, is count of unread messages ('Message.isUnread == true') to each 'ContactChatInfo'. I think it should be possible using the "raw SQL query + scope adapters" way. I'll let you know when I implement the final solution to the problem.

Thanks again!

**Comment by groue** [comment]
Adapters are pretty low-level, but hey have their uses. A working example is always a good way to start, because now _you know_ that there's something here that helps decoding database rows into structs that have record properties.

I'm looking forward for your final solution :-)

**Comment by darrarski** [comment]
I've updated my original fetch request from the issue description. Now it looks like this:

```swift
SQLRequest(
  sql: """
    SELECT
      -- All contact columns:
      c2.*,
      -- All message columns:
      m.*,
      -- Latest message date column:
      MAX(m.date) AS date
    FROM
      messages m
    INNER JOIN contacts c1
      ON c1.id IN (m.senderId, m.recipientId)
    INNER JOIN contacts c2
      ON c2.id IN (m.senderId, m.recipientId)
      AND c1.id <> c2.id
    WHERE
      c1.id = :userId
    GROUP BY
      c2.id
    ORDER BY
      date DESC;
    """,
  arguments: [
    "userId": query.userId
  ]
)
.adapted { db in
  let adapters = try splittingRowAdapters(columnCounts: [
    Contact.numberOfSelectedColumns(db)
  ])
  return ScopeAdapter([
    ContactChatInfo.Column.contact.rawValue: adapters[0],
    ContactChatInfo.Column.lastMessage.rawValue: adapters[1],
  ])
}
```

[Here](https://git.xx.network/elixxir/client-ios-db/-/blob/c8bf7f052a795d19ec8d1cf30dd54748950d519e/Sources/XXDatabase/ContactChatInfo%2BGRDB.swift) you find it in its full context. This feature is being developed on a [separate branch](https://git.xx.network/elixxir/client-ios-db/-/tree/feature/db-models-3). I'm trying to keep it up to date with all the changes I made thanks to your support.

I don't mind the lack of a strongly typed interface for building this query, because of the test coverage. All my tests are passing now! 🎉

Next step is figuring it out how to add `unreadCount: Int` property to `ContactChatInfo` model. Still working on it. If you have some hints on how to do it, please share them with me :-)

**Comment by groue** [comment]
> Next step is figuring it out how to add `unreadCount: Int` property to `ContactChatInfo`

Perform two queries, and join the partial results together into your final output.

---

People often look for one big GRDB expression, or one big SQL query that does everything they need in one strike.

That's mislead at multiple levels.

The first misunderstanding is thinking that one read access must perform one request. This is incorrect. All GRDB read accesses allow to run multiple queries (including database observation). You can always run as many requests as you want, and join them together with your regular programmer skills.

The second misunderstanding is thinking that it's _always_ better to perform one single request, because _some_ database accesses are indeed better when written as a single request. Again, this is incorrect. The topic has always been algorithmic complexity (which means how your code behaves when the number of inputs grows), and I/O latency (quite reduced with SQLite).

The third misunderstanding is thinking that the ability to perform an SQL or GRDB _tour de force_ is a desirable skill. Nothing is more wrong. large cathedral requests are very difficult to understand and maintain.

In your case, running two requests instead of one does not sound frightening to me.

Use your experience, your technical intuition, and run experiments. For example, feed your app with a huge number of contacts or messages, and see how it behaves. Maybe your code needs refactoring. Maybe SQLite needs indexes. Only you can discover.

In all cases, aim at correctness first. Optimize later.

**Comment by groue** [comment]
So... @darrarski, it looks like we can close the issue, since the main question found an answer. Feel free to continue the conversation, reopen the issue, or open a new issue as you wish :-)
