### ISSUE TITLE
Migrator dies when altering a table

### ISSUE THREAD

**Issue by ggoraa** [groue/GRDB.swift#1230]
### What did you do?

Set up a migration, where I alter a database, and inside that alteration, I drop a column

### What did you expect to happen?

For the migration to run successfully and update my database

### What happened instead?

The migrator died for some reason

```
2022-06-05 16:11:57.691730+0300 Moc[88506:4243438] Caching/CacheService.swift:32: Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1: near "DROP": syntax error - while executing `ALTER TABLE "chatFilter" DROP COLUMN "unreadCount"`
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24.1
**Installation method:** SPM
**Xcode version:** 13.3.1
**Swift version:** 5.6
**Platform(s) running GRDB:** macOS 12.4
**macOS version running Xcode:** macOS 12.4

### Demo Project

The project itself: https://github.com/ggoraa/moc/tree/2227e889745e5549b26150b10a67ca34911cf83d

Before building the project, run `./environment.sh 123456 qwertyuiop` in the project directory
The arguments are there to make the script happy, they are not relevant in this case

Code that fails:
```swift
private func registerMigrations() {
    migrator.registerMigration("v1") { db in
        try db.create(table: "chatFilter") { t in
             t.column("title", .text).notNull()
             t.column("id", .integer).notNull().primaryKey(onConflict: .replace, autoincrement: false)
             t.column("iconName", .text).notNull()
             t.column("unreadCount", .text).notNull()
             t.column("order", .integer).notNull().unique(onConflict: .replace)
         }
     }
     migrator.registerMigration("v1.1") { db in
         try db.create(table: "unreadCounter") { t in
             t.column("chats", .integer).notNull()
             t.column("messages", .integer).notNull()
             t.column("chatList", .text).notNull().unique(onConflict: .replace)
         }
         try db.alter(table: "chatFilter") { t in
             t.drop(column: "unreadCount")
         }
     }
 }
```

### Additional info

So, I did some research on this topic, and here are my conclusions

SQLite didn't support ALTER TABLE DROP COLUMN up to version 3.35, only renames or additions of new columns could've been done. But macOS 12.4 is rocking 3.37, which is interesting, to say the least
And when I do all of this manually (creating a table, then dropping a column), it works like a charm! I have no idea why GRDB died at that moment 🧐

**Comment by groue** [comment]
Hello @ggoraa,

So it looks like your app:

- Imports GRDB via SPM, so it uses the SQLite version that ships with the OS.
- When it runs on macOS 12.4, SQLite does not support ALTER TABLE DROP COLUMN.

Is that correct? That's unexpected indeed.

I do not have any macOS 12.4 (I run on 12.3.1 currently). What happens when you run those lines in a terminal? Could you please paste the verbatim, including any eventual error?

```
% sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
% sqlite3 
SQLite version 3.37.0 2021-12-09 01:34:53
sqlite> create table t(a, b);
sqlite> alter table t drop column a;
sqlite>
```

**Comment by ggoraa** [comment]
> What happens when you run those lines in a terminal? Could you please paste the verbatim, including any eventual error?

Well, in my original comment there is an "additional info" section at the end, with the exact info you were looking for

**Comment by groue** [comment]
Yes, please pardon my wish to test expectations.

So: `alter table t drop column a` does not fail: SQLite 3.37 that ships with macOS 12.4 is able to drop columns. That's a relief.

(Just as you said.)

> I have no idea why GRDB died at that moment

Me neither. Technically, the `try!` in your source made your app "die". But anyway, just like you, I don't know why SQLite raised an error.

[Your migrator](https://github.com/ggoraa/moc/blob/2227e889745e5549b26150b10a67ca34911cf83d/Caching/Sources/Caching/CacheService.swift) looks correct. Maybe [those lines](https://github.com/ggoraa/moc/blob/2227e889745e5549b26150b10a67ca34911cf83d/Caching/Sources/Caching/CacheService.swift#L28-L33) could be replaced with a plain `try! migrator.migrate(dbQueue)` (since a migrator knows how to only run unapplied migration, this is its job), but this is not related to the error.

I'm afraid you'll have to make more investigation...

**Comment by groue** [comment]
Hello @ggoraa, did you find a way to reproduce this error?

**Comment by ggoraa** [comment]
> Hello @ggoraa, did you find a way to reproduce this error?

Hello! Currently I was only able to make it trigger the error in my app's environment, but not when accessing the database directly. I will also try reproducing the bug on macOS Ventura, maybe it will help

**Comment by groue** [comment]
> Currently I was only able to make it trigger the error in my app's environment

I could help if you could share a reproducing sample code or project.

**Comment by ggoraa** [comment]
> I could help if you would share a reproducing sample code or project.

wellll it's already in the issue description, right at the end before "additional info" 😁

**Comment by groue** [comment]
A good sample code or project is short, focused, and does not require the tester to make an act of faith (run untrusted code). The ideal, in such case, is a [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). The key words are:

- minimal: easily inspectable in order to build trust
- reproducible: focused on the topic

Your project is big, with a script to run first. I'd have to spend a lot of time inspecting it. Fortunately, I quickly found that the script would install software on my machine. This is not acceptable, I'm sorry!

You did not intend to be rude, I know. But this isn't quite a correct way to ask for help either. Please aim at minimal reproducible examples.

**Comment by groue** [comment]
Since I had a few other minutes to give, I assumed that the failing migrator was the one in `CacheService`.

So I added a test to the Caching package, and ran on macOS 12.4:

```swift
import XCTest
@testable import Caching

class CachingTests: XCTestCase {

    func testExample() throws {
        let service = CacheService()
    }
}
```

There is no error.

**Comment by ggoraa** [comment]
> You did not intend to be rude, I know. But this isn't quite a correct way to ask for help either. Please aim at minimal reproducible examples.

Oh, I am very sorry! I will try to make a minimally reproducible example ASAP

> There is no error 🤷‍♂️

Well that's awkward

I thought it was failing while editing an existing, populated database, but it was breaking even when deleting the database file, which is even more strange
I will inspect closer all of my code, maybe I can find the cause, big thanks!

**Comment by groue** [comment]
Issues don't stay open unless someone is working on them. Please just reopen when you have some news, @ggoraa! Happy GRDB!

**Comment by ggoraa** [comment]
Sorry for not responding for long! I just didn't make it work in a clean project
Maybe I messed up somewhere
Anyways, i think it's just a local issue, so it can be easily marked as done
