### ISSUE TITLE
Value Observation in GRDB 4 versus 5

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#1236]
### Using ValueObservation in GRDB 4
I was wondering if the `observationForAll` function in GRDB 4 (yes I know, we need to update) reports changes if the root object in the case of a one-to-many associations is modified.

#### Code Example
```swift
struct Team: TableRecord, EncodableRecord {
    var name: String
    static let players = hasMany(Player.self)
    var players: QueryInterfaceRequest<Player> {
        return request(for: Team.players)
    }
}

var observation = team.players.observationForAll()
observation.scheduling = .async(onQueue: DispatchQueue.global(), startImmediately: false)
let transactionObserver = try observation.start(in: dbPool, onChange: { players in
					updatedChanges(players)
}

// Only update the team name
team.name = "New Team Name"
try team.update(db)
})
```

### Behavior
In our current codebase, it looks like the observation is reported for a root object change. 
Is this a valid assumption? 

In the above example, will the `updatedChanges` be called after the `.update(db)`? 
If so, any mechanism in GRDB 4 to only be notified of children record changes? Or we need to migrate to 5 which has more flexibility?

Merci 
### Environment

**GRDB flavor(s):** GRDB
**GRDB version:4.14
**Installation method:** CocoaPods
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** macOS

**Comment by groue** [comment]
Hello @martindufort!

> In our current codebase, it looks like the observation is reported for a root object change.
> Is this a valid assumption?

No it is not. In GRDB 5, only transactions that modify players would trigger the observation. If you describe the actual GRDB 4 behavior, this behavior is not the intended one.

_Maybe_ `team.update(db)` does indeed trigger modifications in players due to [conflict resolution](https://www.sqlite.org/lang_conflict.html)?

_Maybe_ the SQLite version you are running notifies changes in an unexpected way?

_Maybe_ GRDB 4.14 has a bug?

_Maybe_ you misinterpreted the behavior of your app?

I can't tell 😅 

> In the above example, will the updatedChanges be called after the .update(db)?

It will not with GRDB 5 (assuming the transaction does not modify players).

> If so, any mechanism in GRDB 4 to only be notified of children record changes?

Yes, it is [ValueObservation.tracking(_:fetch:)](https://github.com/groue/GRDB.swift/blob/v4.14.0/README.md#valueobservationtracking_fetch):

```swift
let observation = ValueObservation.tracking(team.players, fetch: { db in
    try team.players.fetchAll(db)
})
```

> Or we need to migrate to 5 which has more flexibility?

Migrating would bring you more control, and probably less bugs 😉 The [Migrating From GRDB 4 to GRDB 5](https://github.com/groue/GRDB.swift/blob/master/Documentation/GRDB5MigrationGuide.md) guide should help 🤞 

Your code, in GRDB 5, would read:

```swift
let observation = ValueObservation.tracking { db in
    try team.players.fetchAll(db)
}
let cancellable = observation.start(
    in: dbPool,
    scheduling: .async(onQueue: DispatchQueue.global())
    onError: { error in ... },
    onChange: { players in ... })
```

GRDB 5 would allow to answer your initial question with the `observation.print()` debugging api. The observation would print what it does, and especially which [database region](https://github.com/groue/GRDB.swift/blob/master/README.md#databaseregion) is tracked:

```swift
// Prints:
// - start
// - fetch
// - tracked region: player(id,name,teamId)
// - value: [Player(id: 1, ...), Player(id: 2, ...)]
// - cancel
let cancellable = observation
    .print()
    .start(...)
```

Here the tracked region is `player(id,name,teamId)` (the full `player` table). The `team` table is *not tracked*.

<details><summary>Click here for the full sample code</summary>

```swift
import GRDB

struct Team: Codable, Identifiable, FetchableRecord, PersistableRecord {
    var id: Int64
    var name: String
    
    static let players = hasMany(Player.self)
    
    var players: QueryInterfaceRequest<Player> {
        request(for: Self.players)
    }
}

struct Player: Codable, Identifiable, FetchableRecord, PersistableRecord {
    var id: Int64
    var teamId: Int64
    var name: String
}

let dbQueue = DatabaseQueue()

try dbQueue.write { db in
    try db.create(table: "team") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text).notNull()
    }
    
    try db.create(table: "player") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("teamId", .integer).references("team").notNull()
        t.column("name", .text).notNull()
    }
    
    try Team(id: 1, name: "Red").insert(db)
    try Team(id: 2, name: "Blue").insert(db)
    
    try Player(id: 1, teamId: 1, name: "Red 1").insert(db)
    try Player(id: 2, teamId: 1, name: "Red 2").insert(db)
    try Player(id: 3, teamId: 2, name: "Blue 3").insert(db)
    try Player(id: 4, teamId: 2, name: "Blue 4").insert(db)
}

let team = try dbQueue.read { try Team.fetchOne($0, id: 1)! }

// Prints:
// - start
// - fetch
// - tracked region: player(id,name,teamId)
// - value: [Player(id: 1, ...), Player(id: 2, ...)]
// - cancel
_ = ValueObservation
    .tracking(team.players.fetchAll)
    .print()
    .start(in: dbQueue, scheduling: .immediate, onError: { _ in }, onChange: { _ in })
```

</details>

**Comment by martindufort** [comment]
Thanks @groue 

### Your questions
> Maybe team.update(db) does indeed trigger modifications in players due to [conflict resolution](https://www.sqlite.org/lang_conflict.html)?

There is no conflict resolution in place that would affect that

> Maybe the SQLite version you are running notifies changes in an unexpected way?
Possible but unlikely

> Maybe you misinterpreted the behavior of your app?

Most likely the case 😆 

### Resolution
Let me schedule time to update to **GRDB 5** and use the provided mechanisms to discover why I don't understand the complete behavior or the side-effects of our app. 

You can close this and I will report back later. 
Thanks - Martin

**Comment by groue** [comment]
All right Martin! I hope the migration will be smooth :-)
