### ISSUE TITLE
Best practices for fetching from a list of IDs?

### ISSUE THREAD

**Issue by spicymatt** [groue/GRDB.swift#1237]
hello Gwendal,
Kudos on your great work on GRDB.

I was reading through your performance tests and was wondering whether you had done some fetch performance testing when dealing with object lists. For example, fetch 100, 1000, 10000 records for which I know their ID from a database of 1M records.
Are there some strategies that are better than others, tuned for list size. For small lists, is it more efficient to use a query such as "... where id IN <list>" or is it always faster to fetch one record at a time. For longer list are there some recommended best practices to achieve maximum performance.
Sorry if this a naive question or if this has been answered already (could not find it).
Take care.

**Comment by groue** [comment]
Hello @spicymatt,

No, I did never perform such tests myself 🙂 

Clearly first perform a plain `MyRecord.fetchAll(db, ids: [...])`, which generates the `... WHERE id IN (...)` SQL.

If this is too slow (according to some expectation you did not disclose), get inspired from the _plain struct optimized for fetching performance_ in the [Examples of Record Definitions](https://github.com/groue/GRDB.swift/blob/master/README.md#examples-of-record-definitions). This technique is tested as "Optimized Records" in the [performance tests](https://github.com/groue/GRDB.swift/wiki/Performance). It significantly enhances the performances of `MyRecord.fetchAll(db, ids: [...])` and all regular query interface requests, because all string-based conveniences are avoided during row decoding (i.e. Codable machinery, string comparisons and dictionary lookups).

And finally, I'd probably perform some of the experiments you mentioned. Some people would tweak the schema in order to replace a string primary key with the [rowid](https://www.sqlite.org/rowidtable.html). Some other people would also fine tune SQLite parameters in order to squeeze the last bits of performance (I'm totally unaware of this topic). Eventually, I guess the best strategy starts to depend on the hardware and operating system version 🥵

You have all the apis you need to perform those checks, and Instruments to profile your app. Setup some clear performance expectations, report your progress towards them, and ask questions if you have any!

**Comment by spicymatt** [comment]
Thanks @groue for the quick and precise answer. 
We are aware of fetching improvements that come with optimized structs as clearly explained in the doc. BTW, the benchmark page is very helpful (I use the opportunity to mention a small link error in the **fetch/insert** hyperlink under **Optimized Records** as they point to the non-optimised code).
We will put it to the test.... 
I did not realize that fetchAll(db, ids:...) was available and never really explored such queries. I was worried that a 'SELECT IN...' could become very large with thousands of IDs passed and somewhat hit a limit on query size. But after confirming that the max query length is set at 1,000,000 I guess that it works in most of my use cases
We do have, indeed, all we need (apis, documentation...)
Thanks a lot.

**Comment by groue** [comment]
> TW, the benchmark page is very helpful (I use the opportunity to mention a small link error in the fetch/insert hyperlink under Optimized Records as they point to the non-optimised code).

Thanks :-)

> I did not realize that fetchAll(db, ids:...) was available and never really explored such queries.

There are quite a few ways to fetch by id indeed:

```swift
let ids = [1, 2, 3, ...]

// Explicit filter:
let records = try R.filter(ids.contains(Column("id"))).fetchAll(db)

// Shorthand syntax for primary key filter:
let records = try R.fetchAll(db, keys: ids)
let records = try R.filter(keys: ids).fetchAll(db)

// `Identifiable` records can profit from more type safety,
// where only collection of `ID` are accepted:
let records = try R.fetchAll(db, ids: ids)
let records = try R.filter(ids: ids).fetchAll(db)
```

It is not a mistake to use one form or the other, because they are all equivalent! There are a lot of choices, but some GRDB users target operating systems were `Identifiable` is not yet available, for example.

> But after confirming that the max query length is set at 1,000,000

Yes. You can access this value at runtime (it may depends on operating system version), and batch your requests if needed:

```swift
let ids = [1, 2, 3, ... ]
let records: [R] = try dbQueue.read { db in
    if ids.count > db.maximumStatementArgumentCount {
        // Oops, we need to perform several requests
        // Use https://github.com/apple/swift-algorithms/blob/main/Guides/Chunked.md
        return try ids
          .chunks(ofCount: db.maximumStatementArgumentCount)
          .flatMap { try R.fetchAll(db, ids: $0) }
    } else {
        return try R.fetchAll(db, ids: ids)
    }
}
```

It's unclear whether such batching should be automatically performed by GRDB - it's not *always* possible to do it, and I decided to wait and see 😬 

> Thanks a lot.

You're welcome! Thanks for your question and your interest :-)
