### ISSUE TITLE
Setup with custom SQLCipher build 

### ISSUE THREAD

**Issue by AKoulabukhov** [groue/GRDB.swift#1244]
### What did you do?

As SQLCipher currently doesn't support integration via SPM I'm looking for solution to integrate GRDB with custom SQLCipher build. As far as I understand it's possible to compile own SQLCipher following the [instruction](https://www.zetetic.net/sqlcipher/ios-tutorial/) and embed it into xcframework to be able to use SPM with precompiled binary. Also GRDB supports custom SQLite builds.

### What did you expect to happen?

I'm looking for support on how to glue things together to have SPM package with custom SQLCipher build until SQLCipher will support SPM. Thanks in advance.

**Comment by groue** [comment]
Hello @AKoulabukhov,

Your request falls beyond the scope of the free support brought by this library. Here is not the right place to discuss SPM limitations.

GRDB supports custom SQLite builds via a tremendous contribution (#62). Maybe someone will do the same for SQLCipher one day, _with the same level of quality and ease of maintenance through 6+ years_. I do not hold my breath, because good build engineers are not so common (and I am not one of them).

My advice is to reconsider CocoaPods, or to look for an existing GRDB fork that uses SQLCipher through SPM in the [network](https://github.com/groue/GRDB.swift/network) page. You will find some.
