### ISSUE TITLE
Distribute binary framework for release 0.80.2

### ISSUE THREAD

**Issue by craigzour** [groue/GRDB.swift#125]
Hi,

Quick question ! Would it be possible for you to bundle the compiled Framework with the 0.80.2 release ?

It takes too much time to build... It would be faster if we only had to download it.

**Comment by groue** [comment]
Hello @craigzour,

I can't tell, from your quick question, if you mismatch the compilation time of GRDB with the compilation time of your application.

Xcode compile sources that don't change only once. This initial compilation of GRDB may be long, but it should not be a recurring problem that can plague a developer's life.

**Comment by craigzour** [comment]
@groue I am using Carthage to import your library to my project. Each time I am calling carthage update it is doing a checkout of your sources and then building it. If you were providing a .framework.zip, Carthage would not have to build because it would just download it. You can look at  this example: https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.2.1 (Downloads part)

**Comment by groue** [comment]
Did you consider opening an issue in the Carthage repo itself? So that all developers of open source libraries don't have to spend their free time fixing their tool?

**Comment by groue** [comment]
@craigzour It looks like Carthage is able to update only a subset of dependencies. Quoting their [0.12 release notes](https://github.com/Carthage/Carthage/releases/tag/0.12):

> `build`, `checkout`, and `update` now take an optional list of dependencies

This may help avoiding a full rebuild of your dependencies. And please be vocal on Carthage repo so that they eventually understand they're creating problems for users (you) who lose time and library developers (me) who have to answer this kind of issue and lose time as well.

**Comment by craigzour** [comment]
@groue :( too bad you did not understand my point. Maybe Carthage is slow maybe not. My point is  I would like to download a fully compiled framework instead of having to build it. By the way the command which does that is carthage archive. Did you check ReactiveCocoa example I gave you ?

**Comment by groue** [comment]
> too bad you did not understand my point

On the contrary, I understand it quite well. And this understanding makes me refusing to access your request.

Your own very ReactiveCocoa example shows how pre-built binaries are not a viable option: there is no pre-built binary in [ReactiveCocoa 4.2.2](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.2.2), mind you. That's because pre-built binaries create their own set of problems, given Swift ABI is not stable - for a short sample: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/608.

Target the real source of trouble: tell Carthage it has to stop spending useless time building frameworks. Or run the `carthage archive` command yourself.

**Comment by craigzour** [comment]
@groue Alright ! Got it :)
