### ISSUE TITLE
SQLite error 13 while creating grdb_issue_102 ?

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1251]
### What did you do?

We have a piece of code that attempts to open the database. If that fails, it destroys the entire folder containing the database and tries recreating it from scratch.

We're seeing a really odd crash coming from some user when trying to open their database. Our logs show something like this in this order:

1.  `Failed opening database, attempting wiping and starting over: SQLite error 13: database or disk is full - while executing CREATE TABLE grdb_issue_102 (id INTEGER PRIMARY KEY)`
2. `Failed creating database/tables, trying to recreate: SQLite error 14: unable to open database file`
3. `Failed opening database, attempting wiping and starting over: SQLite error 13: database or disk is full - while executing CREATE TABLE grdb_issue_102 (id INTEGER PRIMARY KEY)`

I tried to see what's this issue 102 and it seems like it's happening here:
https://github.com/groue/GRDB.swift/blob/e02f2c8abacff2799ed14926edcbf6e76fb9f805/GRDB/Core/DatabasePool.swift#L84-L97

So I'm trying to understand what's happening here - it tries to open the database, bumps into the WAL file missing, tries to create a database table and fails ? 

The disk space error is also strange here because out of 8 crashes, we have 2 over 1GB of available disk space, based on our reports.

### What did you expect to happen?

Understanding what's the real cause of the issue and why wiping the database doesn't seem to help,

### What happened instead?

User crashed and database was unable to be open even after a full wipe

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.24
**Installation method:** xcframework (from Carthage)
**Xcode version:** 13.4.1
**Swift version:** 5.6.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 12.4 

### Demo Project
No reproducible project at the moment, i did confirm the code that destroys the folder indeed works

**Comment by groue** [comment]
Hello Shai,

> So I'm trying to understand what's happening here - it tries to open the database, bumps into the WAL file missing, tries to create a database table and fails ?

Yes it does!

The `grdb_issue_102` table is created and destroyed as a way to support one specific scenario:

1. A non-WAL database exists on disk.
2. The app opens this database with a DatabasePool.
3. The first operation performed by the app is a read.

Without the `-wal` file, SQLite can't perform a read-only access to a WAL database. That's why the `-wal` file is created at step 2 (with the `grdb_issue_102` table), so that step 3 can succeed.

Maybe this trick is a bad idea (we'll see), but so far it has made the life of GRDB users simpler.

---

Let's look at the possible reasons for the SQLITE_FULL error.

[It is documented](https://www.sqlite.org/rescode.html#full):

> The SQLITE_FULL result code indicates that a write could not complete because the disk is full. Note that this error can occur when trying to write information into the main database file, or it can also occur when writing into [temporary disk files](https://www.sqlite.org/tempfiles.html).
>
> Sometimes applications encounter this error even though there is an abundance of primary disk space because the error occurs when writing into [temporary disk files](https://www.sqlite.org/tempfiles.html) on a system where temporary files are stored on a separate partition with much less space that the primary disk.

Full disks are rare, but they do exist 😅

> The disk space error is also strange here because out of 8 crashes, we have 2 over 1GB of available disk space, based on our reports.

OK.

Although I don't know if iOS devices have a special (and small) partition for temp files, to be honest (I'm trying to have your input match with the SQLite documentation).

Now, SQLite sometimes reuses some error codes for other kinds of trouble, so I  [searched Google](http://google.com/search?q=%22SQLITE_FULL%22+site%3Awww.sqlite.org%0D%0A) for the various meanings of SQLITE_FULL.

It is also thrown [when SQLite can't generate a new unique rowid](https://www.sqlite.org/autoinc.html).

I could not find any other documented interpretation of SQLITE_FULL on the website.

For extra certainty, I've even searched SQLITE_FULL in sqlite3.c. Definitely, there are only two possible reasons for this error if this file:

- disk full (no room on the device)
- table full (no free rowid in a table)

Apple ships a custom version of SQLite, so we can not be 100% certain they do not throw SQLITE_FULL for some extra reason.

Do you have more information about those 8 users? Is it their first installation of the app? Do they migrate from an old version of the app which did not use a DatabasePool? Any specific OS version?

**Comment by groue** [comment]
A big search of SQLITE_FULL and "database or disk is full" on Google could bring more information that relate to what you know about your database and your users.

**Comment by groue** [comment]
> 8 users

This is really not much: you really go the extra mile for solving the issues met by so few people!

As the GRDB maintainer, I'm always supportive for this kind of dedication: solving this issue for your app could solve it for other users as well.

There are two areas where I lack experience, but feel like there is room for "problems":

- An SQLite file can become really big, even if the database does not contain much information, because space that turns unused is not reclaimed on disk until a VACUUM. There exist a feature named "auto-vacuum", but I don't have any experience with it. On top of that, A VACUUM operation requires roughly twice the disk space as the database, which means that it may be impossible to perform one, exactly when it is dearly needed! Again, I don't have much experience or good practices to share about this.
- A read-only transaction (DatabasePool read) prevents [WAL checkpointing](https://www.sqlite.org/pragma.html#pragma_wal_checkpoint), which means that the -wal journal file can become quite big as well. Can this create any issue? I don't know.

I don't even know which kind of instrumentation could help figuring out the behavior of an app deployed in the wild. Maybe monitoring the size of the database and all its [temporary files](https://www.sqlite.org/tempfiles.html) may become interesting at some point?

**Comment by groue** [comment]
Any news, @freak4pc?

**Comment by freak4pc** [comment]
Hey @groue,
I agree 8 users isn't a large amount of go by at the moment. We'll keep monitoring and investigate based on some of the information you shared here.

Thank you :)
