### ISSUE TITLE
Suggestion: Automatic Schema Inference from Property Wrappers

### ISSUE THREAD

**Issue by emoonadev** [groue/GRDB.swift#1280]
Hi,

This is the best lib for SQLite.

Currently you can add inter row by giving an object that conform to codable, you know map the files to his table column.

I want to ask if there is a reason why for create table you must set each column manually?
If the object conform to codable I suppose that you can get each fields name and fields type to create the column automatically?

```swift
typealias Persistable = Codable & FetchableRecord & PersistableRecord & TableRecord & Identifiable

struct Player: Persistable {
    var id: UUID
    var name: String
}

// Instead of below:
try db.create(table: Player.databaseTableName, options: [.ifNotExists]) { t in
t.column("id", .text).primaryKey()
t.column("name", .text).notNull()
}

//Use
try db.create(table: Player.self, options: [.ifNotExists])
```
I suppose with the codable you can know the type of the property by casting it to set the correct `ColumnType`, and if is `Optional` or not  to set `.notNull()` (if not let use `propertyWrapper` below to know that)

But something is missing how you can add column definition for each field? Using power of swift with `PropertyWrapper`

```swift
struct Player: Persistable {
    @Persisted var id: UUID
    @Persisted(definition: { d in d.unique() }  var name: String
}

try db.create(table: Player.self, options: [.ifNotExists])
```

With `propertyWrapper` I suppose that you can get all missing info to build column. If property not wrapped with `Persisted` don't create column and when trying to save or fetch this field ignore it. Use only properties that wrapped (Like realm)

It will be perch, what do you think about it? ISound to you possible?

**Comment by groue** [comment]
Hello @emoonadev,

Thanks for the compliment, and the suggestion!

There are two main reasons that prevent the library from providing such a feature.

---

First, the library does not only want to help you build your application. It also wants to remain useful as you ship new versions of your app over time.

GRDB assumes that when your app is installed on a device, it may find on disk an SQLite database that does not match the record types defined in your Swift code, and wants to bring it up-to-date.

Bringing a schema up-to-date automatically from Swift record types (creating database tables, modifying others, and deleting obsolete ones) is possible (many libraries do this), but it can only create a database schema of limited quality. It is impossible, when looking at Swift record types alone, to create all relevant indexes, foreign keys, check constraints, views, maybe triggers, and generally to enable the SQLite features that your app may need.

Sure, this "limited" quality can be "good enough". But the library aims at helping everybody, including users who need specific SQLite features, and need more than "good enough".

Often, users who are satisfied with "good enough" eventually learn something useful about SQLite, and want to apply their new knowledge.

Eventually, programmers start to understand the importance of their database schema, that SQLite has generally much less bugs than their application code, and that they can trust it for the storage and integrity of their precious users' data.

That's why GRDB follows them along, and ships with [migrations](https://github.com/groue/GRDB.swift/blob/master/Documentation/Migrations.md), a tool that aims at addressing the needs of everybody. Writing `try db.create(table: ...)` is boring as hell, but it is not difficult. And it supports all use cases, from the most naive to the most expert.

---

Next, the property wrappers provided by the Swift language are limited in a very important way. They can only store information in an **instance** of a record type. It is impossible to store information in the type itself. This is how the language has specified property wrappers.

Given this, your sample code looks nice, but it contains dead-ends.

```swift
struct Player: Persistable {
    @Persisted var id: UUID
    @Persisted(definition: { d in d.unique() }  var name: String
}
```

First, the `@Persisted(definition: ...)` can't support the `Decodable` protocol, because `Decodable` does not provide the `definition` when decoding a database row. It just can't access static information. That's how property wrappers are designed by the language.

Next, if one would want to infer a (limited) database schema from this type, one would need to create a `Player` instance in order to to access its properties. Again, that's how property wrappers are designed by the language. So we need an `init()` without any parameter in order to create this instance.

Some other libraries out there (e.g. [Fluent](https://docs.vapor.codes/fluent/overview/)) use such a technique: they define "static" information with property wrappers, and require a blank `init()` (because this "static" information is, well, not static at all). There is a consequence: they allow the creation of **invalid** instances: a Player without any `id` or `name`: `Player()`.

This blank `init()` gives me the shivers. It is just begging for runtime bugs, surprising behaviors, or crashes:

```swift
func printPlayerName(_ player: Player) {
    print(player.name)  // 😰
}
let player = Player()   // 😈
printPlayerName(player) // 💣
```

That's why I decided that GRDB records build on top of the same 100% trustable types you use everyday:

```swift
// 100% certain that it is impossible to create an invalid player
struct Player {
    var id: UUID
    var name: String
}

// 100% trustable
func printPlayerName(_ player: Player) {
    print(player.name)
}

// Add database powers if you want
extension Player: FetchableRecord, ... { }
```

---

In the end:

- Yes, GRDB wants you to define your schema by hand. It is boring... until it is useful.
- No, GRDB does not use property wrappers. They are just not well-suited for the job.

**Comment by groue** [comment]
OK, I suppose you have an answer to your question, and I can close the issue. Please reopen if you think something has to be added, and happy GRDB!
