### ISSUE TITLE
Crash on "

### ISSUE THREAD

**Issue by skreutzberger** [groue/GRDB.swift#129]
The framework seems to internally use `try!` when executing statements which lead to a hard crash if the query is not perfect. A big No-No for Swift which should never crash in front of a user.

Anyway, here is what happens:
My user enters astring in the front end and I am using that string as value for one of the `StatementArguments`.

The crash occurs now at `Row.fetch` the call:
```Swift
 db.inDatabase { db in
            for row in Row.fetch(db, sql, arguments: StatementArguments(args)) {
```

Here is the crash output from console when `message = 'foo "'`:

fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1 with statement ` SELECT e.id, e.deviceID, e.level, e.appVersion, e.appBuild, e.session, e.thread, e.fileName, e.function, e.line, e.timestamp, e.status, messages.message, devices.uuid, devices.userName FROM entries as e INNER JOIN messages ON e.id = messages.id INNER JOIN devices ON e.deviceID = devices.id WHERE e.timestamp < 4102358400.0 AND messages.message MATCH :message ORDER BY e.timestamp DESC LIMIT 50` arguments [message:"foo \""]: malformed MATCH expression: [foo "]: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.46.2/src/swift/stdlib/public/core/ErrorType.swift, line 178
2016-09-26 08:52:09.382465 Project[56385:2104611] fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1 with statement ` SELECT e.id, e.deviceID, e.level, e.appVersion, e.appBuild, e.session, e.thread, e.fileName, e.function, e.line, e.timestamp, e.status, messages.message, devices.uuid, devices.userName FROM entries as e INNER JOIN messages ON e.id = messages.id INNER JOIN devices ON e.deviceID = devices.id WHERE e.timestamp < 4102358400.0 AND messages.message MATCH :message ORDER BY e.timestamp DESC LIMIT 50` arguments [message:"foo \""]: malformed MATCH expression: [foo "]: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.46.2/src/swift/stdlib/public/core/ErrorType.swift, line 178

The crash occurs even if I wrap the `"` into a `\\\"`. Something else Xcode does not allow me to do. How can I fix it or better: can GRDB stop using `try!`?

**Comment by groue** [comment]
> The framework seems to internally use try! when executing statements which lead to a hard crash if the query is not perfect. A big No-No for Swift which should never crash in front of a user.

[GRDB Error handling](https://github.com/groue/GRDB.swift#error-handling) is more subtle than that. Let me guide you through it:

The `message` argument contains "foo \"" which is an invalid operated of the MATCH operator.

Maybe this is a bug in your application, and you have to fix it.

Maybe the message comes from some *untrusted* source (the user, some internet request...). In this case, you have one alternative:

- Either you escape the untrusted message so that it doesn't trigger unwanted FTS features (turn the message back to a trusted input).
- Either you want to let anything go and catch errors: this is covered by the [How to Deal with Untrusted Inputs](https://github.com/groue/GRDB.swift#how-to-deal-with-untrusted-inputs) paragraph of the documentation.

**Comment by skreutzberger** [comment]
You are right, I double-checked the query in a SQLite Browser and it seems that `MATCH` does not like having a `"` in it at all. Even if it is properly escaped. So my solution is now to remove all `"` from the user input. Thanks!

**Comment by groue** [comment]
You're welcome! SQLite support for full text searches is powerful, but sometimes it bites, I agree...

Turning naive user query strings into valid [full-text Index queries](https://www.sqlite.org/fts3.html#full_text_index_queries) is hard! A reminder of the various queries, and magic characters and words:

- Token queries: `MATCH 'Database'`
- Token prefix queries: `MATCH 'data*'`
- Document prefix queries: `MATCH '^data'`
- Phrase queries: `MATCH '"Lady Gaga"'`
- Near queries: `MATCH 'Lady NEAR Gaga'`
- Boolean queries: `MATCH 'Lady AND Gaga'` (OR and NOT are also magic words)
- Columned queries: `MATCH 'subject:Database'`
- Complex queries: `MATCH 'subject:^data* AND Madonna NEAR/6 "Lady Gaga"'`

User input really needs to be escaped in order to prevent both unwanted syntax errors and unwanted features in the SQLite parser for full text index queries. If you acheive this *tour de force*, @skreutzberger, I'd be very interested integrating your solution as a step towards the completion of #92.

**Comment by skreutzberger** [comment]
Currently I need to escape the user input in the following way:

```swift
cleanedMessage = message.replace("\"", replacement: "")
cleanedMessage = cleanedMessage.replace("\\", replacement: "")
cleanedMessage = cleanedMessage.replace("(", replacement: "")
cleanedMessage = cleanedMessage.replace(")", replacement: "")
conditions += " AND messages.message MATCH :message"
args["message"] = cleanedMessage as Any?
```
`args` is used as parameter of `StatementArguments()` and `conditions` is used to create the value of the `WHERE` condition in the `sql` string.  So it seems the `"`, `(` and `)` are toxic for a MATCH value.

**Comment by groue** [comment]
OK, backslashes and parenthesis can be toxic as well. And when I look at the [list of various queries above](https://github.com/groue/GRDB.swift/issues/129#issuecomment-249515014), I think that the presence of AND, OR, NEAR, NOT (uppercase) may also be toxic, and maybe also `/`, `*`, `^` in various edge cases. The definitive reference is of course https://www.sqlite.org/fts3.html. I recommend a long long long test suite that tries a lot of vicious edge cases (you never know what people type or paste in a text field)

**Comment by skreutzberger** [comment]
Yes, I run tests with your query examples and need to also filter `AND`, `NOT`, etc.

Here is my new cleaning logic:

```swift
let illegalWords = ["\"", "\\", "(", ")", "and", "AND",
                   "or", "OR", "not", "NOT", "near", "NEAR"]
for word in illegalWords {
    msg = msg.replace(word, replacement: "")
}
```
