### ISSUE TITLE
Why do you set up the database multiple times on Persistence.swift?

### ISSUE THREAD

**Issue by filipealva** [groue/GRDB.swift#1308]
### What did you do?

I'm playing with the demo apps to understand GRDB in practice better so I can create a wrapper around it.

### What did you expect to happen?

Maybe I got something wrong, but I thought setting up the database file should happen only once per installation. 

### What happened instead?

Per the `Persistence.swift` file, it will happen every time that `AppDatabase.shared` is initialized, which will happen once per session.

I'm assuming that the code that runs on `private static func makeShared() -> AppDatabase`  will take effect once per installation anyway. It seems to me that there's no point in creating the directory that holds the `.sqlite` file again every time `AppDatabase.shared` is initialized.

If I'm setting a database for a production app, should I check if the database file was already set up when launching the app? Or is it safe to run this database file set up more than once? 

Thank you, and congratulations on the great work on GRDB 👏

**Comment by groue** [comment]
Hello @filipealva,

> Maybe I got something wrong, but I thought setting up the database file should happen only once per installation.

Yes, this is my expectation as well. The database file should be created on initial application lauch. On future launches, nothing should happen.

You'll see that the database setup runs methods and functions that _do nothing_ if the file system is already in the expected state 🙂 

> Per the Persistence.swift file, it will happen every time that AppDatabase.shared is initialized, which will happen once per session.

Yes, this is correct.

> I'm assuming that the code that runs on private static func makeShared() -> AppDatabase will take effect once per installation anyway.

It runs once per session, and does nothing if it has already run in a previous session (except creating an SQLite connection).

> It seems to me that there's no point in creating the directory that holds the .sqlite file again every time AppDatabase.shared is initialized.

That's why `try fileManager.createDirectory(at: folderURL, withIntermediateDirectories: true)` does nothing if the directory already exists.

> If I'm setting a database for a production app, should I check if the database file was already set up when launching the app? Or is it safe to run this database file set up more than once?

It is safe to run this database setup more than once, yes. You'll see it when you run your app multiple times :-)

**Comment by filipealva** [comment]
Nice, thank you for the answer! And sorry for the extra-cautious question, haha. I just wanted to be sure that it was the best way to do it. It clarified a lot for me. 

Happy new year!

**Comment by groue** [comment]
You're welcome! Happy GRDB, and happy 2023 above all!
