### ISSUE TITLE
Do we have a way to synchronously write/read data in my custom thread???

### ISSUE THREAD

**Issue by glve1027** [groue/GRDB.swift#1318]
### What did you do?
Do we have a way to synchronously write data in my custom thread???

### What did you expect to happen?
I want to synchronously write/read data in my custom thread.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)   GRDB
**GRDB version:**  "4.14.0"
**Installation method:** (CocoaPods, SPM, manual?) "Cocoapods"
**Xcode version:** "13.2.1"
**Swift version:** "5.0"
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) "iOS"
**macOS version running Xcode:** "12.5"

### Demo Project
```swift
            var event = ....
            try dbWriter.write { db in  // my thread
                try event.save(db)        // switch to Queue : GRDB.DatabaseQueue (serial) 
            }
```

**Comment by groue** [comment]
Hello @glve1027,

[GRDB concurrency](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/concurrency) is based on  the Dispatch library. Synchronous database accesses call [`DispatchQueue.sync(execute:)`](https://developer.apple.com/documentation/dispatch/dispatchqueue/1452870-sync). This method states in its documentation:

> As a performance optimization, this function executes blocks on the current thread whenever possible.

This documentation does not guarantee that a synchronous database access is performed on the calling thread.

However, since synchronous methods block the current thread until database accesses are completed, you are 100% sure that they are serialized with regard to your custom thread.
