### ISSUE TITLE
Interrupt all connections on a DatabaseQueue or DatabasePool

### ISSUE THREAD

**Issue by palpatim** [groue/GRDB.swift#132]
The sqlite interface provides `void sqlite3_interrupt(sqlite3*);`, which cancels in-process queries on a connection. GRDB provides access to the raw database connection via `db.sqliteConnection`, as you describe in the docs.

However, if there is an in-process query that I want to interrupt, I don't see a way of getting access to the handle, and it would probably be dangerous for me to try in any case.

Is there an API-supported way of interrupting long-running queries?

**Comment by groue** [comment]
Hello @palpatim!

> The sqlite interface provides `void sqlite3_interrupt(sqlite3*);`, which cancels in-process queries on a connection.

I didn't know this function, thanks for talking about it.

> GRDB provides access to the raw database connection via `db.sqliteConnection`, as you describe in the docs.

An area of the doc that should probably be updated: I'm not sure that the SQLite symbols are available right away, without importing extra an extra module: `import SQLiteMacOSX` (`SQLiteiPhoneOS` on iOS, and `SQLiteiPhoneSimulator` on iPhone simulator).

Still, you're right: assuming this import succeeds, the `sqlite3_interrupt` function will be available.

> However, if there is an in-process query that I want to interrupt, I don't see a way of getting access to the handle

If you use a database queue, it's easy because it uses a single connection:

```swift
dbQueue.inDatabase { db in
    sqlite3_interrupt(db.sqliteConnection)
}
```

For database pools, you're out of luck: there is currently no API that would grant you access to all database handles.

> and it would probably be dangerous for me to try in any case.

I don't know sqlite3_interrupt enough to tell.

> Is there an API-supported way of interrupting long-running queries?

As you have guessed, the answer is no.

There are several ways to answer your request:

- one being documenting properly the access to raw SQLite handles, AND provide a new API that gives access to all open database connections. This would help you calling `sqlite3_interrupt`, but this would solve other situations as well.
- another being providing an explicit API

In both case, I need more details and context. I'm interested in the general goal you want to achieve.

*Extra bonus (optional question)*: if you feel comfortable with threads and queues, please tell me more about your scheduling needs. For example, the [releaseMemory](https://github.com/groue/GRDB.swift#memory-management) method blocks the current thread until all database handles have executed the `sqlite3_db_release_memory` functions. **But** it does not prevent concurrent threads from consuming some new memory before it has ended iterating database connections. Would such a model fit your need? Is it too strong? Is it too weak?

**Comment by groue** [comment]
> and it would probably be dangerous for me to try in any case.

Reading [the doc](https://www.sqlite.org/c3ref/interrupt.html) of sqlite3_interrupt I do expect troubles (read crashes) if SELECT queries are interrupted.

**Comment by palpatim** [comment]
Hi @groue, thanks for your prompt response.

Yes, I did note the necessity of the libsql import. :)

My specific use case is that I wish to do database cleanup upon user logout, but there exist a few cases where long-running database queries can block the logout operation. I use a DatabasePool to manage DB access (migrated recently from DatabaseQueue).

There are a number of ways we could manage this, including sandboxing database files by login and performing operations on background threads, but even with those in place, the in-process queries would be consuming CPU and IO resources.

I haven't found any other cases where I need explicit access to all of the SerializedDatabases of a pool--the special case here is that I explicitly want to operate on something that is in process, which the current concurrency model (quite rightly) obscures from public view. That makes me lean toward an explicit `interrupt` API. (In my thinking about this, I modeled an `Interruptible` protocol with one function, `interrupt()` with conformances on DatabaseQueue, DatabasePool and (internally) SerializedDatabase.

Documenting the access would probably be a great addition in any case, along with a note that access to a handle specifically means the handle isn't in use. :)

> Extra bonus (optional question): if you feel comfortable with threads and queues, please tell me more about your scheduling needs:

My read on the `sqlite3_interrupt` docs is that this operates on an in-process query, and that is certainly the use case I'm attempting to solve. The scheduling model you describe for releaseMemory (block the invoking thread on completion of the overall operation, but do not block concurrent threads) seems about right to me. The invoking thread should not return until `sqlite3_interrupt()` has invoked and returned on each connection. But once a connection is interrupted, there is nothing to stop a process from starting another query. `sqlite3_interrupt()` appears to address this in a similar way:

> New SQL statements that are started after the running statement count reaches zero are not effected by the sqlite3_interrupt() call.

which seems reasonable.

**Comment by groue** [comment]
> Design a parallel fetching API that throws

A solution could be to expose the `interrupt` method only on interruptible queues and pools. Once you have an interruptible queue or pool, fetching methods keep the same signature, but can throw:

```swift
// Regular pool
let dbPool = DatabasePool(path: "...")
let persons = dbPool.read { db in Person.fetchAll(db) } // No error handling
dbPool.interrupt() // Compiler error

// Interruptible pool
let dbPool = DatabasePool.makeInterruptible(path: "...")
let persons = try dbPool.read { db in try Person.fetchAll(db) } // Error handling required
dbPool.interrupt()
```

With such a solution, only those who opt in interruptions have to pay the price (fetching methods that throw).

**Comment by palpatim** [comment]
Thanks again for your thoughts on this.

> A solution could be to expose the interrupt method only on interruptible queues and pools. 

I'm not wild about the idea of introducing a throwing version. It seems cumbersome and increases the existing disparity in behaviors between DatabaseQueues and DatabasePools by introducing another flavor to keep track of.

Rather than requiring explicit opt-in, perhaps an interim step would be to document best practices around interruption, since it's a rather special use case. For example, the way I ended up handling this in my project is to temporarily set up a cancellation closure when performing a long-running transaction:

```swift
// Thread safety omitted for brevity
class Foo {
    var cancelCallback: ( () -> () )?
    var canceled = false

    func cancel() {
        cancelCallback?()
        canceled = true
    }

    func doLongRunningTransaction() {
        guard !canceled else { return }
        do {
            try Globals.dbPool.writeInTransaction(nil) {
                db in
                self.cancelCallback = {
                    sqlite3_interrupt(db.sqliteConnection)
                }
                defer {
                    self.cancelCallback = nil
                }
                // ... perform long-running task, guarding against `canceled`
            }
        } catch let error as DatabaseError {
            // This will be executed on SQLITE_INTERRUPT return value
            Log("DatabaseError in \(#function)", error)
        } catch let error as PersistenceError {
            Log("PersistenceError in \(#function)", error)
        } catch let error as NSError {
            Log("NSError in \(#function)", error)
        }
    }
}
```

Based on your description above, that still runs the risk of crashes if I end up doing a non-throwing call in the transaction block, so it's incumbent on me to avoid those.

Thoughts?

**Comment by groue** [comment]
> Based on your description above, that still runs the risk of crashes if I end up doing a non-throwing call in the transaction block, so it's incumbent on me to avoid those.

This is true. You will avoid crashes if you interrupt the pool writer connection, and make sure the pool writer is not running any fetching method when the interrupt occurs.

The way you capture the writer connection is correct.

> Rather than requiring explicit opt-in, perhaps an interim step would be to document best practices around interruption, since it's a rather special use case.

Well, this issue is already a rather good introduction to the question "How can I use the SQLite sqlite3_interrupt function?", don't you think?

Your need is very specific, and I'm actually pretty happy that you can interrupt your writer connection with the current version of GRDB.
