### ISSUE TITLE
Association persistence with Codable-based records

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1322]
### What did you do?

I have a model which includes a different model (relationally), gist:

```swift
struct User: Codable, FetchableRecord, PersistableRecord {
    static let profilePhoto = hasOne(Photo.self)

    let id: Int
    let profilePhoto: Photo?
}

struct Photo: Codable, FetchableRecord, PersistableRecord {
    let id: Int
    ...
}
```

I'm trying to work with the automatically-synthesized insertion/fetching for Codable records, which basically works fine, but -

The problem is with insertion and decoding with associations. When inserting a `User`, I'd want it to insert the `profilePhoto.id` into a `profilePhotoId` field, and not the entirety of the profile photo model. Also, when fetching it back, I'd want it to "fill in" the profilePhoto with whatever matching information exists if any.

Is there any option to do this aside for resorting to custom `encode(to:)` / `into(row:)` implementations?
It seems like a mostly basic use-case. 

Thank you :)

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.1.1
**Installation method:** (CocoaPods, SPM, manual?) SPM
**Xcode version:** 14.2
**Swift version:** 5.7 
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Ventura

**Comment by freak4pc** [comment]
Tried some thing and this works, but it feels kinda messy. Am I doing something wrong? Is this the way to do this?

For the `User` model, I created a subset that adds the `profilePhotoId` and I stored _that_ in the Database:

```swift
struct User: Codable, Equatable, Identifiable {
  struct Persistable: Codable, PersistableRecord, FetchableRecord {
    static var databaseTableName: String { "user" }
    static let profilePhoto = hasOne(Photo.self, using: .init(["uploaderId"]))

    let id: Int
    let name: String
    let phone: String?
    let email: String
    let isPending: Bool
    let profilePhotoId: Int?

    init(user: User) {
      self.id = user.id
      self.name = user.name
      self.phone = user.phone
      self.email = user.email
      self.isPending = user.isPending
      self.profilePhotoId = user.profilePhoto?.id
    }
  }

  let id: Int
  let name: String
  let phone: String?
  let email: String
  let isPending: Bool
  let profilePhoto: Photo?
```

For fetching, I added a pair-type like the documentation suggests. This portion works nicely, I guess?

```swift
struct UserWithPhoto: FetchableRecord, Decodable {
  var user: User.Persistable
  var photo: Photo?
}

let storedUsers = try await db.read { db in
  let request = User.Persistable
    .including(optional: User.Persistable.profilePhoto)
    .asRequest(of: UserWithPhoto.self)

  let usersWithPhotos: [UserWithPhoto] = try UserWithPhoto.fetchAll(db, request)
  return usersWithPhotos.map { user -> User? in
    return User(persistable: user.user, photo: user.photo)
  }
}
```

**Comment by groue** [comment]
Hello @freak4pc, glad to hear from you :-)

The library does not deal with "sub-records", this is all up to the application.

> It seems like a mostly basic use-case.

I know that many users want this service. Basically, they want to define one type for an entity and its relations, and expect the library to handle both reads and writes of full graphs.

Some ORMs provide a somewhat leaky implementation of this service. In Fluent, for example, one must [take care of checking whether a relation was loaded or not](https://docs.vapor.codes/fluent/relations/#lazy-eager-loading) before using it, otherwise... the documentation is shy... I hope it's a good old crash and not a silent failure... You can perform a late fetch of a missing relationship, but now you may well fetch from a different state of the database. So what's the price? You can't express in the type system that a relationship has been loaded, and database invariants are weakened.

Some ORMs provide a very robust implementation of this service. Core Data does, thanks to its support for lazy loading and uniquing. What's the price? Records are mutable reference types, and concurrency is really hard to get right.

So, no, it's not a basic use-case. It's part the [most difficult problem of ORMs](https://en.wikipedia.org/wiki/Object–relational_impedance_mismatch). 😄

In the end, GRDB does strictly nothing for dealing with "sub-records". A `PersistableRecord` type deals with one table only. Specific composite `FetchableRecord` types express which relationships have been fetched:

```swift
struct User: FetchableRecord, PersistableRecord {
    // No property of type Photo
}

struct Photo: FetchableRecord, PersistableRecord {
    // No property of type User
}

struct UserWithPhoto: FetchableRecord {
    var user: User

    // Here, nil means "no photo". It does not mean "no photo or photo not loaded".
    var photo: Photo?
}
```

I'm open for enhancements, of course. It's better if the enhancement can realistically be implemented. It's better if one is conscious of eventual downsides. It's better if the enhancement does not solve a narrow use case: other users with a reasonably "basic" need that is slightly different should be not forgotten.

**Comment by freak4pc** [comment]
Hey there :) 
Thanks for the detailed response, as usual.

When I wrote "Basic", I really meant that it's _common_ - not that it's easy to solve necessarily :) 

The problem with the approach you suggest is that if the server response returns a `User` that already has a `profilePhoto`, I necessarily need to have separate models for the database and the server response. It kinda seems like a partial step similar to what I suggested above. 

Is the code I suggested above reasonable for this use case? I'll try to think about some other possible ergonomic improvements if that's the general direction.

**Comment by groue** [comment]
> The problem with the approach you suggest is that if the server response returns a `User` that already has a `profilePhoto`, I necessarily need to have separate models for the database and the server response. It kinda seems like a partial step similar to what I suggested above.

Yes, you're right.

I wish it were possible in Swift to implement something similar to Kotlin [`@Embedded`](https://developer.android.com/reference/android/arch/persistence/room/Embedded). Then we could write:

```swift
// Deals with the user table
struct User: Codable, FetchableRecord, PersistableRecord { ... }

// Deals with the photo table
struct Photo: Codable, FetchableRecord, PersistableRecord { ... }

// Deals with the server response.
struct ServerUser: Decodable {
    @Embedded var user: User
    var profilePhoto: Photo?
}
```

The `@Embedded var user` property would be decoded from the root, instead of searching for a "user" key, as `Decodable` does today.

The `ServerUser` struct could decode a nested JSON structure (as server usually send), without any need to repeat all user properties (`var id, var name, var etc`):

```js
{
  // user properties
  "id": ...,
  "name": ...,
  "email": ...,

  "profilePhoto": {
    // photo properties
    "id": ...,
    "url": ...
  }
}
```

Last time I tried to implement `@Embedded` in Swift, I failed - maybe I missed something.

**Comment by freak4pc** [comment]
I think I'll try to work with the current approach I landed on, but I'll ping back on this thread if I can think of something nicer. Thanks a ton, as usual :)

**Comment by groue** [comment]
All right, Shai.

I thought a little more about the other very common case of non optional belongs-to relationships.

The standard JSON for such a case is:

```js
{
  // Player properties
  "id": 1,
  "name": "Arthur",

  // Player's photo
  "photo": {
    "id": 1,
    "url": "..."
  },

  // Player awards
  "awards": [
    {
      "id": 1,
      "name": "..."
    },
    ...
  ]
}
```

The matching database records are:

```swift
struct Player {
    static let photo = hasOne(Photo.self)
    static let awards = hasMany(Photo.self)

    var id: Int
    var name: String
}

struct Photo {
    static let player = belongsTo(Player.self)

    var id: Int
    var playerId: Int // Not optional
    var url: URL
}

struct Award {
    static let player = belongsTo(Player.self)

    var id: Int
    var playerId: Int // Not optional
    var name: String
}
```

See how both `Photo` and `Award` structs have a non-optional `playerId` property that is missing in the JSON snippet.

Only a custom `Decodable` implementation can produce actual `Photo` and `Award` instances from the above JSON.

So... we all have to pick our poison: distinct types for db and json models (no `playerId` property in `API.Photo` and `API.Award`), or a [custom Codable implementation](https://forums.swift.org/t/codable-passing-data-to-child-decoder/12757).

I tend to think that distinct types are much simpler to understand and maintain.
