### ISSUE TITLE
Trouble with nested associations

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1324]
Hey there, this isn't exactly an issue but a support request for a side project im working on :)

I have the current DB structure:
![image](https://user-images.githubusercontent.com/605076/215206517-e34b61eb-2824-41b4-b417-6e0827192cb4.png)

Before, I only had a user with a profile photo, and I fetched the photo with the user:

```swift
private struct UserWithPhoto: FetchableRecord, Decodable {
  var user: User.Persistable
  var photo: Photo?
}

... 

User.Persistable
      .filter(key: id)
      .including(optional: User.Persistable.profilePhoto)
      .asRequest(of: UserWithPhoto.self)
```

Now - each user also has tag links, each of these links itself references a tag and category. Also, each user has multiple photos linked to their ID (based on the graph above).

The associations look like this:

```swift
extension TagLink: PersistableRecord, FetchableRecord {
  static let user = belongsTo(User.Persistable.self)
  static let category = hasOne(Category.Persistable.self)
  static let tag = hasOne(Tag.self, using: .init(["id"]))
}

extension User.Persistable: PersistableRecord, FetchableRecord {
  static let profilePhoto = hasOne(Photo.self, using: .init(["uploaderId"]))
  static let tagLinks = hasMany(TagLink.self)
  static let tags = hasMany(Tag.self, through: tagLinks, using: TagLink.tag)
}

extension Tag: FetchableRecord, PersistableRecord {
  static let tagLinks = hasMany(TagLink.self, using: .init(["tagId"]))
}

extension Category.Persistable: FetchableRecord, PersistableRecord {
  static let tagLinks = hasMany(TagLink.self)
}
```

I'm a bit confused on how to fetch everything, I'd like my `UserWithX` request object would look like this somehow:

```swift
private struct UserWithDetails: FetchableRecord, Decodable {
  var user: User.Persistable
  var photo: Photo?
  var photos: [Photo]
  var tagLinks: [TagLink]
  var tags: [Tag]
  var categories: [Category]
}
```

Or something similar, but not entirely sure how to form the right relations, associations, and the request building itself.

Would appreciate some direction and help 🙏 
Thank you!

**Comment by groue** [comment]
Hello Shai, let's have a look!

Maybe let's proceed step by step, and add properties in `UserWithDetails`, one after the other.

So, the first property is `photo`. I guess it should be fed from the `profilePhoto` association, right? Maybe you'd even like the property to be named `profilePhoto` as well:

```swift
// First step
private struct UserWithDetails: FetchableRecord, Decodable {
  var user: User.Persistable
  var profilePhoto: Photo?
}
```

It looks like you want to use [`including(optional:)`](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#includingoptional):

> This method accepts any association. It has the base record fetched along with one associated record, which is "included" in the fetched results. The associated record can be missing: it is "optional".

Sounds like a match. In `UserWithDetails`, each user comes with one associated record, and it is optional.

The documentation also says:

> The CodingKey for the [decoded] property must match the association key of the association. [...] [The key] can be configured with the association `forKey(_:)` method.

All right, let's give the `profilePhoto` association key to the `profilePhoto` association:

```swift
extension User.Persistable: PersistableRecord, FetchableRecord {
  static let profilePhoto = hasOne(Photo.self, using: .init(["uploaderId"])).forKey("profilePhoto")
}
```

This distinct association name further breaks the ambiguity with the other photos attached to the user.

I have to stop there, because I'm very surprised that the `profilePhoto` association is defined as a `hasOne` association. It looks like it should be a `belongsTo` association from the `user.profilePhotoId` column.

Of course, it's odd to say that a user "belongs to" a photo.

But we're talking computer language. It is the structure of the database that drives the choice of association, not our human language and concepts. "A belongs to B" whenever it is the A table that has a column that points to B. That's [how `belongsTo` association work](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#convention-for-the-belongsto-association).

So it's odd, but correct, to say that a user belongs to its profile photo (via the `user.profilePhotoId` column).

I can try to say it differently.

It is not a good idea to say "has one" when the database says "has many". According to the schema, I can have many photos uploaded by the same user (via the `photo.uploaderId` column). I don't know if this is what is intended, but this is what the schema says.

Anyway, the schema is always more correct than the Swift code of us poor developers. The schema says that one user "has many" uploaded photos. But the code says "has one":

```
// Does not match the schema -> highly suspicious
static let profilePhoto = hasOne(Photo.self, using: ForeignKey(["uploaderId"]))
```

This is confusing, and this confusion will get you into trouble because your app will eventually load duplicates when I'm not sure this is what you want:
> 1. user 1 attached to photo 1 (uploaded by user 1)
> 2. user 1 (again) attached to photo 2 (uploaded by user 1)

That what happens when one says "has one" when the reality is "has many".

Before this question is solved, I'm not sure it's a good idea to proceed to other properties of `UserWithDetails` 😅

**Comment by freak4pc** [comment]
Thanks for the detailed response, as usual! 
About the photos question, I was a bit unsure myself.

A user _does_ belong to a photo in the sense you mentioned, but there is a profilePhotoId which there can only be one of, and additionally we'd like to get all other photos separately as well. It should actually be much simpler to get all photos together, and separate the profilePhoto based on the ID.

This does seem to work:

```swift
struct UserWithDetails: FetchableRecord, Decodable {
  var user: User.Persistable
  var photos: [Photo]
  var profilePhoto: Photo? { photos.first(where: { $0.id == user.profilePhotoId }) }
}

let user = try await database.read { db in
  try User.Persistable
    .filter(key: 8)
    .including(all: User.Persistable.photos)
    .asRequest(of: UserWithDetails.self)
    .fetchOne(db)
}

dump(user?.profilePhoto) // Photo...
```

User got this association instead of `profilePhoto`:
```swift
static let photos = hasMany(Photo.self, using: .init(["uploaderId"]))
```

This was the "easy" part I guess but I'm still quite baffled about the "has many through"-styled relationships (i.e. get tag links, and then _their_ linked tags and categories). 

Thank you 🙏

**Comment by groue** [comment]
> I'm very sorry about this current limitation.

Your `UserWithDetails` struct was unexpected, but this does not make it invalid. I'm investigating.

**Comment by freak4pc** [comment]
That's really interesting, and nothing to apologize about :) 

I think the main reason I need the tag links in the top level is not having a good way to connect them otherwise. But if we're doing something like this that you suggested:

```
User.tagLinks
        .forKey("tagLinksWithDetails") // same name as the decoded property
        .including(required: TagLink.tag)
        .including(required: TagLink.category)
```

Is already quite helpful! I don't actually need the linking meta data aside for creating objects that link each tag with each category. I'll investigate a bit from my side as well but didn't realize you could "nest" associations this way. Quite interesting.

Thanks again for your wisdom 🙏

**Comment by groue** [comment]
All right, I'll stay tuned :-)

**Comment by freak4pc** [comment]
So I'm bumping into some trouble even fetching the "basic" tag link:

```swift
struct TagLinkWithDetails: Decodable, FetchableRecord {
  var tagLink: TagLink
  var tag: Tag
  var category: Category.Persistable
}

let items = try await database.read { db in
  try TagLink
    .including(required: TagLink.tag)
    .including(required: TagLink.category)
    .asRequest(of: TagLinkWithDetails.self)
    .fetchAll(db)
}

// 0 items
```

Am I missing something? Looking in TablePlus, the foreign keys etc, seem to be correct:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/605076/215285674-d2b582bc-e481-4b38-99eb-b2d4a88743bb.png">

**Comment by groue** [comment]
I think your associations are reversed:

> "A belongs to B" whenever it is the A table that has a column that points to B. That's [how belongsTo association work](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#convention-for-the-belongsto-association).

```diff
 extension TagLink: PersistableRecord, FetchableRecord {
   static var databaseTableName: String { "tagLink" }
-  static let category = hasOne(Category.Persistable.self, using: .init(["id"]))
-  static let tag = hasOne(Tag.self, using: .init(["id"]))
+  static let category = belongsTo(Category.Persistable.self)
+  static let tag = belongsTo(Tag.self)
 }
```

Also, you don't have to provide the `ForeignKey` (argument to `using:`) when the database schema defines one single foreign key from one table to the other.

**Comment by freak4pc** [comment]
That seems to do the trick! Requires some transformations but seems to be doing the job:

```swift
private extension UsersClient.Persistence {
  @Sendable static func fetchAllUsers(_ db: GRDB.Database) throws -> [User] {
    try User.Persistable
      .all()
      .detailedUserQuery()
      .fetchAll(db)
      .map(User.init(userWithDetails:))
  }

  @Sendable static func fetchUser(_ db: GRDB.Database, id: User.ID) throws -> User? {
    try User.Persistable
      .filter(key: id)
      .detailedUserQuery()
      .fetchOne(db)
      .map(User.init(userWithDetails:))
  }
}

private extension QueryInterfaceRequest where RowDecoder == User.Persistable {
  func detailedUserQuery() -> QueryInterfaceRequest<UserWithDetails> {
    including(
      all: User.Persistable.tagLinks
        .forKey("tagLinksWithDetails")
        .including(required: TagLink.tag)
        .including(required: TagLink.category)
    )
    .including(all: User.Persistable.photos)
    .asRequest(of: UserWithDetails.self)
  }
}

```

Seems my instincts around hasOne vs. belongsTo aren't that sharp, yet :) Will have to re-read your explanation again.

Anyways, appreciate any other feedback you might have before closing this :)

**Comment by groue** [comment]
Looks like something I'd write myself 👍 

Big bonus for the methods that accept an initial `db` argument: that's how one builds a set of methods that can be composed and arranged in transactions (`read` or `write`) 💯 

If you're on Swift 5.7 and the latest GRDB, you can replace:

```diff
-private extension QueryInterfaceRequest where RowDecoder == User.Persistable {
+private extension QueryInterfaceRequest<User.Persistable> {
```

**Comment by freak4pc** [comment]
Oh nice, good point!
Thanks a lot :)

**Comment by groue** [comment]
Happy GRDB Shai :-)

**Comment by freak4pc** [comment]
Very very happy ;-)
