### ISSUE TITLE
Stop/Cancel transactions pull

### ISSUE THREAD

**Issue by mipopov** [groue/GRDB.swift#1335]
Hello, my friend; I am a big fan of GRDB; u do great job!

I have question about stopping transaction; I use DataBasePool for work; So let's imagine that I have a lot of transactions(read and write, for example 30-50); And then I want to stop them, all transactions which are waiting - must be canceled, so

**Can GRDB stop them or cancel?**

v 6.0.0

/////
Something like OperationQueue style?
cancelAllOperation()

**Comment by groue** [comment]
Hello @mipopov,

I'm not sure the library ships with what you need. You can compare GRBD database access methods (`read`, `write`, etc.) to `DispatchQueue.sync()` or `DispatchQueue.async()`: closures submitted to those methods can not be cancelled. They *will* execute.

So you're about to handle cancellation explicitly, maybe with a `isCancelled` flag that you check at some points.

You may find in the documentation the built-in tool for stopping database jobs: [`dbPool.interrupt()`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasereader/interrupt()). This method does nothing unless a database statement is being executed or iterated at the moment the method is called. This is important, because DatabasePool can only run, at any given point in time, a single write transaction and a limited number of read transactions (default 5). This means that very few of your 30-50 scheduled jobs can actually be interrupted by `interrupt()`. A few may be interrupted, but the rest will just eventually run, just like a closure submitted to `DispatchQueue`.

**Comment by groue** [comment]
All right, I close the issue. Feel free to ask further questions if needed, and happy GRDB!
