### ISSUE TITLE
Getting "attempt to write a readonly database" while trying to write

### ISSUE THREAD

**Issue by Momeks** [groue/GRDB.swift#1344]
Hello, 

I am trying to add a word to bookmark by setting  `bookmark` column to `1`.  Since in the `init()` I have set `config.readonly = false` but still getting this error on device:

`Error bookmarking word: SQLite error 8: attempt to write a readonly database - while executing UPDATE DICM SET bookmark = 1 WHERE NAME = ?`

Here is my code:
//class init()
```
init(_ dbName: String) {
		self.dbName = dbName
		var config = Configuration()
		config.readonly = false
		guard let dbPath = Bundle.main.path(forResource: dbName, ofType: "sqlite") else { return }
		do {
			self.dbQueue = try DatabaseQueue(path: dbPath, configuration: config)
		} catch let error {
			print(error.localizedDescription)
		}
	}
```

and then try adding word to bookmark:

```
func bookmarkWord(_ word: String) {
		do {
			try dbQueue.write { db in
				try db.execute(
					sql: "UPDATE DICM SET bookmark = 1 WHERE NAME = ?",
					arguments: [word]
				)
			}
		} catch {
			print("Error bookmarking word: \(error)")
		}
	}
```

any help would be appriciated

**Comment by groue** [comment]
Hello @Momeks,

You are opening a database stored as a resource in your application. Application resources can not be modified, and I suggest you read Apple documentation about the file system so that you can start understanding what you are doing.

Meanwhile, let me provide the [same answer as in your previous issue](https://github.com/groue/GRDB.swift/issues/1340#issuecomment-1445416079):

> If you have further questions, please check the "FAQ: Opening Connections" at https://github.com/groue/GRDB.swift

In particular, the "How do I open a database stored as a resource of my application?" question is for you.

**Comment by Momeks** [comment]
Thank you! So I need to copy all db files into document directory and then try to read and write.
