### ISSUE TITLE
Is there any attribute that can determine whether it is a read out entity?

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1366]
```
struct Player: Decodable, FetchableRecord & PersistableRecord {
    var id: Int64
    var name: String
    var score: Int
}

let player =  try? Player.fetchOne(db, sql: "SELECT ...", arguments:...) ?? Player() // here is not null
```
Hello everyone.

Assuming that I fail to read the database using _fetchOne_, I receive a nil value.

But as I used the initialization method, I created a new object to replace it, so I ensured that a variable was not nil.

At this point, do I have a variable or method that can determine whether this _player_ is from a database or a newly created object?

thanks.

**Comment by groue** [comment]
Hello @SF-Simon,

The `Player` struct defines the storage for three properties, and... that's all. There's no room to store the information you're after. Generally speaking, Swift protocols can not add storage to their conforming types, and GRDB record protocols are no exception.

To achieve your goal, the easiest technique is to track the information in a separate boolean:

```swift
let player: Player
let playerIsFetchedFromDatabase: Bool

if let fetchedPlayer = try? Player.fetchOne(...) {
    player = fetchedPlayer
    playerIsFetchedFromDatabase = true
} else {
    player = Player()
    playerIsFetchedFromDatabase = false
}
```

You could also track the information in a transient property (read "transient" as "not stored in the database"). To make a property transient, provide a custom `CodingKeys` enum, as described in [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types#2904057). But now you have a problem: this property is available to all code, present and future, that can access a `Player` instance. The property must be **accurate**, or some code, present or future, will make bad decisions, due to a `Player` instance with a bogus flag. To do that, avoid `Decodable` and provide an explicit `init(row:)` initializer:

```swift
struct Player {
    var id: Int64
    var name: String
    var score: Int
    var isFetchedFromDatabase: Bool = false

    enum CodingKeys: CodingKey, String {
        // isFetchedFromDatabase is transient
        case id, name, score
    }
}

extension Player: FetchableRecord, PersistableRecord, Encodable {
    init(row: Row) {
        isFetchedFromDatabase = true
        id = row["id"]
        name = row["name"]
        score = row["score"]
    }
}
```

If you only need this flag in a very specific component of your app, maybe the first technique is the way to go. Your call :-)

**Comment by groue** [comment]
Note to myself: is it possible to help people by allowing `init(row:)` to call `Decodable.init(from:)`?

```swift
extension Player: FetchableRecord, Decodable {
    init(row: Row) throws {
       self.init(from: /* some decoder */)
       isFetchedFromDatabase = true
    }
}
```

Flagging as "needs revisiting".

**Comment by SF-Simon** [comment]
Thank you very much, @groue 
I finally added an _isFeededFromDatabase_ field to complete this requirement.

PS: This is much more comfortable than the EF experience, haha.

**Comment by groue** [comment]
In the next version of the library, you will be able to use `FetchableRecordDecoder`, and this may simplify your setup:

```swift
struct Player: Decodable {
    var id: Int
    var name: String
    var score: Int
    var isFeededFromDatabase: Bool = false // Transient

    enum CodingKeys: String, CodingKey {
        case id, name, score
    }
}

extension Player: FetchableRecord {
    init(row: Row) throws {
        // No need to decode individual properties!
        self = try FetchableRecordDecoder().decode(Player.self, from: row)
        self.isFeededFromDatabase = true
    }
}
```
