### ISSUE TITLE
 I changed the name of the "Author" table to uppercase, so I can't get the "Author" in "BookI nfo

### ISSUE THREAD

**Issue by jyyjkt** [groue/GRDB.swift#1367]
### What did you do?
 I changed the name of the "Author" table to uppercase, so I can't get the "Author" in "BookI
nfo" 

### What did you expect to happen?

I want to change the table name "BookInfo" to get "Author" 

### What happened instead?
The default table name returns normal,and "Author" in "BookInfo" returns nil after changing the table name. 

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
**Installation method:*SPM* (CocoaPods, SPM, manual?)
**Xcode version:*Version 14.2 *
**Swift version:*5.0*
**Platform(s) running GRDB:*iOS* (iOS, macOS, watchOS?)
**macOS version running Xcode:*12.6.5*

### Demo Project
https://github.com/groue/GRDB.swift/files/11351427/GRDBDemo.zip

**Comment by groue** [comment]
Hello @jyyjkt,

Please refer to the [documentation about table names that do not follow the recommended convention](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databaseschema#Table-names-should-be-English-singular-and-camelCased). Read carefully: you will probably need to specify explicit keys to your associations.

Since your app is free to define its database schema, you may also prefer to stick to the [recommended practices](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databaseschema#Database-Schema-Recommendations) - so that you don't have to perform extra configuration.
