### ISSUE TITLE
Empty ValueObservationTracking

### ISSUE THREAD

**Issue by baum-sparton** [groue/GRDB.swift#1389]
### What did you do?

I'm using MVVM in a SwiftUI app using Combine to get updates from GRDB.  I have binding setup for one screen with data being populated as expected, but changes to the backing data are not being reflected in the UI.  The query users two models with a hasOne relationship between them.

### What did you expect to happen?

I expect that an update notification will be sent when either of the contributing models are updated.

### What happened instead?

No update notifications are sent.  Using .trace() shows an empty region is being observed.  I was able to manually specify a region parameter for the tracking.  Doing so resolved the issue.

So I've worked passed the issue, and am fine with the solution.  I was just wondering if this is the intended behavior, or if perhaps I had done something incorrectly?

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.15.0
**Installation method:** Xcode Package Manager
**Xcode version:** 14.3
**Swift version:**
**Platform(s) running GRDB:** iPhone4 Pro Simulator on Mac
**macOS version running Xcode:** 13.4

### Demo Project

The model for the UI looks something like this:

    struct Entry: Identifiable, Decodable, FetchableRecord {
        var userId: Int64
        var name: String
        var riskLevel: RiskLevel

        enum CodingKeys: String, CodingKey {
            case userId = "id"
            case name = "name"
            case risk = "risk_level"
        }
    
        var id: Int64 { userId }
    }

The query being passed into the fetch parameter of the ValueObservation is as follows:

    func entryQuery(db: Database) throws -> [Entry] {
        return try User
            .select(Column(User.CodingKeys.id), Column(User.CodingKeys.name))
            .annotated(withRequired: User.userStats.select(Column(UserStats.CodingKeys.riskLevel)))
            .asRequest(of: Entry.self)
            .fetchAll(db)
    }

And the publisher is created as such:

    func entryPublisher() -> AnyPublisher<[Entry], Never> {
        return ValueObservation.tracking(fetch: entryQuery)
            .publisher(in: reader, scheduling: .immediate)
            .catch { (error) in
                Database.logger.error("Error in publisher. \(error, privacy: .public)")
                return Empty<[Entry], Never>()
            }
            .eraseToAnyPublisher()
    }

I'm not sure how much you needed.  I may be able to put together more if necessary.

**Comment by groue** [comment]
Hello @baum-sparton,

Thanks for reporting this issue. You will fix the observation with the following change in your code:

```diff
-ValueObservation.tracking(fetch: entryQuery)
+ValueObservation.tracking(entryQuery)
```

The method you were calling accepts a variadic list of regions to track: [`tracking(region:fetch:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation/tracking(region:fetch:)), but when the list is empty... Well no region is tracked.

There is an issue with ergonomics, here. I'll see how I can address this so that other users don't fall in the same trap.

**Comment by groue** [comment]
I pushed in the development branch a commit that addresses this issue. You'll no longer be able to write `ValueObservation.tracking(fetch: entryQuery)`. It will ship with the next release.

This technically is a breaking change, but it shouldn't be noticed by anyone because only the "faulty" usage will stop compiling. In a way, users who upgrade and see an error will understand that they were not observing anything (and will have an opportunity to fix their app).

I think this is enough to close this issue.

**Comment by baum-sparton** [comment]
Wow, you are on top of things.  Thanks for getting back so quickly.  That was indeed my issue.
