### ISSUE TITLE
No such table error after calling erase()

### ISSUE THREAD

**Issue by vadimvitvickiy** [groue/GRDB.swift#1393]
Hello!
Hope I didn't get too intrusive. :)
I'm experiencing an issue when trying to erase the database and can't find any best practices or examples to find out where I might be doing wrong.

The code is simple, I'm calling `try db.erase()` and at some point after new database writes are happening, but all of them failed with error.
What I saw in tests this shouldn't be a case, the table should exist, and the method documentations with code states that it only clears the database content.
So I wonder if this is a plain bug, or am I missing something?

### What did you do?

Trying to erase database content by calling `try db.erase()` on `DatabasePool` object.

### What did you expect to happen?

The database is empty and new records can be filled.

### What happened instead?

The error is thrown: `SQLite error 1: no such table: SomeTable - while executing SELECT * FROM "SomeTable"`.

### Environment

**GRDB flavor(s): GRDB
**GRDB version: 6.15.0
**Installation method: SPM
**Xcode version: 14.3.1
**Swift version: 5.8
**Platform(s) running GRDB: iOS
**macOS version running Xcode: 13.4

**Comment by groue** [comment]
Hello @vadimvitvickiy,

You're not intrusive :-)

I'll update the documentation of [`erase()`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasewriter/erase()-w5n7) so that it is clear that it deletes all data, and drops all tables. After `erase()` has been called, the database is completely empty, as if you just created a new database file.

If you want to delete the contents of the tables, see #1300. There's no convenience method for this because I'm not sure it is possible to do it reliably for **all** databases. But you'll find some code to copy and paste.

**Comment by vadimvitvickiy** [comment]
> If you want to delete the contents of the tables, see https://github.com/groue/GRDB.swift/issues/1300. There's no convenience method for this because I'm not sure it is possible to do it reliably for all databases. But you'll find some code to copy and paste.

Oh, I see, thanks for pointing it out. This looks like exactly what I need.
Seems like I misunderstood the code of the method.

Thank you again for the help!
