### ISSUE TITLE
iOS17 Simulator produces 42 GRDB messages

### ISSUE THREAD

**Issue by smithi01** [groue/GRDB.swift#1395]
Thank you so much for GRDB and GRDBQuery. They are superb. I have run into an issue with the iOS17 simulator.

### What did you do?

I created a new project called GRDB Example in Xcode 15 beta, made no changes to the source code, added GRDB via SPM, and ran the default 'hello world' code on the ios17 simulator

### What did you expect to happen?

I expected the default hello world app to run without GRDB issues

### What happened instead?

I received 42 messages in the console of the form: 

objc[2211]: Class _TtC4GRDB18SQLStatementCursor is implemented in both /Library/Developer/CoreSimulator/Volumes/iOS_21A5248u/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GRDB.framework/GRDB (0x1c0be3ea8) and /Users/myname/Library/Developer/CoreSimulator/Devices/55E0C4E1-F07E-4647-A897-E7B3CCFDDB93/data/Containers/Bundle/Application/115EB5C9-1E90-4411-89D5-8C365C83220F/GRDB Example.app/GRDB Example (0x104b787e0). One of the two will be used. Which one is undefined.

Each of the 42 messages referred to a different GRDB class.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** master
**Installation method:** SPM
**Xcode version:** 15 beta
**Swift version:** 5.9
**Platform(s) running GRDB:** iOS17 Simulator
**macOS version running Xcode:** 13.4

### Demo Project

[GRDB Example.zip](https://github.com/groue/GRDB.swift/files/11780205/GRDB.Example.zip)

**Comment by groue** [comment]
Hello @smithi01,

You're running beta software, and beta software have problems :-)

Here the problem is that the compiler is unable to make the distinction between your copy of GRDB, and the copy of GRDB that is included in the system itself.

Yes, I'm very proud that GRDB is used inside the operating system. Still, it is used in a private way (see the "PrivateFrameworks" components in the messages), and that's why you still need to add GRDB as a dependency of your application.

And Apple needs to let you do that without any error message of any kind. After all, the private frameworks of the system are not supposed to be your business in the first place. So please file a report to Apple using https://feedbackassistant.apple.com, so that Apple engineers learn about the problem, and fix their developer tools.

Meanwhile, I can't install the iOS 17 simulator on my computer, and [I'm not the only one](https://developer.apple.com/forums/thread/731189). Beta software, I told you 😉

**Comment by smithi01** [comment]
Thanks so much.

**Comment by groue** [comment]
Thank you very much! Let's hope the next beta removes those messages 🤞

**Comment by groue** [comment]
See also https://github.com/groue/GRDB.swift/discussions/1396

**Comment by smithi01** [comment]
This appears to be fixed with beta 2

**Comment by groue** [comment]
You're right :-) Thanks @smithi01 👍
