### ISSUE TITLE
GRDB notifies transaction observers of database region when running `INSERT INTO ... SELECT ...`

### ISSUE THREAD

**Issue by mallman** [groue/GRDB.swift#1400]
### What did you do?

I set up a `TransactionObserver` `observer` on a `DatabaseRegion` `region`. Then I used `INSERT INTO ... SELECT ...` to insert rows into a table from a query on a subset of `region`.

### What did you expect to happen?

I expect that `observer` is not be notified by the `INSERT INTO` statement.

### What happened instead?

My `observer` is notified by the `INSERT INTO` statement.

This is problematic for two reasons.

1. There is a performance penalty to handling change notifications from false positives.
2. (More importantly) The spurious notification causes havoc in my app logic.

In addition to my `TransactionObserver`, I also have a `DatabaseRegionObservation` `observation` on essentially the same region as `region`. My `observation` is responsible for executing the `INSERT` statement that queries from `region` whenever `region` changes (this is my hacky version of a materialized view). Thus, I actually have two observers that are getting confused because of the `INSERT INTO` notifications. I'm actually kind of surprised that my app works with this logic. I only encounter these errors in failed unit tests. If I disable the `INSERT INTO` statement, the test failures go away. Either way, my app appears to work as expected.

It would be super helpful if GRDB did not notify observers of the select region when executing an `INSERT INTO ... SELECT ...` query. Instead, notify observers of the table. (Incidentally, I don't know whether it does this or not, because I do not observe the table itself. But maybe I should? Hmmm...)

### Environment

**GRDB flavor(s):** Custom SQLite 3.42.0 build
**GRDB version:** GRDB 6.15.0
**Installation method:** manual
**Xcode version:** 14.3.1
**Swift version:** 5.8.1
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 13.4.1

**Comment by groue** [comment]
Hello @mallman,

I can't reproduce the behavior you describe.

In the sample code below, I setup an observer on the "origin" table (this is your `region`), and then perform an `INSERT INTO dest SELECT * FROM origin`. As expected, the observer is not notified of anything when `INSERT INTO ... SELECT ...` runs, because the "origin" table is not modified:

```swift
// TODO: add this conformance in GRDB itself
extension DatabaseEvent: CustomStringConvertible {
    public var description: String {
        switch kind {
        case .delete: return "DELETE \(tableName)(\(rowID))"
        case .update: return "UPDATE \(tableName)(\(rowID))"
        case .insert: return "INSERT \(tableName)(\(rowID))"
        }
    }
}

// Print all changes to a region.
class Observer: TransactionObserver {
    let observedRegion: DatabaseRegion
    
    init(observedRegion: DatabaseRegion) {
        self.observedRegion = observedRegion
    }
    
    func observes(eventsOfKind eventKind: DatabaseEventKind) -> Bool {
        observedRegion.isModified(byEventsOfKind: eventKind)
    }
    
    func databaseDidChange(with event: DatabaseEvent) {
        if observedRegion.isModified(by: event) {
            print(event)
        }
    }
    
    func databaseDidCommit(_ db: Database) { }
    func databaseDidRollback(_ db: Database) { }
}

try DatabaseQueue().inDatabase { db in
    try db.create(table: "dest") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("a")
    }
    try db.create(table: "origin") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("a")
    }
    
    // Observe the origin table only
    let region = try Table("origin").databaseRegion(db)
    let originObserver = Observer(observedRegion: region)
    db.add(transactionObserver: originObserver, extent: .databaseLifetime)
    
    // Prints INSERT origin(1)
    try db.execute(sql: "INSERT INTO origin (id, a) VALUES (1, 1)")

    // Prints nothing
    try db.execute(sql: "INSERT INTO dest SELECT * FROM origin")
}
```

The sample code uses actual regions of type `DatabaseRegion`, because you mention them in your report.

Please note how a transaction observer can use a region as a faithful assistant:

- The region is used in both `observes(eventsOfKind:)` and `databaseDidChange(with:)`.
- `databaseDidChange(with:)` must check `region.isModified(by: event)` before considering that a change impacts the observed region.

Surely the documentation could be improved on that topic.

If your application uses regions in this way, and you still get undesired change notifications, would you please share some reproducing code? It will help figuring it what's wrong.

**Comment by mallman** [comment]
I see the problem with my code. The unwanted notifications I'm receiving are `databaseWillCommit` and `databaseDidCommit`. I expected those to be called only for transactions affecting the region my observer is observing. However, it appears they are called when _any_ database transaction will or did commit. Oops.

This is a case of misunderstanding the API.

I need to spend a bit more time debugging this issue in my app. Then I should have a better understanding and be able to provide a more informed explanation.

**Comment by groue** [comment]
Oh, yes. Transaction observers are intended to set a flag from `databaseDidChange` (and call `stopObservingDatabaseChangesUntilNextTransaction` when they have enough information about a transaction). This flag is checked (and cleared) in `databaseDidCommit`/`databaseDidRollback` in order to trigger any desired side effect whenever interesting changes were committed on disk/rollbacked.

**Comment by groue** [comment]
It looks like we can close the issue. Don't hesitate reopening if necessary!

**Comment by mallman** [comment]
I've debugged the issue with my app.

Basically, I have two database observers, `observer1` and `observer2` that observe similar database regions (for this example, we may assume they are identical). `observer2` is registered for notifications first, then `observer1`. The following sequence ensues:

1. I start a transaction `A` running my app logic.
2. `observer2` is notified with `databaseWillCommit`.
3. `observer1` is notified with `databaseWillCommit`.
4. `observer1` reads from the database using a new read transaction. It does this to collect the "before commit" state.
5. `A` is committed.
6. `observer2` is notified with `databaseDidCommit`. (Because it was registered before `observer`.)
7. `observer2` executes a new transaction `B` with the `Database` handle it's provided.
8. `B` is about to commit.
9. `observer1` is notified with `databaseWillCommit` (for txn `B`).
10.  `B` is committed.
11. `observer1` is notified with `databaseDidCommit` (for txn `B`).
12. `observer1` is notified with `databaseDidCommit` (for txn `A`).

`observer2` does the right thing, but `observer1` gets confused. Paring down the transaction will/did commit notifications above just for `observer1`, we have:

1. `observer1` is notified with `databaseWillCommit` for txn `A`.
2. `observer1` is notified with `databaseWillCommit` for txn `B`.
3. `observer1` is notified with `databaseDidCommit` for txn `B`.
4. `observer1` is notified with `databaseDidCommit` for txn `A`.

The fact is, I want `observer1` to ignore the notifications for any transaction other than `A`. Assuming the notifications are "balanced", I created a variable in `observer1` to count the "depth" of the transaction notifications. Basically, it looks like this:

```swift
class MyTransactionObserver: TransactionObserver {
  private var txnDepth: Int = 0

  ...

  func databaseWillCommit() throws {
    txnDepth += 1
    guard txnDepth == 1 else { return }
    ...
  }

  func databaseDidCommit(_ db: Database) {
    txnDepth -= 1
    guard txnDepth == 0 else { return }
    ...
  }

  func databaseDidRollback(_ db: Database) {
    txnDepth -= 1
    guard txnDepth == 0 else { return }
    ...
  }
}
```

Does this make sense? Just writing this out helped me with the diagnosis and solution. With this implementation my unit tests are happy again. 😄

**Comment by groue** [comment]
Let's reopen. I have a few comments.

First, we made it clear [in a previous discussion](https://github.com/groue/GRDB.swift/discussions/1399#discussioncomment-6289683) that the database should not be accessed from `databaseWillCommit`. It looks like `observer1` is doing so at step 4. Even if it looks like it works, SQLite may decide to make it fail at any point. If your app is relying on this, I suggest you consider looking for another solution. The linked discussion suggests using `[DatabaseRegionObservation](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databaseregionobservation)`.

Next, when several transaction observers are registered, their `databaseWillCommit` methods are called, in the order of registration, and then their `databaseDidCommit` methods. This makes it possible for any transaction observer to prevent the transaction from being committed to disk by throwing an error from `databaseWillCommit`. If no registered observer throws, all observers can then handle the successful commit.

Next, transaction observers that start a new transaction in `databaseDidCommit` must be ready for reentrant callbacks (`databaseDidCommit` is called by the transaction started in the previous, unfinished `databaseDidCommit` callback). And other transaction observers must be ready for multiple subsequent calls to `databaseWillCommit` (in case their `databaseDidCommit` for the 1st transaction was not called yet). Reentrancy is not easy to deal with, I agree.

Finally, transaction observers are not notified of read-only transactions. This could reduce reentrant callbacks. Unfortunately, there is no public api yet that makes it possible to start such a read-only transaction on the `Database` instance provided by `databaseDidCommit` 🤣. This was not yet considered as a big problem, because I haven't yet met the reentrancy nightmare you describe 😉.

We can discuss addressing the reentrancy problem. At the same time, accessing the database from `databaseWillCommit` is a misuse, so reentrancy might be the wrong problem to focus on.

**Comment by mallman** [comment]
> First, we made it clear [in a previous discussion](https://github.com/groue/GRDB.swift/discussions/1399#discussioncomment-6289683) that the database should not be accessed from `databaseWillCommit`. It looks like `observer1` is doing so at step 4. Even if it looks like it works, SQLite may decide to make it fail at any point. If your app is relying on this, I suggest you consider looking for another solution. The linked discussion suggests some alternatives.

This is where the confusion begins. The linked discussion does not represent this use case, because I want to access the database at its state at the start of the transaction. That is, I want to query the database as it existed _before_ any changes were made by the current transaction. In the discussion, I ask about accessing it _after_ the changes made by the transaction, but before it's committed.

Regarding accessing the database in `databaseWillCommit`, let me quote the documentation from https://www.sqlite.org/c3ref/commit_hook.html:

> The callback implementation must not do anything that will modify the database _connection_ that invoked the callback.

(Emphasis mine.)

If I understand correctly, this does not prohibit accessing the database from _another_ connection under ordinary circumstances. For example, we should use a single writer. Now we get into some territory where GRDB does not define behavior, but where I believe it could.

As the [documentation of GRDB](https://swiftpackageindex.com/groue/grdb.swift/v6.15.1/documentation/grdb/transactionobserver/databasewillcommit()-7mksu) states:

> This method must not access the database.

However, as stated by the SQLite documentation, I believe this only applies to the current SQLite connection (`sqlite3*`), i.e. the current `GRDB` `Database` instance. This instance is, I believe, the sole writer connection of `DatabasePool`. But what about the reader connections? What if one of those is used to access the database? I don't see how https://www.sqlite.org/c3ref/commit_hook.html forbids that access.

So what I suggest here is that it _is_ safe to read from the database in `databaseWillCommit` using a `DatabasePool` in the following manner:

```swift
func databaseWillCommit() throws {
  try dbPool.read { db in
    db stuff...
  }
}
```

If you agree, I believe the documentation for the `databaseWillCommit` method can be amended to state that reads from a `DatabasePool` are safe. What do you think?

> Next, transaction observers that start a new transaction in `databaseDidCommit` must be ready for reentrant callbacks (`databaseDidCommit` is called by the transaction started in the previous, unfinished `databaseDidCommit` callback). And other transaction observers must be ready for multiple subsequent calls to `databaseWillCommit` (in case their `databaseDidCommit` for the 1st transaction was not called yet). Reentrancy is not easy to deal with, I agree. And there may even exist a flaw in the way GRDB notifies observers in unexpected order.

This is why I added the `txnDepth` property to `MyTransactionObserver`. Are you saying this is the wrong thing to do?

**Comment by groue** [comment]
> So what I suggest here is that it _is_ safe to read from the database in `databaseWillCommit` using a `DatabasePool` in the following manner:
> 
> ```swift
> func databaseWillCommit() throws {
>   try dbPool.read { db in
>     db stuff...
>   }
> }
> ```

Oh, yes, that's perfectly valid 👍 Thanks for making your technique explicit. I've clarified the documentation in 59c41c97afa0d1e84bd46cf404ebbc114398dc73.

OK, so we only have to deal with reentrancy.

> This is why I added the `txnDepth` property to `MyTransactionObserver`. Are you saying this is the wrong thing to do?

Not at all! I just feel sorry it is difficult to handle reentrant transaction observers. I had no opportunity to contemplate the case of multiple observers yet.

Do you happen to need the read-only transaction (the one that does not trigger the reentrant callback)?

**Comment by mallman** [comment]
> Oh, yes, that's perfectly valid 👍 Thanks for making your technique explicit. I've clarified the documentation in https://github.com/groue/GRDB.swift/commit/59c41c97afa0d1e84bd46cf404ebbc114398dc73.

Excellent. Glad I could help!

> Do you happen to need the read-only transaction (the one that does not trigger the reentrant callback)?

I do not, no. Unless I've missed something, I don't believe I've ever needed to observe a read-only transaction commit.

I think this pretty much wraps this up. Thanks again for your help and the documentation. By contrast, I have been absolutely _struggling_ to work with a very complex C++ API that is almost completely _undocumented_. Fortunately, the project is open source. Otherwise I'd be completely lost.
