### ISSUE TITLE
Database was inexplicably cleared

### ISSUE THREAD

**Issue by SF-Simon** [groue/GRDB.swift#1407]
```
    var configuration: Configuration = Configuration()
    configuration.label = "lableName"
    configuration.readonly = false
    configuration.busyMode = .timeout(10)
    configuration.prepareDatabase { db in
        if db.configuration.readonly == false {
            var flag: CInt = 1
            let setPersisWalCode = withUnsafeMutablePointer(to: &flag) { flagP in
                sqlite3_file_control(db.sqliteConnection, nil, SQLITE_FCNTL_PERSIST_WAL, flagP)
            }
            if setPersisWalCode != SQLITE_OK{
                ...
            }
        }
    }
    self.dbWriter = try DatabasePool(path: self.dbPath, configuration: configuration)

....

            DispatchQueue.global(qos: .userInteractive).async { [weak self] in
                let tempSourceURL = FileManager.default.temporaryRandomDirectory // A temporary directory without a file name.
                var destination: DatabaseQueue! = try DatabaseQueue(path: tempSourceURL.path) // Create a backup object database.
                try self?.dbWriter.backup(to: destination)
            }
```

Some MacOS users reported inexplicably losing the entire database data.  I'm not sure if there is still a table, or if even the table disappeared together.
They speculate that the problem occurred during the backup database process, but my code is very concise, just like the above, and there is no other possibility of data changes.

And this problem seems to be accidental, not every time it occurs. I tested my machine for 3 hours without any problems.

Their macOS systems are all 13+versions, but the specifics are not clear.

We really have no choice. can you confirm if the entire contingency occurred during the backup database process? Or is there any possibility of improvement in our overall writing style?

GRDB.swift version 6.13.0.

thx.

**Comment by groue** [comment]
Hello @SF-Simon,

I'm very sorry about users losing data. It's the worse problem ever.

Unfortunately, I can't see in the code snippet you have written anything that could end up with such a bad outcome.

**Comment by SF-Simon** [comment]
> Hello @SF-Simon,
> 
> I'm very sorry about users losing data. It's the worse problem ever.
> 
> Unfortunately, I can't see in the code snippet you have written anything that could end up with such a bad outcome.

If the entire backup process fails, will it lead to this situation? Like... Unable to read the table and content, but it may still be inside.

**Comment by groue** [comment]
I don't know. Please report the results of your investigations!

**Comment by SF-Simon** [comment]
I don't know how to go next. Please remember this matter. If anyone else encounters it, please let me know. thanks

**Comment by groue** [comment]
Sure, @SF-Simon.

Maybe your initial report could be enhanced by specifying _which_ database is "cleared". Is it the one that is backed up, or is it the backup? Or is it the result of the backup restoration (not described)?

In other words, there must be _some scenario_ that can lead to the data loss. You are asking where to go next, so if you would make one or several reasonable hypothesis of such scenario, this would certainly help identifying a way to reproduce the problem. You know that reproduction is key in solving such issues.

How to find those reasonable hypothesis? Something must write garbage into the database, since there is some data loss. Perform an exhaustive list of all writes. Remove the ones that can not possibly write garbage, using your most rigorous reasoning. Yes, this means learning things on the way, maybe asking further questions. Once innocuous writes are removed from the list, the problem must lie in the remaining ones: that's where you'll start exercising your imagination and look for nasty scenarios.

**Comment by SF-Simon** [comment]
> Sure, @SF-Simon.
> 
> Maybe your initial report could be enhanced by specifying _which_ database is "cleared". Is it the one that is backed up, or is it the backup? Or is it the result of the backup restoration (not described)?
> 
> In other words, there must be _some scenario_ that can lead to the data loss. You are asking where to go next, so if you would make one or several reasonable hypothesis of such scenario, this would certainly help identifying a way to reproduce the problem. You know that reproduction is key in solving such issues.
> 
> How to find those reasonable hypothesis? Something must write garbage into the database, since there is some data loss. Perform an exhaustive list of all writes. Remove the ones that can not possibly write garbage, using your most rigorous reasoning. It might be necessary to learn things on the way, maybe ask further questions, in order to reach the desired level of precision. Once innocuous writes are removed from the list, the problem must lie in the remaining ones: that's where you'll start exercising your imagination and look for nasty scenarios. Yes, it's a detective work 🕵️‍♂️ _When you have eliminated the impossible, whatever remains, however improbable, must be the truth._

I want to try copying a new database file, not through the _backup_ method, but like copying a regular file, copying the database file in use.

For example, my original database is at _~/User/a.sqlite_, and then I copy it to _~/User/folder/b.sqlite_ using the _FileManager.default.copyItem_ method. Of course, this a.sqlite is opening.

My idea is whether there is any bug that affects the integrity of my original database after the backup method is completed.

May I ask if this is feasible?

**Comment by groue** [comment]
> I want to try copying a new database file, not through the _backup_ method, but like copying a regular file, copying the database file in use.
> 
> For example, my original database is at _~/User/a.sqlite_, and then I copy it to _~/User/folder/b.sqlite_ using the _FileManager.default.copyItem_ method. Of course, this a.sqlite is opening.

Now this gets interesting.

Did you check if there weren't any [SQLite temporary file](https://www.sqlite.org/tempfiles.html) next to the copied file? Those "temporary" files are important, and not copying them along with the main database file is a frequent source of data loss or corruption.

Also, copying a database with file system apis may result in data corruption if there remain open connections to the copied database. What good can happen if the database is modified during the copy? Well, [no good](https://unix.stackexchange.com/questions/6924/what-happens-if-a-file-is-modified-while-youre-copying-it).

For all those reasons, it is strongly recommended to only use SQLite apis in order to perform copies (backup, or [`vacuum(into:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasewriter/vacuum(into:)-5lo41)). Only SQLite has the proper locking mechanisms that protect data during a copy.

**Comment by SF-Simon** [comment]
I have tried to replicate the database in various situations and the results have all met expectations, so I believe GRDB is robust. I don't understand the root cause of user issues, but I will try to find answers from other aspects.

This issue is temporarily over. If there is any new progress or content related to GRDB, I will reopen this issue .

If anyone else has a similar situation, please call me.
