### ISSUE TITLE
Filtering by Date with Decoding Strategy Not Working

### ISSUE THREAD

**Issue by baum-sparton** [groue/GRDB.swift#1412]
### What did you do?

I have a model which stores a timestamp using the .millisecondsSince1970 DatabaseDateDecondingStrategy.

    extension Model: Codable, FetchableRecord, MutablePersistableRecord {
        static let databaseDateDecodingStrategy: DatabaseDateDecodingStrategy = .millisecondsSince1970
        static let databaseDateEncodingStrategy: DatabaseDateEncodingStrategy = .millisecondsSince1970
    }

From my testing I can save and load the date and it appears in the correct format in the database.

Where I ran into an issue is when querying against the date.

    let someDate: Date = XXX
    let models: [Model] = try Model.filter(Column(CodingKeys.DateField) == someDate).fetchAll(db)

### What did you expect to happen?

I am expecting to get records with a matching timestamp returned from the database.

### What happened instead?

I was always getting zero records returned.

I have worked around the issue with the following:

let models: [Model] = try Model.filter(Column(CodingKeys.DateField) == Int(someDate.timeIntervalSince1970*1000)).fetchAll(db)

The work around is straightforward, but my initial impression was that it should not have been necessary.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.16.0
**Installation method:** Xcode Package Manager
**Xcode version:** 14.3.1
**Swift version:**
**Platform(s) running GRDB:** iPhone
**macOS version running Xcode:** 13.4.1

**Comment by groue** [comment]
Hello @baum-sparton,

The [Date and UUID Coding Strategies](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-uuid-coding-strategies) documentation mentions where the strategies apply (look for "Customized date and uuid handling apply"). Conditions such as column equality do not apply.

> The work around is straightforward, but my initial impression was that it should not have been necessary.

My thoughts exactly, but there is a difficulty.

One can write requests that involve several tables and several sources of dates at the SQL level. It's not possible to precisely track *what* a given Swift `Date` will be compared to, and which encoding the developer has in mind.

Eventually, I settled on not applying the encoding strategies at all, so that all requests are treated the same.

**Comment by baum-sparton** [comment]
>  "do the right thing"™
:joy: :grin: :joy:

No problem, I'm good with the work around.

The documentation is certainly a strength of the library.  I failed to properly digest the section you point out.  It is so information dense it can be easy to miss what may end up being a key detail to you.  Anyway, thanks for the quick response and keep up the good work.
