### ISSUE TITLE
Inconsistent prefix of index name

### ISSUE THREAD

**Issue by pixyzehn** [groue/GRDB.swift#1414]
### What did you do?

Created index using [indexed()](https://github.com/groue/GRDB.swift/blob/e83f3eb25ef4d5a36a13dbee98f8ac67e24e5c8f/GRDB/QueryInterface/Schema/ColumnDefinition.swift#L210) and [create(indexOn:columns:)](https://github.com/groue/GRDB.swift/blob/e83f3eb25ef4d5a36a13dbee98f8ac67e24e5c8f/GRDB/QueryInterface/Schema/Database%2BSchemaDefinition.swift#L573-L578).

### What did you expect to happen?

The index name should be consistent like `index_[table name]_on_[column name]_[column_name]...` using [Database.defaultIndexName(on:columns:)](https://github.com/groue/GRDB.swift/blob/e83f3eb25ef4d5a36a13dbee98f8ac67e24e5c8f/GRDB/QueryInterface/Schema/IndexDefinition.swift#L23).

### What happened instead?

While [create(indexOn:columns:)](https://github.com/groue/GRDB.swift/blob/e83f3eb25ef4d5a36a13dbee98f8ac67e24e5c8f/GRDB/QueryInterface/Schema/Database%2BSchemaDefinition.swift#L573-L578) generated index with `index_[table name]_on_[column name]_[column_name]...` name, [indexed()](https://github.com/groue/GRDB.swift/blob/e83f3eb25ef4d5a36a13dbee98f8ac67e24e5c8f/GRDB/QueryInterface/Schema/ColumnDefinition.swift#L210) generated index with `[table name]_on_[column name]` name without `index_` prefix.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.16.0
**Installation method:** CocoaPods
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @pixyzehn,

Thanks for opening this issue!

Yes, I regret having introduced two inconsistent index naming schemes. Not that this creates any bug, as far as I know.

Unfortunately, this inconsistency has shipped, and some apps may already have shipped code that relies on the names of those indexes (with or without the `index_` prefix). Fixing this inconsistency would break some apps.

All GRDB apis that change the database schema are usually embedded in migrations, and it is very important that migrations always execute the same schema changes. That's how apps can rely on a 100% deterministic schema. And that's why it's not possible to change the implementation of those apis. **We can fix bugs, but we can not fix regrets**.

So, I'm afraid the library will have to maintain this inconsistency forever 😅

Now, maybe someone will come up with a strategy for fixing this particular regret, though?

For example, we could enhance `DatabaseMigrator` so that it stores the GRDB version when it applies the first migration. This way, we could have databases created by a future GRDB 6.x+ avoid the inconsistency, while preserving the old behavior for databases created with older versions.

This would make the code much more complex, though. So I'm reluctant to do it until someone explains how precisely the inconsistent naming of indexes creates "real harm".

**Comment by pixyzehn** [comment]
@groue Thank you for your quick response. That's totally understandable as those indexes are already shipped and used.

For the sake of consistency, we'll rename it by dropping those indexes without `index_` and adding them again with `index_`.

Anyway, any suggestions are welcome. Otherwise, we can close the issue.

**Comment by groue** [comment]
Thank you for your answer @pixyzehn. Since you spend time fixing the names of those indexes, maybe you face some practical problems that go beyond consistency and "schema aesthetics". Don't hesitate sharing them here, so that we can reopen the issue if needed.
