### ISSUE TITLE
About DatabasePool write/read 

### ISSUE THREAD

**Issue by tksrl0379** [groue/GRDB.swift#1415]
### What did you do?

Thank you for creating such a great library.

![image](https://github.com/groue/GRDB.swift/assets/20080283/0233e40f-563d-46e7-a6a7-8cbec092273f)
> https://swiftpackageindex.com/groue/grdb.swift/v6.16.0/documentation/grdb/concurrency#Write-Transactions

I have a question about the write/read operations of DatabasePool,
According to the picture above, I understood that if it read before the end of a write, it read the previous state value. But what if the read itself was requested during the write, and I want to read the state value after the end of the write? Is there any other way besides observation? 

The only way to do that is to use a semaphore to make the read wait if the write is running?

### What did you expect to happen?

Executing a write in one thread, followed by a read in another thread, with the read waiting for the write to complete.

### What happened instead?

In the picture above, READ reads the previous state value without waiting for a WRITE.

### Environment

GRDB flavor(s): GRDB
GRDB version: 6.16.0
Installation method: CocoaPod
Xcode version: 14.3.1
Swift version:
Platform(s) running GRDB: iOS iPhone Device
macOS version running Xcode: 13.4

**Comment by groue** [comment]
Hello @tksrl0379,

> Executing a write in one thread, followed by a read in another thread, with the read waiting for the write to complete.

One way to achieve this is to start reading after the write has completed (was committed on disk).

I don't quite know if you're using synchronous APIs, or asynchronous ones (async/await, Combine publishers, completion blocks). Anyway, all of them can chain a read immediately after a write.

Those reads are not guaranteed to run in different _threads_. GRDB uses `DispatchQueue` internally, and queues don't make much guarantee about the threads that execute database jobs.

The guarantee that `DatabasePool` provides is that reads do not block writes. In our particular context, the read performed after the initial write does not prevent other subsequent (and concurrent) writes.

Now, you may look after another guarantee, which is that the read sees the database _in the exact same state_ as it was left by the previous write. This goes one step further, because now we don't want other writes to start until the read was able to acquire snapshot isolation right after the previous write transaction was committed on disk. This is a supported use case, described in the [Advanced DatabasePool](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/concurrency#Advanced-DatabasePool) chapter of the Concurrency Guide.

Does this answer your questions?
