### ISSUE TITLE
What's the "right" way to use `autoIncrementedPrimaryKey`?

### ISSUE THREAD

**Issue by OscarApeland** [groue/GRDB.swift#1435]
Fresh to GRDB. Loving it so far.

I can't seem to find documentation on the preferred method for creating objects with auto-incrementing IDs. Lets say I'm creating a table like this.
```
try db.create(table: "row") { t in
    t.autoIncrementedPrimaryKey("id")
}
```
First of all, should this property be `Int` or `Int64`? Then, how should the property be defined in the corresponding record?
```
struct Row: ... {
    let id: Int 
    // or
    let id: Int!
    // or 
    let id: Int?
}
```
It seems like it needs to be either optional or implicitly-unwrapped-optional, because just initing with `Row(id: 0).insertAndFetch(db)` crashes due to non-unique IDs. Initing the model with `Row(id: nil).insertAndFetch(db)` works, but that requires the Optional/IUO.

Is using IUO's the intended method for creating objects with auto-incremented IDs?

**Comment by groue** [comment]
Hello @OscarApeland,

I think you'll find GRBD documentation that is slightly outdated about this, so your question is a perfect opportunity to clarify ideas. It will be easier to update the doc after that.

**The recommended type for auto-incremented ids is the optional `Int64?`.**

```swift
// THE SETUP FOR AUTO-INCREMENTED IDS
try db.create(table: "player") { t in
    t.autoIncrementedPrimaryKey("id")
}

struct Player: FetchableRecord, MutablePersistableRecord {
    var id: Int64?

    // Update auto-incremented id upon successful insertion
    mutating func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
}
```

**Why `Int64` instead of `Int`?**

`Int64` is sure to fit the [64-bit rowids](https://www.sqlite.org/lang_createtable.html#rowids_and_the_integer_primary_key) generated by SQLite.

`Int` will *often* work just as well, because `Int` is 64 bits on most platforms and devices. But sometimes `Int` is only 32-bits. And since we generally do not make any computations with such ids, `Int` has no real advantage when compared to `Int64`.

**Why an optional?**

Because it makes it possible to use `nil` for records that are not saved yet, waiting for their auto-incremented id:

```swift
var player = Player(id: nil, name: "Albert")

// An unsaved player has a nil id:
player.id // nil

// A new id is generated when player is inserted:
try player.insert(db)
player.id // 42
```

If you used a non-optional `Int64`, you couldn't instantiate a `Player` without any id as in the above sample code, and you'd have to come up with some unique id yourself, without profiting from the SQLite auto-increment feature. Sounds like a missed target.

If you used an implicitly unwrapped optional `Int64!`, your application would not be able to deal with unsaved records safely:

```swift
struct Player {
    var id: Int64!
    var name: String
}

let player = Player(name: "Beatrix") // Looks innocuous, right?
print(player.id)                     // 💥 Well, it is not
```

This is wrong, because being unsaved is a normal state. Many records start their life unsaved until they are inserted in the database, and get an id.

**Don't make such record types conform to `Identifiable`**.

That's where I should update the documentation:

```swift
// BAD IDEA: Identifiable type with an optional id
struct Player: Identifiable {
    var id: Int64?
}
```

This makes it difficult to refer to a non-optional user id:

```swift
// This is an optional, because `User.ID` is `Int64?`
// It's impossible to express "a non-optional User.ID".
// One has to write `Int64`, which is less clear.
let userId: User.ID
```

This makes two unsaved players identical as far as `Identifiable` is concerned, with plenty of bad interactions with SwiftUI and other libraries:

```swift
let christopher = Player(id: nil, name: "Christopher")
let diane = Player(id: nil, name: "Diane")

// 100% legit, and very unsettling at the same time.
christopher.id == diane.id // true
```

The truth is that unsaved players *are not* identifiable, because they don't have any id yet. And that's why it is not recommended to have types with optional ids conform to `Identifiable`.

**Comment by OscarApeland** [comment]
That clarified everything I was wondering about and more - thank you very much!

**Comment by johankool** [comment]
Great answer! Would be great to add to the documentation.

In this example it's easy to keep the properties of `Player` and `PersistedPlayer` in sync but that won't scale. Would it make sense to define something like this protocol and generic?

```swift
public protocol Persistable: Codable, FetchableRecord, MutablePersistableRecord {
  associatedtype ID: Hashable, DatabaseValueConvertible
  static var databaseTableName: String { get }
}

public struct Persisted<V>: Identifiable, FetchableRecord, MutablePersistableRecord where V: Persistable {
  static public var databaseTableName: String { V.databaseTableName }
  
  public typealias ID = V.ID
  public var id: V.ID
  public var value: V
  
  public init(row: GRDB.Row) throws {
    id = row[Column("id")]
    value = try V(row: row)
  }
  
  public func encode(to container: inout GRDB.PersistenceContainer) throws {
    container[Column("id")] = id
    try value.encode(to: &container)
  }
}

struct Player: Persistable {
  typealias ID = Tagged<Player, Int64>
  var name: String
  var score: Int
}

typealias PersistedPlayer = Persisted<Player>

func foo(dbQueue: DatabaseQueue) throws {
  try dbQueue.write { db in
    // Insert
    var player = Player(name: "Arthur", score: 100)
    let persistedPlayer = try player.insertAndFetch(db, as: PersistedPlayer.self)!
    
    let persistedName = persistedPlayer.value.name
  }
}
```

**Comment by groue** [comment]
Sure @johankool, go ahead if your app can profit from this `Persisted` wrapper :-)

For extra convenience, you may want to make it `@dynamicMemberLookup`:

```swift
@dynamicMemberLookup
struct Persisted<V> ... {
    subscript<T>(dynamicMember keyPath: KeyPath<V, T>) -> T {
        value[keyPath: keyPath]
    }
    
    subscript<T>(dynamicMember keyPath: WritableKeyPath<V, T>) -> T {
        get { value[keyPath: keyPath] }
        set { value[keyPath: keyPath] = newValue }
    }
}

// No `value` in sight!
let persistedName = persistedPlayer.name
```

**Comment by DandyLyons** [comment]
To clarify, does the `Identifiable` conflict exist even if the `autoIncrementedPrimaryKey` is something other than `id`. For example: 

```swift
try db.create(table: "player") { t in
    t.autoIncrementedPrimaryKey("player")
}
```
then we could have a different property for the ID. Maybe something like this: 

```swift 
struct Player: Identifiable, Codable, PersistableRecord {
    var player: Int64?
    private let _uuid: UUID
    enum Identifier: Codable, Hashable {
        case db(Int64)
        case temp(UUID)
    }
    // Use a random UUID as the id until the db creates an auto incrementing primary key
    var id: Self.Identifier {
        guard let player else { return .temp(self._uuid) }
        return .db(player)
    }
}
```

Would GRDB/SQLite still have a conflict even if we used an approach like this?

**Comment by groue** [comment]
Hello @DandyLyons, Using a custom identifier type is fruitful idea, yes. I've performed a few similar attempts but did not find anything that could reach the level of a recommended technique. Probably I didn't try hard enough, and fresh ideas are welcome.

It's good that you can make something work in your app.

I'm not personally found of toying with the schema itself, and by that I mean that I'd try to find a solution that has no impact on the schema (so that people can name their column "id" if that's what they feel like doing).

If your `Identifier` type would provide a custom implementation of [`DatabaseValueConvertible`](https://swiftpackageindex.com/groue/grdb.swift/v6.23.0/documentation/grdb/databasevalueconvertible), it would probably become autonomous (no need for two extra properties).

And if it would provide a custom implementation of `==` from `Equatable`, it would not need to create a `UUID`.

> I guess my question is, is there a way that we could call `Player.find()` but use the primary key instead of the `Identifiable` id?

You can call `Player.find(_:key:)` instead of `Player.find(_:id:)`. The `key` variant accepts any database value, so a plain `Int64` will do.

You can also add an extension:

```swift
// App code
extension Player {
    static func find(_ db: Database, id: Int64) throws -> Player {
        try Player.find(db, key: rowid)
    }
}
```

If you want to share this extension between multiple record types, define a protocol.

**Comment by milesegan** [comment]
Having two distinct types for persisted vs unpersisted records makes sense but if there's a lot of fields in the record this seems like it results in a lot of code duplication. Is there a good way to avoid this?

**Comment by jubishop** [comment]
perhaps also adding:

```swift
extension Savable {
  static var databaseTableName: String {
    let prefix = "Unsaved"

    let typeName =
      String(describing: Self.self).components(separatedBy: ".").last ?? ""
    guard typeName.hasPrefix(prefix) else {
      fatalError("Struct name: \(typeName) must start with \"\(prefix)\".")
    }

    let suffix = typeName.dropFirst(prefix.count)
    guard let firstCharacter = suffix.first else {
      fatalError("Struct name after '\(prefix)' prefix is empty.")
    }

    let tableName = firstCharacter.lowercased() + suffix.dropFirst()
    return tableName
  }
}
```

so that my implementation can become as clean as:

```swift
struct UnsavedPodcast: Savable {
  let feedURL: URL
  var title: String
}

typealias Podcast = Saved<UnsavedPodcast>
```

**Comment by groue** [comment]
Thank you for sharing your solution, @jubishop 👍 Applications can indeed define their own protocols when they want several of their record types to share a common behavior. Another example can be found in the [Record Timestamps and Transaction Date](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/recordtimestamps) guide: `TimestampedRecord`.

**Comment by jubishop** [comment]
I just implemented Tagged into my codebase,  I added

```swift
import Foundation
import GRDB
import Tagged

extension Tagged: @retroactive SQLExpressible
where RawValue: SQLExpressible {}

extension Tagged: @retroactive StatementBinding
where RawValue: StatementBinding {}

extension Tagged: @retroactive StatementColumnConvertible
where RawValue: StatementColumnConvertible {}

extension Tagged: @retroactive DatabaseValueConvertible
where RawValue: DatabaseValueConvertible {}
``` 

per your advice given here in sept 2023.  does this remain the same for fully up to date grab 7.0 here in early 2025?

**Comment by groue** [comment]
Yes @jubishop, that's what I do in my apps that use GRDB 7 beta 👍
