### ISSUE TITLE
Provide prebuilt XCFramework with releases

### ISSUE THREAD

**Issue by anlaital-oura** [groue/GRDB.swift#1440]
I apologize for not using the PR template as this is more of a feature request rather than reporting an issue in the project itself.

We are still suffering from a SIL optimizer crash when building our project with GRDB linked to it when optimizations are enabled. This means that we still have to manually strip out some inlines from GRDB even after updating to Swift 5.9.

This issue combined with the fact that a prebuilt XCFramework would speed up compile times in general leads me to request if a prebuilt XCFramework could be provided with releases in this repository.

There seems to already be XCFramework creation present in the [Makefile](https://github.com/groue/GRDB.swift/blob/c599f6423ebaa9a927e831ecbc12378894768f10/Makefile#L222). I was wondering if this might be something you could also ship as part of the release assets? Or perhaps there is some blocker preventing this from happening, in which case I'd be very happy to contribute!

**Comment by groue** [comment]
Hello @anlaital-oura,

The ability to build an XCFramework is tested indeed, because some GRDB users need to build some. Quoting the FAQ from the main README:

> **Does GRDB support library evolution and ABI stability?**
> 
> No, GRDB does not support library evolution and ABI stability. The only promise is API stability according to semantic versioning, with an exception for experimental features.
>
> Yet, GRDB can be built with the "Build Libraries for Distribution" Xcode option (`BUILD_LIBRARY_FOR_DISTRIBUTION`), so that you can build binary frameworks at your convenience.

As far as I know, shipping binaries sends a wrong message, is not technically appropriate, and creates quite a burden. I would be glad to be corrected.

The wrong message is related to ABI stability. Users could think that they can replace a GRDB XCFramework with a newer one and let the linker do its job without recompiling their app, as they can with resilient Swift libraries. But GRDB is not resilient. Shipping an XCFramework would create wrong expectations, user frustration, and pointless GitHub issues.

All those issues that could have been avoided are a burden.

Now consider that the library supports multiple Xcode and Swift versions, and makes use of the `#if compiler` and `#if swift` directives. Shipping a single binary for the latest Xcode version makes sure we use the latest language features, but excludes users of older versions (frustration, issues, etc.). A single binary built the oldest supported Xcode version would lack latest language features (and create the false feeling of resilience mentioned above). This is why I do not think shipping binaries is technically appropriate. The only "solution" should be to ship as many binaries as there are language versions, help users picking the correct one (which, again, means answering more issues).

That's why the resting point is to not ship any binary, but to make sure users can.

Again, I'd be glad to be corrected if I made any mistake in my above reasoning.

**Comment by groue** [comment]
> we can simply build our own XCFramework since that is already supported by GRDB.

Glad you are not blocked 👍 

Thank you for opening this issue, @anlaital-oura. As you see, the door is not closed, but we have to move carefully.

**Comment by aehlke** [comment]
@anlaital-oura are you publishing these xcframeworks on github?
