### ISSUE TITLE
DatabaseValueConvertible use throws methods instead of properties

### ISSUE THREAD

**Issue by kdubb** [groue/GRDB.swift#147]
Currently, since `DatabaseValueConvertible` uses a property or a non throwing method, any errors in the conversion process cannot be propagated and there is no way to cancel a current transaction.

Unless I am missing something, the only options available to the implementor is to log an error and return some valid value (e.g. database null) or use some horrible overreach such as `fatalError`.

Switching this protocol to use throwing methods for both the to & from direction would allow errors during this phase to propagate and successfully fail any in-flight transactions.

A proposed implementation would be:
```
public protocol DatabaseValueConvertible : SQLExpressible {
    /// Returns a value that can be stored in the database.
    func databaseValue() throws -> DatabaseValue
    
    /// Returns a value initialized from *databaseValue*, if possible.
    static func fromDatabaseValue(_ databaseValue: DatabaseValue) throws -> Self?
}
```

If you are open to this change, I'd be more than happy to submit a PR implement it as such.

**Comment by groue** [comment]
Hello @kdubb. Please provide an actual use case that we can discuss.

**Comment by kdubb** [comment]
No problem.

```
extension Message.Attachments: DatabaseValueConvertible {

  public var databaseValue: DatabaseValue {

    guard let data = try? Message.Attachments.serialize(self) else {
      // TODO: report error
      return DatabaseValue.null
    }

    return DatabaseValue(value: data)!
  }

  public static func fromDatabaseValue(_ databaseValue: DatabaseValue) -> Message.Attachments? {

    guard case let .blob(data) = databaseValue.storage else {
      // TODO: report error
      return nil
    }

    guard let atts = try? Message.Attachments.deserialize(data) else {
      // TODO: report error
      return nil
    }

    return atts
  }

}
```

In this code we need to serialize our `Attachments` structure into a blob to store in the database; the complexity of `Attachment` makes it overly cumbersome to normalize the database into an "attachments" type table.

On insert/update we have no good options for failing any running transaction if the serialization fails. Actually, there are only two options available to us as suggested previously. First we could log the error and return database "null". While this works, it puts an unexpected value into the database. This essentially just pushes the error down the road. We now have to deal with it each time this record is loaded. Second, we could use a catastrophic method such as `fatalError`, to log and quit the application. Although useful for clear cut cases of programmatic misuse, `fatalError` should never be used to report legitimate runtime errors.

On load the options are quite as dire but they aren't very informative to the outside world.  If the deserialization fails we can log the error and return 'nil'. The biggest problem is that `nil` is a valid value for this column so the calling code doesn't know any error occurred.  If we made `nil` an invalid value for this column the calling code encountering `nil` would signal an error but wouldn't provide any information on what the error was or how to handle it. As pointed out previously, `fatalError` isn't really an option here because it's a runtime error for which it's not suited. 

Switching to the suggested protocol would allow throwing a serialization error, or letting one propagate. As the error propagates up the call chain it can rollback any in flight transaction.  This is preferable because it allows code outside the database serialization code to make decisions on errors while at the same time avoiding pollution of the database or application with invalid or incorrect values.

**Comment by groue** [comment]
Thanks @kdubb for the details.

A little background: DatabaseValueConvertible does not throw any error because GRDB focuses on trust and control. Trust of SQLite, control of database schema, control of data. Trust and control allows this library to provide non-throwing methods to database operations that should simply not fail:

```swift
// Look, ma: no try/catch!
//
// Both conversions methods of DatabaseValueConvertible are invoked:
// "Johnson" is converted to DatabaseValue, and person properties are
// converted from DatabaseValue.
let arthur = Person.filter(emailColumn == "arthur@example.com").fetchOne(db)
```

The reasoning is that most applications are simply unable to recover from errors that happen in such statements, and it's an actual service to crash inside GRDB instead of giving the developper the opportunity to catch and ignore errors.

Of course, there are ways to avoid crashes, and handle errors. I highly recommend a reading of [GRDB error handling](https://github.com/groue/GRDB.swift#error-handling) for more information. You'll learn how GRDB uses `fatalError` to report application bugs, and let the developer know that the application code, or the database, has to be fixed.


----

Now, back to your `Message.Attachments` type.

Please let me shed some more light on GRDB usage.

**First, deserialization.** The documentation of [DatabaseValue.fromDatabaseValue(_:)](https://github.com/groue/GRDB.swift#custom-value-types) says:

> The fromDatabaseValue() factory method returns an instance of your custom type if the databaseValue contains a suitable value. If the databaseValue does not contain a suitable value, such as "foo" for Date, the method returns nil.

**Follow this rule**. Have this method return nil in case of failed deserialization.

You'll then have two ways to handle invalid deserialization:

```swift
// Technique 1: crash on invalid conversion
// GRDB will crash on potential data loss: when database value is not NULL,
// and can't be converted:
let attachment: Attachment? = row.value(named: "attachment") // fatal error: could not convert ... to Attachment.

// Technique 2: don't crash on invalid conversion
let dbv: DatabaseValue = row.value(named: "attachment")
if dbv.isNull {
    // Handle NULL
if let attachment = Attachment.fromDatabaseValue(dbv) {
    // Handle valid attachment
} else {
    // Handle invalid attachment
}
```

You'll chose one technique or the other after you have picked your answer to this question: *is it true that the database should store invalid attachments?* I'd personnaly answer NO, granted wasting bytes on the user's hard drive is a *bug* that needs to be fixed (by changing the application code so that it can't fail, instead of throwing dubious errors).

**Next, serialization.** You claim that Attachment serialization can fail. Now I don't know. It may be true. In this case, I recommend not letting GRDB serialize attachments:
    
```swift
// Store attachment
let attachment = ...
let data = try attachment.serialize() // Explicit handling of serialization error
try db.execute("INSERT INTO messages (atts) VALUES (?)", arguments: [data])
```

Of course, if you eventually find out that attachment serialization failure should be considered a a bug (which requires changing the application code so that it can't fail, instead of throwing dubious errors), then you'll get:

```swift
extension Message.Attachments: DatabaseValueConvertible {
  public var databaseValue: DatabaseValue {
      return try! Message.Attachments.serialize(self).databaseValue
  }

  public static func fromDatabaseValue(_ databaseValue: DatabaseValue) -> Message.Attachments? {
    guard let data = Data.fromDatabaseValue(databaseValue) else {
        // No data, no attachment
        return nil
    }
    // Return nil in case of failed deserialization, as documented
    return try? Message.Attachments.deserialize(data)
  }
}
```

**Comment by groue** [comment]
@kdubb Maybe my previous message sounded like I wanted to push fatal errors down your throat. This is not my goal at all. GRDB does make a favor to specific situations, but it certainly won't lock you.

So if you really have to consider Attachments as a fundamentally untrustable type, and need to handle your serialization errors, then simply don't use DatabaseValueConvertible for Message.Attachments, and don't use RowConvertible for Message. They just don't fit your needs.

Instead of:

```swift
// Using RowConvertible and DatabaseValueConvertible attachments:
let messages = Message.fetchAll(db) // [Messages]
```

You'll write instead something like:

```swift
let messages = Row.fetchAll(db, Message.all()).map { try Message(row: $0) }
```

**Comment by kdubb** [comment]
While your answer seems reasonably thought out and well explained it seems very nonsensical to me.

Speaking generally, not specifically about `DatabaseValueConvertible`...

Your suggesting that the database file, which is outside the bounds of total control of the application developer, should be treated as "fundamentally trustable". In simple terms that can never be the case. There will be times that errors crop up due to mishandled files, edited files, write errors, and about a million of things I can think of.  In any of these cases your use of `fatalError`, or even `try!` statements, impose a finality on what should happen; and that is that the application should completely crash.

**What I really don't understand is what's the harm?**

Imagine changing all `fatalError` usage to `throw SomeError` and changing `try!` statements to `try`; with requisite changes to method signatures to allow throwing. Now the GRDB is flexible enough to be used in any way imaginable. You would be free to take your "fundamentally trustable" stance. I can be free to accept that database errors can happen (and code can be written to correct them). **In the end what's the net change to people using GRDB? They just add a `try!` to the affected statements and they are back to where GRDB is right now with just as much information as `fatalError` provides.**

Allowing errors to propagate freely to outside code seems that it should be a basic design tenant of any well written library. Instead you have taken a fairly hard line stance that says for most unforeseen errors crash the application and let the developer pick through the pieces of the crash; you offer no alternative of allowing anything else.

In the end, as I said previously, `fatalError` and `assert` are to be used to signify programming errors only. Essentially you've detected a fundemental misuse of the library and you will not take steps to work around it. This is not only a good use it is encouraged and applauded as only the programmer could have created these errors and only he can fix them.  Using these constructs in situations where something unthinkable thing CAN happen but it's not expected is rigid and inflexible.

**Comment by kdubb** [comment]
Let me put a simpler finer point on this...

**Should an application that has an invalid database crash or display a message to the user?**

**Secondly, if I wanted to display a message (maybe suggest a solution) where should I do this detection?**  

In GRDB currently you are forcing me to ensure the database is 100% valid before using it. In an error handling model, I could skip writing that code and just use the database. If an error pops up I can catch it and display a useful message to the end user.

**Comment by kdubb** [comment]
One file note... I'm not by any means bashing GRDB or you or any other authors.  The library is AWESOME already. So a great step up from our homegrown solutions built on FMBD.  I just want to help make it better and more useful to other if I can; I'm more than happy to write the code to implement it as well.

**Comment by groue** [comment]
> While your answer seems reasonably thought out and well explained it seems very nonsensical to me.

I'll try to explain.

> Speaking generally, not specifically about `DatabaseValueConvertible`...
> 
> Your suggesting that the database file, which is outside the bounds of total control of the application developer, should be treated as "fundamentally trustable".

Yes, I do. SQLite itself is more trustable than most applications. A local database is not some random JSON loaded from a remote server. GRDB is an application toolkit, and helps applications that control their database. Dealing with untrusted input is still possible (because this lib is not a toy) but untrusted input has not been the focus.

> In simple terms that can never be the case. There will be times that errors crop up due to mishandled files, edited files, write errors, and about a million of things I can think of.

GRDB exposes all write errors to the application.

> **What I really don't understand is what's the harm?**

Database sequences returned by the [fetch()](https://github.com/groue/GRDB.swift#fetching-methods) method are a very important tool of GRDB: they allow iterating database values while keeping memory footprint low, unlike the fetchAll() method which returns an array.
    
```swift
for message in Message.all().fetch(db) {
    // process message
}
```

Unfortunately, Swift sequences don't support errors: the `next()` method of the Iterator protocol does not throw.

It is thus *impossible* to provide a throwing sequence. That's the fundamental problem.

But what are we talking about, by the way? Since you have read [GRDB error handling](https://github.com/groue/GRDB.swift#error-handling), you know that you *can* iterate a database sequence and catch errors.

> Should an application that has an invalid database crash or display a message to the user?

As a user, I don't even want to read the kind of message you'll come up with.

> Secondly, if I wanted to display a message (maybe suggest a solution) where should I do this detection?

If `try DatabasePoolt(path: ...)` does not throw, the database is guaranteed to be usable. GRDB performs sanity checks on the database before returning the connection to you. If you find a counter-example, please file a bug.

On macOS, I agree that the user could trash the database file after the connection has been opened. I'll happily discuss this subject with you, *granted this is an actual problem you have*.

> In GRDB currently you are forcing me to ensure the database is 100% valid before using it.

Yes. Sorry if I repeat myself: **a local database is not some random JSON loaded from a remote server.**

> One file note... I'm not by any means bashing GRDB or you or any other authors. The library is AWESOME already. So a great step up from our homegrown solutions built on FMBD. I just want to help make it better and more useful to other if I can; I'm more than happy to write the code to implement it as well.

Thanks ! GRDB is also the child of years of home-grown code around FMDB ;-)

Listen: DatabaseValueConvertible does not throw. I do believe it is good design. Just like integer division does not throw, and crashes on `1/0`. If a type can't reliably be turned into a database value, it is not DatabaseValueConvertible. That's it.

RowConvertible, TableMapping, and Persistable are three built-on protocols that implement what GRDB calls "records". **Those protocols are not the end of the story.** I already know GRDB users who built their own recod layer on top of the SQL API. Nothing prevents you from writing a `FailableRowConvertible` protocol with a throwing `init(row:)` initializer!

**Comment by groue** [comment]
@kdubb Here is what I suggest:

- don't have Attachments adopt DatabaseConvertible
- don't have Message adopt RowConvertible
- convert attachments to DatabaseValue before sending them into GRBD, with error handling
- don't fetch messages, but rows that you map into messages, with error handling
- use prepared statements and the step() method of DatabaseIterator in order to expose all failure points and prevent all fatal errors.

Come back with some new feedback after that.

**Comment by groue** [comment]
Here is some sample code for you to chew on. Guaranteed without any fatal errors:

```swift
//: Playground - noun: a place where people can play

import GRDB

struct Message {
    let from: String
    let to: String
    let attachments: Attachments?
    
    struct Attachments {
        init(data: Data) throws {
            // TODO
        }
        
        func serialize() throws -> Data {
            // TODO
            return Data()
        }
        
        func validateSerialization() throws {
            // TODO
        }
    }
}

extension Message : TableMapping {
    static var databaseTableName = "messages"
}

extension Message : Persistable {
    // See https://github.com/groue/GRDB.swift#customizing-the-persistence-methods
    func insert(_ db: Database) throws {
        try attachments?.validateSerialization()
        try performInsert(db)
    }
    
    // See https://github.com/groue/GRDB.swift#customizing-the-persistence-methods
    func update(_ db: Database, columns: Set<String>) throws {
        try attachments?.validateSerialization()
        try performUpdate(db, columns: columns)
    }
    
    var persistentDictionary: [String: DatabaseValueConvertible?] {
        return try! ["from": from, "to": to, "attachments": attachments?.serialize()]
    }
}

extension Message {
    init(row: Row) throws {
        from = row.value(named: "from")
        to = row.value(named: "to")
        attachments = try row.dataNoCopy(named: "body").flatMap { try Attachments(data: $0) }
    }
}

let dbQueue = DatabaseQueue()
try! dbQueue.inDatabase { db in
    try db.create(table: "messages") { t in
        t.column("from", .text)
        t.column("to", .text)
        t.column("attachments", .blob)
    }

    try Message(from: "me", to: "you", attachments: Message.Attachments(data: Data())).insert(db)
    try Message(from: "you", to: "me", attachments: Message.Attachments(data: Data())).insert(db)
}

try! dbQueue.inDatabase { db in
    // Iterate messages from SQL
    do {
        let sql = "SELECT * FROM messages"
        let statement = try db.makeSelectStatement(sql)
        let rows = Row.fetch(statement)
        let iterator = rows.makeIterator()
        while let row = try iterator.step() {
            let message = try Message(row: row)
        }
    }
    
    // Iterate messages from a fetch request
    do {
        let request = Message.all()
        let (statement, adapter) = try request.prepare(db)
        let rows = Row.fetch(statement, adapter: adapter)
        let iterator = rows.makeIterator()
        while let row = try iterator.step() {
            let message = try Message(row: row)
        }
    }
}
```

**Comment by groue** [comment]
@kdubb Your questions did ring a bell in me. Although I still stand by non-failable DatabaseValueConvertible and RowConvertible conversion protocols, I have to admit that the state of handling errors that happen when reading from the database lacks a lot:

```swift
// A chore
let request = Message.all()
let (statement, adapter) = try request.prepare(db)
let rows = Row.fetch(statement, adapter: adapter)
let iterator = rows.makeIterator()
while let row = try iterator.step() {
    let message = try Message(row: row)
}
```

That's why I've pushed to the [DatabaseCursor branch](https://github.com/groue/GRDB.swift/tree/DatabaseCursor) support for a new type: DatabaseCursor.

Unlike DatabaseSequence which can not throw (because of Swift), DatabaseCursor throws whenever it can.

The code above can now read:

```swift
let request = Message.all()
let cursor = try Row.fetchCursor(db, request)
while let row = try cursor.step() {
    let message = try Message(row: row)
}
```

Of course, with records that can always initialize from rows, it's even shorter:

```swift
let cursor = try Message.fetchCursor(db)
while let message = try cursor.step() {
    ...
}
```

The fetchCursor() methods completes the list of [fetching methods](https://github.com/groue/GRDB.swift/tree/DatabaseCursor#fetching-methods):

```swift
try Type.fetchCursor(...) // DatabaseCursor<Type>
Type.fetch(...)           // DatabaseSequence<Type>
Type.fetchAll(...)        // [Type]
Type.fetchOne(...)        // Type?
```

I think this branch may help you.

**Comment by groue** [comment]
All right, @kdubb

Cursors are in pretty good shape now, and tested. No documentation yet, though. Generally speaking, cursors share traits from both `Sequence` and `IteratorProtocol`, although it is neither:

- Unlike sequences and iterators, all cursor method throw
- Unlike sequences, cursors can not be repeated
- Unlike iterator, cursor.next() does not mutate the cursor (disputable, but YAGNI has won)

```swift
protocol Cursor {
    associatedtype Element
    func next() throws -> Element?
}

// Get a cursor
let cursor: DatabaseCursor<T> = try T.fetchCursor(...)

// Iterate cursor elements
while let elem = try cursor.next() { ... }

// Iterate cursor elements with indices
while let (i, elem) = try cursor.enumerated() { ... }

// All elements
let elems = try Array(cursor)   // [T]

// Functional stuff
try cursor.filter { (elem: T) -> Bool in ... }                 // [T]
try cursor.flatMap { (elem: T) -> U? in ... }                  // [U]
try cursor.flatMap { (elem: T) -> [U] in ... }                 // [U]
try cursor.flatMap { (elem: T) -> DatabaseCursor<U> in ... }   // [U]
try sequence.flatMap { (elem: T) -> DatabaseCursor<U> in ... } // [U]
try cursor.forEach { (elem: T) in ... }
try cursor.map { (elem: T) -> U in ... }                       // [U]
try cursor.reduce(initial) { (acc: U, elem: T) -> U in ... }   // U
```

---

Now that you and @swiftlyfalling have succeeded convincing me that fetching methods have to throw, we'll face a big GRDB refactoring :-)

Swift sequences can't throw errors while iterated, so we have to get rid of them. So long, DatabaseSequence!

```diff
-func fetch(...) -> DatabaseSequence<T>
-func fetchAll(...) -> [T]
-func fetchOne(...) -> T?
+func fetchCursor(...) throws -> DatabaseCursor<T>
+func fetchAll(...) throws -> [T]
+func fetchOne(...) throws -> T?
```

That's for the upcoming episode.

**Comment by groue** [comment]
@kdubb The [DatabaseCursor branch](https://github.com/groue/GRDB.swift/tree/DatabaseCursor) is more solid than ever.

You asked for throwing DatabaseValueConvertible, and you got something different: fetching methods that throw:

```swift
Type.fetchCursor(...) throws -> DatabaseCursor<Type>
Type.fetchAll(...) throws -> [Type]
Type.fetchOne(...) throws -> Type?
```

**DatabaseValueConvertible and RowConvertible are still types that do not throw.**

In the new context of fetching methods that throw, I did check the consequences of having those protocols throw errors. They still are undesirable: `record.copy()` would need to throw, [FetchedRecordsController](http://github.com/groue/GRDB.swift#fetchedrecordscontroller) could no longer lazily instantiate records, and we'd see code like the following:

```swift
// Meh
self.name = try row.value(named: "name")
```

The line above is the gist of the problem with a throwing DatabaseValueConvertible protocol. It would be OK for some remote JSON, but not for a local database. Developers who control their database don't have to pay for people who don't know their tools.

Considering your Message.Attachments type, the fact that it can not reliably be fetched and stored in SQLite means that it is not DatabaseValueConvertible. For the same reason, I doubt Message is RowConvertible or Persistable.

I did provide [above](https://github.com/groue/GRDB.swift/issues/147#issuecomment-262901110) some sample code that work around conversion errors, *but I now recommend that you don't follow this path*. Forcing these types to adopt protocols that were not designed for them is fighting the library (practically speaking, persistentDictionary becomes unreliable, and this hampers [changes tracking](https://github.com/groue/GRDB.swift#changes-tracking)). Instead, consider doubling Message with a clean [MessageDAO](https://en.wikipedia.org/wiki/Data_access_object) type that does adopt RowConvertible.

I'm closing this issue in favor of #148.

I will happily welcome comments about each remaining `try!` that you'll find in GRDB code base. I think I have an answer for each of them.

**Comment by kdubb** [comment]
Sorry for the delayed response... holidays are here!

@groue First let me say, thank you for all the effort put into this!

A couple of the points you made really cement some of the decisions that you made. For example, `Sequence` not being able to throw errors is an aspect I hadn't thought of. Also, having to write `try row.value(named: name)` does seem cumbersome.

The `DatabaseCursor` branch really looks great. It looks to be more of "my style" when it comes to dealing with errors.  Yes it has a slightly more verbose nature as compared to the `Sequence` variants but I think that the error handling capabilities outweigh that cost.  I'll be digging into this branch tonight and see how it works for us.

As far as `DatabaseValueConvertible`, I am wondering if there's a Swift solution that we could come up with that would only require `try row.value(named: "name")` for special types that are from a mythical type such as `DatabaseValueSerializable`; an overload on `Row` would be required but that's even doable in an extension. I can play around with this idea on my own.

Again, thanks for the awesome effort!

**Comment by groue** [comment]
@kdubb I'm happy we're on the same wagon :-)

> As far as DatabaseValueConvertible, I am wondering if there's a Swift solution that we could come up with that would only require try row.value(named: "name") for special types that are from a mythical type such as DatabaseValueSerializable; an overload on Row would be required but that's even doable in an extension. I can play around with this idea on my own.

Yes, this should be possible.
