### ISSUE TITLE
Xcode "Hang Risk" warning due to "itemsSemaphore.wait()" priority inversion.

### ISSUE THREAD

**Issue by leotumwattana** [groue/GRDB.swift#1482]
### What did you do?

We are using GRDB in our project which also uses CloudKit's new CKSyncEngine. When we try to write data from CloudKit fetch events into GRDB, we sometimes see some kind of hang to the app even though we are doing CloudKit and GRDB writes on a background thread. We are also getting the following Xcode "Hang Risk" warning:

**Thread running at User-interactive quality-of-service class waiting on a lower QoS thread running at Utility quality-of-service class. Investigate ways to avoid priority inversions.**

So our current working hypothesis is that this priority inversion is causing hangs in our app.

### What did you expect to happen?

Be able to write a batch of fetched CKRecords into GRDB without hangs possibly caused by priority inversion.

### What happened instead?

We are getting the "Hang Risk" warning and also seeing our app hang when we try to write data from our CloudKit fetch events into GRDB.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.23.0
**Installation method:** SPM
**Xcode version:** 15.1
**Swift version:** 5.9
**Platform(s) running GRDB:** iOS, macOS
**macOS version running Xcode:** Sonoma 14.1.1

![CleanShot 2024-01-17 at 01 01 49](https://github.com/groue/GRDB.swift/assets/544211/54412a8f-9dcc-4c2b-b0ad-b28aa1a03c54)

**Comment by groue** [comment]
Hello @leotumwattana,

This is a warning about sub-optimal use of threads. Check Apple documentation [Diagnosing performance issues early](https://developer.apple.com/documentation/xcode/diagnosing-performance-issues-early) in order to understand what this warning is about.

There are already [a few issues opened about priority inversion warnings](https://github.com/groue/GRDB.swift/issues?q=priority+inversion). Take care that some applications instruct GRDB to perform the wrong actions: it's important that you understand the above Apple documentation. By default, all database operations run with the `userInitiated` quality of service (see [`Configuration.qos`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/configuration/qos)).

Finally, check if your application performs any **synchronous** access to GRDB from an **asynchronous** `Task`:

```swift
// WRONG APPLICATION PATTERN

// An async function...
func asyncFunction() async throws {
    try performSyncDatabaseAccess()
}

func performSyncDatabaseAccess() throws {
    // ...should not call a synchronous database access method.
    try dbPool.read { db in... } // sync
}
```

If this happens, refactor your app so that all database accesses performed from a `Task` are asynchronous:

```swift
// CORRECT APPLICATION PATTERN
// An async function...
func asyncFunction() async throws {
    try await performSyncDatabaseAccess()
}

func performSyncDatabaseAccess() async throws {
    // ...can call asynchronous database access methods.
    try await dbPool.read { db in... } // async
}
```

**Comment by leotumwattana** [comment]
Thanks @groue!
