### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by gabors** [groue/GRDB.swift#1489]
Hi, was wondering if/when you would be adding the privacy manifest to the GRDB SDK as per https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by groue** [comment]
Hello @gabors,

I'm not currently working on it, because I'm not sure it is strictly necessary to ship a privacy manifest with the library. A pull request would be gladly accepted, though. [This comment](https://github.com/groue/GRDB.swift/issues/1479#issuecomment-1914190713) describes what has to be done.

**Comment by gabors** [comment]
I understand, like it was mentioned in the other thread this link has the relevant information. https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
I cannot contribute with a PR because I do not know what APIs from the above list this SDK uses. It would be helpful if you add a privacy manifest.

**Comment by groue** [comment]
Yeah. Basically nobody cares :)

**Comment by gabors** [comment]
I guess if you don't want to add the privacy manifest we will find out if
Apple objects. 
It would certainly not hurt to add it to avoid developers having problems.
