### ISSUE TITLE
Returning fetched values from high-level specialised methods

### ISSUE THREAD

**Issue by jmcazaux** [groue/GRDB.swift#151]
Hi there,

I am fairly new to iOS development and coming from the Android world, I am looking for a basic ORM for my app.

GRDB seems to fit the bill.
I have started playing with it and I have a question already.

I want to hide all data access into high level helpers that expose specialised methods.
I was wondering how returning values would work in such a schema and how it should be done.

For example, a MapDbHelper provides a method to get a map by name 

```
    public func getMap(withName name: String) throws -> Map? {

        let column = Column("name")

        let request = Map.filter(column == name)

        var r: [MapSource]?

        try queue.inDatabase { db in
            r = try request.fetchAll(db)
        }

        return r?[0]
    }
```

Is it the way to do it ?
My guess is that r will always be nil when returning (as it is asynchronously set in the closure) 

I tried returning from the closure but the compiler did not like it.

I have not been able to find a similar exemple in the doc / demo app.

That would be great if someone can put me on the right track.

_Merci beaucoup ;)_

**Comment by groue** [comment]
*Bonjour Jean-Michel !*

> GRDB seems to fit the bill.

Thanks!

> I want to hide all data access into high level helpers that expose specialised methods.

You're perfectly entitled to do so!

> ```swift
> public func getMap(withName name: String) throws -> Map? {
>     let column = Column("name")
>     
>     let request = Map.filter(column == name)
>     
>     var r: [MapSource]?
>     
>     try queue.inDatabase { db in
>         r = try request.fetchAll(db)
>     }
>     
>     return r?[0]
> }
> ```

This code looks like it works, doesn't it?

Note that the `inDatabase` method is *synchronous*, as most GRDB methods. The `r` variable is thus set to a non-nil array when inDatabase has executed.

If you want a shorter version, you can use the `fetchOne` method (among the [fetching methods](https://github.com/groue/GRDB.swift#fetching-method), it is the one that consumes a single row and returns a single optional value):

```swift
// With fetchOne:
public func getMap(withName name: String) throws -> Map? {
    return try dbQueue.inDatabase { db in
        return try Map.filter(Column("name") == name).fetchOne(db)
    }
}
```

And if the `name` column is the primary key of your maps table, or a unique key, you can also check [Fetching By Key](https://github.com/groue/GRDB.swift#fetching-by-key) for some extra fetching methods that may fit well.

I think this should already help you a lot :-)

**Now I have an advice.**

The signature of `getMap` method has a slight issue which makes it not quite OK if your application is multi-threaded.

It *should* read instead:

```swift
public func getMap(withName name: String, from db: Database) throws -> Map? { ... }
```

Why so? That's because getMap should let the objects that use it (for example your application controllers) execute the database scenarios they have to implement, in a *safe* way. And *safe*, here, means that concurrent threads should not be allowed to mess things up.

This point is *very important* with GRDB: the DatabaseQueue *should not* be hidden in some DatabaseManager object (which does not manage much if it hides important database management methods). The DatabaseQueue should instead be available throughout your application, so that application controllers can leverage its safe concurrency methods.

For a technical explanation, please read of the [Concurrency Guide](http://github.com/groue/GRDB.swift#concurrency), especially the "Rules" section, and their explanation of possible issues.

For another, more high-level, take on the same subject, see [How to build an iOS application with SQLite and GRDB.swift](https://medium.com/@gwendal.roue/how-to-build-an-ios-application-with-sqlite-and-grdb-swift-d023a06c29b3), particularly the "Let Controllers Control" chapter.

Sorry for this reading list :-)

**Comment by jmcazaux** [comment]
Hi Gwendal,

many thanks for the clarification that is really helpful, but as you may think, your advice raises my interest.

The idea I had was to not expose the DBQueue to "consumers", but at the sale time when reading the documentation, I understood that it was likely to mess with the threading safety.

Your suggestion would be to let the "consumer" objects access the DBQueue (exposed in a singleton for example) and use the "specialized" objects within the closure ?

Sort of like this ?
```
class MyNiceController {

    /* Loads of code */
    func myFunc(withName name: String) {
    
        let dbQueue = DBManager.sharedInstance.dbQueue
        let result = try dbQueue.inDatabase { db in
            return try MapDataHelper.doSmothingSpecial(withName:name, from:db) 
        }

        /* Do something with result */
    }
    /* Loads of code again */
}
```

I understand the principle and the benefit, the issue I see with this (and this is not a criticism) is that GRDB then becomes spread into the entire code (much more of it at least) instead of being ringfenced into a few classes.

But I assume it is coming with the choice (of using GRDB). It has to be used this way...

**Comment by groue** [comment]
> Sort of like this ?

Yes.

> I understand the principle and the benefit, the issue I see with this (and this is not a criticism) is that GRDB then becomes spread into the entire code (much more of it at least) instead of being ringfenced into a few classes.

Yes. Your application will benefit from those little blocks of indented code from place to place. And you can (I do) shorten `DBManager.sharedInstance.dbQueue` to `DB.queue` or even `dbQueue`.

Back in the past, GRDB used to allow direct access to data, and the inDatabase blocks were optional. It has been painful to [remove](https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md#0570) these direct access methods. But, *voilà*, an application has sane threading rules or it has not! GRDB is not really complex: it just provides the robust concurrency tools that lack in most other SQLite libraries.

Happy GRDB!
