### ISSUE TITLE
Latest version 6.26.0 is not deployed to the Cocoapod 

### ISSUE THREAD

**Issue by kosratdev** [groue/GRDB.swift#1518]
### What did you do?
I tried to Install the latest version 6.26.0 via Cocoapod but it isn't available there. 

### What did you expect to happen?
Version 6.26.0 is available on Cocoapod.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.26.0
**Installation method:** CocoaPods
**Xcode version:**
**Swift version:**
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:**

**Comment by groue** [comment]
Hello @kosratdev,

That's unfortunate, but this is due to a CocoaPods issue: https://github.com/CocoaPods/CocoaPods/issues/11839. Please raise your concerns there.

You can also modify your Podfile as below:

- Depend on the GRDB6 branch. This is more or less equivalent to `pod 'GRDB.swift', '~> 6.0'`:

    ```ruby
    # Can't use semantic versioning due to https://github.com/CocoaPods/CocoaPods/issues/11839
    pod 'GRDB.swift', git: 'https://github.com/groue/GRDB.swift.git', branch: 'GRDB6'
    ```

- Depend on 6.26.0 explicitly:

    ```ruby
    # Can't use semantic versioning due to https://github.com/CocoaPods/CocoaPods/issues/11839
    pod 'GRDB.swift', git: 'https://github.com/groue/GRDB.swift.git', tag: 'v6.26.0'
    ```

**Comment by SagarSDagdu** [comment]
Hi @groue ,
Just wanted to inform you about a workaround I found to solve this, just in case you want to release the new version of your awesome library to Cocoapods:
https://github.com/stephencelis/SQLite.swift/issues/1250#issuecomment-2053121732

**Comment by groue** [comment]
Thank you @SagarSDagdu, that's very nice of you 👍 I do not want to workaround the CocoaPods issue, though. As a library owner, I need a stable, reliable, and long-term solution. If CocoaPods can't fix their stuff, my heart is broken but that's a problem with CocoaPods. I duly reported the problem, a long time ago, with a lot of details and arguments: I did my part, maybe even more than that. I won't pretend that I commit to maintaining a workaround in the long run, because this is just not true.

**Comment by SagarSDagdu** [comment]
Yeah, I read the entire thread, and you have pinpointed the exact issue in the above thread.
It is sad that Cocoapods maintainers do not want to address it on priority and it is resulting into a lot of libraries just moving away from Cocoapods 😢
Anyways I think it is your call for GRDB 👍🏻
Thank you for this lib.

**Comment by BirdArch** [comment]
Thank you for this workaround. It took me a while to find it, after I noticed pod update did not work any more. Maybe mention it in the [installation instructions](https://github.com/groue/GRDB.swift?tab=readme-ov-file#installation)?

**Comment by SagarSDagdu** [comment]
Hi @BirdArch , the maintainer of this repository has decided to not use this workaround for this lib, hence I did not raise a PR to add this to the installation instructions.

**Comment by BirdArch** [comment]
@SagarSDagdu My comment was not clear. It was not aimed at your workaround, but the [workaround](https://github.com/groue/GRDB.swift/issues/1518#issuecomment-2028690806) provided by @groue for users of the GRDB toolkit. The [installation instructions](https://github.com/groue/GRDB.swift?tab=readme-ov-file#installation) still state that CocoaPods can be used, - even as the first option - without mentioning this issue, which will leave users stuck with an old GRDB version.

**Comment by groue** [comment]
You're right, @BirdArch, users are currently mislead. I have been hoping that CocoaPods would solve their issue, but... it may be time today to acknowledge that this may never happen.

I'll thus favorably welcome a pull request that updates the installation instructions. It's important to give clear steps that are easy to follow. It is also important to underline that those instructions deviate from the norm, based on semantic versioning, and why.

**Comment by SagarSDagdu** [comment]
@groue I have raised a PR to address the installation instructions change: https://github.com/groue/GRDB.swift/pull/1584
Please have a look and review.
