### ISSUE TITLE
ValueObservation.tracking called on the updating thread

### ISSUE THREAD

**Issue by kernandreas** [groue/GRDB.swift#1529]
### What did you do?

I have a ValueObservation set up for an expensive record like that:
```
        ValueObservation
            .tracking { database in try ExpensiveRecord.fetchAll(database) }
            .publisher(in: dbQueue, scheduling: .async(onQueue: .global(qos: .background)))
```

This record is updated from multiple parts in the application using the synchronous API `try dbQueue.write`. Some of the updates are done on the main thread.

### What did you expect to happen?

Since I defined a background scheduler for the publisher, I did expect that the `.tracking{}` closure is called on this thread.

### What happened instead?

The `.tracking{}` closure is called on the thread that makes the update. If it is the main thread, then this results in app hangs. This behavior is somehow unexpected.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.26.0
**Installation method:** SPM
**Xcode version:** 15.3
**Swift version:** 5.10
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 14.0

**Comment by groue** [comment]
Hello @kernandreas,

I understand your surprise, but things are behaving normally. I'll explain how you can make sure the expensive fetch is not done on the main thread.

First, a word about the `scheduling` parameter:

The `scheduling` parameter controls where the fresh values are _notified_ to your app, not where the `.tracking{}` closure, which fetches fresh values, is called.

By instructing the value observation to notify fresh values on a concurrent background queue, you are not solving your initial problem. Instead, you are creating a new one ;-) The concurrent background queue is _concurrent_, which means that it does not guarantee the correct ordering of notifications (correct ordering requires a serial queue). If the app makes a change A and then a change B, in this order, your app may handle the fresh values B _before_ the fresh value A - and that is much probably a serious bug.

It is important to *never* use a concurrent queue in `scheduling`.

---

The observation you describe fetches its fresh value synchronously right after the write. This is why performing an update from the main thread calls the `.tracking{}` closure from the main thread.

There are two reasons for this synchronous fetch:

- Your app uses the `ValueObservation.tracking` method.
- Your app uses a `DatabaseQueue`.

In order to make sure fresh values are never fetched from the main thread, you have to change two things:

- Use the [`ValueObservation.trackingConstantRegion`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation/trackingconstantregion(_:)) method instead of `tracking`.
- Use a [`DatabasePool`](https://swiftpackageindex.com/groue/grdb.swift/v6.26.0/documentation/grdb/databasepool) instead of a `DatabaseQueue`.

With this different setup, the observation will be able to avoid the main thread when fetching new values, and notify the fresh values on the main thread (as most apps need):

```swift
ValueObservation
    // Track a constant region so that fresh values
    // are fetched asynchronously.
    .trackingConstantRegion { database in ... }
    // Use a DatabasePool so that ValueObservation
    // can perform asynchronous fetches.
    .publisher(in: dbPool)
```

**Make sure you read the `trackingConstantRegion` documentation before performing these changes**. If you don't do it correctly, the observation will miss some database changes.

**Comment by kernandreas** [comment]
Hello @groue,

thank you very much for your quick and detailed reply. I admire your detailed answers that explain things in detail.

I applied your recommended changes and everything works as advertised.

We are using in memory databases in the unit tests. Now I have to figure out how to refactor the tests to use `DatabasePool`. Maybe using the common protocols `DatabaseReader` and `DatabaseWriter` could do this trick.

Thank you!

**Comment by groue** [comment]
Thanks, @kernandreas :-)

> We are using in memory databases in the unit tests.

Yes, that's the way to do it :-)

> Now I have to figure out how to refactor the tests to use DatabasePool. Maybe using the common protocols DatabaseReader and DatabaseWriter could do this trick.

Yes, exactly! `DatabaseWriter` is the protocol you're after:

```diff
-let dbQueue: DatabaseQueue
+let dbWriter: DatabaseWriter
```

**Comment by groue** [comment]
Oh, and note that `ValueObservation.trackingConstantRegion` will work fine with both DatabaseQueue and DatabasePool. Just, only the app and its DatabasePool will profit from the scheduling optimization (fresh values not fetched on the main thread).

**Comment by groue** [comment]
Flagged as "needs revisiting" because avoiding the main thread is a reasonable desire, and the documentation should be enhanced.
