### ISSUE TITLE
GRDB does not seem to copy over all rows when inserting within a migration

### ISSUE THREAD

**Issue by anlaital-oura** [groue/GRDB.swift#1530]
### What did you do?

I am trying to do a migration for a table to fix a primary key issue. Since SQLite does not support altering constraints, I am using a migration written like this to achieve it:
```swift
var migrator = DatabaseMigrator()

migrator.registerMigration("some_migration") { db in
    try db.rename(table: "some_table", to: "some_table_old")

    try db.create(table: "some_table") { t in
        // column creation using t.column omitted
    }
    
    try db.execute(sql: "INSERT INTO some_table SELECT * FROM some_table_old")
    
    try db.drop(table: "some_table_old")
}
```

### What did you expect to happen?

I expected the SQLite database to contain `some_table` that has exact same dataset as was present in `some_table_old`. This is not the case, as only about ~240k rows are inserted out of ~400k.

If I run the same SQL statements using `sqlite3` then everything is as expected.

### What happened instead?

`some_table` does not contain all rows from `some_table_old`.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.26.0
**Installation method:** SPM
**Xcode version:** 15.3
**Swift version:** 5.10
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 14.4.1

### Demo Project

No repro case yet, but I can try to isolate the issue and provide one here later.

**Comment by groue** [comment]
Hello @anlaital-oura,

This is weird indeed, because well those GRDB statements translate into plain `RENAME TABLE`, `CREATE TABLE`, etc, without anything fancy. You can activate tracing to see them:

```swift
migrator.registerMigration("some_migration") { db in
    #warning("TODO: remove debugging SQL trace")
    db.trace { print("SQL> \($0)") }
    
    // Proceed with the rest of the migration
    ...
}
```

My only concern with your code is that it does not precisely follow the [SQLite instructions](https://www.sqlite.org/lang_altertable.html#making_other_kinds_of_table_schema_changes) for performing such changes to the database schema. The GRDB documentation translates it into Swift in the [Defining the Database Schema from a Migration](https://swiftpackageindex.com/groue/grdb.swift/v6.26.0/documentation/grdb/migrations#Defining-the-Database-Schema-from-a-Migration) chapter.

According to those instructions, I would expect to read instead:

```swift
migrator.registerMigration("some_migration") { db in
    // Create a new table with a fixed schema.
    try db.create(table: "new_some_table") { t in
        ...
    }

    // Transfer values. A word of caution here: this SQL
    // statements assumes both table have the same columns.
    try db.execute(sql: "INSERT INTO new_some_table SELECT * FROM some_table")
    
    // Drop old values and rename.
    try db.drop(table: "some_table")
    try db.rename(table: "new_some_table", to: "some_table")
}
```

This will solve some potential problems (described by the linked SQLite documentation), but I do not know if this will fix the weird dataset changes. I hope this is just a glitch in your testing, or a wrong copy statement, and not an SQLite or GRDB bug.

Please report your findings!

**Comment by groue** [comment]
😅 Don't worry! You had a good idea opening the issue anyway!
