### ISSUE TITLE
PlayerRequest.swift is identical in GRDBAsyncDemo and GRDBCombineDemo

### ISSUE THREAD

**Issue by hjrnunes** [groue/GRDB.swift#1532]
Per README of GRDBAsyncDemo:

> The topics covered in this demo are:
> 
> - How to track database changes and animate a SwiftUI List with an async sequence built from [ValueObservation](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation).
> 

I would expect this to happen in `PlayerRequest.swift`? But it's identical to the version in GRDBCombineDemo:

```swift
   func publisher(in appDatabase: AppDatabase) -> AnyPublisher<[Player], Error> {
        // Build the publisher from the general-purpose read-only access
        // granted by `appDatabase.reader`.
        // Some apps will prefer to call a dedicated method of `appDatabase`.
        ValueObservation
            .tracking(fetchValue(_:))
            .publisher(
                in: appDatabase.reader,
                // The `.immediate` scheduling feeds the view right on
                // subscription, and avoids an undesired animation when the
                // application starts.
                scheduling: .immediate)
            .eraseToAnyPublisher()
    }
```

Am I missing something? Thanks!

**Comment by groue** [comment]
Hello @hjrnunes,

Oh, I suppose you're surprised because there is no async sequence in `GRDBAsyncDemo`.

Thank you for reporting this: I'll update my wording, so that it is less misleading.

I did try to build a SwiftUI app from the [`ValueObservation.values(in:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/valueobservation/values(in:scheduling:bufferingpolicy:)) async sequence.

Unfortunately, there is no way to tell Swift Concurrency to start an async sequence _synchronously_, which means that a SwiftUI view that feeds from an async sequence MUST display an empty state until the first value is produced. While some apps can live with this, some other apps can not. That's why the GRDBAsyncDemo demo is still Combine-based for the database observation feature - Combine has no problem starting a publisher synchronously.

If you really want to use an async sequence, there's no problem: start a Task, and iterate the values returned by `ValueObservation.values(in:)`. There's no demo for that, but nothing prevents you from doing it. Your view will have to display an empty state - and maybe this is ok for you.

**Comment by groue** [comment]
The next version of the lib will not mention async sequences in the README of GRDBAsyncDemo.

Thank you for the report, @hjrnunes!

**Comment by hjrnunes** [comment]
Thanks @groue

**Comment by groue** [comment]
The doc was updated in the new version v6.27.0. Thanks again!
