### ISSUE TITLE
GRDB 6 missing DatabasePool/DatabaseQueue interchangeability 

### ISSUE THREAD

**Issue by freak4pc** [groue/GRDB.swift#1541]
### What did you do?

I upgraded from GRDB 5.26.0 to 6.27.0, mostly seamlessly :) 

### What did you expect to happen?

We have some wrapper code that keeps the databaseWriter in following property:

```swift
var dbWriter: any GRDB.DatabaseWriter
```

Then, in our production code we use a `DatabasePool`, but in tests we would sometimes swap to an in-memory `DatabaseQueue`.

This worked fine in GRDB 5 and I hoped it would behave the same in 6.

### What happened instead?

The compiler complains that certain pieces like `ValueObservation` or `DatabaseMigrator` expect a `some DatabaseWriter` and not `any DatabaseWriter`, like so:

<img width="909" alt="image" src="https://github.com/groue/GRDB.swift/assets/605076/53ded386-bf82-4735-82b5-c9cf4d37457f">

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.27.0
**Installation method:** SPM over Tuist
**Xcode version:** 15.3
**Swift version:** 5.10
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Sonoma

### Demo Project

Doesn't seem needed in this case

**Comment by groue** [comment]
Thank you @freak4pc for reporting this issue.

It looks that some auditing should be done indeed. Those are APIs I rarely use myself in this way, so I did not notice the problem.

I'll make an exhaustive list of methods that accept a generic DatabaseWriter or Reader.

I don't quite get why [SE-0352](https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md#when-can-we-open-an-existential) does not apply, though.

In the linked proposal text, search for "In the existing language, one could implement a shim..." The described technique will give you the needed workaround until GRDB7 can do what is needed so that no one faces the same issue as you do.

**Comment by freak4pc** [comment]
This section even more explicitly states you should be able to move from any to some and back, any chance this could be a bug? 

https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md#moving-between-any-and-some

**Comment by groue** [comment]
> This section even more explicitly states you should be able to move from any to some and back, any chance this could be a bug?
> 
> https://github.com/apple/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md#moving-between-any-and-some

I'll open a Github issue in the Swift repo if something does not behave as described by the proposal, yes. I'll need a closer look. Meanwhile, we just need GRDB users to be able to use `any DatabaseWriter` freely, since this is how we can use a pool in the app, and a queue in tests and previews. That's what's important.

(I'm late in my answer because I was in vacations 😎)

**Comment by groue** [comment]
Hello @freak4pc,

I listed all GRDB apis that accept a DatabaseWriter or DatabaseReader in a generic fashion (`some DatabaseReader` instead of `any DatabaseReader`), and gave them an existential. I got no compiler error, from Xcode 15.4 to Xcode 15.0.

In particular, this code compiles, which is as close as possible as your sample code:

```swift
func testValuesFromAnyDatabaseWriter(writer: any DatabaseWriter) {
    func observe<T>(
        fetch: @Sendable @escaping (GRDB.Database) throws -> T
    ) throws -> AsyncValueObservation<T> {
        let observation = ValueObservation.tracking(fetch)
        return observation.values(in: writer)
    }
}
```

All the GRDB demo apps use a common pattern, with a "manager" type that hides an `any DatabaseWriter` and exposes an `any DatabaseReader`:

```swift
public struct MyDatabaseManager {
    // Hidden because responsible of database integrity
    private let writer: DatabaseWriter

    // Public because reading can't harm
    public var reader: DatabaseReader { writer }
}
```

Those demo apps observe the database from this reader without any compiler error.

I'm not sure how you were able to get this compiler error.

**Comment by freak4pc** [comment]
I missed this being closed, apologies. I'm still able to reproduce this on an entirely brand new project, example:

<img width="1152" alt="image" src="https://github.com/groue/GRDB.swift/assets/605076/f8ed11c9-56af-4500-949c-56374f1e2b55">

Attaching the project, i might be missing something:
[GRDBInterTest.zip](https://github.com/user-attachments/files/15935930/GRDBInterTest.zip)

**Comment by groue** [comment]
Thank you @freak4pc. 

I recommend you open an issue at `https://github.com/swiftlang/swift/`, because it does not handle implicitly unwrapped optionals correctly.

I found a workaround:

```swift
let writer: DatabaseWriter = dbWriter
return observation.values(in: writer)
```

**Comment by groue** [comment]
> I recommend you open an issue at `https://github.com/swiftlang/swift/`

I filed https://github.com/swiftlang/swift/issues/74652

**Comment by freak4pc** [comment]
Was just about to file something, thank you for doing it 🙌 I'll follow there
