### ISSUE TITLE
How to temporarily disable observing changes?

### ISSUE THREAD

**Issue by Asura19** [groue/GRDB.swift#1547]
Question: I should update record in `cellForRow` method, then database gives onChange callback, and I will reload table and it will call `cellForRow`, it's an infinite loop, how to temporarily disable observing changes when I update a certern column? 

GRDB 6.21.0

**Comment by groue** [comment]
Hi @Asura19,

I would not recommend having your `UITableViewCell` subclass start its own observation of the database. It can create a performance problem, because as the number of cells grows, so does the number of observations, and this will not scale nicely.

A better approach is to perform one single observation, of the whole list, and create passive cells from the fetched items:

1. The view controller starts one observation of the database.
2. Fresh database items feed the table view data source.
3. The data source creates one cell per fetched item, and configure the values displayed by the cell, according to the item.
4. And that's it: no infinite loop.

See [`PlayerListViewController.swift`](https://github.com/groue/GRDB.swift/blob/v6.27.0/Documentation/DemoApps/GRDBDemoiOS/GRDBDemoiOS/ViewControllers/PlayerListViewController.swift) for an example of such view controller.

**Comment by Asura19** [comment]
Thanks for your replying. I think I didn't express clearly.
I do start observation in the view controller， just like the example app, and additionally: 
* I update the record in the cellForRow method, 

* and it triggered database onChange callback， 

* then I reloadData, 

* and uikit call cellForRow again

and it will cause an infinite loop

**Comment by groue** [comment]
I'll suppose that the thing you update is not visible on screen, then. Otherwise, it would make no sense.

There are two possible techniques.

First technique: make sure that the modification does not trigger a data source refresh. For example, remove the modified value from the observation, and filter out duplicate:

```swift
// Only values visible in the cell
struct MyCellContent: Equatable {
    var id: Int64
    var name: String
}

let observation = ValueObservation
    .tracking { db in
        try Player.fetchAll(db)
    }
    .map { players in
        // Only keep the information needed by the cell.
        players.map { player in
            MyCellContent(id: player.id, name: player.name)
        }
    }
    // Avoid an infinite loop caused by the update
    // made by the cell.
    .removeDuplicates()
```

Another possible technique is to specify the tracked region (see [Specifying the Tracked Region](https://swiftpackageindex.com/groue/grdb.swift/v6.27.0/documentation/grdb/valueobservation#Specifying-the-Tracked-Region)), so that the observation is not triggered by the update you perform:

```swift
// Don't track the column modified by the cell, in order to avoid
// an infinite loop.
let observation = ValueObservation.tracking
    region: Player.select(Column("name")),
    fetch: { db in
        try Player.fetchAll(db)
    })
```

**Comment by Asura19** [comment]
`Tracked Region` will work for me, A very great thanks to you !!!

**Comment by groue** [comment]
> Tracked Region will work for me

Great :-) Happy GRDB, @Asura19!

**Comment by martindufort** [comment]
Solved by issue as well.
