### ISSUE TITLE
DatabaseWriter missing transaction capability

### ISSUE THREAD

**Issue by kdubb** [groue/GRDB.swift#159]
We were planning on passing around DatabaseWriter instead of a specific implementation.  It was then we realized there is no common transaction oriented write request.

There is `DatabaseQueue.inTransaction` and `DatabasePool.writeInTransaction` which have the exact same signature.  It seems this should be pulled up into `DatabaseWriter`.

Is there a reason this was not done?

**Comment by groue** [comment]
Hello @kdubb.

There is no real reason.

DatabaseWriter was introduced *after* DatabaseQueue and DatabasePool came to life, as a support for FetchedRecordsController. It eventually occurred that it was possible to provide common robust concurrency primitives, and I felt like those primitives deserved being publicly exposed, through DatabaseReader and DatabaseWriter.

Now DatabaseQueue had `inTransaction` (inherited from [FMDB](https://github.com/ccgus/fmdb)), and DatabasePool had `writeInTransaction`, because pools insist on distinguishing reading from writing. Those method names don't match, and that's why DatabaseWriter has no transaction method.

With the current state of DatabaseWriter API, you perform a transaction like this:

```swift
try writer.write { db in
    try db.inTransaction {
        ...
        return .commit
    }
}
```

I can clearly admit that this can be improved.

I will welcome any improvement suggestion, as long as DatabaseQueue and DatabasePool remain true to themselves. I fear not being clear: queues and pools are very important types of GRDB, that *all* users have to use: their method names must remain clear, focused, and to the point. Those types are much more important than DatabaseReader and DatabaseWriter protocols that are only used by advanced users.

Since you're the first GRDB user who asks about DatabaseWriter, I'm quite interested into your use case, and your ideas for eventual improvements.

**Comment by kdubb** [comment]
Another team member, not knowing the tradeoffs between `DatabasePool` and `DatabaseQueue` used a queue when we really wanted a pool.  Now we're switching the code to use a pool.

Really the question came up as simply "Would we ever need to switch it back to a queue?". Initially my reaction was simply "no".  Although, one never knows exactly what the future holds so we thought we'd use the writer protocol until we realized it had no transactional method.

Looking at `DatabasePool.writeInTransaction`

**Comment by kdubb** [comment]
Another team member, not knowing the tradeoffs between `DatabasePool` and `DatabaseQueue` used a queue when we really wanted a pool.  Now we're switching the code to use a pool.

Really the question came up as simply "Would we ever need to switch it back to a queue?". Initially my reaction was simply "no".  Although, one never knows exactly what the future holds so we thought we'd use the writer protocol until we realized it had no transactional method.

Looking at `DatabasePool.writeInTransaction`
```swift
    public func writeInTransaction(_ kind: Database.TransactionKind? = nil, _ block: (Database) throws -> Database.TransactionCompletion) throws {
        try writer.sync { db in
            try db.inTransaction(kind) {
                try block(db)
            }
        }
    }
```
and `DatabaseQueue.inTransaction`
```swift
    public func inTransaction(_ kind: Database.TransactionKind? = nil, _ block: (Database) throws -> Database.TransactionCompletion) throws {
        try serializedDatabase.sync { db in
            try db.inTransaction(kind) {
                try block(db)
            }
        }
    }
```

These are essentially the same blocks of code.  Why name normalize the name and pull it up into `DatabaseWriter` to allow switching between pool and queue easily.  Just seems kind of an obvious change.

For backward compatibility the interfaces can keep their current methods and without any impact.

**Comment by groue** [comment]
Thanks for the context.

**DatabaseWriter has been designed for reusable agnostic code, not for hesitant apps.** Your feature request is out of scope.

Unlike reusable code, an app *positively* needs a pool, or a queue. It may switch from queue to pool, once in its lifetime, if it ever switches. In your context, it occurred that your app needs a pool. I'm glad you are positive about that.

Using DatabaseWriter would make it *harder* to write your app. That's because even though all types/protocols provide the same concurrency primitives, you would have to code against the smallest common guarantees. Fact is, queues are easier than pools, and pools are easier than DatabaseWriter:

- Pools are less forgiving than queues when one overlooks wrapping statements in a transaction (see rule 3 of the [concurrency guide](https://github.com/groue/GRDB.swift#concurrency)).
- DatabaseWriter.readFromCurrentState is synchronous, or asynchronous, depending on whether it is run by a queue or a pool. It thus requires higher libDispatch skills, and more complicated code.

I thus recommend that you code against DatabasePool, now that you know that this is the concurrency model you need.

**Comment by groue** [comment]
> one never knows exactly what the future holds

If you eventually switch from a pool to a queue, that's easy: replace all `DatabasePool` with `DatabaseQueue`, all `read` and `write` with `inDatabase`, and all `writeInTransaction` in `inTransaction`: you won't introduce any bug. The opposite is not true, though.

**Comment by groue** [comment]
I added a [few paragraphs](https://github.com/groue/GRDB.swift#databasewriter-and-databasereader-protocols) in the documentation.
