### ISSUE TITLE
Null field causes error on fetch

### ISSUE THREAD

**Issue by RocketCity** [groue/GRDB.swift#16]
If I have a Record something like this,
    class Thing: Record {
        var id: Int64!
        var name: String
        var description: String?
If I have a NULL value in the database for description, Thing.fetch causes  'fatal error: Could not convert NULL to String'.   Shouldn't declaring description as String? allow for NULLs? What am I doing wrong?

**Comment by groue** [comment]
Hello @RocketCity 

Reading the error, It looks like you are trying to extract a NULL value is a non-optional String. And it fails because only optionals can be set to nil.

I also guess the application crashes when it tries to set the `name` property of a Thing, since `name` is the only non-optional String property I can see.

So I don't quite know what you are doing wrong, but here is my advice:

1. Make sure you update your application to latest version of GRDB (v0.36.0) if not done yet, because the last time we talked together, the Record class had design issues which made it painful to deal with non-optional properties. It is much cleaner now. See the [documentation](https://github.com/groue/GRDB.swift#subclassing-record) for details.
2. If the name really must not be nil, then keep your non-optional property, but adapt your database so that column is NOT NULL, as in `CREATE TABLE things (name TEXT NOT NULL, ...)`. It is then likely that your application will exhibit another error, when SQLite itself will prevent you from storing a NULL value in that name column. But at least your database schema and your Record will agree on the valid values of name.
3. Otherwise, if the name can be nil, make it an optional `String?`, and your error will vanish.

**Comment by RocketCity** [comment]
Sorry --  dumb mistake on my part,  I was just looking at the wrong class!   Working as expected for NULLs for optional properties when I am looking at the right class.... :-P
(And yes everything going well on latest version, thanks!)

**Comment by groue** [comment]
OK then :-) Happy GRDB!

**Comment by rajeshm20** [comment]
Great!, same error...working now..Thanks @groue .

**Comment by rajeshm20** [comment]
Great!, Same Error...clear now....Thanks @groue
