### ISSUE TITLE
Help troubleshoot fatal error 

### ISSUE THREAD

**Issue by shams-ahmed** [groue/GRDB.swift#161]
```
fatal error: 'try!' expression unexpectedly raised an error: SQLite error 10 with statement `PRAGMA table_info("members")`: disk I/O error: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178
```

It only happens when doing unit test with empty table or table with some data... any help on how to figure out why this happens? at this current time am not planning to use their latest version since it has so many breaking changes 

Version: 
v0.90.1

**Comment by groue** [comment]
Hello @shams-ahmed,

Please update to latest GRDB version, and if the error is still there, please provide a full stack trace.

**Comment by groue** [comment]
BTW, the SQLite error 10 `SQLITE_IOERR` is triggered by an iOS application that attempts to use a database that is unavailable due to [data protection](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/StrategiesforImplementingYourApp/StrategiesforImplementingYourApp.html#//apple_ref/doc/uid/TP40007072-CH5-SW21).

If this is your case, GRDB 0.99.2 will make you able to catch this kind of error.

**Comment by shams-ahmed** [comment]
@groue Thanks for helping, i figured out what was wrong... my database was stored in user directory and while unit testing a framework it all done in a sandbox environment

**Comment by majorgilles** [comment]
@shams-ahmed 

Hello, if you have time, could you describe how you solved this env error?

**Comment by shams-ahmed** [comment]
@majorgilles There two solutions:

- Use in-memory database (my choice)
- Use another location to store your database like tmp folder
