### ISSUE TITLE
Delete database: "bug in client of libsqlite3.dylib"

### ISSUE THREAD

**Issue by JohnRbk** [groue/GRDB.swift#164]
It is sometimes useful to be able to delete the underlying sqlite database (ex: when writing unit test cases).  When using FileManager to delete the database, Sqlite will occasionally throw an error:

```
unlinked while open: /var/mobile/Containers/Data/Application/4F96AB5F-7A0A-4DA3-BBEE-EC7A52504411/Documents/testdb.sqlite (Code 28)
```

Is there a way to explicitly close the underlying connection to the database to avoid this error?

For reference, this is how I delete my database within my unit test class:

```
    func deleteDatabase() {
        dbQueue.releaseMemory() // Unfortunately, this does not close the connection
        
        do {
            try FileManager.default.removeItem(atPath: databasePath())
        }
        catch {
            log.error("Got an error deleting database file")
        }
    }
```

**Comment by groue** [comment]
Quoting https://github.com/groue/GRDB.swift#how-do-i-close-a-database-connection:

> You do not explicitely close a database connection: it is managed by a database queue or pool. The connection is closed when all usages of this connection are completed, and when its database queue or pool gets deallocated.
>
> Database accesses that run in background threads postpone the closing of connections.

You just have to release your `dbQueue`.

If dbQueue is a property, make it an implicitly unwrapped optional, to convey the idea that it is not nil under regular operations:

```swift
class MyTests : XCTestCase {
    var dbQueue: DatabaseQueue!
    
    func openDatabase() throws {
        dbQueue = try DatabaseQueue(past: databasePath())
    }

    func deleteDatabase() throws {
        dbQueue = nil
        FileManager.default.removeItem(atPath: dbQueue.path)
    }
}
```

**Comment by JohnRbk** [comment]
Thank you - that works perfectly.

**Comment by gotev** [comment]
As of today, with latest GRDB version 1.0, dropping database [like that](https://github.com/groue/GRDB.swift/issues/164#issuecomment-275309406) works, but if I want to re-create it without restarting the app, using:
```swift
var database: DatabasePool!

// Add database migrations here
fileprivate let migrations = [
    M1_CreateTables()
]

fileprivate func databasePath() -> String {
    let documentsPath = NSSearchPathForDirectoriesInDomains(
            .documentDirectory, .userDomainMask, true).first! as NSString

    return documentsPath.appendingPathComponent("db.sqlite")
}

func setupDatabase(_ application: UIApplication) throws {    
    // Connect to the database
    // See https://github.com/groue/GRDB.swift/#database-connections
    database = try DatabasePool(path: databasePath())
    
    // See https://github.com/groue/GRDB.swift/#memory-management
    database.setupMemoryManagement(in: application)
    
    // Register all migrations and perform them
    var migrator = DatabaseMigrator()
    
    migrations.forEach({ migration in
        migrator.add(migration)
    })
    
    try migrator.migrate(database)
    
}
```
I get the following error when executing `try setupDatabase(UIApplication.shared)`: 
```
SQLite error 522 with statement `CREATE TABLE grdb_issue_102 (id INTEGER PRIMARY KEY);`: disk I/O error
```
I discovered that GRDB creates two other files: `-shm` and `-wal`. If I drop also those files, I can successfully re-create the database using the above mentioned `setupDatabase` function.
```swift
func dropAndRecreateDatabase(_ application: UIApplication) throws {
    database.releaseMemory()
    database = nil

    let fileManager = FileManager.default
    let dbFilePath = databasePath()
    let dbShmFile = "\(dbFilePath)-shm"
    let dbWalFile = "\(dbFilePath)-wal"

    try fileManager.removeItem(atPath: databasePath())

    do {
        if fileManager.fileExists(atPath: dbShmFile) {
            try fileManager.removeItem(atPath: dbShmFile)
        }
    } catch {
        log.debug("Unable to delete \(dbShmFile): \(error)")
    }

    do {
        if fileManager.fileExists(atPath: dbWalFile) {
            try fileManager.removeItem(atPath: dbWalFile)
        }
    } catch {
        log.debug("Unable to delete \(dbWalFile): \(error)")
    }

    try setupDatabase(application)
}
```
@groue Don't know if it's the best approach, but at least it works now

**Comment by groue** [comment]
Hi @gotev 

Your `dropAndRecreateDatabase` method is correct (yet the `releaseMemory()` line is purposeless since you're deallocating the database right after).

Let's see if we can make it simpler. And to make it simpler, let's first understand the level of complexity we want to avoid:

The `.shm` and `.wal` files are created by SQLite when the database is set to the [WAL mode](https://sqlite.org/wal.html), the mode that supports the enhanced concurrency of GRDB's database pools.

They are two of the many [temporary files used by SQLite](https://sqlite.org/tempfiles.html). As a matter of fact, `.shm` and `.wal` files are not quite temporary since they persist after a database connection is closed. But SQLite calls them "temporary" anyway.

Consequences:

- Databases are not always stored in a single file.
- The list of files used by a database is documented by SQLite, but their exact list is somewhat difficult to gather, and it may well depend on the SQLite version (a piece of information that is even more difficult to grab).
- A crash may leave extra temporary files around a database file. They won't bother SQLite when it eventually opens the database again, because it is [very robust](https://www.sqlite.org/howtocorrupt.html). But they may surprise other pieces of software.

This is really complicated.

**Conclusion: I recommend to store databases in their dedicated directories.**

When you want to delete a database, you just have to delete its directory:

```swift
// Good bye database, .shm, .wal, whatever!
try FileManager.default.removeItem(atPath: databaseDirectoryPath)
```

Another advantage is easier data protection with On-Disk Encryption on iOS. Some databases should be encrypted when the device is locked, and some other databases should be available when your application runs in the background on a locked device. Storing the database in a directory makes it possible to setup the same protection level for all database files (including the many temporary ones). See [Data Protection](https://github.com/groue/GRDB.swift#data-protection).

**Comment by gotev** [comment]
I completely agree. Thank you! Just to have an updated example for future reference:
```swift
import Foundation
import GRDB
import UIKit

var database: DatabasePool!

// Add database migrations here
fileprivate let migrations = [
    M1_CreateTables()
]

// https://github.com/groue/GRDB.swift/issues/164#issuecomment-312468700
fileprivate func databaseDir() -> String {
    let documentsPath = NSSearchPathForDirectoriesInDomains(
            .documentDirectory, .userDomainMask, true).first! as NSString

    return documentsPath.appendingPathComponent("db")
}

fileprivate func databasePath() throws -> String {
    let dbPath = databaseDir()
    try FileManager.default.createDirectory(atPath: dbPath, withIntermediateDirectories: true)
    return NSString(string: dbPath).appendingPathComponent("db.sqlite")
}

func setupDatabase(_ application: UIApplication) throws {    
    // Connect to the database
    // See https://github.com/groue/GRDB.swift/#database-connections
    database = try DatabasePool(path: databasePath())
    
    // See https://github.com/groue/GRDB.swift/#memory-management
    database.setupMemoryManagement(in: application)
    
    // Register all migrations and perform them
    var migrator = DatabaseMigrator()

    migrations.forEach { migrator.add($0) }
    
    try migrator.migrate(database)
}

func dropAndRecreateDatabase(_ application: UIApplication) throws {
    database = nil
    try FileManager.default.removeItem(atPath: databaseDir())
    try setupDatabase(application)
}
```
In this example `M1_CreateTables` is a class which implements the `DatabaseMigration` protocol.
```swift
import Foundation
import GRDB

protocol DatabaseMigration {
    func migrationIdentifier() -> String
    func migrate(_ db: Database) throws -> Void
}

extension DatabaseMigrator {
    mutating func add(_ migration: DatabaseMigration) {
        self.registerMigration(migration.migrationIdentifier()) { db in
            print("Performing database migration: \(migration.migrationIdentifier())")
            try migration.migrate(db)
            print("Database migration: \(migration.migrationIdentifier()) done")
        }
    }
}
```
