### ISSUE TITLE
How to prefetch an empty set of associated records?

### ISSUE THREAD

**Issue by leotumwattana** [groue/GRDB.swift#1646]
Hi @groue,

What is the syntax in order to `annotate` an `empty set` for a given `key` that is mapped to a Set<Item>?

I understand I can annotate default databaseValues as below:

``` swift
.annotated(with: [true.databaseValue.forKey(<someKey>)])
```

but is there a way to so something like:

```swift
.annotated(with: [Set<Item>().databaseValue.forKey(<someKey>)] )
```

Many thanks in advance.

**Comment by groue** [comment]
Hello @leotumwattana,

I assume that the record type expects to decode its `var someKey: Set<Item>` property from a JSON array. If I'm wrong, the rest of this answer is probably incorrect.

Since you want this set to be empty, the goal becomes to annotate the request with an empty JSON array. Probably this will just work out of the box:

```swift
.annotated(with: ["[]".databaseValue.forKey("someKey")] )
```

Alternatively, based on [JSON Support](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/json):

```swift
.annotated(with: [Database.jsonArray([]).forKey("someKey")] )
```

**Comment by leotumwattana** [comment]
Hi @groue,

Actually, the record type is expecting to get `var someKey: Set<Item>` from a `hasMany` association.

However, it seems doing the below fixes `keyNotFound` error, albeit the syntax is a little strange.

```swift
.annotated(with: ["[]".databaseValue.forKey("someKey")] )
```

**Comment by groue** [comment]
> Hi @groue,
> 
> Actually, the record type is expecting to get `var someKey: Set<Item>` from a `hasMany` association.

OK

> However, it seems doing the below fixes `keyNotFound` error, albeit the syntax is a little strange.
> 
> ```swift
> .annotated(with: ["[]".databaseValue.forKey("someKey")] )
> ```

The decoded type does not know if it decodes an hasMany association or a JSON array, and that's why it happens to work. But I agree that the intent is not clear.

Here is my new recommendation:

```swift
.including(all: theAssociation.none())
```

**Comment by leotumwattana** [comment]
Thanks @groue. That is nicer.

Have a great day!

**Comment by groue** [comment]
Thank you! You too :-)
