### ISSUE TITLE
Detecting unknown migrations when migrator is split into parts

### ISSUE THREAD

**Issue by tcwalther** [groue/GRDB.swift#1665]
### What did you do?

In my app, I have three different migrator instances.

1. The first one sets up the basic schema, after which I run a function that moves everything over from CoreData. While the whole moving function isn't a GRDB migration, I *may* actually be able to rewrite it as one. As it currently stands, the part that sets up the initial GRDB schema is a GRDB migration.
2. The second migrator migrates everything up to a certain point. After that point, we moved all the data from the app directory to the app group directory.
3. The third migrator starts after the app data has been relocated to the app group directory. This is where all current (and future) migrations will lie.

I would love to check for any unexecuted migrations to prevent beta users from downgrading to a version that may do unexpected things to the database.

### What did you expect to happen?

I want migrator3.hasBeenSuperseded(db) to return true only if newer migrations are available.

### What happened instead?

migrator3.hasBeenSuperseded(db) always returns true as migrator3 doesn't know about the migrations from migrator1 and migrator2.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 6.29.3
**Installation method:** SPM
**Xcode version:** 16.0
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 15.1

### Question

What is the recommended way of setting up migrations in a situation like this so I can correctly use hasBeenSuperseded? Should I never have created three migrators in the first place and instead work with only one object that I pass in as reference?

I'd normally try these things with trial and error, but since we're talking about DB migrations I'd prefer some advice on a best practice. Thank you so much in advance!

**Comment by groue** [comment]
Hello @tcwalther,

The life of an app can become complicated, hu? 😉 

> migrator3.hasBeenSuperseded(db) always returns true as migrator3 doesn't know about the migrations from migrator1 and migrator2.

Strictly speaking, migrator3 has no way to know how the unknown migrations (applied by migrator1 and 2) are ordered relatively to its own registered migrations. But it assumes they are posterior, because the scenario I had in mind was an app that has a single migrator, and wants to deal with the potential existence of other versions of itself (think of a Mac where two versions of the app exist in the Applications folder - the older version can detect it has been superseded by the newer version).

Well, your issue shows that other scenarios exist 😅 

Several times in the past, I've been pondering whether it should be possible to specify the name of the migrations database table used by a `DatabaseMigrator`, so that multiple independent migrators could coexist independently. In your application, this would have helped `migrator3.hasBeenSuperseded` to ignore migrations of the other migrators, and return the value you expect.

Maybe this feature could help solving your problem? Maybe it's too late, because your app has been shipped already, and all migration identifiers are already merged in a single database table on your users' devices. Anyway, I'll remember this issue as an argument for customizing the database table name ;-)

You should be able to implement the necessary logic with some raw information:

- [`migrator.appliedIdentifiers(_:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasemigrator/appliedidentifiers(_:)): the set of all applied migration identifiers (can be called from any migrator instance)
- [`migrator.migrations`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/databasemigrator/migrations): (badly named) the array of registered migration identifiers.

```swift
// Something like this?
let appliedIdentifiers = try migrator3.appliedIdentifiers(db)
let knownIdentifiers = Set(migrator1.migrations + migrator2.migrations + migrator3.migrations)
let containsUnknownMigration = appliedIdentifiers.contains { !knownIdentifiers.contains($0) }
```

**Comment by tcwalther** [comment]
Hi @groue,

Thank you so much for your wonderfully thorough and fast help.

One other idea: would it hurt to just add all the other migrations to `migrator3`, so that `migrator3` contains every migration ever in the correct order? Sure, it would duplicate a bit of code, but since that bit will never change again it should be alright.

**Comment by groue** [comment]
👍 This is a good idea, because migrators do indeed chain:

```swift
var migrator1 = DatabaseMigrator()
migrator1.registerMigration(...)
migrator1.registerMigration(...)

var migrator2 = migrator1
migrator2.registerMigration(...)
migrator2.registerMigration(...)

var migrator3 = migrator2
migrator3.registerMigration(...)
migrator3.registerMigration(...)
```

**Comment by tcwalther** [comment]
Oh, interesting. I guess migrators are stateless, and basically configuration objects. I never thought of that. That makes your solution very elegant.

Thank you very much for the excellent support!

**Comment by groue** [comment]
It makes `migrator3.hasBeenSuperseded` works as expected, right?

OK, so I think we can close this issue :-)
