### ISSUE TITLE
Proposal: Modify FTS5Pattern to support a mix of AND and OR.

### ISSUE THREAD

**Issue by charlesmchen-bc** [groue/GRDB.swift#1666]
`FTS5Pattern` is great but it's initializers don't cover all cases.

e.g. `init?(matchingAnyTokenIn:)` covers "foo OR bar" and `init?(matchingAllTokensIn:)` covers "foo AND bar", but what about: "(foo OR bar) AND other"?

In some cases you want a single pattern that does all of your matching, e.g. `ColumnExpression.match(_ pattern: GRDB.FTS5Pattern)`.  

Proposal 1: 
```
extension FTS5Pattern
   static func allOf(_ patterns: [FTS5Pattern]) -> FTS5Pattern 
   static func anyOf(_ patterns: [FTS5Pattern]) -> FTS5Pattern 
```
"(foo OR bar) AND other" could be expressed like so:
```
FTS5Pattern.allOf([
   .init(matchingAnyTokenIn:"foo bar"),
   .init(matchingAnyTokenIn:"other"),
])
```

Proposal 2:
Expose a `FTS5Pattern` .initializer that takes `rawPattern` as an escape hatch, so that client code can construct the pattern.

If you consider either proposal a good idea, I could prepare a PR.

Thanks for all of your hard work @groue .

**Comment by groue** [comment]
Hello @charlesmchen-bc,

If you have access to a database connection, you can combine other patterns with [`makeFTS5Pattern(rawPattern:forTable:)`](https://swiftpackageindex.com/groue/grdb.swift/v6.29.3/documentation/grdb/database/makefts5pattern(rawpattern:fortable:)):

```swift
func fetchDocuments(_ db: Database) -> [Document] {
  let pattern1: FTS5Pattern = ...
  let pattern2: FTS5Pattern = ...
  let combinedRawPattern = "(\(pattern1.rawPattern)) OR (\(pattern2.rawPattern))"
  let combinedPattern = try db.makeFTS5Pattern(rawPattern: combinedRawPattern, forTable: "document")
  return Document.matching(combinedPattern)
}
```

As you see, a database connection is required in order to build a FTS5Pattern from a raw string. The goal was to validate [FTS5 Column Filters](https://sqlite.org/fts5.html#fts5_column_filters) and to fail early, at the pattern creation, instead of failing when the request is executed. Retrospectively, this was probably a mistake.

Will you please tell if you can use this technique? If not, we'll relax the api. Your first proposal is interesting as well 👍

**Comment by groue** [comment]
Closing due to lack of feedback.
