### ISSUE TITLE
What colors is your function, blue vs red

### ISSUE THREAD

**Issue by kdeda** [groue/GRDB.swift#1667]
This more of a discussion/question.

From a glance it seems GRDB is mostly red (async) now.
`public func read<T>(_ value: @Sendable @escaping (Database) throws -> T) async throws -> T {`

Sometime a blue func is convenient, example: `UserDefaults.standard.bool `
```
        if UserDefaults.standard.bool(forKey: "SQL.debug") {
          // ... do something
        }
```

Is there way for me to write a proper generic blue func in GRDB ?
That will look like the following at the call site.
```
  let userCredentials = UserMetadata.value(for: \.userCredentials)
  let didAskAuthOnFirstRun = UserMetadata.value(for: \.didAskAuthOnFirstRun)
```
UserMetadata is capable of read/write a single row based on that keypath
You are not expected to write this, just provide some hints whether it can be done and what are some of gotchas.

I tried to use `SerializedDatabase.sync` and quickly got stuck at `GRDBPrecondition(!watchdog.allows(db), "Database methods are not reentrant.")`

Thank you.

**Comment by groue** [comment]
Hello @kdeda,

GRDB supports both synchronous and asynchronous database accesses. The library is agnostic and has no preference.

Since it might be difficult to choose, I hope you'll find some inspiration from [Choosing between Synchronous and Asynchronous Database Accesses](https://swiftpackageindex.com/groue/grdb.swift/v7.0.0-beta.6/documentation/grdb/swiftconcurrency#Choosing-between-Synchronous-and-Asynchronous-Database-Accesses) (in the documentation of GRDB 7 beta, but this mostly applies to GRDB 6 as well).

> I tried to use `SerializedDatabase.sync` and quickly got stuck at `GRDBPrecondition(!watchdog.allows(db), "Database methods are not reentrant.")`

This fatal error prevents misuses of the library. It fosters, in the GRDB user, the consciousness of transaction boundaries, which are important for preserving database invariants.

To better understand, please check the [Concurrency](https://swiftpackageindex.com/groue/grdb.swift/v7.0.0-beta.6/documentation/grdb/concurrency) guide.

Oh, and the public database access methods are `read` and `write`. `SerializedDatabase.sync` is an internal api that you are not supposed to use directly!

**Comment by groue** [comment]
You can have a look at the [demo app](https://github.com/groue/GRDB.swift/tree/master/Documentation/DemoApps/GRDBDemo). Its [`AppDatabase`](https://github.com/groue/GRDB.swift/blob/master/Documentation/DemoApps/GRDBDemo/GRDBDemo/Database/AppDatabase.swift) provides both sync and async methods in order to better serve the needs of the application.

**Comment by kdeda** [comment]
Excellent architecture and advice, Thank you.

I was doing some code reviews for a new iOS app and the programmer had been very liberal with async funcs, which tend to turn the whole code base purple.
Not a fan of marking each call as async unless necessary.

15 years ago I had invented my own sync sqlite ORM.
It was fast as hell and all was sync :-)

Thank you for all the hard work.
This package has been excellent so far.
