### ISSUE TITLE
Build error :  The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:GRDBSQLite'

### ISSUE THREAD

**Issue by Regatta45** [groue/GRDB.swift#1672]
### What did you do?

Create a new project in swift 6 with xib and core data
Build Ok
Add GRDB package in Package Dependencies
Build Ko

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** Version 7.0 Beta 6
**Installation method:** SPM
**Xcode version:** 16.1
**Swift version:** 6
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 15.1.1

### Demo Project

[TestGrdb.zip](https://github.com/user-attachments/files/17843153/TestGrdb.zip)

**Comment by Jnosh** [comment]
I think you are getting this error since you have added both the statically and dynamically linked versions of GRDB to the project.

From the [Swift Package Manager section in the README](https://github.com/groue/GRDB.swift#swift-package-manager):

> GRDB offers two libraries, GRDB and GRDB-dynamic. Pick only one. When in doubt, prefer GRDB. The GRDB-dynamic library can reveal useful if you are going to link it with multiple targets within your app and only wish to link to a shared, dynamic framework once. See [How to link a Swift Package as dynamic](https://forums.swift.org/t/how-to-link-a-swift-package-as-dynamic/32062) for more information.

When adding GRDB as a package dependency Xcode defaults to selecting both and you need to manually remove one of them:

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/f013f0a1-15ab-4c8a-9812-cd64f8ccaf1c">

You can fix the error by going to the settings for the target in Xcode and removing `GRDB-dynamic` from the linked libraries.

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/7577b080-94cf-462c-aaf2-639dc7a916ad">
