### ISSUE TITLE
Filter with negated boolean

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#175]
Hi there. I guess there is probably a Swift language limitation behind this but just in case:

```
MyRecord.filter(Column("id") > 10 && !Column("isDeleted")) // WORKS
MyRecord.filter(!Column("isDeleted")) // DOESN'T WORKS
MyRecord.filter(Column("isDeleted").negated) // WORKS
```

Is there a reason that `!` can't be applied to a `Column` when its alone in an expression?

**Comment by groue** [comment]
Hello @hartbit!

There is a [test](https://github.com/groue/GRDB.swift/blob/v0.101.1/Tests/Public/QueryInterfaceRequest/SQLSupportTests.swift#L694-L696) that makes sure `!Column("isDeleted")` is turned into the `NOT isDeleted` SQL snippet.

Is not not what you expect?

Also, please enable SQL tracing so that we know the SQL generated for each of your requests - it will help us better understand any issue:

```swift
var config = Configuration()
config.trace = { print($0) }
let dbQueue = DatabaseQueue(dbPath, configuration: config)
```

BTW, the `negated` property is documented with "This property is an implementation detail of the query interface. Do not use it directly."

**Comment by hartbit** [comment]
This very weird, but this is the error I'm encountering:

```
let result = try! dbQueue.read { db in
    try subSegment.applicationGroups
        .filter(!ApplicationGroup.isDeleted) // Cannot convert value of type 'Column' to expected argument type 'Bool'
        .order(ApplicationGroup.name)
        .fetchAll(db)
}
```

`applicationGroups` is a property returning `QueryInterfaceRequest<ApplicationGroup>` and `ApplicationGroup.isDeleted` is a `static let isDeleted = Column("isDeleted")`.

**Comment by hartbit** [comment]
Ok, figured it out, I was missing `import GRDB` :) Swift was doing type inference fine because it was getting the types through indirect imports, but it needed the explicit import for getting the custom operator functions.

**Comment by groue** [comment]
Well spotted @hartbit :-)
