### ISSUE TITLE
AnyTypedRequest with arguments

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#179]
As GRDB does not (yet) support joins, I can't return a `QueryInterfaceRequest` which requires joins. Instead, I've used the `AnyTypedRequest` type. The only problem is that, contrary to `QueryInterfaceRequest`, the only I've found to set arguments looks a bit ugly. Is there a better way?

```
func people(in country: Country) -> AnyTypedRequest<Person> {
	return AnyTypedRequest { db in
		let statement = try db.cachedSelectStatement(
			"SELECT people.* " +
			"FROM people " +
			"INNER JOIN country ON people.countryId = country.id " +
			"WHERE country.name = :country")
			
		statement.unsafeSetArguments([
			"country": country
		])
			
		return (statement, nil)
	}
}
```

**Comment by groue** [comment]
@hartbit Your code is correct. Prepared statements have a safe 'arguments' property that may be a better choice (see [Prepared Statements](https://github.com/groue/GRDB.swift#prepared-statements)). The unsafe setter won't catch mismatching or missing arguments, with the opportunity for unexpected queries to run.

Also I advise against using a cached statement here because arguments are fragile: if another request uses the same cached statement, and is executed *before* your request with different arguments, then your initial arguments will be lost.

**Comment by hartbit** [comment]
Thanks! I had missed that the `arguments` property was settable.

**Comment by groue** [comment]
No problem.

I'd personnally have used SQLRequest rebound to Person, as below. But your code is perfectly valid, when also more low-level. It has access to a connection instance (the `db`), and this allows custom requests to query the db for some schema information when they build their prepared statement and optional adapter.

```swift
// Using SQLRequest
func people(in country: Country) -> AnyTypedRequest<Person> {
    return SQLRequest(
        "SELECT people.* " +
        "FROM people " +
        "INNER JOIN country ON people.countryId = country.id " +
        "WHERE country.name = :country",
        arguments: ["country": country])
        .bound(to: Person.self)
}
```

Do as you wish. You are the first user I know that explores this area of GRDB, so please build your own experience ;-)

**Comment by hartbit** [comment]
I didn't know `SQLRequest`. Definitely cleaner!

**Comment by groue** [comment]
http://cocoadocs.org/docsets/GRDB.swift/0.101.1/Structs/SQLRequest.html
