### ISSUE TITLE
Repository Size

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#182]
I'm opening this issue in response to my earlier [tweet](https://twitter.com/simmelj/status/835243501042429952) about repo size (been out traveling, hence the delay).

Basic gist is:

* Tests are **99** megs, specifically performance tests are **90+** megs in and of themselves.
* `SQLiteCustom` is **73** megs.
* `SQLiteCipher` is **70** megs.

`GRDB` "proper" and demo apps are **~3** megs.

As someone on a pretty slow connection this can sometimes be frustrating! I realize this is an edge case and not high priority. But if there's something that can be done to split things out and make the GRDB repo itself smaller that'd be nice :)

**Comment by groue** [comment]
Hello @simme 

As you say, there are several "big" stuff in GRDB today:

- performance tests
- submodules such as SQLiteCustom et SQLiteCipher

If you don't use [custom SQLite builds](https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md) or [database encryption](https://github.com/groue/GRDB.swift#encryption), then you don't have to download any submodule: they are not part of this issue.

Now, performance tests. They are big because them embed an SQLite database, a Core Data database, and a Realm file. This is how we can perform [comparisons](https://github.com/groue/GRDB.swift/wiki/Performance) between GRDB, SQLite.swift, FMDB, Core Data, and Realm - and also spot performance regressions as GRDB evolves.

Splitting performance tests in another repository could be a great idea : this would reduce standard GRDB to its "proper" code ~3 MB.

But the GRDB git repo itself would still store the big benchmark databases, and cloning GRDB would still be long on a slow connection.

What do you think?

**Comment by simme** [comment]
Ah, I haven't actually looked in to the repo structure itself. I'm using Carthage to download the framework and it seems like it's initializing the submodules as well then. So maybe my solution is just to figure out if it's possible to tell Carthage to ignore submodules :)

And in regards to the performance tests, you're saying those could be split out into a submodule too?

**Comment by groue** [comment]
Ha, Carthage. It does not easily let its users minimize the work it performs. Especially, I think that it downloads all submodules - including GRDB submodules that are not needed for a regular build.

But some of those submodules (SQLCipher and SQLiteLib) are needed to support encryption and custom SQLite builds. Not anyone is satisfied with a regular build: that is a matter of fact. And GRDB will thus keep on supporting those extra configurations, and embed those two submodules. Regardless of Carthage.

Now GRDB has the SQLite, FMDB and Realm submodules that are only needed for performance tests, along with the three big benchmark databases. I guess we could extract those in a separate repository, and reduce the GRDB repo. An open question would then remain: how to make those external performance tests run with a local copy of GRDB – when it is used as the tool that spots performance regressions – and I'm not sure this is easy.

In all cases, I think that this issue you have opened in the GRDB repo is, as a matter of fact, a [Carthage issue](https://github.com/Carthage/Carthage/issues/new). One that could be titled along with "how to have `carthage build` limit the downloaded submodules?" Maybe this is already possible (but the [doc](https://github.com/Carthage/Carthage/blob/master/README.md) does not talk about that, or I missed it). Should it be solved in Carthage, it would profit all users of all libraries that liberally use submodules for any reason deemed reasonable.

Sorry if I pass the buck here - but, well, do you think Carthage should serve its users, or the other way around? You may already know my answer: GRDB itself goes a long way to ease its users' life.

Your ideas on how to extract performance tests are still welcome.

**Comment by simme** [comment]
I agree that this is probably more of an issue related to the way I handle my dependencies. I wasn't aware that many of the large things was from submodules that I didn't actually need to download.

I'm completely on the same page. I think we can close this as a "non-issue" :)
