### ISSUE TITLE
Swift 4 Archival & Serialization Proposal

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#186]
The Swift mailing list is currently discussing a proposal brought forward by the Foundation team to introduce a Swift-centric archival and serialization API. I think GRDB could greatly benefit from it to reduce it's API surface. We should probably try to see what that would look like and see if improvements can be made to the proposal to better work for GRDB.

Here are a few ideas of mine after reading the proposal. I'm not necessary saying they are great ideas, but that it's worth discussing:
• `Column` could be replaced by the `CodingKey` protocol. For example, this would allow me to get rid of my automatic generation of columns with Sourcery:

```
Person.filter(Person.CodingKeys.name == "David")
Person.filter({ $0.name == "David" })
```

• As a consequence, `init(row:)` and `propertiesDictionary` could be expressed through `Codable` and `RowEncoder` and `RowDecoder` types.

When pitting those two things together, GRDB massively benefits from the compiler generation that comes with this proposal.

Thoughts?

**Comment by groue** [comment]
I just seen that on [Twitter](https://twitter.com/mark_sabbatical/status/842164565479628800), and just had a quick read :-)

- Swift-evolution link: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170313/033910.html
- Proposal link: https://github.com/apple/swift-evolution/pull/639

I agree that it's very interesting, and that GRBD could take profit from those new protocols (along with your code samples).

Yet the proposal is very focused on NSCoding/JSON/Plist (all *hierarchical* formats). Maybe we could enter the discussion and see how *flat* formats like database rows could be supported without ruining @itaiferber's proposal.

I mean: should a database record embed *two* `CLLocationCoordinate`, the encoding/decoding code for those would have to deal with two different pairs of lat/long columns. There is a mismatch with a *natural* `Codable` adoption by `CLLocationCoordinate`, which encapsulates its own keys. And the *unique* `encode(to:)` implementation would output flat NSCoding/JSON/Plists as well, which may be undesired. Not necessarily a big issue, but I suffer from cognitive dissonance right now.

**Comment by groue** [comment]
Regardless on my previous comment, there's room for a default conformance to `RowConvertible` and `Persistable` based on `Codable`, *provided* the implementation of the Codable protocol does not involve any object hierarchy.

**Comment by groue** [comment]
The discussion on Swift-evolution is... not very interesting so far. Closing this issue.

**Comment by itaiferber** [comment]
@groue I'm not familiar with GRDB, so looking to learn. What is your use case, and do you feel that the new API doesn't cover it? Perhaps it can.

Is it the discussion that you feel is unclear and bloated, or the API itself?

**Comment by groue** [comment]
Hello @itaiferber, thanks for asking. The discussion still happens on the Swift evolution mailing list, and I don't quite have the time to enter the long-running expert debates that happen there. I'll thus just tell how GRDB and you proposal overlap, and stress some important design differences.

Some context first: GRDB is a toolkit for SQLite databases *with a focus on application development*. Since app developers usually don't like dealing with raw database rows, custom types (named records) can be directly stored and fetched to and from a database:

```swift
struct Farm { ... }
extension Farm : GRDB.RowConvertible { ... }
extension Farm : GRDB.Persistable { ... }

let farms = try Farm.fetchAll(db, "SELECT * FROM farms ORDER BY name")
let farms = try Farm.order(name).fetchAll(db)
if let farm = try Farm.fetchOne(db, key: 1) {
    farm.barnColor = .red
    try farm.update(db)
}
```

Now let's talk API design:

The conversion from raw SQL rows to records is safe, and without any ad-hoc list or enum of declared columns enum (the equivalent of your `CodingKey`). This list is implicit and embedded right into the **record properties**. Add a good use of type inference on return type, which exists for a reason after all, and you get a safe, short, obvious, and boring adoption of the RowConvertible protocol:

```swift
struct Location {
    let latitude: Double
    let longitude: Double
}

struct Farm {
    let name: String
    let location: Location
}

extension Farm : RowConvertible {
    // Not much skill required:
    init(row: Row) {
        name = row.value(named: "name")
        location = Location(
            latitude: row.value(named: "latitude"),
            longitude: row.value(named: "longitude"))
    }
}
```

Should string keys be a problem, you can of course define your list of ad-hoc constants (the equivalent of your `CodingKey`).

```swift
extension Farm : RowConvertible {
    // Opt-in
    static let name = Column("name")
    static let latitude = Column("latitude")
    static let longitude = Column("longitude")
    
    init(row: Row) {
        name = row.value(Farm.name),
        location = Location(
            latitude: row.value(Farm.latitude),
            longitude: row.value(Farm.longitude))
    }
}
```

At that point, we're almost as verbose as your proposal (but the type inference). @hartbit, who opened this issue, wonders how your proposal could benefit to GRDB. It sure [can](https://github.com/groue/GRDB.swift/issues/186#issuecomment-286999912), with caveats due to the flat nature of SQL rows.

But maybe I had you understand why I'm not overwhelmed by the proposal right now. The **mandatory** complexity and verbosity of your `CodingKey` protocol looks like an attempt at acheiving a "perfect" type safety, which is *not the crux* of your proposal: its primary job is to provide a serialization API. The whole discussion about int and string keys, and the fact that some serializers are flat and others hierarchical, should make it clear that the type safety you aim at needs runtime support (which means it's not that safe, after all). I'd rather have developers of various skills (even beginners) have a rich yet simple serialization tool. `CodingKey` should be opt-in.

Quoting our beloved [Chris Lattner](https://overcast.fm/+CdTE-_oY/1:07:12):

> The secret to Swift in being easy to learn, easy to use as a teaching vehicle, but also powerful enough to solve the problems that need to be solved, is that the complexity in the language needs to be [progressively disclosed](https://en.wikipedia.org/wiki/Progressive_disclosure).

**Comment by hartbit** [comment]
> The mandatory complexity and verbosity of your CodingKey protocol looks like an attempt at acheiving a "perfect" type safety, which is not the crux of your proposal: its primary job is to provide a serialization API.

It's funny because the discussion on the mailing-list argues that the proposal should have even more type-safety, which I tend to agree with. And I don't see how we can't have more type-safety AND a great serialisation API.

> The whole discussion about int and string keys

That's actually a case where people on the mailing list have come up with type-safe solutions.

> and the fact that some serializers are flat and others hierarchical

Perhaps something could be done around the `SingleValueDecodingContainer` protocol to disallow other nested coders.

> should make it clear that the type safety you aim at needs runtime support

I think we can do without much runtime support.

> I'd rather have developers of various skills (even beginners) have a rich yet simple serialization tool.

We should be able to have both type-safety and rich and simple serialization APIs.

**Comment by groue** [comment]
Go, go, the Swift-evolution team 👍

**Comment by groue** [comment]
> • Column could be replaced by the CodingKey protocol.
> 
> ```
> Person.filter({ $0.name == "David" })
> ```

@hartbit, thinking about it, the line above has a serious caveat: it wouldn't work for class hierarchies:

```swift
class TimestampedRecord : Record, Codable {
    var updateDate: Date?
    var creationDate: Date?
    
    override func insert(_ db: Database) throws {
        creationDate = Date()
        updateDate = Date()
        try super.insert(db)
    }
    
    override func update(_ db: Database, columns: Set<String>) throws {
        updateDate = Date()
        try super.performUpdate(db, columns: columns)
    }
    
    // Automatically generated by the compiler according to SE-0166
    private enum CodingKeys : CodingKey {
        case latitude
        case longitude
    }
}

class MyRecord : TimestampedRecord {
    var name: String
    
    // Automatically generated by the compiler according to SE-0166
    private enum CodingKeys : CodingKey {
        case name
    }
}

// I don't see how the compiler could deal with this:
MyRecord.filter({ $0.updateDate == $0.creationDate && $0.name != nil })
```

> This would allow me to get rid of my automatic generation of columns with Sourcery

This is not the goal of [SE-0166](https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md). Look at the `private` modifier of the generated `CodingKeys` enum: it's not designed for public consumption.

**Comment by groue** [comment]
Superseded by #221. Your ideas @hartbit are still welcome :-)
