### ISSUE TITLE
Unexpected "' character in string interpolation

### ISSUE THREAD

**Issue by aadilkeshwani90** [groue/GRDB.swift#19]
I am getting this error on statement.swift line 226
throw DatabaseError(code: SQLITE_MISUSE, message: "missing statement argument(s): \(caseInsensitiveSort(namedMissingKeys).joinWithSeparator(", "))", sql: sql, arguments: nil)

**Comment by groue** [comment]
Hello @aadilkeshwani90,

Yes, this is normal.

Your SQL query has named arguments (identifiers starting with a colon), and you have have tried to run the query without providing values for those arguments.

*Look closely at your crash log*. I mean, do it: it contains a very explicit message that tells which arguments are missing. For example:

```swift
// error: missing statement argument(s): name
...fetch(db, "SELECT * FROM table WHERE name = :name") 
```

To fix this error in your application, you just have to run your query with the needed arguments:

```swift
// OK
...fetch(db, "SELECT * FROM table WHERE name = :name", arguments: ["name": "Arthur"])
```

**Comment by groue** [comment]
Ha. You may also have this error because you directly embed strings into SQL requests, as in:

```swift
// Wrong
let string = ... // some string
let sql = "INSERT INTO table (name) VALUES ('\(string\)')"
try db.execute(sql)
```

Don't do that. Never ever. The string may contain SQL characters that SQLite may interpret in surprising ways, and I think this is what is happening to you.

For example:

```swift
// Wrong
let string = "foo'); DELETE FROM table; SELECT ('"
let sql = "INSERT INTO table (name) VALUES ('\(string\)')"
try db.execute(sql)
// Actually executed: INSERT INTO table (name) VALUES ('foo'); DELETE FROM table; SELECT ('')
```

Funny surprise! Your table is empty now!

Listen carefully: the *only correct* way to introduce values in SQL queries are *arguments*, as below:

```swift
// Correct
let string = ... // some string
let sql = "INSERT INTO table (name) VALUES (?)"
try db.execute(sql, arguments: [string])
```

See [Executing updates](https://github.com/groue/GRDB.swift#executing-updates) and [Fetch Queries](https://github.com/groue/GRDB.swift#fetch-queries) for more information.
