### ISSUE TITLE
[XCode 8.2] build error:  Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by omarfraiwan** [groue/GRDB.swift#192]
Hi Guys,

I am facing issue while building on Xcode 8.2 using Cocapods 
the compiler alwayes give me 
**"Command failed due to signal: Segmentation fault: 11"**

tracing the issue 
there is some files cause the failure like 
**CGFloat.swift , Configuration.swift , Cursor.swift , Data.swift , Database.swift , DatabaseCoder.swift , ..**

Please advice,

here is the compile issue if it is useful 

[log.pdf](https://github.com/groue/GRDB.swift/files/878251/log.pdf)

**Comment by groue** [comment]
Hello @omarfraiwan.

Unless I'm mistaken, your application has been using GRDB for a while. And you hadn't any issue then. What did you recently change, which could help understanding why you're having this new error?

**Comment by omarfraiwan** [comment]
Thank you @groue  my application is new and i just start using GRDB less than month ago, i used to build on real device and it run without issues, when i try to build on simulator it give me this error 

here is my project https://github.com/salemoh/GoldenQuraniOS/tree/master/GoldenQuranSwift

**Comment by groue** [comment]
Check again, **carefully**, the installation procedure: https://github.com/groue/GRDB.swift#cocoapods. I think you have missed a step.

**Comment by omarfraiwan** [comment]
Thanks @groue 
it fixed after return XCode8.2 to original name XCode

**Comment by groue** [comment]
Good! Happy GRDB!

**Comment by kdubb** [comment]
@groue Why does building GRDB require the Xcode to be specifically named `Xcode.app`?  This error happens (and only seemingly with GRDB [although maybe it's just the first in our dependency list that causes the issue?)]  when my Xcode is named for example `Xcode-8.3.app`.

**Comment by kdubb** [comment]
@groue Makes using tools like `xcversion` to install multiple Xcode versions impossible. Not to mention it's just very curios behavior.

**Comment by groue** [comment]
@kdubb That's because latest GRDB version has a [module map](https://github.com/groue/GRDB.swift/blob/v0.103.0/Support/module.modulemap) and module maps require hard-coded paths (there's no way to provide an SDK-relative path).

This module map doesn't work with Xcode 8.3: the work to fix it is not completed yet. It's very time consuming to support five targets (macOS, iOS, iOSSimulator, watchOS, watchOSSimulator), three installation methods (manual, CocoaPods, Carthage), and three variants of SQLite (system-provided, custom, SQLCipher). There's a WIP in the Xcode8.3beta and moduleMapRefactor branches. In these branches, the module map is no longer there (unless I'm mistaken): you'll be free to put Xcode where you want. If not, well, your help will be welcome. But I don't know if the future GRDB that supports Xcode 8.3 will use module maps or not. Making it work in all the variety of situations I have listed above is all I'm looking after. If it means a fixed Xcode path... so be it.

**Comment by kdubb** [comment]
Certainly understand now and if it is a limitation that cannot be overcome... "so be it".

Two thoughts...
1. **This information be displayed prominently somewhere** - It should include the error message from Xcode, so Google indexes it and people can get past it quickly. I realize it is there in README.md but It took me a lot longer that I would have thought to link up your comments above to the fact that the name of Xcode was the _actual_ problem.

2. Could an installation script, run during `pod install` generate a module map on the fly for the currently selected version of Xcode? The command line tools can point you to the absolute path of the selected Xcode version.

**Comment by groue** [comment]
@kdubb Pull requests are welcome!
