### ISSUE TITLE
column can't be updated because it is missing from persistentDictionary:

### ISSUE THREAD

**Issue by ryoid** [groue/GRDB.swift#197]
> fatal error: column localpicful3 can't be updated because it is missing from persistentDictionary: file GRDB/GRDB/Record/Persistable.swift, line 636

Getting that error when I try to update a record, when I have the column (localpicful3) declared in the persistent dictionary. I think it has to do with the variable being a nil, after I initialise it the error doesn't come up for that column, but it is thrown for another column that is nil instead. No issue with creating or deleting.

I'm pretty new to swift so I am probably making a mistake somewhere, any help is appreciated.

Relavent parts:
**Record**
Declaring the dictionary this way as I have quite a few columns
```
class Medicine: Record {

    var localpicful3: String?

    override var persistentDictionary: [String : DatabaseValueConvertible?] {
        var dictionary: [String: DatabaseValueConvertible?] = [:]
        dictionary["localpicful3"] = localpicful3
        return dictionary
    }
}
```

**Controller** that updates the record
```
try! dbQueue.inDatabase { db in
   if medicine.hasPersistentChangedValues {
      try medicine.update(db)
   }
}

```

Creating the table as such:
```
try db.create(table: "medicine") { t in
   t.column("localpicful3", .text)
```

**Comment by groue** [comment]
Hello @ryoid,

The error says `column localpicful3 can't be updated because it is missing from persistentDictionary`.

Why not simply take this message literally? The dictionary lacks a key. Your assumption that the persistent dictionary contains the "localpicful3" key is wrong.

> I think it has to do with the variable being a nil.

You bet. This is a Swift gotcha, and you're not the first falling into it. When a value is nil, `dic[key] = value` *removes* the key (if any), instead of associating the key with nil.

When localpicful3 is nil, the persistentDictionary has thus no associated value for this column. GRDB doesn't know which value it should store in the database for this column, and rightfully complains.

There is a reliable way to associate a dictionary key with an optional value, that works even when the value is nil. This is the `updateValue` method:

```swift
dictionary.updateValue(localpicful3, forKey: "localpicful3")
```

This is the solution to your issue.
