### ISSUE TITLE
sqlite_trace is depreciated in swift 3.1

### ISSUE THREAD

**Issue by GabbiOS** [groue/GRDB.swift#198]
I am working on a dictionary project. I was using GRDB as my external database. As soon as I upgraded to Xcode 8.3 it is not showing search results in my app. Earlier it was working fine. 
I know the two methods that has been initiated:
sqlite_trace_v2
sqlite_expanded_sql()

but they were no help to me. Kindly resolve this issue in GRDB(iOS)->core->Database.swift

![screen shot 2017-04-06 at 10 52 58 am](https://cloud.githubusercontent.com/assets/26952640/24739009/44e3653a-1ab7-11e7-93b0-70f2b8d5e993.png)

**Comment by groue** [comment]
Hello @GabbiOS

Ignore the sqlite_trace deprecation warning: deprecation warnings are not the sign that a feature has stopped working.

> As soon as I upgraded to Xcode 8.3 it is not showing search results in my app.

That looks more interesting: what has stopped working exactly? You don't explain anything. Please provide a detailed bug report if you need help (see http://stackoverflow.com/help/mcve)

**Comment by GabbiOS** [comment]
Earlier when I type in the textfield, the search results (table view) appears. But after upgrading, it's not showing up. No error has been encountered, only this single issue is being highlighted.

**Comment by groue** [comment]
@GabbiOS I do want to understand your trouble, because you may have found a GRDB bug. My responsibility as the main maintainer of this library is to fix its bugs so that GRDB users enjoy a robust and stable library.

Unfortunately, you did not provide any proper bug report that I can look at. A proper bug report makes it possible for the person you ask help from to *investigate*. That's why I linked to this page: http://stackoverflow.com/help/mcve. To help you provide the bug report that will help clearing things out. Please understand that until you make your part of the debugging job, my own part will not start.

**Comment by GabbiOS** [comment]
Thanks, but I figured out the bug. The bug isn't in the GRDB but in my code.

**Comment by groue** [comment]
Glad to hear that +1

Happy GRDB!
