### ISSUE TITLE
Swift compiler 2.1.1 hang forever on dictionary for persistentDictionary: [String: DatabaseValueConvertible?]

### ISSUE THREAD

**Issue by mamcx** [groue/GRDB.swift#21]
As reported on https://stackoverflow.com/questions/35325788/swift-compiler-2-1-1-hang-forever-on-dictionary

Plus, why is persistentDictionary: [String: DatabaseValueConvertible?] not a type?

**Comment by groue** [comment]
Hello @mamcx,

I guess the dictionary is too long for the Swift compiler. You can try to break it, or build it key after key as in:

```swift
var dic: [String: DatabaseValueConvertible?] = [:]
dic["id"] = id
dic["nombre"] = nombre
// etc.
return dic
```

Tell me if this works.

I'm sorry about such inconvenience: we can only hope that the Swift compiler will improves over time.

> Plus, why is persistentDictionary: [String: DatabaseValueConvertible?] not a type?

I did not understand your second question.

**Comment by groue** [comment]
A side note: I notice in your stack overflow question properties declared as NSDecimalNumber:

```swift
var capital: NSDecimalNumber
var interes: NSDecimalNumber
var cuota: NSDecimalNumber
var valor: NSDecimalNumber
var valorPagar: NSDecimalNumber
var saldo: NSDecimalNumber
```

No problem here.

The problem is that you store those numbers directly:

```swift
override var persistentDictionary: [String: DatabaseValueConvertible?] {
    return ["capital": capital,
            // etc.
```

**Beware**: SQLite has no decimal type. Your decimal numbers will be stored as double values, with all the approximations you wanted to avoid by using NSDecimalNumber in the first place.

Make this funny experiment:

```swift
dbQueue.inDatabase { db in
    let a = NSDecimalNumber.fetchOne(db, "SELECT 0.1 + 0.2")!
    // 0.3000000000000000512
    print(a)
}
```

Ouch! We are far from the expected 0.3, aren't we?

The bug is not in GRDB, not in SQLite. It is in the application code that erroneously thinks it can store and load NSDecimalNumber in a database that does not provide support for such a type.

My advice is to store *integers*, because SQLite performs exact computations on integers. For example, don't store pesos, but store centavos instead:

```swift
override var persistentDictionary: [String: DatabaseValueConvertible?] {
    return [
        "capital": capital.decimalNumberByMultiplyingByPowerOf10(2).longLongValue, // Int64
        // etc.
```

And of course, convert back those integers to NSDecimalNumber in `init(_ row:Row)`:

```swift
init(_ row: Row) {
    capital = NSDecimalNumber(longLong: row.value(named: "capital").decimalNumberByMultiplyingByPowerOf10(-2)
    // etc.
```

**Comment by groue** [comment]
@mamcx I guess your issue is solved, now.

**Comment by mamcx** [comment]
Is possible to automate the conversion of NSDecimalNumber? I try to implement DatabaseValueConvertible but the compiler say is already there..

**Comment by groue** [comment]
NSDecimalNumber inherirta DatabaseValueConvertible from NSNumber. Did you try to override the protocol methods, instead of trying to replace them?

**Comment by mamcx** [comment]
How?

I do this:

```
extension NSDecimalNumber : DatabaseValueConvertible {
...
...
}
```

But the compiler complain with

> Redundant conformance of 'NSDecimalNumber' to protocol 'DatabaseValueConvertible'
> Declarations in extensions cannot override yet

**Comment by groue** [comment]
Well, remove the extra protocol conformance declaration, because the compiler tells you to do so, and instead *override* the databaseValue property and fromDatabaseValue class function that NSDecimalNumber already inherits from NSNumber.

**Comment by groue** [comment]
Ha. The error message "declarations in extension can not override yet" looks like a dead-end. I'm afraid you can not make NSDecimalNumber behave the way to want.

Your other option in to extend NSDecimalNumber with centavos property and init(centavos: Int64). This should clean up your code a bit, shouldn't it?
