### ISSUE TITLE
build failed with Xcode 9(beta)

### ISSUE THREAD

**Issue by Petitsurume** [groue/GRDB.swift#228]
```
Value of optional type 'UnsafeMutablePointer<UInt8>?' not unwrapped; did you mean to use '!' or '?'?
```
in [this line](https://github.com/groue/GRDB.swift/blob/10e669423f623cd07fc3863fc2784f762dd2c6ba/GRDB/Core/Support/Foundation/UUID.swift#L10)

**Comment by groue** [comment]
Hello @Petitsurume, thanks for your interest in GRDB!

Xcode beta will be eventually handled in separate branches.

If you want to wait until I or another contributor updates GRDB for Xcode 9 beta, watch GRDB in order to be notified.

If you want to use GRDB with Xcode 9 as fast as possible, consider [submit a pull request](https://github.com/groue/GRDB.swift/pulls): use the master branch for Swift 3.2, and the [Swift4 branch](https://github.com/groue/GRDB.swift/tree/Swift4) for Swift 4.

**Comment by groue** [comment]
Superseded by #230
