### ISSUE TITLE
support: Building Custom Requests

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [groue/GRDB.swift#229]
Hi @groue, 

I was wondering if you can elaborate more on the documentation section (Building Custom Requests):
what does the "adapted" keyword does?
what is the logic behind choosing this index (
db.columnCount(in: "books") for authors 
and 0 for books
)
what if I want to get specific columns with alias like "count(*) AS CoulmnCount" OR
"MAX (Table.time) as CurrentTime" with a GROUP BY statement, what should I do? 

`
struct BookAuthorPair : RowConvertible {
    
    let book: Book
    let author: Author

    init(row: Row) {
        // Those scopes are defined by the all() method below
        book = Book(row: row.scoped(on: "books")!)
        author = Author(row: row.scoped(on: "authors")!)
    }
    
    static func all() -> AnyTypedRequest<BookAuthorPair> {
        return SQLRequest(
            "SELECT books.*, authors.* " +
            "FROM books " +
            "JOIN authors ON authors.id = books.authorID")
            .asRequest(of: BookAuthorPair.self)
            .adapted { db in
                try ScopeAdapter([
                    "books": SuffixRowAdapter(fromIndex: 0),
                    "authors": SuffixRowAdapter(fromIndex: db.columnCount(in: "books"))])
            }
    }
    
    static func fetchAll(_ db: Database) throws -> [BookAuthorPair] {
        return try all().fetchAll(db)
    }
    }

        for pair in try BookAuthorPair.fetchAll(db) {
            print("\(pair.book.title) by \(pair.author.name)")
      }
`

**Comment by groue** [comment]
Hello @Mina-R-Meshriky 

[Row adapters](https://github.com/groue/GRDB.swift#row-adapters) are an advanced feature of GRDB whose purpose is to help consuming complex rows.

I'm not reluctant to explain the sample code above in full details, but I'm not sure that row adapters and the `request.adapted` method are the correct answer to your needs:

Since you talk about `count(*)` and `MAX(Table.time)`, I encourage you to read the documentation about [aggregated values](https://github.com/groue/GRDB.swift#fetching-aggregated-values). That's because `count`and `max` are called [aggregate functions](https://sqlite.org/lang_aggfunc.html).

And if you know how to write SQL, I also recommend [this article](https://medium.com/@gwendal.roue/grdb-stories-9bfcfb8b6a88), which talks about consuming aggregated values from joined requests.

Come back if you have further questions.

**Comment by Mina-R-Meshriky** [comment]
Hi @groue  :) 

this article actually solves my problem, which was that I had 4 tables joined together and I wanted to consume specific columns from each and some of these fields were aggregated values...
However, I was under the impression that I can't consume columns from other tables other than the One initiating the Call (i.e. `Person.fetchAll(db,sql)` then I can only get columns from the table Person)
that is why I thought that `request.adapted` was the way to go.

as a friendly request I suggest that you make that idea explicit in the documentation and not just in the article 

also, -if you have time- then elaborating on the advanced topics in GRDB would be very beneficial to the library and to many people

**Comment by groue** [comment]
Hi back @Mina-R-Meshriky 

> this article actually solves my problem, which was that I had 4 tables joined together and I wanted to consume specific columns from each and some of these fields were aggregated values...

That's great!

> However, I was under the impression that I can't consume columns from other tables other than the One initiating the Call (i.e. `Person.fetchAll(db,sql)` then I can only get columns from the table Person) that is why I thought that `request.adapted` was the way to go.

Yes. That's a common assumption: record types must exactly match the underlying table.

But in GRDB, the RowConvertible protocol only requires that a type can feed from a row. No matter how the row was constructed, how many tables are involved, where the result columns come from:

```swift
// Sure, why not?
let person = try Person.fetchOne(db, "SELECT 1 AS id, 'Arthur' AS name")
```

Check also this StackOverflow question, where I suggest building convenience types for consuming convenience requests when appropriate: https://stackoverflow.com/questions/43697172/with-grdb-use-raw-sql-but-consume-the-results-in-the-convenience-form/43704210#43704210

> as a friendly request I suggest that you make that idea explicit in the documentation and not just in the article.
> also, -if you have time- then elaborating on the advanced topics in GRDB would be very beneficial to the library and to many people

That's why I sometimes post on https://medium.com/@gwendal.roue/, in order to cover a few advanced or unexpected topics around GRDB. Also, the README has this sentence at the top:

> It comes with [up-to-date documentation](http://github.com/groue/GRDB.swift#documentation), [general articles](https://medium.com/@gwendal.roue), [sample code](http://github.com/groue/GRDB.swift#sample-code), and a lot of interesting resolved issues that may answer your eventual [questions](https://github.com/groue/GRDB.swift/issues?utf8=✓&q=is%3Aissue%20label%3Aquestion) and foster [best practices](https://github.com/groue/GRDB.swift/issues?q=is%3Aissue+label%3A%22best+practices%22).

One-to-one and focused discussions like the one we're having are also a great way enhancing the general knowledge of the community.

It's also a matter of managing my personal time, you know :she

I'm sure you'll get
You're a GRDB guru, already!

**Comment by groue** [comment]
> But in GRDB, the RowConvertible protocol only requires that a type can feed from a row. No matter how the row was constructed, how many tables are involved, where the result columns come from [...]

The only constraint is that the record can feed from the row:

```swift
struct Person : RowConvertible {
    let name: String
    init(row: Row) {
        // Feed from the "name" column:
        name = row.value(named: "name")
    }
}
```

What happens when a row doesn't match the columns expected by a record?

```SQL
-- no "name" column
SELECT 'Arthur' AS identifier

-- the leftmost "name" column is a company name, not a person name
SELECT companies.name, persons.name FROM companies JOIN persons ...
```

That's where row adapters help: they can present the fetched row in the way expected by the record. If we want the Person struct above to be able to feed on `SELECT companies.name, persons.name FROM companies JOIN persons ...`, then the row must be *adapted*. The adapter will have `row.value(named: "name")` pick the correct column.

I guess you can know understand the initial sample code (`BookAuthorPair`).

And that's why GRDB really [needs an API for joins](https://github.com/groue/GRDB.swift/issues/176): row adapters are simply too much advanced. Powerful, but too complex.
