### ISSUE TITLE
upgrade my preloaded  database for app update

### ISSUE THREAD

**Issue by gitton** [groue/GRDB.swift#23]
How can i upgrade my database (pragma user_version 1 to 2 ) with certain changes (like add new table or column) in my database and without changing any user changes made( eg : counter :- number of times an app was used)  for my pre built database when updating an app (1.0 to 2.0).

**Comment by groue** [comment]
Hello @gitton. I'm not sure I understand the scope of your question. Is it about GRDB, or about SQLite?

**Comment by gitton** [comment]
about GRDB

**Comment by groue** [comment]
There are similar but but not identical concepts in GRDB. The similarities are about running upgrading code when needed, in order to upgrade the database to its latest scheme version. The differences are in the support for database assets: GRDB has none, or more specifically: it lets the resources/documents management to the application developer.

So.

If your application has a bundled database that may be modified by the user or later versions of your application, you *need* to know the difference between an application *resource* (immutable), and other mutable files. Check how to copy a database resource into the documents folder, and understand what this sentence means.

Next, versioning. SQLite comes with the user_version pragma, which you can simply query with `let version = Int.fetchOne(db, "PRAGMA user_version")!`, and set with `db.execute("PRAGMA user_version 42")`.

GRDB also comes with another versioning tool that has my personal preference over user_version, called [migrations](https://github.com/groue/GRDB.swift#migrations). Check them out, you may like it.

OK now. I hope this first answer has some food for you!

**Comment by groue** [comment]
Hello @gitton. Did you find your way in this maze?

**Comment by groue** [comment]
OK. I'm closing this issue since it does not look like it is still relevant to you. Please open a new one if you have another question.

**Comment by gitton** [comment]
Sorry for the late response .it Works 
Thank you for the response +1:

**Comment by groue** [comment]
Great! Happy GRDB!

**Comment by danielctf** [comment]
Looks like `db.execute("PRAGMA user_version = 42)` is working instead of `db.execute("PRAGMA user_version 42")`
