### ISSUE TITLE
question: FetchedRecordController with two queries feeding two kinds of UITableViewCells

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [groue/GRDB.swift#233]
Hi @groue 

Suppose we have a UITableView with 2 different UITableViewCell prototypes, one having several UITextFields [firstName, lastName, hobby, salary, salary_type, etc] let's call it (CELL_1) and the other contains a UIImageView that eventually will contain a picture, let us call it (CELL_2)

for CELL_1 I am using a FetchedRecordController to get the data from different tables and observing if any change happens and I feed it into the tableView successfully. 
Now, for the CELL_2, I also want to use a FetchedRecordController -in the same tableView- to also observe if the picture changes in that cell
one last thing is that I want to be able to merge these cells together meaning that I want to have a table view like this 

          CELL_2
          CELL_1
          CELL_1
          CELL_2
          CELL_1
          CELL_1
          CELL_2
          CELL_1
          CELL_1
so, indexpath % 3 == 0 ? CELL_2 : CELL_1
So the question is: How to approach that problem in GRDB ? 
should I make another FetchedRecordController for the second cell or there is a way to have a single FetchedRecordController for both cells?

**Comment by groue** [comment]
Hello @Mina-R-Meshriky,

FetchedRecordController observes one request, and computes index paths assuming a table view is only filled with the results of this request.

This is the purpose of FetchedRecordController, and it will remain so.

Consequently, you have two options in order to achieve your goal:

1. either use a single fetched records controller that feeds both kinds of cells
2. or use two fetched records controllers and perform *index path translation*. Index path translation converts to and from the index paths generated by a fetched records controller, and the index paths in the actual table view.

I don't have enough information to know which option is the best for your application.

**Comment by Mina-R-Meshriky** [comment]
well, the second option seems better ... but how can I get the index path generated by the fetched record controller Do you mean like this `Controller.record(at: indexPath)`

**Comment by groue** [comment]
> but how can I get the index path generated by the fetched record controller Do you mean like this `Controller.record(at: indexPath)`

I mean that in your case, the index paths of a fetched records controller don't match the index paths of your actual table view. For example, the controller that manages CELL_1 doesn't know about CELL_2. You thus have to perform a translation:

```
Cell    UITableView  Controller1  Controller2
CELL_2  (0,0)        -            (0,0)
CELL_1  (1,0)        (0,0)        -
CELL_1  (2,0)        (1,0)        -
CELL_2  (3,0)        -            (1,0)
CELL_1  (4,0)        (2,0)        -
CELL_1  (5,0)        (3,0)        -
CELL_2  (6,0)        -            (2,0)
CELL_1  (7,0)        (4,0)        -
...            
```

Conversion functions will have to perform a little arithmetics.
