### ISSUE TITLE
Changes tracking for record structs

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#255]
Hi,

I have migrated my code to swift 4, and changed all `class` to `struct`, like:

`struct xxx: RowConvertible, Persistable, Codable { }`

But now, i got this error:

`Value of type 'xxx' has no member 'hasPersistentChangedValues'`

Thanks.

**Comment by groue** [comment]
Hello @skrew,

`hasPersistentChangedValues`, `persistentChangedValues`, and `updateChanges` belong to the Record class. They don't come from the RowConvertible or Persistable protocols. And that's why you have "lost" them (check out the [list of record methods](https://github.com/groue/GRDB.swift/blob/master/README.md#list-of-record-methods) when you need to know which protocol or class gives a method).

**This does not mean that you were wrong switching to struct types.**

Just like you, I often prefer my record types to be structs instead of `Record` subclasses. And just like you, it eventually happens that I need to know which column has changed.

A typical example is an application that downloads some JSON from a server, and wants to update the local database in an efficient manner: there's no need updating rows that have not changed, is it?

Since this example is very common, I will below describe a technique to handle it. If your application has a different need, I hope that you will be able to adapt it.

Here it goes: changes tracking is provided by the Record class, that's a given. When I need changes tracking for a struct, I hence define a *Record subclass that wraps that struct*. This subclass delegates all the database job to the record struct, which already knows how to do it. And as a Record subclass, it knows how to track changes. For example, say we have a `Player` struct, and a `synchronizePlayer` function:

```swift
// A regular record struct
struct Player: RowConvertible, Persistable { ... }

// A function that synchronizes a player:
func synchronizePlayer(withId id: Int64, in db: Database, from json: ...) throws {
    // Define a Record subclass that wraps a player. It can be defined inside
    // this method, since it isn't used anywhere else.
    class SyncPlayer : Record {
        // The wrapped Player
        var player: Player
        
        // The mandatory record overrides:
        required init(row: Row) {
            player = Player(row)
            super.init(row: row)
        }
        override func encode(to container: inout PersistenceContainer) {
            player.encode(to: &container)
        }
        override class var databaseTableName: String {
            return Player.databaseTableName
        }
    }
    
    // Load a sync player that knows how to track change:
    let syncPlayer = try SyncPlayers.fetchOne(db, key: id)
    
    // Update the sync player with a new player built from json:
    syncPlayer.player = Player(json: json)
    
    // Save if changed:
    if syncPlayer.hasPersistentChangedValues {
        try syncPlayer.save(db)
    }
}
```

**This technique provides changes tracking when needed, while preserving simple and pristine structs in the rest of the application.**

I hope you will be able to adapt this schematic example for your particular use. If you want to go further with this "synchronization records", and are OK with Swift generics, check out this [sample code](https://gist.github.com/groue/0fcea1752ce3566f4021d8ac6339161e). It defines a generic SyncRecord class that can wrap any record struct, and shows a general and efficient synchronization algorithm.

**Comment by groue** [comment]
No news is good news!

**Comment by skrew** [comment]
Hi @groue, sorry for the delay, i'm working on it right now, seem to works.
Thanks !

**Comment by groue** [comment]
(Removed the best practice tag, because [changes tracking](https://github.com/groue/GRDB.swift/blob/master/README.md#changes-tracking) works for all records since GRDB 2.9.0)
