### ISSUE TITLE
Dose Record support the enum property ,calculated property and combined object?

### ISSUE THREAD

**Issue by ChokShen** [groue/GRDB.swift#257]
The model like this:
class Person: Record {
    var name:String?
    var phone:Phone?
    var weight:Float?
}

enum SystemType: String{
    case iOS = "iOS"
    case Android = "Android"
}

class Phone:Record {
    var system:SystemType = .iOS
    var name:String?
    var money:Int?
    var description:String {
        get {
            return "\(name)"+"\(money)"
        }
    }
 }

**Comment by groue** [comment]
Hello @ChokShen 

Answers to your questions are yes.

Your Phone class will override the `init(row:)` initializer, the `encode(to:)` instance method, and the `databaseTableName` class property, in order to define its relationship with the database. Everything is explained with great detail in the [documentation](https://github.com/groue/GRDB.swift/blob/master/README.md#record-class).
