### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by prsolucoes** [groue/GRDB.swift#259]
Hi,

After i update the repository to latest version, my code start shows a lot of errors. Before the update to version 2 i use:

```
download.id = row.value(named: "id") as Int? ?? 0
download.catalogId = row.value(named: "catalog_id") as Int? ?? 0
download.downloaded = row.value(named: "downloaded") as Bool? ?? false
download.createdAt = row.value(named: "created_at") as Date? ?? nil
```

And now, what i do?

**Comment by groue** [comment]
Hello @prsolucoes.

The bump from version 1.3 to version 2.0 has brought incompatible changes, yes. But be assured that versions 2.1, 2.2, 2.3, etc, will not break your code. But when version 3.0 ships, eventually, it will bring incompatible changes again. This is how [semantic versioning](http://semver.org) works.

**Your first action is to know what are the changes brought by GRDB 2.0**: https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md#20. This link to the changelog is prominently written at the very top of the repository's README, so that you won't miss it when you need it again:

> GRDB 2.0
> ========
> 
> ### A toolkit for SQLite databases, with a focus on application development
> 
> **Latest release**: October 5, 2017 • version 2.0.2 • [CHANGELOG](CHANGELOG.md)

In the changelog, you'll read that the requirements have changed: Xcode 9 / Swift 4. If you still use Xcode 8 or Swift 3, don't upgrade GRDB!

**Your second action is to read the error messages displayed by the compiler.** It writes:

```swift
// 'value(named:)' is unavailable: use subscript instead: row[column]
download.id = row.value(named: "id") as Int? ?? 0
```

What is "subscript"??? A quick Google search for "Swift subscript" gives [this link](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Subscripts.html), which tells you that subscript is just another word for `row["id"]`:

```swift
// Compiler is now happy
download.id = row["id"] as Int? ?? 0
```

Much easier to read, isn't it? This subscript notation is only possible with Swift 4, and that's why we had to wait Swift 4 and GRDB 2.0 to improve rows with it. This change was announced in the [changelog](https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md).

With those two efficient "techniques", I'm sure you'll complete your migration to Swift 4 and GRDB 2 smoothly. After that, things will calm down: future versions will bring novelties, not incompatibilies. Until Swift 5 and GRDB 3.0 :wink:
