### ISSUE TITLE
Search with UISearchBar for FetchedRecordsController 

### ISSUE THREAD

**Issue by StriderHND** [groue/GRDB.swift#265]
Hello 

Right now im working with a prototype using GRDB looking at the documentation i started to use FetchedRecordsController with a table view but I wanted to implement a UISearchBarController to filter and search restaurants but I cannot find a simple way to do this.

Any help

Thanks!

**Comment by groue** [comment]
Hello @StriderHND 

I'll assume that you are familiar enough with UISearchController. Check out Apple documentation or Stack Overflow otherwise.

I'll also assume that you know the SQLite request that should be run on your database when the user has entered, say, "deli-sushi" in the search bar. If this is not the case, then grab an SQLite course, and focus on the `LIKE` operator. If you have extra time, look at full-text search (which GRDB supports very well), but this is harder.

Remains only one "simple" question to which I can provide a "simple" answer. It is about updating the fetched records controller's results in the UISearchResultsUpdating.updateSearchResults(for:) method.

The answer is: change the tracked request with the `setRequest` method, documented at [Modifying the Fetch Request](https://github.com/groue/GRDB.swift/blob/master/README.md#modifying-the-fetch-request):

```swift
func updateSearchResults(for searchController: UISearchController) {
    if let queryString = searchController.searchBar.text, !queryString.isEmpty {
        // filtered results
        let request = Restaurant.filter(Column("name") == queryString)
        try! fetchedRecordsController.setRequest(request)
    } else {
        // no results
        try! fetchedRecordsController.setRequest(Restaurant.none())
    }
}
```

Your search results will automatically update.

**Comment by StriderHND** [comment]
Thanks for the replay @groue ! 

I was doing something similar with modifying the fetch request, but is not working the way I like to. 

Lets say I have the name "El Portal de las carnes", I just type "portal" in the searchBarController I want all the Restaurants that contains "portal" show up, I think I'll have to go with the full-text search using FTS3 

Because I just using one table to save the little data of the restaurants so I think the implementation will be a little easy.

Thanks for the help!

**Comment by groue** [comment]
Great, @StriderHND. If you go with full-text search, have a look at [WWDCCompanion](http://github.com/groue/WWDCCompanion), a GRDB demo app for full-text search.

WWDCCompanion is a little more complex that strictly necessary, because it uses a custom SQLite build in order to demonstrate how to use the FTS5 full-text engine, its `rank` column, and its `snippet` function. The UISeachController dance should easily adapt to your needs, though.

If FTS4 is enough for you, you'll be able to use the regular GRDB with regular system SQLite.

So make sure you have a good read of GRDB full-text documentation. A good read
 of SQLite full-text documentation won't harm either. We leave the "simple" area now ;-)

I think I can close this issue now. Don't hesitate opening a new one if you get stuck somewhere.
