### ISSUE TITLE
Regexp Function Not Working

### ISSUE THREAD

**Issue by malavagile** [groue/GRDB.swift#270]
Hello Team,

I am using this library for local database related functionality.
I would like to use regex to find content from database. If I pass simple "AB" in arguments then it's working but if I pass regex in it then it's not working. 
Below is code snippet of my code.

`lazy var regexpFunction = DatabaseFunction("regexp", argumentCount: 2, pure: true) { (values) -> DatabaseValueConvertible? in
            guard
                let pattern = String.fromDatabaseValue(values[0]),
                let string = String.fromDatabaseValue(values[1])
                else { return nil }
            let reg = try NSRegularExpression(pattern: pattern, options: [])
        
            let match = reg.firstMatch(in: string, options: [], range: NSRange(location: 0, length: string.utf16.count))
        return (match != nil)
    }`

`let dbQueue = try DatabaseQueue(path: databasePath, configuration: configuration)
dbQueue.add(function: regexpFunction)`

Here is the query I am firing.
`Search Query : select * from tableA where ID = 1 and content regexp "(^|[[ઁ-ૠ])(ABC)([^ઁંઃ઼ા-્][ઁ-ૠ])"

Response I got from it.
Error Domain=NSCocoaErrorDomain Code=2048 "The value “(^|[[ઁ-ૠ])(ABC)([^ઁંઃ઼ા-્][ઁ-ૠ]*)” is invalid.

The same query is working when I run it from "DB Browser for SQLite" program.

Can anyone help me in it?

Thanks in advance.

**Comment by groue** [comment]
Hello @malavagile 

>Response I got from it
> Error Domain=NSCocoaErrorDomain Code=2048 "The value “(^|[[ઁ-ૠ])(ABC)([^ઁંઃ઼ા-્][ઁ-ૠ]*)” is invalid.

The error NSCocoaErrorDomain of code 2048 is the error thrown by the NSRegularExpression initializer when provided with an invalid pattern.

That NSRegularExpression error is rethrown by GRDB so that you can catch it.

To avoid this error, check NSRegularExpression documentation.

> The same query is working when I run it from "DB Browser for SQLite" program.

The only possible conclusion is that this program uses a different regular expression engine. It accepts the provided pattern, when NSRegularExpression does not.
