### ISSUE TITLE
Invalid escape sequence in literal

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [groue/GRDB.swift#271]
Hi,

I installed this library via CocoaPodswhich installed the v2.3.1. And then I built the project and it failed with the following error.

> Invalid escape sequence in literal

It occurs in the following code snippet which is in the Database.swift file.

```swift
private static func validateSQLCipher(_ sqliteConnection: SQLiteConnection) throws {
        // https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688
        //
        // > In order to avoid situations where SQLite might be used
        // > improperly at runtime, we strongly recommend that
        // > applications institute a runtime test to ensure that the
        // > application is actually using SQLCipher on the active
        // > connection.
        var sqliteStatement: SQLiteStatement? = nil
        let code = sqlite3_prepare_v2(sqliteConnection, "PRAGMA cipher_version", -1, &sqliteStatement, nil)
        guard code == SQLITE_OK else {
            throw DatabaseError(resultCode: code, message: String(cString: sqlite3_errmsg(sqliteConnection)))
        }
        defer {
            sqlite3_finalize(sqliteStatement)
        }
        if sqlite3_step(sqliteStatement) != SQLITE_ROW || (sqlite3_column_text(sqliteStatement, 0) == nil) {
            throw DatabaseError(resultCode: .SQLITE_MISUSE, message: """
                GRDB is not linked against SQLCipher. \
                Check https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-new-sdks/1688
                """)
        }
    }
```

The line `GRDB is not linked against SQLCipher. \` is causing the error. 

I'm on Xcode 9 beta 4.

**Comment by groue** [comment]
Hello @Isuru-Nanayakkara,

The trailing `\` in the multi-line string is causing troubles. Thanks for reporting this.

The faster way for you to avoid this issue is to upgrade your obsolete copy of Xcode 9 beta 4 to Xcode 9.1.

**Comment by Isuru-Nanayakkara** [comment]
Hi @groue,

Thanks for the prompt reply. Unfortunately I'm kinda stuck with the Xcode 9 beta version for the moment because I have Xcode 8 installed to support some older Swift projects. Which is named as `Xcode.app`. If I install Xcode 9, that Xcode 8 .app will get replaced.

Will it take long to fix this issue?

**Comment by t089** [comment]
Just rename Xcode.app to Xcode 8.app before installing the new version.

**Comment by groue** [comment]
@Isuru-Nanayakkara In order to download a copy of Xcode without upgrading the previous version, you can go to this stackoverflow.com answer: https://stackoverflow.com/questions/10335747/how-to-download-xcode-dmg-or-xip-file (you don't have to remember this link, just remember to search for "Xcode download" on stackoverflow).

This answer link to all versions of Xcode you can dream of. And that's secure: all links download from Apple servers.

**Comment by groue** [comment]
@Isuru-Nanayakkara: I could successfully compile GRDBCipher with both Xcode 9 and Xcode 9.1. As far as I know, GRDB complies to its [requirements](https://github.com/groue/GRDB.swift/blob/master/README.md#grdb-2----), which do not include support for beta software in general, and Xcode 9 beta 4 in particular.

I thus close this issue with the recommendation of installing Xcode 9.1. I do too have multiple Xcode versions installed in order to support older Swift projects: that's the regular situation of a professional Swift developer.

Of course, ask further questions if you keep on having difficulties running GRDBCipher in your app!

**Comment by Isuru-Nanayakkara** [comment]
Thanks, guys. I installed Xcode 9 and it's all good now.
