### ISSUE TITLE
Extended Regular Expression error (egrep) Target Support  Files/GRDB.swift a directory

### ISSUE THREAD

**Issue by cantleyc** [groue/GRDB.swift#274]
The name of the pod is being interpreted as a file even though it is a directory.  This throws errors but nothing that returns a nonzero exit code.

To keep from stepping on naming conventions that may throw critical errors in future compiler releases the pod name should be changed.  Recommend GRDB-swift.

> egrep: /Users/chriscantley/Desktop/cmh.pubweb.connectupios/Pods/GRDB.swift: Is a directory
> egrep: /Users/chriscantley/Desktop/cmh.pubweb.connectupios/Pods/Target Support Files/GRDB.swift: Is a directory
> ....
> Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by groue** [comment]
Hello @cantleyc 

Would you mind editing your issue so that readers have a tiny chance to understand what you are talking about? Thanks.

**Comment by groue** [comment]
Due to the recent trend of issues that are written in a way that make it difficult to provide any useful answer, GRDB now has an [issue template](https://raw.githubusercontent.com/groue/GRDB.swift/master/ISSUE_TEMPLATE.md) that should enhance future issues. @cantleyc, your issue has been written before this template was activated. Will you please have a look at it, and enhance your issue accordingly?

**Comment by groue** [comment]
I have a better idea: let's close this issue. If you really think that GRDB has something wrong that should be discussed, you'll open another issue with the new issue template. If not, thanks for passing by!
