### ISSUE TITLE
List inserts (Question)

### ISSUE THREAD

**Issue by foxware00** [groue/GRDB.swift#292]
What would be the recommended way to do a batch insert, just wondering if I was on the right track of there was a more optimal way to do this.

## What i'm trying to achieve in simple terms?

`db.insert([User])`

## What happened instead?
This is what i've come up with

```
func insert(apps: [App]) {
    try dbQueue.inTransaction { db in
        for app in apps {
            try app.insert(db)
        }
        return .commit
    }
}
```

**Comment by groue** [comment]
Hello @foxware00

You do it pretty well in my opinion. Using a transaction is a very good idea, because it reduces the number of times SQLite has to synchronize with the disc.

Maybe you wanted to execute a single SQL statement:

```sql
INSERT INTO 'tablename' ('column1', 'column2') VALUES
    ('data1', 'data2'),
    ('data1', 'data2'),
    ('data1', 'data2'),
    ('data1', 'data2');
```

This syntax is not currently generated by GRDB. You may still use it in a raw SQL request, though.

The [release notes for SQLite 3.7.11](https://sqlite.org/releaselog/3_7_11.html), which introduces support for insertion of multiple rows, does not mention any improvement on top of the new syntax. Especially, no performance increase has to be expected.

Besides, GRDB already reuses the same pre-compiled SQLite statement when you perform multiple record inserts.

Conclusion: there's no evidence that the support for insertion of multiple rows should be added to GRDB. And your code is quite correct 👍

**Comment by mecoFarid** [comment]
@groue Just a side note:

I know it is easy for developer to do but adding extension function for Collections would add extra safety for developers.

We could have config params for that function with defaults. For example the config would have flags like:
1. Rollback transaction if any insert fails. Defaults to `true`
2. And others that I can't think of right now :)

The extension would be something like:
```
extension Set where Element: PersistableRecord{
    func insert(db: Database, rollbackOnFail: Boolean = true){
       db.inTransaction{
            // Rest of code 
       }
   }
}
```

If sounds sounds okay, I can create issue and PR for this as soon as I have time.

**Comment by groue** [comment]
Hello @mecoFarid,

Thank you for your interest, and your exploration of the library :) You can write this extension in your own application code, because it only uses public GRDB apis!
