### ISSUE TITLE
Getting "attempt to write a readonly database" error from backup 

### ISSUE THREAD

**Issue by clehew** [groue/GRDB.swift#294]
## What did you do?

I'm attempting to back up one database to another via this code:

`var poolConfig = Configuration()
poolConfig.readonly = false
poolConfig.foreignKeysEnabled = true
poolConfig.trace = { print($0)}//prints all sql statements
poolConfig.maximumReaderCount = 10

do {
    var mainDBPool = try DatabasePool(path: self.mainDBPath, configuration: poolConfig)
    var oldDBPool = try DatabasePool(path: self.oldDBPath, configuration: poolConfig)
    try mainDBPool.backup(to: oldDBPool)
    
} catch let error as DatabaseError {
    NSLog("error")
}
`
## What did you expect to happen?

> Just didn't expect to get the error, should've been a simple back up.

## What happened instead?

I received a Database error code 8 - attempt to write a readonly database.  I have used backup in multiple places in the app, but this is the only place that I receive this error.  Is there anything I am missing?  does the backup change the database somehow in terms of writability?

the databases are all stored under "~/Library/databases/" 

iOS 

**GRDB flavor(s):** GRDB.swift 
**GRDB version:** 2.7.0
**Installation method:** CocoaPods
**Xcode version:** 9
**Swift version:** 4
**Platform(s) running GRDB:**  - iOS
**macOS version running Xcode:**. 10.13.2 (high Sierra)

**Comment by groue** [comment]
Hello @clehew

Can you please provide some sample code that reproduces the error?

**Comment by clehew** [comment]
[grdbtest.zip](https://github.com/groue/GRDB.swift/files/1669454/grdbtest.zip)

Hi @groue , Sorry I didn't have a chance to get to this until just now, but see the attached project, I'm not sure what's going on. Same error regarding "attempt to write to a readonly database"

**Comment by groue** [comment]
Thanks @clehew for the sample project. I can reproduce the error.

Adding a breakpoint on all Swift errors reveals the GRDB lines that fail:

```swift
switch sqlite3_backup_step(backup, -1) {
case SQLITE_DONE:
    afterBackupStep?()
    break backupLoop
case SQLITE_OK:
    afterBackupStep?()
case let code:
    throw DatabaseError(resultCode: code, message: dbDest.lastErrorMessage)
}
```

So we have the SQLite function `sqlite3_backup_step` return the error [SQLITE_READONLY](https://www.sqlite.org/c3ref/c_abort.html) (8).

The [documentation](https://sqlite.org/c3ref/backup_finish.html) says:

> The sqlite3_backup_step() might return SQLITE_READONLY if
> 
> 1. the destination database was opened read-only, or
> 2. the destination database is using write-ahead-log journaling and the destination and source page sizes differ, or
> 3. the destination database is an in-memory database and the destination and source page sizes differ.

It's not 1: the destination database was not opened read-only, and I could check that the file permissions are ok as well.

It's not 3: The destination database is not an in-memory database.

It's thus 2: the destination database indeed uses write-ahead-log journaling, because is has been created with a DatabasePool. Database pools open databases in the WAL mode, and WAL means "write-ahead-log".

We have this SQLITE_READONLY error because "the destination and source page sizes differ".

I'm not expert in SQLite page sizes, and I don't know how to make the destination and source page sizes equal. But I know how to avoid write-ahead-log journaling.

In your case, this is simple to do because the app *creates* the destination database. We just need to create a database that is not in the WAL mode. And this is done with a DatabaseQueue:

```diff
 let mainDB = try DatabasePool(path: self.mainDBPath, configuration: poolConfig)
-let oldDB = try DatabasePool(path: self.oldDBPath, configuration: poolConfig)    
+let oldDB = try DatabaseQueue(path: self.oldDBPath, configuration: poolConfig)    
 try mainDB.backup(to: oldDB)
```

This fixes the errorin the attached project. I hope it will fix the error with your actual database, too.

**Comment by clehew** [comment]
Thanks so much for the explanation! that should do the trick!

**Comment by clehew** [comment]
Ok something is still amiss.  In my main project there are 3 databases: main, old, and update.  (basically the old is a back up and the update database is a copy of main that gets updates applied to it incrementally). The code I'm calling is this:

` try mainDBQueue.backup(to: oldDBQueue)
            try udpateDBQueue.backup(to: mainDBQueue)
            try updateDBQueue.backup(to: backUpDBQueue)`

It now fails on the 3rd call with the same error.

**Comment by groue** [comment]
What about you perform the investigation this time, and come back with your explanation? Maybe you'll solve it by yourself. If not, then please share your eventual findings anyway, and provide again a way to reproduce the error.

**Comment by clehew** [comment]
I did solve it, was just updating.  It's simply that the backup database was created originally with DatabasePool

**Comment by clehew** [comment]
thanks for the help

**Comment by groue** [comment]
Glad we found a solution :-) Happy GRDB!
