### ISSUE TITLE
Confused with the document comment of func for creating a table

### ISSUE THREAD

**Issue by diatoming** [groue/GRDB.swift#306]
I'm a little confused about this document comment of this func, it says 

> - ifNotExists: If false, no error is thrown if table already exists.

But if it is false which is also the default value, in later code(TableDefinition) "IF NOT EXIST" will not be added to the SQL. So i think the comment should be

> If true, no error is thrown if table already exists.

and the default value should also be set to _**true**_?

```
/// Creates a database table.
    ///
    ///     try db.create(table: "pointOfInterests") { t in
    ///         t.column("id", .integer).primaryKey()
    ///         t.column("title", .text)
    ///         t.column("favorite", .boolean).notNull().default(false)
    ///         t.column("longitude", .double).notNull()
    ///         t.column("latitude", .double).notNull()
    ///     }
    ///
    /// See https://www.sqlite.org/lang_createtable.html
    ///
    /// - parameters:
    ///     - name: The table name.
    ///     - temporary: If true, creates a temporary table.
    ///     - ifNotExists: If false, no error is thrown if table already exists.
    ///     - body: A closure that defines table columns and constraints.
    /// - throws: A DatabaseError whenever an SQLite error occurs.
    public func create(table name: String, temporary: Bool = false, ifNotExists: Bool = false, body: (TableDefinition) -> Void) throws

```

**Comment by groue** [comment]
Hello @diatoming.

if you find the documentation confusing, then I should consider improving it.

You'll better understand `db.create(table:)` after you understand the underlying SQL queries:

```sql
CREATE TABLE t1 (id INTEGER PRIMARY KEY, ...)
CREATE TABLE t2 IF NOT EXIST (id INTEGER PRIMARY KEY, ...)
```

The first one creates a table, and ends with an error if the table has already been created: `t.create(table:"t1") { t in ... }`.

The second one creates a table, but only if it does not exist yet. There is no error if the table has already been created: `t.create(table: "t2", ifNotExist: true) { t ... }`.

The `t.create(table: "t1", ifNotExist: false) { t ... }` form is supported, and emits `CREATE TABLE t1 (...)`. But it is more idiomatic to avoid the ifNotExist parameter when it is false: `t.create(table: "t1") { t ... }`.

I hope this answers your question.

> and the default value should also be set to true?

Certainly not, and maybe the information above makes you understand why. The "IF NOT EXIST" form is *unsafe*:

After you have run `db.create(table: "t", ifNotExist: true) { ... }`, you don't know what columns are in the database table. That's because if the table already exists, that command does nothing. The eventual existing table may not have the same column layout as the one you attempt to create.

To avoid this unsafe pattern, GRDB ships with [migrations](https://github.com/groue/GRDB.swift/blob/master/README.md#migrations). Migrations are the recommended way to deal with the database schema. They are designed to let you clearly define your database schema, avoid the dangerous `ifNotExist` parameter, and evolve the schema along with your application's versions.

**Comment by groue** [comment]
BTW, double negations are generally super hard to decipher 😅 . I wish SQL standard had not used the `IF NOT EXIST` syntax!

**Comment by diatoming** [comment]
Thanks for the detailed reply. I guess i misunderstood the IF NOT EXIST syntax.

The app i'm working on still not shipped yet, but i will definitely use migrations in future database scheme modification.

> I wish SQL standard had not used the IF NOT EXIST syntax!

LOL

**Comment by groue** [comment]
Happy GRDB!
