### ISSUE TITLE
How to handle failure in RowConvertible `init(row: Row)`?

### ISSUE THREAD

**Issue by hlung** [groue/GRDB.swift#320]
# What did you do?

> Trying to make my object conform to RowConvertible.

## What did you expect to happen?

> Have a way to throw or return nil in case I cannot create my instance from a row.

## What happened instead?

> Can't find a way to propagate error from `init(row: Row)`. I think this can happen in cases like the database is corrupted. Marking `init(row: Row)` with `throws` result in `does not conform to protocol` error.

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 2.8.0
**Installation method:** CocoaPods
**Xcode version:** Version 9.2 (9C40b)
**Swift version:** 4
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13.3 (17D102)

## Demo Project

> Please link to or upload a project we can download that reproduces the issue.

**Comment by groue** [comment]
Hello @hlung,

> Have a way to throw or return nil in case I cannot create my instance from a row

As you see, `init(row:)` can't throw, and can't return nil. The only way a RowConvertible type can refuse a row is by calling fatalError(), and crashing the program with an error message.

Consider this simple record:

```swift
struct Event: RowConvertible {
    var name: String 
    var date: Date
    
    init(row: Row) {
         name = row["name"]
         date = row["date"]
    }
}
```

If will crash if a database row contains a NULL name, a NULL date, or a date that contains unparsable values such as "Mom's birthday". It will crash because the *contract* of Event can be seen in its properties: it needs a name, and a date. If it can't decode a name and a date from a row, then the database needs fixing. Or Event needs to relax its prerequisites.

Anyway, something needs to be fixed in the application, and the way a Swift program tells that something has be fixed is fatal errors. There's no point displaying an alert telling the users of your application that your app has a bug, is it?

> I think this can happen in cases like the database is corrupted. Marking init(row: Row) with throws result in does not conform to protocol error.

I suggest that you address the question in another way.

First ask yourself if it is useful to deal with corrupted databases. SQLite is very robust, and corrupt databases are almost never seen in the wild.

Second, if you really fear that your app does loads unexpected data from the database, write your RowConvertible type accordingly, so that it can deal with all kinds of inputs:

```swift
struct Event: RowConvertible {
    // Deal with NULL names with an optional property:
    var name: String? 
    
    // Deal with invalid dates with a dedicated flag:
    var date: Date?
    var isDateInvalid: Bool
    
    init(row: Row) {
        self.name = row["name"]
        
        let dbValue: DatabaseValue = row["date"]
        if dbValue.isNull {
            // NULL date
            self.date = nil
            self.hasInvalidDate = false
        if let date = Date.fromDatabaseValue(dbValue) {
            // Valid date
            self.date = date
            self.hasInvalidDate = false
        } else {
           // Invalid date
           self.date = nil
           self.hasInvalidDate = true
        }
    }
}
```

But this verbose code is only useful if you can't control the content of your database. If you tighten your control of the database content, you can just write:

```swift
struct Event: RowConvertible, Decodable {
    var name: String 
    var date: Date
}
```

... and move on to your next task.

**Comment by hlung** [comment]
Thanks @groue for your explanation. I will move on to my next task.

**Comment by groue** [comment]
Good, @hlung! Happy GRDB!

**Comment by groue** [comment]
A new chapter will ship in the GRDB 3 documentation: [Customized Decoding of Database Rows](https://github.com/groue/GRDB.swift/blob/GRDB3/README.md#customized-decoding-of-database-rows)
