### ISSUE TITLE
Is it safe to delete obsolete migration?

### ISSUE THREAD

**Issue by sergeiignatov** [groue/GRDB.swift#322]
## What did you do?

Initially my app used UserDefaults to store single string holding connection url. Later I migrated to GRDB to store multiple urls in database. There were 2 migrations: `v1` to init database table and `import` to copy existing url string from UserDefaults storage to db

```
    migrator.registerMigration("v1") { db in
        try db.create(table: "connections") { t in
            t.column("id", .integer).primaryKey()
            t.column("name", .text).notNull().collate(.localizedCaseInsensitiveCompare)
            t.column("url", .text).notNull().collate(.localizedCaseInsensitiveCompare)
            t.column("mode", .integer).notNull()
            t.column("active", .boolean).notNull()
            t.column("auth", .integer).notNull()
            t.column("username", .text).collate(.localizedCompare)
            t.column("password", .text).collate(.localizedCompare)            
        }
    }
```
```
    migrator.registerMigration("import") { db in
        // "rtmp://192.168.1.1/live/myStream"
        let prefStr = UserDefaults.standard.string(forKey: "connectionUri0")
        if let str = prefStr, let url = URL(string: str) {
            let connUri = validate(url: url)
            if let uri = connUri.uri, let scheme = connUri.scheme, let name = connUri.host {
                let connection = Connection(name: name, url: uri)
                try connection.insert(db)
            }
        }
    }
```

Now I need to add some additional columns for new connection options, so `v2` migration was added and model was updated as well.
```
    migrator.registerMigration("v2") { db in
        try db.alter(table: "connections") { t in
            t.add(column: "passphrase", .text).collate(.localizedCompare)
            t.add(column: "pbkeylen", .integer).notNull().defaults(to: 16)
            t.add(column: "latency", .integer).notNull().defaults(to: 0)
            t.add(column: "maxbw", .integer).notNull().defaults(to: 0)
        }
    }
```
## What did you expect to happen?
Can I just completely delete `import` migration, since it is not required anymore?

## What happened instead?
`v1` -> `import` -> `v2` fails as expected, because model was updated.

`Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1 with statement INSERT INTO "connections" ("mode", "maxbw", "passphrase", "url", "name", "latency", "pbkeylen", "auth", "id", "active", "username", "password") VALUES (?,?,?,?,?,?,?,?,?,?,?,?): table connections has no column named maxbw`

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v2.9.0
**Installation method:** manual
**Xcode version:** 9.3 beta 4
**Swift version:** Swift 4
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13.3

**Comment by groue** [comment]
Hello @sergeiignatov,

> **Is it safe to delete obsolete migration?**

The general answer to this general question is no, since all migrations usually depend on the previous ones (create table, then alter table, then etc.)

We can even go further:

**Is it safe to modify a migration?**

No. By "modify" I mean modify what happens when the migration runs. Modifying a migration is equivalent to replacing one with another, which implies removing the replaced one, which is not a good idea, as we've seen above.

And your "import" migration has been modified. Yes, even if you didn't change the code inside the migration block. That's because the `Connection` type that did exist at the time "import" was 1st defined is no longer the same as the latest `Connection` type.

The error message is quite clear, don't you think? `table connections has no column named maxbw`.

For sure! The "import" migration is run *before* the "v2" migration, and there is no `maxbw` column yet!

The fix you are looking for is thus to make bloody sure that all your migrations are written so that they will never ever change as your application evolves. In your particular case, you must not use the  evolving `Connection` type inside the "import" migration.

Instead, write raw SQL, or use a *locked* type:

```swift
migrator.registerMigration("import") { db in
    struct ConnectionV1: Persistable, Encodable {
        static let databaseTableName = "connections"
        var name: String
        var url: URL
    }
    // "rtmp://192.168.1.1/live/myStream"
    let prefStr = UserDefaults.standard.string(forKey: "connectionUri0")
    if let str = prefStr, let url = URL(string: str) {
        let connUri = validate(url: url)
        if let uri = connUri.uri, let scheme = connUri.scheme, let name = connUri.host {
            let connection = ConnectionV1(name: name, url: uri)
            try connection.insert(db)
        }
    }
}
```

To be really strict, you'd also need to use a locked version of the `validate(url:)` function :-)

I hope this answers your question 😄

**Comment by groue** [comment]
See also #309, which also talks about migration locking.

**Comment by sergeiignatov** [comment]
Thanks a lot @groue for the advice!

**Comment by groue** [comment]
Happy GRDB Sergey!
