### ISSUE TITLE
what is "db" in codes

### ISSUE THREAD

**Issue by MrSinaRJ** [groue/GRDB.swift#323]
I know I'm a total noob in swift and iOS coding.
but not matter what I try I can't figure out what is "db" in codes in this library.
this is my code, and I get this error: "Use of unresolved identifier 'db' "
can someone please help me?!
any help would be great

```
var storeList = [Store]()
var configuration = Configuration()
configuration.readonly = true
let dbPath = Bundle.main.path(forResource: "Floors", ofType: "db")!
let dbQueue = try! DatabaseQueue(path: dbPath, configuration: configuration)
storeList = try! dbQueue.inDatabase( db in try Store.fetchAll(db, "SELECT * FROM Stores"))
```

**Comment by groue** [comment]
Hello @MrSinaRJ 

In `dbQueue.inDatabase { db in ... }`:

- `dbQueue` is a DatabaseQueue that schedules accesses to the database,
- `inDatabase` is a database access method,
- `{ db in ... }` is a closure, argument of `inDatabase`, that executes your code that uses the database. Wrap it in *braces*, because this is how Swift wants you to do it.
- `db` is a database connection that can write or fetch values. It is a value of type `Database`. You always get those connections as arguments of database access closures, themselves arguments of database access methods.

That's a lot of information. I advise you to get a Swift crash course so that you learn what those "closures" are. And the rest should follow naturally :-)

**Comment by groue** [comment]
Feel free to open a new issue if you have further questions.

**Comment by MrSinaRJ** [comment]
Sorry for my late answer, I was under a lot of pressure
Thanks for your answer, I get it and solved the issue.
you were so helpful and explained everything in detail
not even I got to solve my problem I learned something about swift too
I hope there be more developers like you
