### ISSUE TITLE
How can force update database if the transaction failed

### ISSUE THREAD

**Issue by dproton** [groue/GRDB.swift#326]
I use 
```
try db.inTransaction {
}
```
but if one of any queries is failed, the database is rollbacked. How can I force update db in this case ?

**Comment by groue** [comment]
Hello @dproton,

A transaction is a fundamental concept of databases: it guarantees that all changes or no changes are applied. As you see, GRDB chose to rollback the whole transaction on the first uncaught error. That's because in the lack of explicit error handling, the safest path is to invalidate the whole thing and rethrow that error.

Now you can, of course, decide that some errors should be ignored: just catch those errors so that they don't bubble up into GRDB. A transaction commits if and only if the closure given to `inTransaction` successfully returns `.commit`:

```swift
try db.inTransaction {
    // Will rollback on error
    try ...
    
    // Will not rollback on error
    do {
        try ...
    } catch {
        print("oops: \(error)")
    }
    
    return .commit
}
```

**Comment by groue** [comment]
You can also *avoid* some errors. For example, errors triggered by attempts to store duplicate values guarded by unique indexes and primary keys.

For more information, see the [SQLite documentation](https://sqlite.org/lang_conflict.html) about "ON CONFLICT IGNORE/REPLACE/etc" clauses, and the related [Conflict Resolution](https://github.com/groue/GRDB.swift/blob/master/README.md#conflict-resolution) chapter of GRDB documentation.

**Comment by groue** [comment]
No news is good news. Happy GRDB!
