### ISSUE TITLE
'GRDB/GRDB-Bridging.h' file not found error

### ISSUE THREAD

**Issue by nickoffff** [groue/GRDB.swift#33]
Hello,
after update of the Xcode to 7.3 and GRDB to 0.52.0 with CocoaPods we receive the following error during compilation: 'GRDB/GRDB-Bridging.h' file not found

**Comment by groue** [comment]
Please provide more context, including how you integrate GRDB in your application.

**Comment by nickoffff** [comment]
We had to manually remove DerivedData folder of Xcode. Now it works again. We noticed that we should add many "try" keywords and StatementArguments is an optional now.

**Comment by groue** [comment]
If you hadn't updated GRDB in a while, you may have experienced a little glitches because of the changes that I have introduced, yes. I'm sorry for the inconvenience.

You can discuss or criticize those changes here if you want: I'm open to suggestions.

Yet if you had to add many `try` then I guess you use low-level API, which has evolved into throwing functions so that developers have an opportunity to deal with untrusted inputs. Those tries are likely to stay.

Any way, happy GRDB!

**Comment by groue** [comment]
@nickoffff See https://github.com/groue/GRDB.swift#error-handling for a more detailed discussion of error handling with GRDB.
