### ISSUE TITLE
FetchedRecordsController generics confusion

### ISSUE THREAD

**Issue by thommw** [groue/GRDB.swift#343]
While still trying to find a complete solution for polymorphic records, I came across this problem, that seems to be the cause of a SIGABRT error I am getting when running the tests on my modified sources.

In [FetchedRecordsController](https://github.com/groue/GRDB.swift/blob/master/GRDB/Record/FetchedRecordsController.swift) you are using the identifier `Record` as a generics placeholder while it is also a class name. The compiler seems to get confused which one to use. At least the editor is. If nothing else it would be good style to make this unambiguous.

**Comment by thommw** [comment]
I just found this issue in `Row` and `RowConvertible` too.

**Comment by groue** [comment]
Hello again @thommw,

> While still trying to find a complete solution for polymorphic records, I came across this problem, that seems to be the cause of a SIGABRT error I am getting when running the tests on my modified sources.

So the compiler crashes on your computer. It happens when you perform unknown changes using an unknown compiler.

> In FetchedRecordsController you are using the identifier Record as a generics placeholder while it is also a class name. The compiler seems to get confused which one to use. At least the editor is.

When you created this issue, you did ignore and delete a whole [issue template](https://github.com/groue/GRDB.swift/issues/new). This is rude,  you know? And this is also unfortunate, because we lack useful information now.

**Don't ditch issue templates, they're here for a reason even if you don't understand why.**

Last, your last proposal (#341) was refused because it lacked a useful quality that makes GRDB useful for many people: it is not made for **one** person. This new issue is written in the same narrow state of mind: don't expect a warm welcome.

> If nothing else it would be good style to make this unambiguous.

I'll happily talk about coding style with you when your own writing style is fixed.

**Comment by groue** [comment]
You [wrote](https://github.com/groue/GRDB.swift/issues/341#issuecomment-384284797):

> I am a "lazy" developer

Beware with this kind of sentence. You may want to sound ironic, but people may read it literally.

**Comment by thommw** [comment]
I distinctly remember you writing that you are lazy too. Which you clearly are not. You are right, irony doesn't work well on the internets. Please let's get back to a professional conversation.
I am sorry to have ignore the template. I have created a new issue with the required information. I just want to be of some help.
