### ISSUE TITLE
Initializers should be failable and functions should throw errors

### ISSUE THREAD

**Issue by mpurland** [groue/GRDB.swift#35]
First example: 
init(_ row: Row) 

The problem is that the object convertible (Record for example) may not be directly convertible from a row. The data might have changed or the rules for the data model have changed. 

I think this should be:
init(_ row: Row) throws 
OR:
init?(_ row: Row)

Second example: Database fetches using fetch, fetchAll, and fetchOne are currently assuming statements will succeed and use try!. I think these functions should declare that they may throw an error.

**Comment by groue** [comment]
Hello again @mpurland.

> [...] Database fetches using fetch, fetchAll, and fetchOne are currently assuming statements will succeed and use try!. I think these functions should declare that they may throw an error.

I'm very very highly reluctant to generally turn fetching methods into throwing functions. This is because fetching is the most basic of the basic tasks. It usually never fails, unless there is a programmer error:

```swift
// How could it fail? Oops a typo in the table name.
let count = Int.fetchOne(db, "SELECT COUNT(*) FROM personss")!
```

Now you know why fetching methods do not throw, and crash until the developer has fixed his error.

> Initializers should be failable
>
> The problem is that the object convertible (Record for example) may not be directly convertible from a row. The data might have changed or the rules for the data model have changed.

I can see your point, even if it enters a use case that looks very weird at first glance: your application models do not match your database. Here be dragons!

With such throwing initializers, you would obviously need fetching methods that throw.

I see two options here:

1. Application side: tame dragons. [Change your database](https://github.com/groue/GRDB.swift#migrations) so that it fits your application models, and you are sure records can be initialized.

2. GRDB side: introduce a mechanism that lets you opt in for throwing initializers and throwing fetching methods.

My advice is the first option. You have to convince me that the second option has valid use cases. Could you share a more precise example?

**Comment by groue** [comment]
Meanwhile, here is a sample code that gives you support for throwing initializers:

```swift
import GRDB

// Open an in-memory database which logs all SQL statements
var configuration = Configuration()
configuration.trace = { print($0) }
let dbQueue = DatabaseQueue(configuration: configuration)
try! dbQueue.execute(
    "CREATE TABLE items (" +
        "id INTEGER PRIMARY KEY," +
        "name TEXT" +
    ")")

// Define an Item class with a throwing Row initializer
class Item {
    let id: Int64
    let name: String
    
    init(_ row: Row) throws {
        self.id = row.value(named: "id")
        if let name: String = row.value(named: "name") {
            self.name = name
        } else {
            throw NSError(domain: "Item", code: 0, userInfo: [NSLocalizedDescriptionKey: "Invalid NULL name"])
        }
    }
}

extension Item {
    // Fetch items
    class func fetchAll(db: DatabaseReader, sql: String, arguments: StatementArguments? = nil) throws -> [Item] {
        return try Row.fetchAll(db, sql, arguments: arguments).map { try Item($0) }
    }
}

// OK
try! dbQueue.execute("INSERT INTO items (name) VALUES (?)", arguments: ["Banana"])
var items = try! Item.fetchAll(dbQueue, sql: "SELECT * FROM items")

// fatal error: 'try!' expression unexpectedly raised an error: Error Domain=Item Code=0 "Invalid NULL name" UserInfo={NSLocalizedDescription=Invalid NULL name}
try! dbQueue.execute("INSERT INTO items (name) VALUES (?)", arguments: [nil])
items = try! Item.fetchAll(dbQueue, sql: "SELECT * FROM items")
```

**Comment by groue** [comment]
Hello @mpurland. Do you still want to champion built-in support for throwing initializers?

**Comment by groue** [comment]
OK @mpurland. I suppose you have found a solution: let me close this issue.
