### ISSUE TITLE
[Heads-up] Build fails on xcode beta

### ISSUE THREAD

**Issue by kluufger** [groue/GRDB.swift#367]
## What did you do?

Tried to build the project using xcode-10 beta.

## What did you expect to happen?

For the project to build successfully.

## What happened instead?

It failed with

> note: Using new build system
> note: Planning build
> note: Constructing build description
> Build system information
> error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'amalgamation')

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** v.2.10
**Installation method:** git clone
**Xcode version:** Version 10.0 beta (10L176w)
**Swift version:** Apple Swift version 4.2 (swiftlang-1000.0.16.7 clang-1000.10.25.3) Target: x86_64-apple-darwin17.5.0
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** macOS 10.13.4 (17E202)

**Comment by kluufger** [comment]
Hm, seems to be building fine now. Sorry.

**Comment by groue** [comment]
Hello @kluufger,

Not all GRDB flavors build with Xcode-beta:

- GRDBCustom (which embeds a custom build of SQLite) won't build because https://github.com/swiftlyfalling/SQLiteLib refers to i386. I should talk to @swiftlyfalling about this, because he knows Xcode pretty well, and I hope he'll be able to say if this is a bug in Xcode. 32 bits architecture are no longer supported, OK. But does it mean that legacy projects that *support* 32 bits architectures should break?
- GRDBCipher won't build because of some errors I haven't really looked at yet.

Meanwhile, GRDB v2.10.0 for iOS and macOS work well on Xcode-beta 10.

But thanks for your notice! When Xcode 10 will eventually ship, GRDB will be ready.

**Comment by groue** [comment]
The test that fails.... reveals that Swift 4.2 has changed String ordering 😅 

See https://github.com/groue/GRDB.swift/pull/313/commits/6130c6f985ec1461b0a29dcb2afe6d6059016b64 (part of #313)
