### ISSUE TITLE
Registered SQL Functions for the Compress and Uncompress Options on an FTS4 VirtualTable Are Never Called

### ISSUE THREAD

**Issue by robfeldmann** [groue/GRDB.swift#369]
Thanks for the great library. I'm really enjoying using GRDB, but I am fairly new at this still.

For context, I want to be able to implement a "contains"-like match using full text search, similar to what is mentioned in this blog post: [https://blog.kapeli.com/sqlite-fts-contains-and-suffix-matches](https://blog.kapeli.com/sqlite-fts-contains-and-suffix-matches).

This technique requires an innovative use of the compress and uncompress functions, which are options that can be supplied when creating an FTS4 virtual table.

## What did you do?

* I created my DatabasePool

```swift
let dbPool = try DatabasePool(path: path)
```

* then I added the `compress` and `uncompress` functions, both taking 1 argument and returning a `String` value per the [SQLite documentation](https://www.sqlite.org/fts3.html#the_compress_and_uncompress_options)

```swift
let compress = DatabaseFunction("compress", argumentCount: 1) { (dbValues) in
    guard let str = String.fromDatabaseValue(dbValues[0]) else {
        return nil
    }
    // I know this is just returning the same as the input
    // this is where I would perform my actual compression though
    return str
}
dbPool.add(function: compress)

let uncompress = DatabaseFunction("uncompress", argumentCount: 1) { (dbValues) in
    guard let str = String.fromDatabaseValue(dbValues[0]) else {
        return nil
    }
    // I know this is just returning the same as the input
    // this is where I would perform my actual decompression though
    return str
}
dbPool.add(function: uncompress)
```

*Side note*: here I've named my functions, `compress` and `uncompress`, but I've also tried other, more unique, names but they still were never called.

* then I ran my database migrations, one of which creates the FTS4 table supplying the aforementioned function names for the `compress` and `uncompress` options

```swift
try migrator.migrate(dbPool)

...

migrator.registerMigration("createEvent") { db in
    try db.create(table: "event") { t in
        t.column("id", .text).primaryKey()
        t.column("title", .text).notNull()
        t.column("details", .text).notNull()
        ...
    }
}

migrator.registerMigration("createEventSearch") { db in
    try db.create(virtualTable: "eventSearch", using: FTS4()) { t in
        t.tokenizer = .porter
        t.compress = "compress"
        t.uncompress = "uncompress"
        t.column("title")
        t.column("details")
        ...
        t.synchronize(withTable: "event")
    }
}
```

## What did you expect to happen?

I expected my `compress` and `uncompress` functions to get called at some point when event records are created or indexed by the FTS engine.

## What happened instead?

As described above, the `compress` and `uncompress` functions are never called.

Other than this, everything else seems to be working fine because I am getting results when performing a search. Here is a helper function I created to execute the search:

```swift
public static func search(_ db: GRDB.Database, matching terms: String) -> [Event] {
    guard let pattern = FTS3Pattern(matchingAnyTokenIn: terms) else {
        return []
    }

    let sql = """
        SELECT event.*
        FROM event
        JOIN eventSearch
             ON eventSearch.rowid = event.rowid
             AND eventSearch MATCH ?
    """

    do {
        return try Event.fetchAll(db, sql, arguments: [pattern])
    } catch {
        assertionFailure()
        return []
    }
}
```

To be absolutely sure, I tried calling each function separately like so, and it indeed worked great:

```swift
let test = try dbPool.read { (db) in
    try String.fetchOne(db, "SELECT compress(\"test\")")!
}
print(test) // actually prints test
```

## Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 2.10.0 (Haven't updated to 3 yet)
**Installation method:** CocoaPods
**Xcode version:** 9.4
**Swift version:** 4.2 (I think, the latest for Xcode 9.4)
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.13.5

## Demo Project

Upon request I am willing to create this if necessary.

**Comment by groue** [comment]
Hello @robfeldmann,

Thanks for your very detailed issue.

You are instructing SQLite to (1) compress the content of the FTS4 table.

What is this "content" exactly? Is it the *full-text index* itself, or the *indexed text*? The SQLite doc consistently uses the word "content" for the indexed text.

At the same time, you are instructing SQLite to (2) not store any content at all in the FTS4 table, with the `synchronize(withTable:)` method. This method creates an [external content full-text table](https://github.com/groue/GRDB.swift/blob/master/README.md#external-content-full-text-tables) which contains the full-text index, but does not contain any content at all: the indexed text is stored in an external table (the `event` table in your application).

Those two instructions are in conflict: SQLite can't compress text that is not stored in the full-text table.

> For context, I want to be able to implement a "contains"-like match using full text search, similar to what is mentioned in this blog post: https://blog.kapeli.com/sqlite-fts-contains-and-suffix-matches.
> 
> This technique requires an innovative use of the compress and uncompress functions, which are options that can be supplied when creating an FTS4 virtual table.

According to this blog post, the full-text table does not index *raw strings*. Instead, it indexes *processed strings* (let's call them "suffix strings").

It looks like you have two options:

1. If `event` columns contains suffix strings, you can use `synchronize(withTable:)`. But since the indexed content is stored in the regular `event` table, you won't be able to compress it.
2. If `event` columns contains unprocessed strings, you can't use `synchronize(withTable:)`. That's because you don't want to index those unprocessed strings.

    Instead, you'll have to create an FTS4 table that stores its content, made of suffix strings (and compress it if you want).


If you go with option 2, you may stil want to keep the `event` and `eventSearch` tables synchronized. But since `synchronize(withTable:)` is unfit, I recommend that you have a good read of https://www.sqlite.org/fts3.html#_external_content_fts4_tables_. You'll learn about the SQL triggers that keep both tables in sync. You'll adapt those triggers so that they insert suffix strings into the full-text table. If you use this technique, you'll register a compress function, an uncompress function (for the full-text table definition), but also a function that produces suffix strings (for the trigger definition).

**Comment by groue** [comment]
The compress/uncompress feature wasn't tested yet. Thanks for opening this issue: now we have a stronger guarantee that it won't break in future GRDB releases :-) 4e7fc83ad52a9208227042c377b3c67234696dbf

**Comment by robfeldmann** [comment]
Thanks @groue for your quick response. I just **knew** there was something about this that I was misunderstanding and you helped me to see that. 

I basically forgot that my external content FTS table didn't contain the actual content; only the index. I was thinking my functions would run as the database was inserting the content, one word at a time. lol

> You'll adapt those triggers so that they insert suffix strings into the full-text table.

I think I know what I need to do now. The only thing I'm still a little fuzzy on is what exactly a suffix string is, or how it should be constructed. I'll continue researching and reading about this. Hopefully, when I start to actually implement this, it'll make more sense what my `function that turns unprocessed strings into suffix strings` should look like.

I'm going to continue working on this, but since I have other priorities in this app at the moment, it could be a while as I work on improving search in my spare time. In the future, I'd like to update this ticket with my solution so that others can benefit from my learnings. In the meantime, if you want to close this issue that is fine with me.

Again, thank you so much for helping me learn. 👍

**Comment by groue** [comment]
> I'm going to continue working on this, but since I have other priorities in this app at the moment, it could be a while as I work on improving search in my spare time. In the future, I'd like to update this ticket with my solution so that others can benefit from my learnings.

That's totally fine, and I'll be very happy if you share your solution: Even if I could guide you out of a trap, we still don't have the complete solution. And other users may indeed be very interested 👍 

Meanwhile, yes, I'll close this issue. Thanks @robfeldmann, happy GRDB, happy SQLite!
