### ISSUE TITLE
'openConnection' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by sgmckenna** [groue/GRDB.swift#375]

**Comment by sgmckenna** [comment]
I am using XCode 9.4.1 and just did a pod update. Now I get about 70 errors all follwing the same pattern: 'openConnection' is inaccessible due to 'private' protection level. Pls help.

**Comment by groue** [comment]
Hello,

You have those errors because GRDB is not compiled with the proper Swift version. Make sure it is 4.1, as required by the latest GRDB 3.1.0. The swift version is controlled by the ` SWIFT_VERSION` build settings.

**Comment by groue** [comment]
Do you think, @sobri909, that the GRDB podspec should embed `s.swift_version` ?

The [podspec reference](https://guides.cocoapods.org/syntax/podspec.html) says:

> `swift_version` The version of Swift that the specification supports.
>
> Examples:
>
> ```ruby
> spec.swift_version = '3.2'
> ```

This is quite anemic.

What about supporting multiple Swift versions? GRDB currently supports only one Swift 4.1. But it used to support both 4.0 and 4.1, and it may well soon support both 4.1 and 4.2. I'm not afraid of a few `#if` if it can help GRDB users. I don't want Cocoapods to come in the way.

**Comment by sobri909** [comment]
I wondered similar, but didn't have enough time to figure out the correct answer.

It looks like CocoaPods is just copying that value into the Xcode target's `SWIFT_VERSION`. And Xcode / Swift appear to have some fuzzy versioning rules that I don't know the details of.

My guess is that the podspec should specify the minimum Swift version required to compile the code. So if the code supports 4.1 and 4.2, the `swift_version` should be set to 4.1.

But yeah, I don't really understand what Xcode / Swift is doing with that setting yet, and haven't had the time to read up on it properly. 😞

**Comment by groue** [comment]
Same for me. Until somebody gets really interested into this question, and sorts this highly ambiguous stuff out, nothing will happen.

Meanwhile, the GRDB requirements written at the top of README.md are crystal clear: latest GRDB requires Swift >= 4.1. If this is an opportunity for Xcode users to learn about SWIFT_VERSION, so be it. This is a tooling problem, not a GRDB problem.

This topic should enter the FAQ, actually, because it's not the first time this question is asked. If there were a huge crowd of clueless users, I'd look into it. But there isn't.

**Comment by sobri909** [comment]
> This is a tooling problem, not a GRDB problem.

But it's also a problem of GRDB's use of the tooling being incomplete. 😉 Without a value for `swift_version`, an install from CocoaPods will result in a misconfigured Xcode project that doesn't compile, for some subset of users. 

 I *think* the determinate for whether it will default to the wrong value is whatever value the main project's SWIFT_VERSION is set to. I suspect that either Xcode or CocoaPods falls back to the main project's value, if an explicit one isn't given. So for example if the main project is set to 3.2, then GRDB will be added as 3.2.

There's an Apple document out there somewhere that explains how the setting is applied, and what values should be used. I remember reading it either last year or the year before. But I can't find it now... Hmm.

**Comment by groue** [comment]
> But it's also a problem of GRDB's use of the tooling being incomplete.

Doesn't it depend on the goal? As you say below:

> I *think* the determinate for whether it will default to the wrong value is whatever value the main project's SWIFT_VERSION is set to.

This matches my mental model as well.

I suspect that @sgmckenna did switch to Xcode 9.4 from a project written in Swift 3, did update pods before Xcode had the opportunity to upgrade the whole project to Swift 4.1, and got those compilation errors. Since he/she did not read documentation and requirements, dit not search for existing resolved issues, he/she was stuck. I can't blame, but I don't have much pity either.

That's because I won't punish many users in order to accommodate a few who can learn how to avoid this kind of trouble in the future (I hope you did learn something, @sgmckenna).

I like that GRDB can activate features / enhancements / APIs, depending on the Swift version. For example, that's how it used to be able to provide both `Cursor.flatMap` and  `Cursor.compactMap`, when it used to support both Swift 4.0 and Swift 4.1, so that GRDB could align with [SE-0187](https://github.com/apple/swift-evolution/blob/master/proposals/0187-introduce-filtermap.md). I do value the ergonomics of this library very much, if only for my own usage. Those kind of details are rarely noticed, because they are indeed supposed to be invisible. On the other side, people would notice their absence as a mild to big inconvenience.

When pods inherit the SWIFT_VERSION of the hosting app, all things align pretty nicely.

But if GRDB were locked on a specific Swift version:

- It would lag behind the language and behind its host application.
- Supporting the next language version would be a breaking change.
- With a bump of the major version (GRDB 4, 5, 6,etc.)
- And old Xcode versions would no longer be supported.

That would just be bleak IMHO.

**Comment by sobri909** [comment]
> did switch to Xcode 9.4 from a project written in Swift 3, did update pods before Xcode had the opportunity to upgrade the whole project to Swift 4.1,

Thing is, it's possible to support both Swift 3 and Swift 4 in the same project. Each target can have a different Swift version, so the targets could be a mix of Swift 3.2, Swift 4.1, and Swift 4.2, all compiling together. The user doesn't need to upgrade their main project. 

> When pods inherit the SWIFT_VERSION of the hosting app, all things align pretty nicely.

Except in this case 😉 You and I both had separate reports of failed compiles for our libraries in the same week, due to the user's Xcode project defaulting to the wrong SWIFT_VERSION for our libraries' target. 

But it sounds like you want to use Swift 4.2 features while also allowing compilation on Xcode 9.4. Which, yeah, presumably wouldn't be possible if the SWIFT_VERSION is set to 4.1. 

Anyway, I'm going with this new `s.swift_version` podspec thing for now with LocoKit because it will reduce user confusion. It's not ideal, because it (presumably) means I can't conditionally use any Swift 4.2 features, but it solves a problem that some users are having, so that's good enough for now.

**Comment by sobri909** [comment]
Yeah, and eventually it would be good to have a better understanding of exactly what Xcode and CocoaPods are doing with these settings. Right now I'm just making guesses and going on hunches. But neither of us have the time to spend on that right now! Such is life. 😏
