### ISSUE TITLE
Make the Migration struct public

### ISSUE THREAD

**Issue by hartbit** [groue/GRDB.swift#386]
### What did you do?

I'm trying to move my different migrations in separate variables and files for better readability.

### What did you expect to happen?

I expected to be able to use the `Migration` type directly:

```swift
let migration2 = Migration(identifier: "2") { db in
    // migration code
}
```

And in another file:

```swift
var migrator = DatabaseMigrator()
migrator.registerMigration(migration1)
migrator.registerMigration(migration2)
return migrator
```

### What happened instead?

Instead, I've had to write only the migration closure:

```swift
let migration2: (Database) throws -> Void = { db in
    // migration code
}
```

And then:

```swift
var migrator = DatabaseMigrator()
migrator.registerMigration("1", migrate: migration1)
migrator.registerMigration("2", migrate: migration2)
return migrator
```

**Comment by groue** [comment]
Hello @hartbit,

So you want to associate migration closures with their names in a single type, don't you? It happens that the private Migration type does that today. It does so privately.

Should Migration be public, there would be two ways to feed a migrator, and I'm not sure I could find a way to tell the difference (you know, write documentation so that it's possible to tell users whether they should use one or the other form, without discussing the sex of angels).

Deprecating the current migrator API is out of question. Yet we may discuss this again on the way to GRDB4, when we can break things again.

Until then, you can define your own Migration type, and an extension on DatabaseMigrator for convenience. This is my current recommendation, until I grab more information!

**Comment by hartbit** [comment]
> Until then, you can define your own Migration type, and an extension on DatabaseMigrator for convenience. This is my current recommendation, until I grab more information!

Sounds good! Thanks.
