### ISSUE TITLE
Consider opening up Database for initialisation

### ISSUE THREAD

**Issue by robertjpayne** [groue/GRDB.swift#39]
Until GRDB is fully re-entrant it's hard to use in an application that may require nested transactions. For those of us willing to externally enforce Swift/sqlite3's threading rules it would be valuable to just have a raw database...

In my particular case I need a function to start a transaction, run a callback ( passing the database to that callback )

**Comment by groue** [comment]
Hello @robertjpayne 

> Until GRDB is fully re-entrant

Being reentrant is *not* a goal of GRDB.

Reentrancy would favor methods that access the database at their will, introducing a dangerous mismatch between an application API that looks stateless and a database that is stateful. Long story short : models that think they are entitled to open database transactions are a danger for a code base, and by making GRDB not reentrant, I actively work against those.

> For those of us willing to externally enforce Swift/sqlite3's threading rules it would be valuable to just have a raw database...

GRDB does not expose raw database, and only allow access through Database queues and pools because custom threading rules are really hard to do right.

I haven't thought much about nested transactions (save points) yet, and I'm keen to look at the trouble you may have, in detail.

> In my particular case I need a function to start a transaction, run a callback ( passing the database to that callback )

What about writing the code that you wish you could write, and that you can not today? It will be clearer.

**Comment by robertjpayne** [comment]
Hey @groue I think re-entrancing is probably the wrong wording, more specifically is the desire for SAVEPOINT/RELEASE support but currently you can't achieve that with DatabaseQueue or DatabasePool as each of these two are not re-entrant therefore could not even execute the savepoint/release commands when inside a transaction.

I still believe there is value in allowing people to create the `Database` in my particular use case I want to bring my own threading as I'm using ReactiveCocoa and it's schedulers that ensure thread safety.

**Comment by groue** [comment]
> you can't achieve that with DatabaseQueue or DatabasePool as each of these two are not re-entrant therefore could not even execute the savepoint/release commands when inside a transaction.

I really need to see your code. Because nothing prevents you to pass a database along, and run your save points at your will.

> I still believe there is value in allowing people to create the Database in my particular use case I want to bring my own threading as I'm using ReactiveCocoa and it's schedulers that ensure thread safety.

Again, I'm interested, but I need more precision.

**Comment by robertjpayne** [comment]
@groue:

Actually good point, I think I can revise my code to pass the inner db reference around and can issue the savepoints myself then :+1:

**Comment by groue** [comment]
Great! I was unsure that GRDB would fit well in a Reactive pattern, and you comfort me :-) Come back when you have another question!
