### ISSUE TITLE
Crash during deinit of DatabaseQueue

### ISSUE THREAD

**Issue by ptseng** [groue/GRDB.swift#42]
This commit introduces deinit for DatabaseQueue.
https://github.com/groue/GRDB.swift/commit/005c4ded2408611789e01829295b10b40d1c2af3

Which gives me the following crash on deinit:

```
*** NSForwarding: warning: object 0x7f96e526a550 of class 'GRDB.DatabaseQueue' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[GRDB.DatabaseQueue FXNotifications_observers:]
```

Perhaps DatabaseQueue should also inherit from NSObject?

**Comment by groue** [comment]
Hello @ptseng. I can not reproduce your issue. Do you have more detail?

**Comment by ptseng** [comment]
Podfile:

```
platform :ios, '8.0'
use_frameworks!

pod 'GRDB.swift'
pod 'FXNotifications'
```

ViewController.swift:

```
import UIKit
import FXNotifications
import GRDB

class ViewController: UIViewController {
    
    var queue = [Int:DatabaseQueue]()

    override func viewDidLoad() {
        super.viewDidLoad()
        queue[1] = DatabaseQueue()
        queue[2] = DatabaseQueue()
        queue[1] = nil
        queue[2] = nil
    }
}
```

Making DatabaseQueue a subclass of NSObject seems to fix the crash bug.

**Comment by groue** [comment]
Wow.

I did spend a few minutes setting up a new project with your Podfile, and pout your code in a plain ViewController, nothing else. And I get a crash... related to FXNotifications.

I suggest that you open an issue in FXNotifications instead. GRDB has no problem.

**Comment by ptseng** [comment]
@groue I will post this issue with FXNotifications.  However, I think this bug was introduced with the new (26 days) use of deinit() in DatabaseQueue.  Please reference and consider reopening this issue: 

http://stackoverflow.com/questions/24415662/object-x-of-class-y-does-not-implement-methodsignatureforselector-in-swift

**Comment by ptseng** [comment]
https://github.com/nicklockwood/FXNotifications/issues/9

**Comment by groue** [comment]
@ptseng You're totally right, this crash was introduced by the `NSNotificationCenter.defaultCenter().removeObserver(self)` line added in DatabaseQueue.deinit in commit https://github.com/groue/GRDB.swift/commit/005c4ded2408611789e01829295b10b40d1c2af3.

However, this does not mean that GRDB has a bug. This deinit works perfectly well with the stock NSNotificationCenter. DatabaseQueue does not inherit from NSObject, because it has no reason to. And yet it plays perfectly well with the Apple frameworks.

Unfortunately, FXNotifications swizzles `-[NSNotificationCenter removeObserver:]`. Swizzling means replacing the default implementation. Yes, it injects its own code inside an Apple framework. No problem with that. It's an advanced technique that exists to be used. But unfortunately FXNotifications is not as robust as the framework it aims at improving. Oh, the irony!

Do you think I should change GRDB each time a third-party library messes with Apple frameworks and introduces crashes? I do not.

The fix is not to have DatabaseQueue inherit from NSObject. The fix is to have FXNotifications fixed. It will improve their Objective-C handling as well as their interoperability with Swift. They will thank you. And you will thank them. And this issue will remain closed, because there's nothing GRDB can do to fix all the bugs in the world.

**Comment by groue** [comment]
@ptseng FXNotifications has not much value now that NSNotificationCenter has the same features. Remove the FXNotifications pod and move on.

**Comment by ptseng** [comment]
@groue You make a good point.  I will try and see if we can remove FXNotifications from the project.  Thanks for looking into this.

**Comment by groue** [comment]
No problem 😄 Happy GRDB!
