### ISSUE TITLE
SQLite error 5 "database is locked"

### ISSUE THREAD

**Issue by faizbaraja** [groue/GRDB.swift#436]
### What did you do?

I tried to run DBMigrator.registerMigration for alter the table
var migrator = DatabaseMigrator()
        migrator.registerMigration("addTransactionDetailAdditionalInfo") { db in
            try db.alter(table: "TransactionDetail") { t in
                t.add(column: "variantID", .integer)
                t.add(column: "categoryID", .integer)
                t.add(column: "categoryName", .text)
                t.add(column: "itemIcon", .text)
                t.add(column: "itemDescription", .text)
            }
        }
        try migrator.migrate(dbQueue)
        return dbQueue

### What did you expect to happen?

table will add new column

### What happened instead?

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 5 with statement `BEGIN IMMEDIATE TRANSACTION`: database is locked..

is there something wrong with my code ???Please tell me how to run alter table on dbmigrator..

thank you

**Comment by groue** [comment]
Hello @faizbaraja.

SQLite error 5 is [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy). This error happens when several SQLite connections attempt at writing in the same database.

Your app opens multiple connections. It creates several instances of DatabaseQueue.

Maybe your app does, indeed, need multiple connections. But there are much more chances that it does not. So please follow the rule 1 of the [GRDB Concurrency Guide](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency):

> ☝️ **Rule 1**: Have a unique instance of DatabaseQueue or DatabasePool connected to any database file.

Following the rule will prevent this error.

In order to apply the rule, avoid creating multiple database queues. Create only **one**. The `DatabaseQueue(path:)` initializer must run **once** in the whole lifetime of your app. Store this dbQueue somewhere. In a global variable if you want, it does not matter, as long as there is a **single** instance of DatabaseQueue that accesses the database file. Have a look at the [demo app](https://github.com/groue/GRDB.swift/tree/master/DemoApps/GRDBDemoiOS) if you need guidance.

**Comment by faizbaraja** [comment]
just followed the demo app and it worked good.....thanks
