### ISSUE TITLE
Reading Default value from column 

### ISSUE THREAD

**Issue by Mahdimm** [groue/GRDB.swift#439]
Hi @groue 
I created a table and I will insert default value for time like below:

```
  func createRequestTable( _ db:Database ) throws {
        try db.create(table: "Request") { t in
            t.autoIncrementedPrimaryKey("id")
            t.column("request",         .text ).notNull()
            t.column("response",        .text )
            t.column("time",            .datetime ).defaults(sql: "CURRENT_TIMESTAMP")
            t.column("uuid",            .text ).notNull()
            t.column("status",          .integer ).defaults(sql: "\(requestStatus.sent.rawValue)" )
        }
    }
```
and this is my model:

```
struct ResponseModel {
    var id: Int64?
    var request: String
    var response: String
    var time: String?
    var uuid: String
    var status: Int
    
    init(req: String, res: String, uuid: String, status: Int) {
        self.request = req
        self.response = res
        self.uuid = uuid
        self.status = status
    }
}

extension ResponseModel: Codable, FetchableRecord, MutablePersistableRecord {
    
    static let databaseTableName = "Request"

    private enum CodingKeys: String, CodingKey, ColumnExpression {
        case id, request, response, time, uuid, status
    }
    
    mutating func didInsert(with rowID: Int64, for column: String?) {
        id = rowID
    }
    
}
```

and while I set **time** column in enum codingKeys It will set null in table and when I remove it from codingKeys its working fine for inserting in table. but I can't get it while I'm fetching data because I didn't add **time** column to codingKeys so how can I solve this problem?

thanks

**Comment by groue** [comment]
Hello @Mahdimm,

I suggest you follow the same resolution technique as the one used in your previous issue #438:

1. First, understand and express what you want to do.
2. Second, have the code do what you want to do with the help of the available tools.

Above all, don't think anything happens by magic. Everything happens because of your application code. You control your application code, hence you control your application behavior. If your application somehow misbehaves, you can make it behave correctly.

But you have to analyse your problem first.

If you need help performing this analysis, do try [Rubber Duck debugging](https://rubberduckdebugging.com). It's a very very powerful technique for understanding what's wrong.

I'm closing this issue for now. If, after you have understood what's wrong, you still have an issue implementing the needed change, don't hesitate asking again. That's what support is for. But I'm not here to help you figuring out what your application needs. Only you can do this.

**Comment by groue** [comment]
Oh, and please, when you open an issue, **fill in the issue template**. Don't ignore it: it's rude.
