### ISSUE TITLE
Update to SQLCipher 4.0

### ISSUE THREAD

**Issue by vostreltsov** [groue/GRDB.swift#460]
Hi there,

When can we expect an update to sqlcipher 4.0?

Thank you!

**Comment by groue** [comment]
Hello @vostreltsov,

This is a good question. There is a difficulty, though: **SQLCipher 4 is not backward compatible with SQLCipher 3.**

For more information about those breaking changes, don't miss the [Upgrading to SQLCipher 4](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283) article.

This is a difficulty for GRDB, because:

1. [Semantic versioning](https://semver.org) requires that the major version of GRDBCipher is bumped when it eventually ships with SQLCipher 4.

2. I don't quite want GRDBCipher to have a different version number than the regular GRDB, because it would be difficult to track in the long run, both for GRDB maintainers and GRDB users.

3. I wasn't planning a new major version of GRDB before Swift 5. And I haven't started yet thinking seriously about the potential API improvements we could bring to GRDB 4.

In a word: SQLCipher won't be supported out of the box until GRDB 4, which isn't even planned yet.

Conclusion: it you do really want SQLCipher 4, you will have to do it yourself.

For example, you can try to use GRDBCipher and force SQLCipher version in your Podfile, as below (don't assume this works, because I haven't tried it):

```ruby
pod 'GRDBCipher', '~> 3.6'
pod 'SQLCipher', '~> 4.0'
```

I hope this enough essential information so that you can start upgrading your version of SQLCipher.

Will you please tell us your journey in this uncharted territory? I'm positively certain it will be a very precious experience for the whole community.

**Comment by groue** [comment]
I also recommend reading https://github.com/sqlcipher/sqlcipher/issues/296, which contains very useful information about SQLCipher 4 migration.

**Comment by groue** [comment]
You may also fork GRDB and change its podspec, as @N-Olifer did in [his fork](https://github.com/N-Olifer/GRDB.swift/commit/f95bf6fde7b1256c1e6434927d188336bf834668).

I'm closing this issue now. Please come back with any fresh information, any time.

**Comment by groue** [comment]
GRDB 4 and SQLCipher 4: https://github.com/groue/GRDB.swift/issues/480
