### ISSUE TITLE
Write priority ?

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#463]
Hi Gwendal,

In some operations, my app write a lot of datas to DB (scan folders and insert all files in the DB)
This task is running in the background.
When a user manually navigate to a folder, i insert files from this folder and display it from the DB. 

Problem, i have a lot of writes waiting to be inserted, and it can take 5-10 seconds to display datas from this folder, and it look like a bug for the user (as it just see an empty list)

It would be fine to have an insert priority, or at least a way to control the insert, so we can insert some urgent write to the top of the fifo queue.

From the code i see that we can play with the queue & qos (Configuration), but i don't know if it apply to my problem.

Thanks (and happy new year ;p)

**Comment by groue** [comment]
Hi @skrew 

If your write operations are slow, and are preventing reads from fetching anything from the database, then:

1. First make sure all your slow writes are wrapped in a single transaction. This speeds up sqlite operations a lot:

    ```swift
    // no transaction: slow
    try dbQueue.inDatabase { db in ... }
    // implicit transaction: fast
    try dbQueue.write { db in ... }
    // explicit transaction: fast
    try dbQueue.inTransaction { db in ...; return .commit }
    ```

2. If your writes are still slow after being wrapped in a transaction (see above), and your reads are still blocked, use a [DatabasePool](https://github.com/groue/GRDB.swift/blob/master/README.md#database-pools) instead of a DatabaseQueue. Pools lets your application read in the database, even in a write operation is running. This can greatly help the responsiveness of your application. Read the documentation for more details.

**Comment by groue** [comment]
... and happy 2019 too ;-)

**Comment by skrew** [comment]
Hi,

I already use transactions & DatabasePool.

I have "corrected" it by changing the QOS of background operations, the user navigation works more faster (just 2-3 seconds now while background fetching).

Just for your information, my app is released and i got 0 (Z-E-R-O) crash from DB engine, despite of a very high usage of the DB (even in stress operations with a lot of read/write ops in multithread mode).

The nightmare of Realm crashs is over ! So thanks a lot !

**Comment by groue** [comment]
> I already use transactions & DatabasePool.
>
> I have "corrected" it by changing the QOS of background operations, the user navigation works more faster (just 2-3 seconds now while background fetching).

All right. Good!

Did you look for the reason of those long seconds? What does Instrument say when you profile your app?

> Just for your information, my app is released and i got 0 (Z-E-R-O) crash from DB engine, despite of a very high usage of the DB (even in stress operations with a lot of read/write ops in multithread mode).
> 
> The nightmare of Realm crashs is over ! So thanks a lot !

Thank you very much for saying this! It is really pleasing to read, almost as much as it is pleasing to forget about database-related crashes ;-) And kudos to the SQLite team, of course - I hope they know how much we are grateful!

**Comment by groue** [comment]
No news is good news: I'm closing the issue, @skrew. Feel free to reopen if you feel like it!
