### ISSUE TITLE
two connections same time

### ISSUE THREAD

**Issue by ahmedAlmasri** [groue/GRDB.swift#468]
I'm trying to open multiple connections,  But throw this error 

`SQLite error 5 with statement PRAGMA journal_mode = WAL: database is locked`

Sample My Code : 

```

    private func connection() -> DatabasePool? {
        do {
            
            var config = Configuration()
            config.busyMode = .callback({ (errorCode) -> Bool in

                print("SQLITE Error code \(errorCode)")

                return errorCode < 3
            })
            
             return try DatabasePool(path:".../mydb.db", configuration: config)
        
        } catch {
            Log.e(error)
            return nil
        }
    }
    
    func insert(_ myObj: CacheableModel) {
        do {
            try connection()?.write { dbs  in
                try myObj.insert(dbs)
            }
            
        } catch {
            Log.e(error)
        }
        
    }

  func select() -> [CacheableModel]? {
        
        do {
            return try connection()?.read { dbs -> [CacheableModel] in
                
                return try CacheableModel.fetchAll(dbs)
            }
        } catch {
            Log.e(error)
            return nil
        }
    }
```

**Comment by groue** [comment]
Hello @ahmedAlmasri 

> I'm trying to open multiple connections, But throw this error

This error is normal, because opening multiple connections is a wrong way to use GRDB.

This is documented in the [Concurrency Guide](https://github.com/groue/GRDB.swift/blob/master/README.md#concurrency):

>☝️ **Rule 1: Have a unique instance of DatabaseQueue or DatabasePool connected to any database file.**
>
> This means that opening a new connection each time you access the database is a bad idea. Do share a single connection instead.
>
> See the [Demo Application](https://github.com/groue/GRDB.swift/blob/master/DemoApps/GRDBDemoiOS/README.md) for a sample app that sets up a single database queue that is available throughout the application.
>
>If there are several instances of database queues or pools that write in the same database, a multi-threaded application will eventually face "database is locked" errors.

In order to get rid of your error, simply follow the documented rules.

**Comment by ahmedAlmasri** [comment]
@groue  Hello , Thank you for replay 

I need to multiple connections, I have two side to connect my database , Unity side and native app side .
How to handle two connection, please help me

**Comment by groue** [comment]
> I need to multiple connections, I have two side to connect my database , Unity side and native app side .

This is not what your sample code shows, @ahmedAlmasri. Instead, your sample code above opens a new connection each time you access the database.

And this is wrong, as explained above.

So please check if it is really impossible for you to share a single database connection.

If it is really impossible, then you'll have to strengthen your knowledge of SQLite in order to avoid "database is locked" errors.

First, understand that those errors are not a GRDB bug. They are fundamental errors of SQLite, which disallows two connections to write in the database at the same time. You must be ready to deal with those errors when you open several connections.

Second, read the [Dealing with External Connections](https://github.com/groue/GRDB.swift/blob/master/README.md#dealing-with-external-connections) chapter. You'll find links to the necessary information. Focus on the "busy handler" part.

I can't really do more. If you insist of using multiple connections, then you have to understand that you have more work to do, and more things to learn.
