### ISSUE TITLE
Crashing fetchOne call

### ISSUE THREAD

**Issue by skreutzberger** [groue/GRDB.swift#48]
I am getting deeper and deeper into GRDB. To avoid crashes, I am wrapping all my `try db.inDatabase{...}` calls in a `do..catch` block and can perfectly catch errors.

But for a `fetchOne` call (SELECT) using `try` is not possible because `fetchOne` seems to internally do a `try!`. Now, if I am using invalid SQL in a `fetchOne` then my app is crashing :(

Are there alternatives to the fetch command which return rows from SELECT and which are properly crash-marked?

Maybe you can replace every `try!` with `try`?

Here is an excerpt of an example which creates a crash:

```
....
// LIMIT 1 must come after ORDER -> the SQL is invalid which leads to a crash
let sql = "SELECT * FROM \(table) WHERE \(column)=:val LIMIT 1 ORDER BY id DESC"
db.inDatabase { db in
    if let row = Row.fetchOne(db, sql, arguments: ["val": value]) {
        ret = row
    }
}
return ret
...
```

**Comment by groue** [comment]
Hello @skreutzberger. Happy to see you again :-)

> Now, if I am using invalid SQL in a fetchOne then my app is crashing :(

Of course your application crashes when you are using invalid SQL. This is how programmer errors are supposed to be treated. Unwrap a nil optional, you get a crash. Access array element at index -1, you get a crash.

Have a look at https://github.com/groue/GRDB.swift#error-handling. You will see that GRDB throws fatal errors for:

1. Programmer errors
2. False assumptions
3. Library misuses.

An invalid SQL query *is* a programmer error (unless the SQL comes from some untrusted external source, but this is not your case). You don't want to pollute your application code with useless do... try... catch... around each SQL request: just write correct SQL, and move on.

A false assumption typically happens when the database does not behave as the application expects it to do. Some table is missing, some column is missing, some value is NULL when it should not. Again, this is a great opportunity for fatal errors to remind the developper that she has to take action, and make application code agree with the database. This can be fixing the database, or fixing the application code. I don't know, it depends on the situation. But just do it. There's no purpose writing do... try... catch... just in case some value would be NULL when it is not supposed to be.

**Comment by skreutzberger** [comment]
I understand but the issue is that I can not wrap the whole statement in a `do...catch` block to prevent it from fatally crashing and to log errors, etc. due to the situation that `fetchOne` does not throw an error.

**Comment by groue** [comment]
> An app should do everything possible to avoid or recover from a crash from my point of view since a crash is the worst experience for a user.

We agree. And in this particular case, it's easy to avoid crashes: just write valid SQL.

**Comment by groue** [comment]
Put in another way: if you have a crash with valid SQL, open an issue here. This should just not happen.

**Comment by skreutzberger** [comment]
Hmm, every function that can crash after proper compiling should throw an error and not just crash. And playing blame-game with developers with a user who has to pay for it is not what I want to support.  Anyway, I will try to fix it by myself.

**Comment by groue** [comment]
@skreutzberger 

- unwrapping a nil optional
- accessing an array beyond its range
- presenting a view controller when there is already one presented view controller
- inserting a row in a table view when the data source has not updated its row count
- writing invalid SQL.

All those situations require a change in the program, and no handing at runtime. This is why they are "punished" by a fatal error. This is not a blame game. This is the proper way to handle programming errors.

Of course, feel free to experiment, and wrap all your database accesses in do... try... catch. I'm curious to see the kind of code you'll put in the catch blocks, and how much time you'll spend working on invalid SQL statements.

At least you know why GRDB is like it is. Come back to this thread later, eventually?

**Comment by groue** [comment]
You may also enjoy reading https://github.com/apple/swift/blob/master/docs/ErrorHandlingRationale.rst.
