### ISSUE TITLE
Linking to local database in Swift iOS

### ISSUE THREAD

**Issue by maartenscherpenisse** [groue/GRDB.swift#491]
I am trying to link to an already existing database via GRDB. This is working already, but not yet how it should be. I am able to load the database and view the contents in de UITableView without any problems, but only when simulating my app on my computer. It is an iOS app, I would like to run it on my iPhone. Also probably relevant to note: I am a beginner.

So far the problem seems to concentrate on the following line:

```
let databasePath = "/Users/<username>/Documents/database.sqlite" // yes, absolute path
let dbQueue = try! DatabaseQueue(path: databasePath)
```

I have a second copy of the database located within my app, in the folder "/Data/database.sqlite". This is the file I would actually prefer to link to, and which most likely will solve the problem of not being able to load the database when running it on my iPhone.

I tried different things with `Bundle.path`, `Bundle.main.path`, `Bundle.main.url`, `FileManager.default.urls`, `documentsDirectory?.appendingPathComponent`, and changing the literal string of let databasePath manually, but none worked so far. 

Summarised short, my question is: how to properly load an already existing, local database file from GRDB.

**Comment by groue** [comment]
Hello @maartenscherpenisse 

> Summarised short, my question is: how to properly load an already existing, local database file from GRDB.

This is a great summary.

The answer is in two steps:

1. Store that existing database as a **resource** of your application, so that it gets embedded in your application, and copied to your device when you install the app. App resources can be SQLite databases, and generally any other embedded file: check Google if you need more information about resources.
2. Don't use an absolute path, but a **resource path**. This is explained in the [How do I open a database stored as a resource of my application?](https://github.com/groue/GRDB.swift/blob/master/README.md#how-do-i-open-a-database-stored-as-a-resource-of-my-application) FAQ.

This should allow you to move forward :-)

**Comment by maartenscherpenisse** [comment]
That made it work, thank you very much!
