### ISSUE TITLE
Date precision

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#492]
When saving a `Date` to a `.datetime` column it seems as though some precision is lost. Which makes sense since a `Date` is basically just a `Double` in pretty clothes.

This is a date as. `dumped()` on a model before saving it to the database:
`timeIntervalSinceReferenceDate : 573385274.217203`

Here's the same date as fetched from the database:
`timeIntervalSinceReferenceDate : 573385274.217`

This makes using the automatic `Equality` implementation of structs unusable as a means of comparing two records.

What would be the recommended way of fixing this? Changing the column type or normalizing dates before saving?

**Comment by groue** [comment]
Hello @simme 

> When saving a Date to a .datetime column it seems as though some precision is lost.

You have an extensive discussion of dates in GRDB at [Date and DateComponents](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-datecomponents), and [Date and UUID Coding Strategies](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-uuid-coding-strategies).

Quoting documentation:

> Dates are stored using the format "YYYY-MM-DD HH:MM:SS.SSS" in the UTC time zone. It is precise to the millisecond.

This format is not the same as the "native" Date representation, with happens to be its `timeIntervalSinceReferenceDate`, the number (`Double`) of seconds since 00:00:00 UTC on 1 January 2001. And this is why you witness a loss of precision.

> This makes using the automatic Equality implementation of structs unusable as a means of comparing two records.

This is one way to define the problem.

Another way is to question the comparison technique.

Imagine that instead of the database, your dates had to undergo a roundtrip through a remote server by the way of JSON coding and decoding. And you discover that server dates are only precise up to the second. You would then redefine "equality" so that it deals with this precision loss.

Now imagine that you have to deal with a companion Android app, whose native date storage is the number (`long`) of milliseconds since January 1, 1970, 00:00:00 GMT. You will again have to redefine "equality".

Last, the [documentation of `Date.timeintervalsincereferencedate`](https://developer.apple.com/documentation/foundation/date/1780268-timeintervalsincereferencedate) makes no promise whatsoever that Foundation.Date will never change its implementation. So even if you store those numbers in the database, you may want to make your app ready for a future change.

**Date equality is just like Double equality: full of traps.** On top of that, the in-memory representation of a Date does not always match its serialized representation(s).

> What would be the recommended way of fixing this? Changing the column type or normalizing dates before saving?

It depends on what the correct fix is.

The general and safe advice is to redefine equality so that it deals with an expected amount precision loss, as seen above.

You may also store `timeIntervalSinceReferenceDate` in the database, and keep the default Date equality. But you don't have any guarantee that you will not, in the future, face equality issues again.

**Comment by simme** [comment]
Thank for an extensive and balanced answer, as always!

I read the documentation but didn't quite draw the connection. It doesn't explicitly spell out that the format that the documentation is talking about doesn't work with the `.datetime` column type. But that's on me for not reading the SQLite documentation :) So I should use `.text` to get the human readable format then?

What you're saying about equality makes 100% sense. I just have to bite the bullet and implement  custom Equality conformance for my records.

**Comment by groue** [comment]
> Thank for an extensive and balanced answer, as always!

Thanks ;-) I will be able to link to this issue whenever one asks the same question!

> I read the documentation but didn't quite draw the connection. It doesn't explicitly spell out that the format that the documentation is talking about doesn't work with the .datetime column type. But that's on me for not reading the SQLite documentation :) So I should use .text to get the human readable format then?

You're right, this topic is completely left out from the doc.

Short story: do use `.datetime` when you want to store dates (the ones with time information, like `Foundation.Date()`):

```swift
try db.create(table: "player") { t in
    t.column("lastGameDate", .datetime) // self-documenting
)
```

Inside such a column, of SQL type `DATETIME`, SQLite will accept both date strings (the default GRDB behavior), and Double (timestamps, if you prefer). Yes, `.datetime` lets you choose your date serialization format. [SQLite data types](https://www.sqlite.org/datatype3.html) are *funny*. On the other hand, `.text` turns everything into text: not only does it not express your intent in the schema, but it prevents you from storing timestamps when you want to.

> What you're saying about equality makes 100% sense. I just have to bite the bullet and implement custom Equality conformance for my records.

Yes, I think this is reasonable. You can store strings or timestamps, depending on your needs, but take care about equality. Maybe your current project does not really need such a level of robustness. But you'll face the same issue several times in the future, so some training can't be harmful :-)

**Comment by iNoles** [comment]
I have same problem when I am trying to do unit testing. I am storing the timeIntervalSince1970 values on the database. Is this okay too?

**Comment by groue** [comment]
@iNoles, timeIntervalSince1970 is indeed a format that loses precision, so yes it is normal that you experience equality troubles in your tests: the database does not store the *exact* original date, as explained [above](#issuecomment-469213429). 

If you use timeIntervalSince1970, then your tests should accommodate for a maximum desired precision loss. For example, don't test that two dates are equal. Instead, test that two dates are less than 1 second apart (choose your maximum delay according to your application domain).
