### ISSUE TITLE
Support for multi-column primary keys?

### ISSUE THREAD

**Issue by schveiguy** [groue/GRDB.swift#52]
I have a table where the primary key is a tuple of the primary key of an owner table, and instance of the sub-item.

Docs say GRDB only supports fetching of single-column primary keys unless you use Record. Why not with just table mapping? e.g.:

```swift
// CREATE TABLE my_table (id INTEGER, instance INTEGER, PRIMARY KEY (id, instance))
struct MyRecord : Persistable, TableMapping
{
   var id : Int64
   var instance: Int
   init(_ row: Row)
   {
      id = row.value(named: "id")
      instance = row.value(named: "instance")
   }
   static func databaseTableName() -> String
   {
      return "my_table"
   }

   // why can't this be auto-added via extension?
   static func fetchOne(db: DatabaseReader, key: (Int64, Int)) -> MyRecord?
   { ... }
}
```

**Comment by groue** [comment]
Hello @schveiguy 

It's not documented in the README, but you can pass a dictionary to the `key` argument of `fetchOne`:

```swift
MyRecord.fetchOne(db, key: ["col1": val1, "col2": val2])
```

Documentation is missing, but the feature is there to stay: I [want](https://medium.com/@gwendal.roue/grdb-stories-8c37a03ef72d) GRDB to support any primary key.

This variant of `fetchOne` actually supports any key, not only primary keys, because it does not introspect the database schema. It implicitly requires that the dictionary columns are actually a table key, and returns the first record that matches.

Why did I not add any generic function that eats a tuple of 2, 3, ... N items? Because these functions would depend on the ordering of columns in the primary key. And this ordering is not always obvious, or may even be fragile (in case of wild schema change):
    
```swift
// Not supported, on purpose:
MyRecord.fetchOne(db, key: (1, 2))  // what is 1? what is 2?
```

So now, I suggest you write your own extension, as below :-)

```swift
extension MyRecord {
    static func fetchOne(db: Database, key: (Int64, Int)) -> MyRecord? {
        return fetchOne(db, ["col1": key.0, "col2": key.1])
    }
}
```

**Comment by schveiguy** [comment]
Hm... yes, that's much better than my SQL string forward that I had written, thanks :)

**Comment by groue** [comment]
You're welcome :smile:

**Comment by groue** [comment]
I added a paragraph in README.md: https://github.com/groue/GRDB.swift#fetching-by-primary-key
