### ISSUE TITLE
Question about prepared statements and arguments

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#520]
Hi Gwendal,

To maximize speed, i use prepared statements almost everywhere when i need to insert a LOT of datas.

Now, i have a struct with Codable, as i have read in the doc, GRDB converts array & dict to JSON (which it's nice and smart)

But everytime i try to use it in a prepared statement, i got `nil` as result

tested with the documentation sample in a playground, this works:
```
let player = Player(name: "Arthur", score: 100, achievements: [achievement])
try player.insert(db)
```

But in a prepared statement:
```
let insertStatement = try db.makeUpdateStatement("INSERT INTO player (`name`, `score`, `casting`) VALUES (?,?,?)")
insertStatement.unsafeSetArguments([ "Arthur", 200, ([achievement] as? DatabaseValueConvertible) ])
``` 

`([achievement] as? DatabaseValueConvertible)` -> is always NULL

As a workaround, i convert myself the struct values in a JSON String before insert it, but do I misuse this function?

Thanks and have a good week end ! ;)

**Comment by groue** [comment]
Hello @skrew, it's been a long time :-)

Indeed, `([achievement] as? DatabaseValueConvertible)` is nil (the Swift nil), because this Array does not conform to DatabaseValueConvertible. That's why you get NULL in the database.

JSON columns are a convenience of [Codable record](http://github.com/groue/GRDB.swift/blob/master/README.md#codable-records) types only. When you want to go raw, go full raw, and perform your own JSON encoding before inserting values:

```swift
let jsonData = JSONEncoder().encode(...)
let jsonString = String(data: jsonData, encoding: .utf8)
let insertStatement = try db.makeUpdateStatement("INSERT INTO player (`name`, `score`, `casting`) VALUES (?,?,?)")
insertStatement.unsafeSetArguments([ "Arthur", 200, jsonString])
```

To maximize speed, you can avoid turning the JSON data into a string. You'll store blobs instead of strings in the database (less easy to debug), but this won't affect decoding at all because both SQLite and GRDB automatically converts strings to blobs and blobs to strings when decoding (a not very well know "feature" of SQLite which is really handy sometimes).

**Comment by skrew** [comment]
Yes long time, but no news = good news ! ;)

Ok you are right i don't need to convert it to a string, i can store it in a blob as Data, If I've understood everything correctly.

But this database schema is already released, and with sqlite we can't delete (nor rename) rows without deleting all (ok you already know it, for sure 😉)...
It can be a good idea to code something to automate this... i have to think about it.

It's better for me to not use any "special" type on this table (it's the biggest and speed is critical here), so I'm not going to add unnecessary conversion work to the device...

Thanks again

**Comment by groue** [comment]
You're welcome @skrew! See you in a couple of years ;-) And have a good week end too!
