### ISSUE TITLE
No error when opening a jpg as a database

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#54]
I attempt to open a jpg file as a database and do not get any error. This must be wrong?
url is pointing to a .jpg file

`var config: Configuration = Configuration()
        
        config.trace = { print($0) }
        config.readonly = true

        let dbQueue = try! DatabaseQueue(path: url.path!, configuration: config)`

**Comment by groue** [comment]
Hello @mtissington 

I think that SQLite won't complain until database is actually accessed. I know that this is the case for encrypted databases: SQLite won't notice any error, for example a wrong passphrase, until the database is accessed.

So that the user gets an early error when the passphrase is not correct, GRDB does an [early check](https://github.com/groue/GRDB.swift/blob/v0.64.0/GRDB/Core/Database.swift#L118-L122). It does this check only for encrypted databases.

Maybe we could do it for regular databases, too.

**Comment by mtissington** [comment]
or set it as an option parameter in the configuration to check db?

**Comment by groue** [comment]
Do you see a reason to want to avoid the check?

**Comment by mtissington** [comment]
Hmm, maybe efficiency?

**Comment by groue** [comment]
> Hmm, maybe efficiency? 

Not really relevant here: we don't open databases that often.

OK, let's perform the check for all databases.

**Comment by groue** [comment]
GRDB v0.65.0 is out: it fixes this issue.

**Comment by groue** [comment]
Thanks for the report.

**Comment by mtissington** [comment]
thanks - how long before cocoapods picks this up?

**Comment by groue** [comment]
A couple of seconds?

**Comment by mtissington** [comment]
strange it seems to be stuck with .62

**Comment by groue** [comment]
v0.65.0 has been pushed: https://cocoapods.org/pods/GRDB.swift.

**Comment by mtissington** [comment]
very strange the latest i can install is .62

**Comment by mtissington** [comment]
i see i need to do a pod repo update now ...
