### ISSUE TITLE
Association missing since 4.x

### ISSUE THREAD

**Issue by skrew** [groue/GRDB.swift#559]
Hi Gwendal,

Since GRDB 4.x i have one association which don't works anymore.
It's strange since others still works.

When i enable debug and print SQL, i can confirm that the generated SQL request is just fine, i can see the joined datas in a SQLite browser like expected.
Without changing anything (except extra stuffs in code like `sql:`), getting GRDB back to 3.7.0 make it works again.

 I'm using it with:

```
    static let movieFK = ForeignKey(["idskmovie"], to: ["idskmovie"])
    static let movie = hasOne(SMovie.self, using: movieFK)
    
    static let mediastatsFK = ForeignKey(["url"], to: ["rawhost"])
    static let mediastats = hasOne(MediaStats.self, using: mediastatsFK)
```

-->
```
let request = SMediaItem
<...>
.including(optional: SMediaItem.movie)
.including(optional: SMediaItem.mediastats)
```

movie have datas, mediastats is `nil`

Any idea ? I will make a Playground if needed

Thanks ;)

Xcode 10.2.1 / Swift 5 for GRDB 4.x - Xcode 10.2.1 / Swift 4.2 for GRDB 3.7.0, iOS 12.2

**Comment by groue** [comment]
Hello @skrew :-)

Yes I think I know what's happening. GRDB 4 ships with automatic pluralization and singularization of association keys in order to support eager loading of has-many associations. Those inflections allow `Author.including(all: Author.books)` to feed a `books` property, from a table named `book`.

In your specific case, I assume the `mediastats` association feeds from the `mediastats` database table. With GRDB 4, it gets [inflected](https://github.com/groue/GRDB.swift/blob/v4.1.1/GRDB/QueryInterface/TableRecord%2BAssociation.swift#L332), and the associated records are present in the fetched rows under the key `mediastat` (without s). In GRDB 3, the table name was not altered, and the associated records were found under the key `mediastats`.

Now, there are singular associations that have a naturally plural name: xxxStats, xxxDemographics, etc.

In order to support them, GRDB [won't inflect](https://github.com/groue/GRDB.swift/blob/v4.1.1/GRDB/QueryInterface/TableRecord%2BAssociation.swift#L330) explicit association names:

```swift
// The explicit "mediastats" key will not be inflected in singular contexts
static let mediastats = hasOne(MediaStats.self, key: "mediastats", using: mediastatsFK)
```

This is the fix your application needs.

**Comment by skrew** [comment]
Hi,

Yes, the table name was my first suspicion, as I'd already had the problem.
But since it's worked before, I wasn't sure.

BTW, it's working now ! 👍🏻

Can't wait to play with Combine 😇

Thanks for all.

**Comment by groue** [comment]
Glad it works :-) There's no clear explanation of the implemented behavior anywhere in the doc, so I'm not surprised you weren't quite assured. I myself spent a few minutes figuring things out before I could remember the intended design, convince me if its soundness, and write the answer :she
