### ISSUE TITLE
Implementation of auto updating Create/Modified date fields

### ISSUE THREAD

**Issue by Querschlag** [groue/GRDB.swift#567]
My database record has two date fields `created` and `modified`.
I want `created` to be set to the current date when a record is created in the database and `modified` set to the current date whenever the record get's modified by an `UPDATE`.
I tried to accomplish this behavior by writing extension functions for every record type, but there are obvious downsides.

I'm looking for a solution that works with every record type and does not rely on dedicated functions.

```swift
struct MyRecord: Codable, MutablePersistableRecord, FetchableRecord {
    
    var id: Int64?
    var created: Date
    var modified: Date
    ...
}
```

```swift
extension MyRecord {
    mutating func modifiy(_ closure: (_ record: inout MyRecord) -> Void) {
        closure(&self)
        modified = Date()
    }
    
    init(startDate: Date) {
        let created = Date()
        self.init(id: nil, created: created, modified: created)
    }
}
```

**Comment by groue** [comment]
Hello @Querschlag,

What did you find so far? Did you look at SQLite triggers, could they provide a solution? Or do you think this feature should be provided at GRDB level?

**Comment by Querschlag** [comment]
Hi @groue,

Thanks for pointing me in the direction.
IT would be great if GRDB supported this feature directly. For now I'm looking how I could accomplish this with what it already features.
I updated my GRDB and tried the approach with `observationForAll()`. The problem is that it just returns **all** objects when a change happens (including unchanged) while I am looking for the **one** that had been changed.

```swift
// Value Observation
observer = try! MyRecord.all().observationForAll().start(in: DatabaseManager.shared.pool) { (records) in
    log.verbose("MyRecord changed")
    try! DatabaseManager.shared.pool.write { db in
        for var record in records {
            record.modified = Date()
            try! record.save(db)
        }
    }
}
```

**Comment by groue** [comment]
Yes. I'm in vacations now so I am not quite able to look at your issue. Please report here any technique you find during your exploration.

**Comment by sobri909** [comment]
@Querschlag Have you investigated triggers yet? Unless you have a need to sometimes *not* set/update these values, I think triggers would be the most efficient and cleanest solution.

Here's an (untested) example of how a trigger for setting a `createdDate` might work: 

```swift
try db.execute(sql: """
    CREATE TRIGGER SomeTable_INSERT
        AFTER INSERT ON SomeTable
        BEGIN
            UPDATE SomeTable SET createdDate = date('now') WHERE rowId = NEW.rowId;
        END
    """)
```

Possibly it would make more sense to do it as a `BEFORE` rather than an `AFTER`. And you'd want to replace `rowId` with whatever your primary key is for the table. 

The updating of a `modifiedDate` field would be similar, except it would be a trigger on `AFTER UPDATE` (and you'd want to name it `SomeTable_UPDATE` or some such). 

Again, these are untested examples. But they're fairly normal SQLite trigger syntax, I think, so they should work. 

Doing this with triggers would simplify your application code, and ensure that the values are always updated for every INSERT and UPDATE.

**Comment by Querschlag** [comment]
@sobri909 I haven't used SQLite Triggers before, but they do cover my case pretty well.
As you stated, having the sqlite drive handle the updates is both simpler and results in better performance.
It might help to mention this in the documentation as the recommended solution.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kabouzeid** [comment]
Hi, is this still the recommended way to do this? :)

**Comment by groue** [comment]
Hello @kabouzeid. Nothing new has happened on that front since this conversation.
