### ISSUE TITLE
Record didInsertWithRowID primarykey single column

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#57]
Looking at this seems to imply that the primaryKey must be a single column of type int.
Is this correct?
I have several tables where the primary key is a combination of two columns (Int, String)

**Comment by groue** [comment]
Hello @mtissington 

Short answer: no. Records support all primary keys. GRDB cares a lot about [supporting all primary keys](https://medium.com/@gwendal.roue/grdb-stories-8c37a03ef72d#.4i1hlek6w).

In detail: all SQLite tables (unless created otherwise with the [WITHOUT ROWID](https://www.sqlite.org/withoutrowid.html) specifier) have a special column named "row id", which is a unique identifier per table row. This special column is there even if you don't explicitly ask for it. It is used as the regular primary key when you create a table with an "INTEGER PRIMARY KEY" column. Read https://www.sqlite.org/autoinc.html for more information.

Since all rows have a row id, the didInsertWithRowID can be relevant for all records. Usually though, you'll only override this method when you have an INTEGER PRIMARY KEY column.

**Comment by mtissington** [comment]
Thanks for the great explanation.

**Comment by groue** [comment]
You're welcome!
