### ISSUE TITLE
Get Last Inserted/Updated record

### ISSUE THREAD

**Issue by RajChanchal** [groue/GRDB.swift#578]
### What did you do?

I used `save(_ db: GRDB.Database)` function on an object whose class confirms to MutablePersistableRecord to insert/update a record. I need the same inserted/updated record back with primary key (newly generated in the case of insertion).
```
static func saveActivity(activity:Activity,completion: @escaping (Result<Activity, Error>) -> Void){
        do {
            try dbQueue.write{db in
                var activity = activity
                try activity.save(db)
                let localDBId = db.lastInsertedRowID
                try dbQueue.read{db in
                     //Get Activity from the ID
                    if let lastInsertedActivity = try Activity.fetchOne(db, key: localDBId){
                        completion(.success(lastInsertedActivity))
                    }else{
                        completion(.failure(CustomError.error("Error")))
                    }
                }
                
                
            }
        }catch (let error){
            print("Error 1: \(error.localizedDescription)")
            completion(.failure(error))
        }
    }
```

### What did you expect to happen?

The function `saveActivity(activity:Activity)` should insert/update 'Activity' object and return the inserted/updated Activity object.

### What happened instead?

Just want to ask if it is the only way to do it? Or there is some better approach to it?

### Environment

**GRDB flavor(s):** (GRDB)
**GRDB version:** 4.0.1
**Installation method:** (CocoaPods)
**Xcode version:** 11.0 beta
**Swift version:** 5
**Platform(s) running GRDB:** (iOS)
**macOS version running Xcode:** 10.15 Beta

**Comment by groue** [comment]
Hello @RajChanchal,

> I need the same inserted/updated record back with primary key (newly generated in the case of insertion).

You get this feature for free when you use the MutablePersistableRecord protocol:

```swift
struct Activity: MutablePersistableRecord {
    var id: Int64?
    var name: String

    // Update auto-incremented id upon successful insertion
    mutating func didInsert(with rowID: Int64, for column: String?) {
        id = rowID
    }
}

var activity = Activity(id: nil, name: "Coding Swift")
try dbQueue.write { db in
    try activity.save(db)
    print(activity.id!) // Not nil
}
```

This works because:

1. the `save` method sees that the activity has a nil id
2. the `save` method calls `insert`
3. the `insert` method, on success, automatically calls the `didInsert(with:for:)` method with the newly inserted id
4. in the end, the activity nows its id.

On the other side, if you call the `save` method again, on the same activity, it gives:

1. the `save` method sees that the activity has an id which is not nil
2. the `save` method calls `update`
3. that's all

So, you don't need to write code that is so much complicated. Just make sure you implement the `Activity.didInsert(with:for:)` method so that it updates the id of your activity.

**Comment by RajChanchal** [comment]
Awesome, thanks for the help.
That is the reason we make `activity` a `var` because the `save` method mutates it.

**Comment by groue** [comment]
> That is the reason we make activity a var because the save method mutates it.

Yes, exactly!

Happy your issue is solved :-)

**Comment by russellraed** [comment]
Make sure to remove `PersistableRecord` from your struct as well. Found out that `MutablePersistableRecord` does not work with it.
