### ISSUE TITLE
Enhance FetchedRecordsController with sqlite Limit

### ISSUE THREAD

**Issue by mtissington** [groue/GRDB.swift#59]
Looking at the existing code of the FetchedRecordsController it appears to select all the rows in the query into a Row collection. If the query returns several 1000 records this is not very efficient, the query may take a long time to run and may consume a large amount of memory.

Enable FetchedRecordsController to support the sqlite option LIMIT
http://www.sqlite.org/cvstrac/wiki?p=ScrollingCursor

**Comment by groue** [comment]
> Looking at the existing code of the FetchedRecordsController it appears to select all the rows in the query into a Row collection. If the query returns several 1000 records this is not very efficient, the query may take a long time to run and may consume a large amount of memory.

True. And on iOS, the Levenshtein algorithm used to compute the differences between two result sets is even more memory hungry.

Yet, don't take FetchedRecordsController for what it is not. Its job is to track changes, and eventually notify of them. Usually it is instantiated by an object that does not trigger database changes itself. All that this object needs is to be eventually notified of changes. So delay is not really a problem here.

> Enable FetchedRecordsController to support the sqlite option LIMIT

I don't quite understand:

1. If we only fetch a subset of the records, then when later one eventually needs to load the rest, we need to make sure that no database update has changed the results set in between. Wouldn't we have trouble if we would just load a subset?
2. FetchedRecordsController does not only fetch: it tracks changes. No one should use this object just to perform a fetch. Now in order to notify changes, we need to load the full list, just in case the change would happen at the end. Aren't we?

If you have answers to those two points, would you please elaborate?

**Comment by groue** [comment]
Thinking a little more, I kind of think that this support for partial fetches is the very reason behind the NSFetchedResultsController cache. Let's keep this issue open, until someone decides to eventually add this optimization to FetchedRecordsController.

**Comment by groue** [comment]
@mtissington Anything more specific? Do you happen to use FetchedRecordsController with many rows yourself, with unwanted memory pressure on your application?

**Comment by mtissington** [comment]
I'm in the process of developing an app which has the potential of having a couple of thousand rows (several columns in the database table) ... I don't have the data yet to test with, hopefully I can do some real testing by the end of the week.

**Comment by groue** [comment]
OK. We'll wait until then.

FYI:

- FetchedRecordsController does indeed keep a copy of all fetched rows.
- Individual records themselves are lazily loaded, on demand: controller.fetchedRecords instantiates all of them, but controller.recordAtIndexPath(_) (iOS only) only instantiates a record on demand.
- The memory-hungry difference algorithm (which computes detailed insertions, updates, deletes and moves) is only run if the tableViewEvent callback (iOS only) is provided.

**Comment by mtissington** [comment]
Updated ... tested with 10,000 rows and performance is good, so looks like a none issue.

**Comment by groue** [comment]
OK @mtissington, I'm glad to hear that.

FYI, v0.70.1 has a slightly better implementation of FetchedRecordsController, in that it is lazier when the [compareRecordsByPrimaryKey](https://github.com/groue/GRDB.swift#implementing-table-view-updates) option is used.

Happy GRDB!
