### ISSUE TITLE
Support for template table in codable

### ISSUE THREAD

**Issue by bikram990** [groue/GRDB.swift#590]
I don't know how to put forward the problem so I'll try to explain it via following example.

Example:
I've a object Player which conforms to codable. By default it will be saved in Player table. To change the table name I can override static variable databaseTableName. Now I want to segregate players based on which sport they belong to. One way of doing this would be to add a new column to the Player object to store the sport. Other way is to create multiple tables. I want to have a Dao class which will accept sport as a initializer and will save all the players to different tables based on the sport. The tableName will be sportName_Player. 

What are my options If I want to achieve this in GRDB?

**Comment by groue** [comment]
Hello @bikram990,

As you have seen, such a feature is not built-in.

Record types have a static `databaseTableName` property which applies to all instances. It is generally assumed by GRDB to be a constant. Nothing prevents you from having it return different values as time passes, but if something wrong then happens, it would be considered as an application misuse, not a GRDB bug.

One record type defines a single database table name because it helps both updating the database, and fetching data, in a single stroke. The TableRecord protocol, which defines the `databaseTableName` property, fuels:

- the generation of INSERT/UPDATE/DELETE statements. For example: `myRecord.insert(db)`.
- the generation of SELECT statements. For example: `MyRecord.fetchAll(db)`.
- database schema inspection: For example, `MyRecord.fetchOne(db, key: 1)` inspects the database schema in order to query the primary key of the record table (assumed to be unique).

This is the current GRDB situation. The fact that record types have a *single* table is rooted. This is unlikely to change.

> Now I want to segregate players based on which sport they belong to.

OK.

> One way of doing this would be to add a new column to the Player object to store the sport.

True. This actually looks like the simplest solution. What's wrong with it?

> Other way is to create multiple tables.

This currently means creating as many record types as there are sports. Those record types could be private to your DAO, if you don't want to pollute the rest of your application.

This would be doable as long as the list of sports is static (not changing for a given version of your app). Otherwise, you'll face a problem because you won't be able to create as many record types as there are sports. But let's not discuss this problem before we are sure it exists for good.

> What are my options If I want to achieve this in GRDB?

Besides the very simple option of using a single table, here is a third one:

If some player columns only make sense for some sports and not for others, then you have another solution than creating one table for each sport. Instead, create one table for all players, and one table dedicated to the columns that are proper for each sport. For example:

- Table player:
    - column id
    - column name
- Table soccerInfo:
    - column playerId
    - column teamName
- Table tennisInfo:
    - column playerId
    - column atpRanking
- etc.

Following the [Good Practices for Designing Record Types ](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md) (do read this one if you haven't already), you would create one record type per table. Your DAO would then have to use those records in normal ways.

On top of that, [Associations](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md) could help you run the following queries:

```swift
// All players for all sports
let players = Player.fetchAll(db)

// Only soccer players:
let soccerPlayers = Player.joining(required: Player.soccerInfo)

// Only soccer players, but with soccer information attached
let soccerPlayers = Player.including(required: Player.soccerInfo)
```

**Comment by groue** [comment]
> What are my options If I want to achieve this in GRDB?

Whenever you ask yourself this question, turn to the good practices linked above, and make sure you follow those steps in order:

1. Define a proper database schema. This is the most important task of all 🤓 
2. Once the database schema is set up, define record types that *reflect* it with high fidelity. There is no point to be smart at this point, because GRDB *serves* the schema :bowtie: 
3. Once those fundamental record types are defined, you're free to do whatever you want with them 😉

**Comment by bikram990** [comment]
Hi @groue,

Thanks for responding to my question.

> True. This actually looks like the simplest solution. What's wrong with it?

There is nothing wrong in this. But the use case I've requires segregation.

> Besides the very simple option of using a single table, here is a third one:

I've already thought of this. I didn't include this in my example as in my use case all the player objects are identical and they will remain identical to each other in future version as well. Choosing Players example might be a wrong example here. I want to achieve abstraction and prevent any possible data leaks between players with this segregation i.e. a Soccer Player should not know that there is Tennis as well. And the Soccer Player's Manager(DAO class for Soccer Players) also would not know anything about Tennis . Only the Sport's Minister(Application) would know there is tennis.

I'm trying to follow the above steps you mentioned. But I'm tied due to my use case. 

With this question I was trying to explore I've missed anything or overlooked any feature in GRDB which could helped me here.

**Comment by groue** [comment]
Thanks for the extra context. It looks like you know where you are going. If you have other questions, feel free to come back!

**Comment by bikram990** [comment]
Thanks for a wonderful library.
