### ISSUE TITLE
How do I make a join from two different databases?

### ISSUE THREAD

**Issue by ahmedk92** [groue/GRDB.swift#597]
Using raw sqlite I could open two database files at once, like: `ATTACH DATABASE path/to/db.sqlite as seconddb`

How can I achieve this with GRDB?

Thanks!

**Comment by groue** [comment]
Hi @ahmedk92,

The topic of attached database has never been addressed yet in GRDB, and it is the first time someone asks about it.

I can give quick advice, based on my limited knowledge of attached databases:

First, just run the raw ATTACH sql query in order to attach a database.

Second, use a single DatabaseQueue for the main database and the attached one(s). This means two things, practically speaking:

- Avoid using several database queues, since they won't be able to guarantee the serialization of database writes, and may throw [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy) errors. If you really need several database queues, set up a [busy handler](https://www.sqlite.org/c3ref/busy_handler.html) with [Configuration.busyMode](http://groue.github.io/GRDB.swift/docs/4.2/Structs/Configuration.html).

- Don't use a database pool, which run in the WAL mode, unless you want to give up atomic commits (see [SQLite documentation](https://www.sqlite.org/lang_attach.html)).

Third, I don't know how well GRDB handles the disambiguation of database tables that have the same name in the main database and its attached databases. If you have such ambiguity, you'll enter uncharted territory.

Please share your experience when you have a working setup, will you?

**Comment by ahmedk92** [comment]
I did this and it worked!
```swift
try! q.write({ db in
  try! db.execute(sql: "attach database '\(OTHER_DB_PATH)' as otherTable")
})
```

**Comment by ahmedk92** [comment]
```swift
try! q.write({ db in
  try! db.execute(sql: "attach database '\(OTHER_DB_PATH)' as otherTable")
})
```

Executing the attach statement inside a write crashes on the iPad 12.9 2nd generation with error: `cannot ATTACH database within transaction`.

Doing it in a `q.read` seems to work:

```swift
q.read({ db in
  try! db.execute(sql: "attach database '\(OTHER_DB_PATH)' as otherTable")
})
```

@groue

**Comment by groue** [comment]
`DatabaseQueue.write` is [documented](https://github.com/groue/GRDB.swift/blob/master/README.md#database-queues) to wrap statements in a transaction. If you want to avoid this transaction, check the [Transactions and Savepoints](https://github.com/groue/GRDB.swift/blob/master/README.md#transactions-and-savepoints) chapter.

**Comment by ahmedk92** [comment]
Thanks! Didn't know about `dbQueue.inDatabase`. That's what I needed. Strange thing though is that crash only happened on iPads.

**Comment by groue** [comment]
Yes, it is strange. Maybe the SQLite version is different?
