### ISSUE TITLE
Subscript 'subscript(_:)' requires that <SomeCodable> conform to 'DatabaseValueConvertible'"

### ISSUE THREAD

**Issue by michaelkirk-signal** [groue/GRDB.swift#598]
You have a helpful example for high performance fetching, using numeric indexes that match the order of Place.databaseSelection, but what if one of the columns is an arbitrary codable struct?

From the README:
```
struct Place: Encodable {
    var id: Int64?
    var title: String
    var isFavorite: Bool
    private var latitude: CLLocationDegrees
    private var longitude: CLLocationDegrees
    
    var coordinate: CLLocationCoordinate2D {
        get {
            return CLLocationCoordinate2D(
                latitude: latitude,
                longitude: longitude)
        }
        set {
            latitude = newValue.latitude
            longitude = newValue.longitude
        }
    }
}

...<snip>

// Fetching methods
extension Place: FetchableRecord {
    /// Creates a record from a database row
    init(row: Row) {
        // For high performance, use numeric indexes that match the
        // order of Place.databaseSelection
        id = row[0]
        title = row[1]
        isFavorite = row[2]
        coordinate = CLLocationCoordinate2D(
            latitude: row[3],
            longitude: row[4])
    }
}
```

You gave an example of a trivial codable property , CLLocationCoordinate2D, which is stored in two integer columns, but what if I have a more complex Codable struct which is stored in a single column, e.g.

```
enum AchievementColor: String, Codable {
    case bronze, silver, gold
}

struct Achievement: Codable {
    var name: String
    var color: AchievementColor
}

struct Place: Encodable {
    var id: Int64?
    var title: String
    var isFavorite: Bool
    var achievements: [Achievement]
}

// Fetching methods
extension Place: FetchableRecord {
    /// Creates a record from a database row
    init(row: Row) {
        // For high performance, use numeric indexes that match the
        // order of Place.databaseSelection
        id = row[0]
        title = row[1]
        isFavorite = row[2]
        achievements = row[3] <-- this fails: "subscript requires that [Achievement] conform to 'DatabaseValueConvertible'".
    }
}
```

It fails because `row[3]` is the encoded representation, which would be (a json string).

I think I could implement `DatabaseValueConvertible' but it seems weird to hardcode assumptions about JSON decoding in an extension to Achievement and (for each Codable struct used similarly). 

Is there a better way?

**Comment by groue** [comment]
Hello @michaelkirk-signal,

There are two answers to your question.

---

First, the decoding itself: how to decode JSON objects with FetchableRecord and `init(row:)`?

In the raw `init(row:)`, you opt out from the automatic decoding provided by Codable records, which includes support for Decodable properties and JSON columns. Instead, you perform manual decoding from a raw row, as described [here](https://github.com/groue/GRDB.swift/blob/master/README.md#column-values).

This manual decoding is based on [DatabaseValueConvertible](https://github.com/groue/GRDB.swift/blob/master/README.md#custom-value-types), the protocol for simple value types that can read raw SQLite values (integer, doubles, strings, and blobs): Data, Date, Int, String etc. DatabaseValueConvertible does not perform JSON decoding.

So you have to create a JSONDecoder, and feed it with Data. Don't miss the [dataNoCopy(atIndex:)](https://github.com/groue/GRDB.swift/blob/master/README.md#data-and-memory-savings) method. You can use it with both text and blobs columns.

---

Now, when you look at the sample code for high-performance decoding, you notice that it accesses row values by their numeric indexes. **The reason why it is fast is that it doesn't perform any string lookup or manipulation.** On top of that, fundamental types like Int, String, Double not only adopt DatabaseValueConvertible, but also [StatementColumnConvertible](http://groue.github.io/GRDB.swift/docs/4.2/Protocols/StatementColumnConvertible.html), another protocol that provides direct access to SQLite C apis.

JSON decoding will add a big overhead, and may ruin the performance gains you are expecting. Be sure to run Instruments in order to check if the optimization is worth it!

**Comment by michaelkirk-signal** [comment]
Thanks for the clarification!
