### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by ueen** [groue/GRDB.swift#607]
Using GRDB gives back escaped strings like this

original string in database: `"something\nThis should be in the next line"`

GRDB gives me this `"something\\nThis should be in the next line"`

This is a issue, cause i want the new line in a label i'm displaying the string in.

Is there a way to fix this?

**Comment by groue** [comment]
Hello @ueen 

Chances are that you misinterpret some problem in your application. GRDB takes great care about preserving database values, including strings, including strings that contain newline characters. **There is absolutely no know issue on this front.**

So... the issue is likely in the application. You're about to enter a debugging session where you have to question your assumptions.

Of course, if you really discover a GRDB issue, reopen this issue. But please take care to come back with some sample code that reproduces the problem, as a proof of your claim.

Thanks in advance.

**Comment by ueen** [comment]
Somewhere in the rercieving is the issue, i dont do anything special, i get a connection just like in the documentation and then i do this

`do {
            try database?.read { db in
                if let row = try Row.fetchOne(db, sql: "SELECT * FROM table WHERE id IN (SELECT id FROM table WHERE someInt=0 ORDER BY RANDOM() LIMIT 1)") {
                    print(row["someString"])
                }
            }
        } catch {
            print(error)
        }`

This is a well tested SQL Statement that does work eg. on Android where i use the same database and `someString` contains newline characters `\n` but the print in Xcode gives me `\\n`
So this if  definitely a GRDB issue or of the underlying functions it relys on!

**Comment by groue** [comment]
@ueen, we won't move forward until you provide a way to reproduce your issue. What about you provide a database file, for example?

**Comment by ueen** [comment]
Appreciate your quick response, heres some Code
[test.zip](https://github.com/groue/GRDB.swift/files/3587024/test.zip)
just run it and you will see what i mean
Heres a screenshot of the initial values in the database
<img width="231" alt="Bildschirmfoto 2019-09-07 um 22 57 17" src="https://user-images.githubusercontent.com/5067479/64480156-e6598d80-d1c2-11e9-9093-2dbd374958c1.png">

**Comment by ueen** [comment]
<img width="1122" alt="Bildschirmfoto 2019-09-07 um 23 19 01" src="https://user-images.githubusercontent.com/5067479/64480334-e909b200-d1c5-11e9-885f-adc9f2aeed1c.png"> some more proof

**Comment by ueen** [comment]
<img width="558" alt="Bildschirmfoto 2019-09-07 um 23 22 41" src="https://user-images.githubusercontent.com/5067479/64480368-849b2280-d1c6-11e9-83a6-f0221d18aa3f.png">
and some more, hope this helps

**Comment by ueen** [comment]
<img width="1011" alt="Bildschirmfoto 2019-09-07 um 23 27 21" src="https://user-images.githubusercontent.com/5067479/64480397-42261580-d1c7-11e9-9140-e94379b2336e.png">
this is also pretty telling

**Comment by groue** [comment]
Great, @ueen, thank you very much.

The included database test.db contains strings that contain backslashes `\` followed by the `n` character. GRDB correctly decodes them as Swift strings made of two characters: a `\` and a `n`, as expected.

Not convinced? Please become so. Open the Terminal app, and open the database with the `sqlite3` command:

```
$ sqlite3 path/to/test.db
sqlite> -- What is stored in the database?
sqlite> select someString from "table";
\n
hello\nnextLine
\n
\n
\n
\n
sqlite> -- Now let's insert a REAL new line
sqlite> insert into "table" (someInt, someString, id) values (1, 'hello
   ...> nextLine', 7);
sqlite> select someString from "table";
\n
hello\nnextLine
\n
\n
\n
\n
hello
nextLine
```

Do you notice how a REAL newline is NOT displayed as `\n`?

Now, if you want to read newline LF characters (10) from the database in your Swift app, then you have two choices:

1. Fix your database: have it contain newline characters, instead of `\` followed by a `n`.
2. Keep `\` followed by a `n` in your database strings, but process the decoded Swift strings in order to convert those sequences into a newline character.

> This is a well tested SQL Statement that does work eg. on Android where i use the same database and someString contains newline characters

Well, maybe does your Android app process raw database strings? I don't know, and I don't really care: What is important is that GRDB is 100% faithful to the data stored SQLite. It does not process raw strings, and will never do. 

The only important fact here is: **your database does not contain newlines**.

**Comment by ueen** [comment]
Well thanks for taking the time, so i guess i was just confused by swifts strange handeling of Strings, as i expected `\n` to the same in the String recieved from the database and in the one i typed in Xcode manually, so apparently Android handles things diffrently...

**Comment by groue** [comment]
Encoding of characters is surely a confusing topic.

That's why, when in doubt, I try to go as close as possible to the source of truth. Here, since we have questions about the data itself, the last word must come from SQLite itself. The `select length(someString) from "table"` is another request that proves that those database `\n` are two characters.

If we have to conclude that Android doesn't decode raw SQLite strings, so be it. But I then feel very, very, very sorry for Android developers. So much useless confusion.

**Comment by ueen** [comment]
Well it does decode raw strings but interprets `\n` as a newline when displayed in a label, if you want actually `\n` to be displayed you would escape like this `\\n`so i guess its kind of the other way round (much like html where `<br>` is interpreted as newline and has to be escaped when it should actually be displayed). Thanks though for explaining this, it was much useless confusion for me, being used to Android and Html :)

**Comment by groue** [comment]
You're welcome @ueen! Happy GRDB, I hope you'll enjoy the library and won't be surprised again :-)
