### ISSUE TITLE
implementing TransactionObserver?

### ISSUE THREAD

**Issue by tanstaafl856** [groue/GRDB.swift#609]
following up on issue #608...
attempted to revert from dictionaies and sectioned tables. still had same low level error, so returned to sevtions and began exploring observer options as suggested.

after melting my brain a couple times trying to absorb ALL the observer info on the readme and linked pages. the combine and rx options don't seem to apply since I'm not using them. after commit seems to require a custom built SQLite which, also, I'm not using. and ValueObservation seems to ONLY cover changing values. I saw no mention of insert/delete. so it seems the lowest level, TransactionObserver, is the only way to go.

I pulled TableChangeObserver from one of the linked pages. xcode [10.2] suggested several changes, all of which were applied. At some point I got an error that lead me to add the TransactionObserverType protocol to TableChangeObserver.

below is a series of various attempt to add an observer with corresponding error msg...I feel like I've missed the snake that's biting me. Any help/point in the right direction would be most appreciated. thnx

         let observer = TableChangeObserver()
       // old syntax...
//        dbQueue.addTransactionObserver(observer)
       // Protocol type 'TransactionObserver' cannot conform to 'FTS5CustomTokenizer' because only concrete types can conform to protocols
        dbQueue.add(tokenizer: TransactionObserver)
        dbQueue.add(tokenizer: TransactionObserverType)
        // Cannot invoke 'add' with an argument list of type '(TableChangeObserver)'
        dbQueue.add(observer)
        // Cannot invoke 'add' with an argument list of type '(UnsafeMutableRawPointer?)'
        dbQueue.add(observationInfo)
        // Instance method 'add(tokenizer:)' requires that 'TableChangeObserver' conform to 'FTS5CustomTokenizer'
        // Instance method 'add(tokenizer:)' requires that 'ValueObservation<Any>' conform to 'FTS5CustomTokenizer'
        dbQueue!.add(tokenizer: ValueObservation<Any>)

**Comment by groue** [comment]
Hello @tanstaafl856,

First, I'm sorry the TableChangeObserver sample code has not been updated in a while. I have to update or remove it.

Second, yes, there is a lot of various observation options - and that's because there's a lot of observation use cases. I'll guide you through below.

Unless I did not understand well your messages, your application wants to display database values in a table view. You thus need to be notified with **fresh values**, on the **main thread**, whenever the database changes.

When such change is notified, you update your table view. Do we agree on that?

Observing such changes can be performed with several tools:

- FetchedRecordsController: an aging API.
- ValueObservation: the "modern" value observation API.
- RxGRDB observables: RxSwift wrappers around ValueObservation.
- GRDBCombine publishers: Combine wrappers around ValueObservation.

The low-level TransactionObserver protocol is the mother of all GRDB observation tools. You can use it, but I would not recommended so. Your app would have to perform a lot of work that is provided by the dedicated value observation tools.

So let's provide a quick sample code, adapted from the stock [ValueObservation usage](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservation-usage) doc. It's very quick and rough: make sure you adapt it for your app.

```swift
class MyViewController: UITableViewController {
    private var observer: TransactionObserver?
    private var sections: ...
    
    override func viewWillAppear(_ animated: Bool) {
        super viewWillAppear(animated)
        
        // Define a ValueObservation which tracks table view sections
        let observation = ValueObservation.tracking { db in
            let dbValues = try fetchSomeDatabaseValues(db)
            let sections = tableViewSections(dbValues)
            return sections
        }
        
        // Start observing the database
        observer = observation.start(
            in: dbQueue,
            onError: { error in /* handle db error */ },
            onChange: { [weak self] sections in
                guard let self = self else { return }
                self.sections = sections
                self.tableView.reloadData()
            })
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        // Stop observing the database
        observer = nil
    }
}
```

**Comment by tanstaafl856** [comment]
awesome! thnx.

I will work with this for a while and see what I can make of it. just a quick confirmation though...

the ValueObservation should raise events for delete [and insert] to be handled prior to the app crashing, allowing for any necessary adjustments to the sections and reload, correct? I'm assuming it's basically an index out of bounds type of error I'm trying to correct

**Comment by groue** [comment]
> the ValueObservation should raise events for delete [and insert] to be handled prior to the app crashing, allowing for any necessary adjustments to the sections and reload, correct? I'm assuming it's basically an index out of bounds type of error I'm trying to correct

ValueObservation tracks changes, insertions, and deletions, yes.

Any out of bounds error you experience happens somewhere in your app because you index an array of oranges with an index of apples. For example, if you fetch/observe database values, and later index them with database values that were fetched later, then you may experience out of bounds errors. That's normal: the database may have changed between the two fetches.

Make sure you *control* which state of the database you are referring to. A GRDB rule of thumb is: **only ever deal with database values that were fetched from a single database access**. A database access is **one** call to `write` or `read`, or **one** value refresh from a database observation.

**Comment by tanstaafl856** [comment]
PROGRESS!
it no longer crashes when I swipe away an item in the table view. now it deletes the first item in section 0 [but does not reflect the change] AND duplicates ALL the items in sections > 0. guessing thats just a side effect of changing so many things and a good cleanup will rectify the remaining issues

ESSENTIALLY, all I needed was to add a var sections = [Entity]() property and these 2 functions to the subclassed UITableView:
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        let observation = ValueObservation.tracking(DatabaseRegion.fullDatabase, fetch: {
            try Entity.fetchAll($0, sql: "SELECT * FROM Entity")
            })
        EntityObserver = observation.start(
            in: dbQueue,
            onError: { error in print("EntityObserver = observation.start ERROR --- investigate further?!?") },
            onChange: { [weak self] sections in
                guard let self = self else { return }
                self.sections = sections
                self.buildDictionaryFromDB(sections)
                //        configureTableView() // called by buildDictionaryFromDB()
                self.tableView.reloadData()
                })
        }
    
        override func viewWillDisappear(_ animated: Bool) {
            super.viewWillDisappear(animated)
            EntityObserver = nil
            }

thnx!

**Comment by tanstaafl856** [comment]
the duplication issue was a simple reset the dictionary when re-reading from the db. but I'm still only ever deleting from section 0. and if section 0 has more items than the section it should delete from, it crashes at the following bit of code.

    override func tableView(_ tableView: UITableView, commit editingStyle: SIPoSTableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        // Delete the Entity
        let Entity = EntityController.record(at: <#T##IndexPath#>)
        try! dbQueue.write { db in
            _ = try Entity.delete(db)
            }
        }

I saw a few referrences to guarantees only when using rowID. how do I change from a FetchedRecordsController type deleting by IndexPath to something deleting by rowID?

**Comment by groue** [comment]
@tanstaafl856

- If you use ValueObservation, stop using FetchedRecordsController. You don't need *two* observation techniques, but only one.
- You call "sections" the array of fetched entities, before grouping them into table view sections. This is very confusing: "section" should mean a table view section, not the full list of items that are splitted into sections.

I'm sure you will figure everything out eventually. Just stay focused, make your bests to *understand* what you are doing, and name things as properly as possible.
