### ISSUE TITLE
'eraseDatabaseOnSchemaChange' behavior with multiple registered migrations. 

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#616]
Salut @groue; 

### What did you do?

So in my code I have set this flag: 
```
// BEWARE: Only for TEST / EXPERIMENTAL version.....
		 
#if DEBUG
	_migrator.eraseDatabaseOnSchemaChange = true
#endif
```

### What did you expect to happen?
According to the documentation, this will *recreate* the schema if the migrator detects a change. I was under the assumption the '_detects a change_' was only applicable for future migrations and not current one...

So If I have applied: 
* _migrate-1_
* _migrate-2_

But not:
* _migrate-3_

I was expecting that when I migrate to _migrate-3_ then the complete database database will be recreated and _migrate-1_ up to _migrate-3_ would be applied. 

### What happened instead?

I changed (by mistake) a column definition in _migrate-1_ and the complete database was re-created. 

Is this the proper behavior ? If so, I will have to adapt during development. 

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.2.1
**Installation method:** CocoaPods
**Xcode version:** 10.2.1
**Swift version:** 4.2
**Platform(s) running GRDB:** macOS

**Comment by michaelkirk-signal** [comment]
Unofficially, I believe this is working as expected and that you've misunderstood the intended behavior.

I use this feature for exactly the behavior you were surprised by.

When I'm first writing a migration, I might have typod the column name or decide I need to add a new column for the record I'm adding. Because the migration has already run (in an earlier form), I need to start the migrations from scratch in order for the migration I'm developing to be able to re-run.

Funny enough, to me the case that you desire actually seems like the one situation in which you might **not** want the migrations to re-run. 

That is, if you already ran migration1 and migration2, and have some data saved in that schema, when you add a new migration3, why would you want to blow away your existing data rather than... migrating... it?

**Comment by martindufort** [comment]
This is how I think it was working:

Run a new migration, flag is true, database is ‘cleared’, all migrations
are ran up to the new one.

FYI: I just added a “.defaults(to: 0)” to a column in an already applied
migration and every was wiped out.

Thanks for the explanation, now understand this is way more “intelligent”
than I assumed.

**Comment by groue** [comment]
Hello both, salut :-)

Michael put it perfectly 👍
