### ISSUE TITLE
More information about SchedulingWatchDog validation

### ISSUE THREAD

**Issue by martindufort** [groue/GRDB.swift#621]
I'm getting this fatal error:
`Fatal error: Database was not used on the correct thread.`

What's the best way to patch the `SchedulingWatchdog` to output the initiating thread versus the offending thread ?

**Comment by groue** [comment]
Hello @martindufort,

The crashing thread is indeed the offending one. I'm not aware of any technique or "patch" that could provide what you need.

If you happen to witness the crash in a debugging session in Xcode, you may be able to see the "cross-queue stack trace" (I don't know how to call it) which reveals the various dispatch queue jumps that lead to the crash.

Anyway, make always sure you never let anything that is db-related (database connections or cursors) escape from a database access method. Those are misuses, and the price is those fatal errors.

**Comment by martindufort** [comment]
Thanks for the reply. I think my question was unclear. 

I was mostly looking for a more explanatory error message, like:

`Fatal Error: Tried to use database on thread 'co.bigwavelabs.ocean.updateStuff' but the connection was initiated on 'GRDB.DataQueue'. ` 

Or something similar...

**Comment by groue** [comment]
> I was mostly looking for a more explanatory error message, like:
>
> `Fatal Error: Tried to use database on thread 'co.bigwavelabs.ocean.updateStuff' but the connection was initiated on 'GRDB.DataQueue'.`

I'm not aware of any way to get the name of the current queue. There is [__dispatch_queue_get_label](https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20160613/002280.html), but the leading underscores are a clear message: don't use it in production!

You may indeed "patch" GRDB so that it uses this name in the fatal error message, if it helps debugging.

The "correct" queue for a database connection has a clear definition but it is not so simple, especially when you code against several databases at the same time. There may be several correct queues. They usually have GRDB in their name, as the debugger will tell you. You can also use [Configuration.label](http://groue.github.io/GRDB.swift/docs/4.4/Structs/Configuration.html) in order to better recognize GRDB queues.
