### ISSUE TITLE
[BUG] [macOS] NSTableView performs wrong animation.

### ISSUE THREAD

**Issue by lastcc** [groue/GRDB.swift#623]
### What did you do?

Updated a property of an object that will cause the order of the table view cells to change.

```swift

user.isActive = false

try! AppDatabase.queue.write { db in
    try user.update(db)
}
```

### What did you expect to happen?

NSTableView to reflect the change of the model correctly and performs correct animation.

onChange was called twice. but the animation is incorrect.

1. ▿ Insertion at [0, 2]
  ▿ insertion : 1 element
    ▿ indexPath : 2 elements
      - 0 : 0
      - 1 : 2

2. ▿ Deletion from [0, 16]
  ▿ deletion : 1 element
    ▿ indexPath : 2 elements
      - 0 : 0
      - 1 : 16

I have managed to manually fix this by changing the code to this: Note the `indexPath.item + 1`

```swift
case .insertion(let indexPath):
    self.tableView.insertRows(at: [indexPath.item], withAnimation: .effectFade)

case .deletion(let indexPath):
    self.tableView.removeRows(at: [indexPath.item + 1], withAnimation: .effectFade)
```

### What happened instead?

Wrong animation and wrong final state of the NSTableView.

The cell above the correct one was animated away instead.

### Environment

**GRDB flavor(s):** Swift 5
**GRDB version:** - GRDB.swift/standard (= 4.3.0)
**Installation method:** COCOAPODS: 1.7.5
**Xcode version:** 11
**Swift version:** Swift 5
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.14.5

**Comment by groue** [comment]
Hello @lastcc,

This issue is a duplicate of #618 by @martindufort, where it appears that FetchedRecordsController handles **UI**TableView and **UI**CollectionView, but not **NS**TableView. In this issue, I explain that I do not plan to add support for NSTableView myself. But I love pull requests.

Now you tell us that a simple post-processing of index paths is enough to gain support for NSTableView.

If have two questions:

- There are two other kinds of change: `update` and `move`. Do you happen to know which post-processing has to be done to them in order to fully support NSTableView? 

- Did you run intensive testing with many kinds of changes, so that we can be reasonably sure that this post-processing is *robust*? I admit I find it odd that in your sample code, it is impossible to delete the first row (at index 0). Something is likely to be off.

I'd be happy to welcome the results of your investigations. If you do not feel like working on this, I suggest you find an alternative and suitable diffing algorithm, as explained in https://github.com/groue/GRDB.swift/issues/618#issuecomment-532989956.

**Comment by lastcc** [comment]
Yes. I'll do some investigations later.

Thank you for your respond!

**Comment by martindufort** [comment]
Your solution won't work as is... NSTableView changes are similar to NSMutableArray contrary to the UITableView changes which are made in batch on a frozen state of the data source. 

Comparison: 
**UITableView** : delete row 1, delete row 2
  - this will actually delete row 1 and row 2

**NSTableView**: delete row 1, delete row 2
  - this will delete row 1, 
  - row 3 will move upward into row 2
  - delete row 2 will actually delete the previous row 3.

AS @groue said, we need to explore a diffing algo (DifferenceKit) and how can make it work with NSTableView...

**Comment by groue** [comment]
For information, @martindufort, @lastcc, I plan to **sunset** FetchedRecordsController in the next GRDB release. It won't be deprecated (you won't get any warning), by I want to clearly express that this class is not planned to be improved in the future. There are many reasons for this sunsetting:

- FetchedRecordsController is almost as old as GRDB itself, as a direct inspiration from Core Data's NSFetchedResultsController. It is limited in its observation features, and difficult to maintain
- There is this NSTableView disappointment
- Its diffing algorithm is not good in terms of performance
- It has never been able to handle sections (useful for UITableView and UICollectionView)

The modern and recommended observation tool is now [ValueObservation](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservation).

**Comment by martindufort** [comment]
Interesting. Thanks for the warning. 

Also I think I discovered a new issue with FetchRecordsController and my .deleteAll test. 
Looks like I was getting 21 `.deletion` callbacks when the table was only containing 20 rows...

Is this possible ?

Anyway, will forge ahead with `DifferenceKit` and `ValueObservation` for my NSTableView implementation.

**Comment by groue** [comment]
> Looks like I was getting 21 .deletion callbacks when the table was only containing 20 rows...
> 
> Is this possible ?

Without a reproducible test case, it is impossible to answer. So far, the diffing algorithm has not shown any bug, though. It is slow, but correct to my knowledge.

**Comment by martindufort** [comment]
OK, lets drop this. Will start integration of `DifferenceKit` and `ValueObservation` today. 
Will report back.
