### ISSUE TITLE
[Question] Fetch aggregate count through 2 relationships

### ISSUE THREAD

**Issue by schveiguy** [groue/GRDB.swift#628]
### What did you do?

I want to fetch an item with a count of subitems, but the subitems are related through an intermediate table.

My structure is roughly as follows (it builds and works for simple queries, I've omitted all the protocols and machinery for brevity):

```Swift
struct Audit
{
    var id : Int64?
    static let rooms = hasMany(Room.self)

    var rooms : QueryInterfaceRequest<Room> {
        return request(for: Audit.rooms)
    }
}

struct Room
{
    var id : Int64?
    var name : String
    var auditId : Int64
    
    static let audit = belongsTo(Audit.self)
    static let photos = hasMany(Photo.self)
    var audit : QueryInterfaceRequest<Audit> {
        return request(for: Room.audit)
    }
    
    var photos : QueryInterfaceRequest<Photo> {
        return request(for: Room.photos)
    }
}

struct Photo
{
    var id : Int64?
    var name : String
    var roomId : Int64
    var uuid : UUID
    
    static let room = belongsTo(Room.self)

    var room : QueryInterfaceRequest<Room> {
        return request(for: Photo.room)
    }
}
```

I know based on docs I can write something to get let's say a list of Audits with a count of how many rooms they have. But how to get a list of Audits with a count of how many Photos total? Do I have to declare a relationship between the Photos and the Audits?

### What did you expect to happen?

Some nifty code to fetch all audits and the number of photos in each audit in one SQL statement.

### What happened instead?

I scratched my head and read the docs, and I'm still confused ;)

### Environment

**GRDB flavor(s):** GRDB ios
**GRDB version:** 4.4.0
**Installation method:** manual
**Xcode version:** 11
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.6

**Comment by groue** [comment]
Hello @schveiguy,

It's good to hear from you again :-)

> I know based on docs I can write something to get let's say a list of Audits with a count of how many rooms they have. But how to get a list of Audits with a count of how many Photos total? Do I have to declare a relationship between the Photos and the Audits?

Yes.

I would declare a **HasManyThrough** association from Audit to Photo, so that I could use the `count` aggregate:

```swift
extension Audit {
    static let photos = hasMany(Photo.self, through: rooms, using: Room.photos)
}

struct AuditInfo: FetchableRecord, Decodable {
    var audit: Audit
    var photoCount: Int
}

let auditInfos = Audit
    .annotated(with: Audit.photos.count)
    .asRequest(of: AuditInfo.self)
    .fetchAll(db)
```

Once defined, a HasManyThrough association behaves just like a regular HasMany: you can fetch associated records, aggregate, filter, etc. I like those associations because they make requests easier to read: in the sample code above, no one cares about rooms, and indeed rooms are out of sight.

The reciprocal association, if you happen to need it, is **HasOneThrough**:

```swift
extension Photo {
    static let audit = hasOne(Audit.self, through: room, using: Room.audit)
    var audit: QueryInterfaceRequest<Audit> {
        return request(for: Photo.audit)
    }
}

let photo: Photo = ...
let audit = try photo.audit.fetchOne(db)
```

**Comment by schveiguy** [comment]
I can respond in more detail later but thanks for the prompt response!

**Comment by schveiguy** [comment]
Hi @groue, sorry for the delay, I was very busy this weekend! I wanted first to say that I really appreciate your promptness and attention to detail. I haven't used GRDB in a long time, and it's really one of the best Swift libraries I've seen. Each time I update, I have to write less and less to get the same results, and more is inferred! I'm really liking the associations.

Now, thank you for the reply and explanation. I was kind of hoping to only have to define the immediate relationship and have the others inferred, but for this application, it's reasonably small, so I can add extra "grandparent" type relationships. I was hesitant on the "HasOneThrough" relationship, because really, it "BelongsToThrough", but if that is the same thing, I suppose it will work!

**Comment by groue** [comment]
Thanks Steven - I'm happy this lib keeps on addressing some needs of fellow developers :-)

> I was kind of hoping to only have to define the immediate relationship and have the others inferred

I actually tried to do it without the grandparent relationship, but the "problem" is that `annotated(with:)` wants types to match: `Room.photos.count` embeds the `Room` type and can't be used to `Audit.annotated(with:)`:

```swift
Audit.annotated(with: Room.photos.count)... // <- won't compile
```

We need a "type-safe" way to jump straight from audit to photos, and... grandparent associations happen to do exactly this.

With a raw SQL snippet we can achieve the same result as the one generated by GRDB, though:

```swift
// SELECT audit.*, COUNT(DISTINCT photo.id) AS photoCount
// FROM audit
// LEFT JOIN room ON ...
// LEFT JOIN photo ON ...
// GROUP BY audit.id
Audit
    .annotated(with: SQLExpressionLiteral(sql: "COUNT(DISTINCT photo.id) AS photoCount"))
    .joining(optional: Audit.rooms
        .joining(optional: Room.photos))
    .groupByPrimaryKey()
```

But at this point one can wonder if such an expression has a net readability advantage over raw SQL (or the grandparent association)... Balance is hard :-)

> I was hesitant on the "HasOneThrough" relationship, because really, it "BelongsToThrough", but if that is the same thing, I suppose it will work!

Yes, it does! HasManyThrough and HasOneThrough are the only two "indirect" associations.

There are only two because we don't want the combinatorial explosion that would happen if all combinations of associations were given a specific name. HasOneThrough can chain any two "to-one" associations (BelongsTo, HasOne, and HasOneThrough - that's nine possible combinations). HasManyThrough can chain any two associations without restrictions (HasMany, HasManyThrough, BelongsTo, HasOne, and HasOneThrough - I'm too lazy to count).

The actual semantics of indirect associations ("belongs to through", "has many through belongs to", "has many through has one through has many"...) only exists in your head (where it is useful). SQL generation itself is only driven by the underlying chain of foreign keys provided by direct associations (BelongsTo, HasOne, and HasMany).
