### ISSUE TITLE
Observation not updating on MacOS 10.15.1 Beta

### ISSUE THREAD

**Issue by technoplato** [groue/GRDB.swift#638]
### What did you do?

Attempted to set up an observation on my iMessage Database

### What did you expect to happen?

Whenever a new record was added to the table (through delivered text or received text), the onChange handler would be called again.

### What happened instead?

The observer is only triggered on the initial load. I must run the application again to see the refreshed records.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:** 4.5.0
**Installation method:** CocoaPods
**Xcode version:** 11.0 (11A420a)
**Swift version:** 5
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) macOS
**macOS version running Xcode:** 10.15.1 Beta (19B68f)

### Demo Project

```swift
//
//  ViewController.swift
//  MessageListener
//
//  Created by Michael Lustig on 10/18/19.
//  Copyright © 2019 lustig. All rights reserved.
//

import Cocoa
import GRDB

struct Message: Decodable, FetchableRecord, TableRecord {
  var text: String?
}

class ViewController: NSViewController {
  private var observer: TransactionObserver?
  
  override func viewDidLoad() {
    super.viewDidLoad()
    let dbQueue = (try?  DatabaseQueue(path: "/Users/lustig/Library/Messages/chat.db"))!
    
    let observation = ValueObservation.tracking { db in
      try Message.fetchAll(db, sql: "SELECT text FROM message ORDER BY ROWID DESC  LIMIT 10")
    }
    
    observer = observation.start(
      in: dbQueue,
      onError: { error in
        
      },
      onChange: { [weak self] (messages: [Message]) in
        // 😢Only triggered on first load, not on subsequent changes to DB.
        let s = messages.map{($0.text ?? "___NONE___")}.joined(separator: "\n")
        print(s)
      }
    }
  }
}


```

**Comment by groue** [comment]
Hello @technoplato,

I'm not running macOS 10.15, even less macOS 10.15 beta, so **I can't help directly**.

But I can try to guide you through an elucidation. So please follow me:

**The first step** is to double check the issue. Do you *really* change the message table? Do you *really* retain the observer for the whole duration of the observation? I mean: make sure you check all your assumptions before looking for an issue in GRDB.

The goal here is that you clearly identify a GRDB issue without any doubt. Ideally you'll reduce the problem to a very very simple app where the maximum of unrelated stuff has been removed.

**The second step** is to report the SQLite version that ships with your version of macOS. Please run those lines from your app that faces observation issues (for example somewhere early in your app delegate):

```swift
let sqliteVersion = String(cString: sqlite3_libversion()!)
let sqliteCompileOptions = DatabaseQueue().inDatabase {
    try! String.fetchAll($0, sql: "PRAGMA COMPILE_OPTIONS").sorted()
}
print("SQLite Version:", sqliteVersion)
print("SQLite Compile Options:", sqliteCompileOptions)
```

The idea here is to check if I can reproduce your issue without installing macOS 10.15.

**The third step** is to clone the GRDB repository, and run the test suite:

1. Clone GRDB
2. Checkout the latest released tag (`v4.5.0`)
3. Open GRDB.xcworkspace with Xcode
4. Select the GRDBOSX scheme
5. Launch tests (Command-U)

Report Xcode version and all tests that fail.

Yes it's a little work for you. And it will be greatly appreciated: maybe we'll find a bug in your app, maybe we'll find a bug in GRDB, maybe we'll find a bug in Xcode, maybe we'll find a bug in macOS beta. Depending on the outcome, the consequences will be very different!

**Comment by technoplato** [comment]
I’m 100% willing not to do all of those steps and am shocked both at how
quickly and how thoroughly you’ve responded.

It might not be today as my wife and I have a fun day of errands planned,
but next time I sit down at my computer will be to run through your
recommendations and to report back.

**Comment by technoplato** [comment]
> Do you really retain the observer for the whole duration of the observation? 

The entirety of my application is pasted above. How could I modify that code to ensure I am retaining the observer throughout the applications runtime?

**Comment by groue** [comment]
> The entirety of my application is pasted above.

:+1: That's crucial information. We'll see where it leads us below.

> How could I modify that code to ensure I am retaining the observer throughout the applications runtime?

Since the view controller holds a strong (non-weak) reference to the observer, the life time of the observer is as least as long as the view controller's - that's plenty of time. A general answer to your question would be... to store it in a global :-) But I'm not sure we need that.

> The entirety of my application is pasted above.

Back to the interesting part of your message. We're still checking our assumptions here, and one of mine has been invalidated :-)

So your app *does not* modify the database.

Hence the modification is performed by another, external, database connection. Do you confirm?

I think I should rewrite this sentence of the [Database Changes Observation](https://github.com/groue/GRDB.swift/blob/master/README.md#database-changes-observation) chapter:

> Database observation requires that a single database queue or pool is kept open for all the duration of the database usage.

I should rewrite it this way (or a better one):

Keep a single single database queue or pool open for the whole duration of your observations. Only modifications performed by this connection are notified. Changes performed by external connections are not.

Before we keep on, will you confirm that the changes are performed by an external connection?

**Comment by technoplato** [comment]
Awesome awesome. That is correct in that my application does not modify the database. The database path corresponds to the Messages application on MacOS. When a new message is sent or received, I can verify that a new record is written to the ‘message’ table. 

I believe that rewrite would be helpful, but is certainly an edge case and I must admit that I didn’t read that much of the documentation. Perhaps it may be relevant in the observation section. 

But yes, I confirm my application is not the one making changes to that database.

**Comment by groue** [comment]
All right. So you did not discover any bug strictly speaking :-)

The use case of observing changes performed by other apps and connections is a valid one. It's just... not very frequent. And I did never personally need it a single time. That's why GRDB does not ship with this feature.

Assuming the new macOS security features allow you to do that, I'd look at **dispatch sources**. They can notify your app whenever specific files or folders are changed.

That's where I would start if I were to add remote observation to GRDB. Your case should be simpler: you'd just need to fetch your new messages or each modification to the database file(s).

**Comment by technoplato** [comment]
Okay awesome I’m going to look into dispatch sources. 

Is that a feature specific to SQLite, MacOS, or something else? Are there any learning resources you’d recommend in particular?

Lastly for now, do you have a buy me a coffee link or a place to donate a few bucks to the project?

**Comment by groue** [comment]
[Dispatch Sources](https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/GCDWorkQueues/GCDWorkQueues.html).

A little more Googling provides more hints, such as https://agostini.tech/2017/08/06/monitoring-files-using-dispatch-sources/

> Lastly for now, do you have a buy me a coffee link or a place to donate a few bucks to the project?

Not yet, so just please talk about GRDB around you! :-)
