### ISSUE TITLE
Hangs in `DatabasePool.asyncConcurrentRead`

### ISSUE THREAD

**Issue by simme** [groue/GRDB.swift#651]
I'm having some issues GRDB hanging in `DatabasePool.asyncConcurrentRead`. It's just sitting around waiting for the semaphore to signal, which it never does.

While debugging and forming this issue I realized the problem goes away if I remove `configuration.targetQueue = queue` from my setup code. So somehow that seems to be creating a dead-lock. I'm creating the queue like this:

```swift
DispatchQueue(
        label: "com.filibaba.pantry",
        qos: .userInitiated,
        attributes: [],
        autoreleaseFrequency: .inherit,
        target: nil)
```

I'll have to admit I don't really know why I created a custom queue. I think I was just experimenting . Since there aren't really any documentation for `targetQueue` I wanted to try to figure out if there were any benefits to doing this.

This is on iOS, using GRDB 4.6.1 and Xcode 11.2.

**Comment by groue** [comment]
Hello @simme,

`asyncConcurrentRead` blocks the writer until a reader is able to establish [snapshot isolation](https://www.sqlite.org/isolation.html). This is the state that guarantees the reader to see the database is the exact state left by the writer. After snapshot isolation has been established, the writer is released, and other writes can happen: the SQLite isolation makes sure they can not mess with the values read inside `asyncConcurrentRead`:

```swift
try pool.writeWithoutTransaction { db in
  try Player.deleteAll(db)
  pool.asyncConcurrentRead { db in
    // Guaranteed 0, even if the fetch is performed *after* the insertion
    try! assert(Player.fetchCount(db) == 0)
  }
  try Player(...).insert(db)
}
```

If Configuration uses a serial target queue, then your app deadlocks: the reader can never start because the target queue is busy waiting for the writer to be released.

The solution to your issue is to provide a concurrent target queue, or set the configuration qos instead of a queue.

**Comment by groue** [comment]
> Since there aren't really any documentation for targetQueue

You're right, the documentation is sparse:

```swift
/// The target queue for the work performed by the database.
///
/// Default: nil
public var targetQueue: DispatchQueue? = nil
```

Well, all database accesses will happen in this queue.

**Comment by simme** [comment]
Thanks,

That makes sense. I figured this was probably working as intended and I was doing something wrong. But wanted to raise a flag just in case. :)

**Comment by simme** [comment]
Would it be possible to add an assertion that the queue is concurrent? Or at least add a note to the docs that the queue has to be concurrent?

**Comment by groue** [comment]
> Would it be possible to add an assertion that the queue is concurrent?

Is it possible?

> Or at least add a note to the docs that the queue has to be concurrent?

Definitely!

**Comment by simme** [comment]
> Database queues can use a serial queue fine.
Oh maybe I misunderstood then. Or maybe it only applies to `DatabasePool`? Not `DatabaseQueue`.

**Comment by groue** [comment]
See above commit for the improved (I hope) documentation.
