### ISSUE TITLE
Fetching rows from two different record types together.

### ISSUE THREAD

**Issue by alivepool** [groue/GRDB.swift#671]
### What did you do?

I have two records r1, r2 who have an association to another record/s through mapping records. 
I am trying to fetch these two different types of Records together. 
I am not able to frame query interface for this case. I am expecting something similar to 'UNION ALL'.

### What did you expect to happen?

I am expecting to get values from these two records together along with their respective associations.

### What happened instead?

I am not able to frame the query. How to achieve this in GRDB, I am not able to wrap my head around that.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.6.2
**Installation method:** Swift Package Manager
**Xcode version:** 11.3
**Swift version:** 5.1.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.6

**Comment by groue** [comment]
Hello @alivepool,

Since it looks like you want to use `UNION ALL`, don't spend time looking for a solution in the query interface of associations. There is no UNION ALL there. GRDB never generates this SQL operator.

Instead, I suggest you solve your issue directly at the SQL level. Design your SQL query with the usual care, design a record type that can decode its results, and you'll be good to go.

**Comment by alivepool** [comment]
Will do it with SQL then.

Thanks @groue !!
