### ISSUE TITLE
sql sorting data based on time string

### ISSUE THREAD

**Issue by sameer4** [groue/GRDB.swift#686]
### What did you do?

I used **IncompleteAnswers.CodingKeys.answertime.desc** for sorting data based on time(time here is in string).

### What did you expect to happen?

sort correctly based on time

### What happened instead?

wrong sorting result as it's in string

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.9.0
**Installation method:** CocoaPods
**Xcode version:** 11.3.1
**Swift version:** 5.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.2

### Demo Project

After searching i came across [CONVERT](https://www.w3schools.com/sql/func_mysql_convert.asp) and [STR_TO_DATE](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_str-to-date) keywords.I just wanted to know if they are supported in **SQLExpressible.** or do i have to apply raw query?

**Comment by groue** [comment]
Hello @sameer4,

> I used IncompleteAnswers.CodingKeys.answertime.desc for sorting data based on time(time here is in string).
>
> *What did you expect to happen?*
>
> sort correctly based on time
>
> *What happened instead?*
>
> wrong sorting result as it's in string

I'm surprised that you get wrong sorting results.

By default, GRDB stores dates in the `YYYY-MM-DD HH:MM:SS.SSS` format, which gives the expected sorting result, even though dates are stored as strings:

```
2019-01-01 00:00:00.000
2019-12-06 00:00:00.000
2019-12-07 00:00:00.000
2020-01-10 12:00:00.000
2020-01-10 12:01:00.000
```

(This format was chosen *precisely* because it allows natural sorting.)

Now maybe your database uses a different string format for dates, a format which can not be used for sorting dates? I don't know, so I can't really provide further advice.

**Comment by sameer4** [comment]
Ok my bad.in my query, i was sorting with date too but in results comparison i was looking at time only. sorry
