### ISSUE TITLE
App extension not notifying app when database changes

### ISSUE THREAD

**Issue by DennisDreissen** [groue/GRDB.swift#702]
### What did you do?

I am trying to access the database from a shared container, both in the app and the app extension. I managed to fix the locking errors by following the documentation here:
https://github.com/groue/GRDB.swift/blob/master/Documentation/AppGroupContainers.md
The next problem I am facing is getting the database observers in my app being notified when the app extension makes changes. I have implemented the CFNotificationCenterGetDarwinNotifyCenter and the notifications are being received in the app, but I don't know what I should do/call to update the database observers. In CoreData I would probably do something like viewContext.refreshAllObjects(). I am using RxGRDB to observe database changes.

### What did you expect to happen?

When the app extension makes changes in the database, my rx observers in the app should be notified.

### What happened instead?

The observers are not notified.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.5.0
**Installation method:** CocoaPods
**Xcode version:** 11.2.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.14.6

**Comment by groue** [comment]
Hello @DennisDreissen,

Thanks for the detailed report. So you manage to notify the main app process of changes performed by the extension, thanks to Darwin notifications. But you don't quite know how to get fresh values in the app.

---

First, let's fix an incorrect assumption.

> When the app extension makes changes in the database, my rx observers in the app should be notified.

Well, no.

RxGRDB currently documents the [following promise](https://github.com/RxSwiftCommunity/RxGRDB/tree/v0.18.0#database-observation):

> 1. RxGRDB notifies changes that have been committed in the database. No insertion, update, or deletion in tracked tables is missed. This includes indirect changes triggered by foreign keys or SQL triggers.
>
> 2. To function correctly, RxGRDB requires that a unique database connection is kept open during the whole duration of the observation.

The first sentence makes a pretty strong guarantee, which is that ALL committed changes are notified. Some users rely on this. We can't break this promise without introducing bugs in some apps.

Since your app has two processes accessing the database, you have at least two connections: you break precondition (2). Hence you don't get (1). Some changes are not notified. As documented.

---

Your solution is to restart your observations afresh when the app gets a remote Darwin notification.

Since you are using RxGRDB, why not use RxSwift in order to build an observable of received Darwin notifications?

Let's start from your existing code, which may look like:

```swift
import RxGRDB

func makeSomeObservable() -> Observable<SomeValue> {
    let request = ...
    return request.rx.observeAll(in: dbQueue)
}

makeSomeObservable().subscribe(onNext: { _ in
    print("Fresh value!")
})
```

You can use a BehaviorRelay which is notified of remote change notifications:

```swift
import RxGRDB
import RxRelay

// A relay which notifies of remote changes
let remoteChanges = BehaviorRelay<Void>(value: ())

// CFNotificationCenter callback
func remoteChangesCallback(...) {
    // kick the remoteChanges relay
    remoteChanges.accept(())
}

func makeSomeObservable() -> Observable<SomeValue> {
    // Restart the database observation for each remote change
    return remoteChanges.flatMapLatest { _ -> Observable<[SomeValue]> in
        let request = ...
        return request.rx.observeAll(in: dbQueue)
    }
}

makeSomeObservable().subscribe(onNext: { _ in
    print("Fresh value!")
})
```

**Comment by DennisDreissen** [comment]
Hello @groue!

Thank you for the quick reply. I was aware that breaking one or more of the rules would also have an impact on the promises GRDB makes. Unfortunately having writes/reads from another process is something that we really needed.

You proposed solution works perfectly!  Thans again for helping me out, keep up the good work with the project! :-)

**Comment by groue** [comment]
You're welcome, @DennisDreissen! Your feedback about shared databases is very much welcome, because I don't have much experience with them myself. Writing the "Sharing a Datatase in an App Group Container" Guide was interesting, but it only scratches the surface.

As you see, there is room for improvements in the area of database observation. Having a documentation which does not lie is good, but solving common problems is even better: I'm keen to listening to suggestions that can help the lib move forward.

I also want to remind the recent article by Brent Simmons: https://inessential.com/2020/02/13/how_we_fixed_the_dreaded_0xdead10cc_cras. Your own experience with `0xdead10cc` will be appreciated.

Meanwhile, sometimes things just work ™ :-) Happy GRDB!

**Comment by AKoulabukhov** [comment]
Would be nice to have the solution inside the lib :) Quite common case when app extensions can help users to add some info to database quickly (e.g. Share extension), so the app wants to be notified.

**Comment by groue** [comment]
Hello @AKoulabukhov. "Sharing a database" is [difficult](https://swiftpackageindex.com/groue/grdb.swift/v6.6.0/documentation/grdb/databasesharing), and must remain uncommon, on the contrary. This does not mean observations should not work cross-process, of course. I'd look at a robust pull request with a high interest, including the technique for testing such a setup. Happy 2023!

**Comment by aehlke** [comment]
@AKoulabukhov did you ever settle on a good pattern here or is using the above working out well? Thanks
