### ISSUE TITLE
Using a newer version of SQLite than what is included with macOS or iOS

### ISSUE THREAD

**Issue by gennaios** [groue/GRDB.swift#704]
### What did you do?

I am aware of Custom SQLite Builds though I am wondering if one simply wants to use the newest build of SQLite, is there a simpler method such as merely adding the SQLite CocoaPod or swiftlyfalling/SQLiteLib and with just that step, GRDB will automatically use the linked version ? I haven't tried SQLiteLib though from adding https://github.com/clemensg/sqlite3pod to my project, e.g. :

```
  pod 'sqlite3', inhibit_warnings: true
  pod 'sqlite3/fts5'
  pod 'sqlite3/stat4'
```

it seems to work. Maybe such is not included in the docs for some reason that I am unaware of, but from what I can tell, maybe such steps is sufficient.

### Environment

**GRDB flavor(s): GRDB
**GRDB version: 4.9.0
**Installation method: CocoaPods
**Xcode version: 11.3.1
**Swift version: 5.1.x
**Platform(s) running GRDB: macOS
**macOS version running Xcode: 10.15.3

**Comment by groue** [comment]
Hello @gennaios,

I understand the request. For example I remember the CocoaPod technique described [here](https://github.com/CocoaPods/CocoaPods/issues/9104) (look for Podfile in the first comment).

However I did never attempt at *packaging* anything. You'll think that I'm lazy, and you'll be totally right. However, I'll happily support anyone that would explore this area.

Currently, GRDB not only supports custom SQLite builds, but also *enables* extra features and optimizations. You'll have to explore GRDB source code in order to find out where (look for GRDBCUSTOMSQLITE, SQLITE_ENABLE_FTS5, SQLITE_ENABLE_PREUPDATE_HOOK, etc.).

We have to make sure those extra features remain enabled when available. And of course we should not break anyone's existing installation.

This may well be a lot of work. Of course, I won't be offended if you do not contribute back, and keep your own setup for you.

**Comment by gennaios** [comment]
Understood. Perhaps they indeed work by merely adding the CocoaPods but testing is required, and as such, it hasn't been documented. As mentioned, I merely added the sqlite3 pod and it seems to work, though I use only FTS5. Perhaps at a later date I can help with testing. For now, feel free to close this issue as you may not wish to test such at the moment and I may not get around to it for a while. I will report back if I find any issues.

**Comment by groue** [comment]
Sounds good to me! Thank you, @gennaios.
