### ISSUE TITLE
Value unexpectedly Double

### ISSUE THREAD

**Issue by crenelle** [groue/GRDB.swift#717]
### What did you do?

I run Row.fetchOne to get a single row from a table in a sqlite db.
I copy the row to a dictionary [String:Any] without converting DatabaseValues.
I grab a particular entry in the dictionary by name to get to the value, and attempt to convert the value from the DatabaseValue to a Decimal(2,1).

### What did you expect to happen?

According to the DB Browser for SQLite app for macOS, the column is defined to be Decimal(2,1) and the value therein is stored as Text/Numeric, with the actual data being stored as chars. I look at the characters and can view them in hexadecimal, so I expected (in order for the format and precision to be maintained to be handed the value as a string in order to initialize the var as a Decimal.

## What happened instead?

The value arrives via DatabaseValue as Double.

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:**
GRDB for Swift v 4.10.0

**Installation method:** (CocoaPods, SPM, manual?)
Swift Package installer

**Xcode version:**
Xcode 11.4 Beta 3

**Swift version:**
Swift 5.2

**Platform(s) running GRDB:** (iOS, macOS, watchOS?)
macOS

**macOS version running Xcode:**
macOS 10.15.3

**Comment by groue** [comment]
Hello @crenelle,

You are seeing a `Double` DatabaseValue because what SQLite actually stores in this row is a Double value. There's no doubt about this fact.

It is time to read [Datatypes In SQLite Version 3](https://www.sqlite.org/datatype3.html) thoroughly.

SQLite can only store values of five types: integers, reals, texts, blobs, and nulls. There is no support for proper decimals.

When we run the `sqlite3` command in a unix shell, we can see how decimal columns are handled:

```
$ sqlite3 
sqlite> -- Create a table with a DECIMAL(2,1) column
sqlite> CREATE TABLE t(id INT PRIMARY KEY, value DECIMAL(2,1));
sqlite> -- Insert values of different types
sqlite> INSERT INTO t VALUES (1, 1);
sqlite> INSERT INTO t VALUES (2, 2.0);
sqlite> INSERT INTO t VALUES (3, 2.1);
sqlite> INSERT INTO t VALUES (4, '3.0');
sqlite> INSERT INTO t VALUES (5, '123.456');
sqlite> INSERT INTO t VALUES (6, '-4e1');
sqlite> INSERT INTO t VALUES (7, '20 small cigars');
sqlite> -- Check the actual types of stored values
sqlite> SELECT *, typeof(value) FROM t;
1|1|integer
2|2|integer
3|2.1|real
4|3|integer
5|123.456|real
6|-40|integer
7|20 small cigars|text
```

See how:

- We could insert integer, double and text literals in the `value` column.
- The `value` column contains heterogeneous values of various types.
- Row 5: `123.456` is fully stored despite the `DECIMAL(2,1)` column type.
- Row 5, 6, 7: texts are converted to numeric values, but only when possible.

This is how SQLite handles the `DECIMAL(2,1)` type. And this explains why you are seeing a DatabaseValue whose storage is Double:

```swift
try DatabaseQueue().write { db in
    try db.execute(sql: """
        CREATE TABLE t(id INT PRIMARY KEY, value DECIMAL(2,1));
        INSERT INTO t VALUES (1, 1);
        INSERT INTO t VALUES (2, 2.0);
        INSERT INTO t VALUES (3, 2.1);
        INSERT INTO t VALUES (4, '3.0');
        INSERT INTO t VALUES (5, '123.456');
        INSERT INTO t VALUES (6, '-4e1');
        INSERT INTO t VALUES (7, '20 small cigars');
        """)
    
    // Prints:
    // - int64(1)
    // - int64(2)
    // - double(2.1)
    // - int64(3)
    // - double(123.456)
    // - int64(-40)
    // - string("20 small cigars")
    let rows = try Row.fetchAll(db, sql: "SELECT * FROM t")
    for row in rows {
        let dbValue: DatabaseValue = row["value"]
        print(dbValue.storage)
    }
}
```

Do you have further question?

**Comment by groue** [comment]
No news is good news!
