### ISSUE TITLE
Saving an emoji inside a utf16le-encoded database

### ISSUE THREAD

**Issue by riccardo-lomazzi** [groue/GRDB.swift#735]
### What did you do?
I'm trying to save some user input data inside an NVARCHAR column in a DB. 
The data is stored in a String, which is then saved on the DB by using a `PersinstanceContainer`
The databse encoding, as indicated by the command `PRAGMA encoding` is `utf16le`.

### What did you expect to happen?
I expected the emoji to be stored in the db with the correct encoding...

### What happened instead?
...however, when I open it with `DB Browser for SQLITE` is saved as '??'.
How can I choose the correct encoding?

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?)
**GRDB version:** 4.6.2
**Installation method:** CocoaPods
**Xcode version:** 11.3.1
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Catalina 10.15.3

**Comment by groue** [comment]
Hello @riccardo-lomazzi,

GRDB currently ignores the database encoding, and feeds SQLite with UTF-8 encoded strings.

But SQLite does store those strings as UTF-16 in the database, as proven by the sample code below. Even if it does not use records and `PersistanceContainer`, it triggers the same GRDB fundamentals:

```swift
try! DatabaseQueue().inDatabase { db in
    try db.execute(
        sql: """
            PRAGMA encoding = 'UTF-16le';
            CREATE TABLE t(name);
            INSERT INTO t VALUES (?);
            """,
        arguments: ["😀"])
    
    // Prints:
    // - 3DD800DE
    // - 😀
    try print(String.fetchOne(db, sql: "SELECT hex(name) FROM t")!)
    try print(String.fetchOne(db, sql: "SELECT name FROM t")!)
}
```

Compare with an UTF-8 database:

```swift
try! DatabaseQueue().inDatabase { db in
    try db.execute(
        sql: """
            PRAGMA encoding = 'UTF-8';
            CREATE TABLE t(name);
            INSERT INTO t VALUES (?);
            """,
        arguments: ["😀"])
    
    // Prints:
    // - F09F9880
    // - 😀
    try print(String.fetchOne(db, sql: "SELECT hex(name) FROM t")!)
    try print(String.fetchOne(db, sql: "SELECT name FROM t")!)
}
```

See how 😀 is [properly](https://graphemica.com/😀) stored as 3DD800DE, or F09F9880, with due respect for the database encoding, as well as properly decoded.

The fact that GRDB feeds SQLite with UTF-8 encoded strings *can* decrease GRDB performances, because SQLite has to perform the encoding conversions.

But it *can not*, as far as I understand, corrupt your database in any way.

> ...however, when I open it with DB Browser for SQLITE is saved as '??'.

I suspect DB Browser to handle utf16le-encoded databases improperly. This issue belong to them, unless you provide a positive evidence that GRDB is doing something wrong.

**Comment by groue** [comment]
> I suspect DB Browser to handle utf16le-encoded databases improperly. 

I didn't have to search a lot:

https://github.com/sqlitebrowser/sqlitebrowser/issues/956

Happy GRDB!

**Comment by riccardo-lomazzi** [comment]
I apologize for the opening of this issue, I've found that the encoding is totally unrelated to my problem a server I was sending the database to was giving me back the database with the wrong character encoding. Actually, before sending it to the server, DB Browser gives me the correct encoding with visibile emojis.
Again, I'm sorry for not testing this enough before opening a ticket.

**Comment by groue** [comment]
It's OK, @riccardo-lomazzi, don't apologize. Your question was very welcome.

Not only this topic is uneasy to deal with, because one needs a serious deal of knowledge in order to find out where to look at. Not all users can find out.

I was myself not quite sure how GRDB was dealing with non-UTF8 databases. Now I know, and this issue can be reused as a reference.

Future users who face an encoding-related issue may find this issue on Google, and be hinted towards a faster solution.

So, really, be relaxed. I love to see how wild users can be, I love to see how SQLite is a rock-solid db engine, and as everybody, I love to see problems solved.
