### ISSUE TITLE
Undo support for record properties

### ISSUE THREAD

**Issue by rpoelstra** [groue/GRDB.swift#786]
Hi,

This is actually a follow-up question on issue 374, specifically this comment:
https://github.com/groue/GRDB.swift/issues/374#issuecomment-398606906

I'm basically having the same problems as the OP, where I've a document based application that needs undo support. I used roughly the same solution of two databases but I don't keep the shadow copy in memory as I want to use DatabasePools.
For undo support of top level records I use the solution as outlined in the above mentioned comment.
What I'm struggling with is undo support for changes to properties of such records.

I've an NSOutlineView (with view controller) that shows the records and it has checkboxes on each row that toggles the 'enabled' property of the corresponding record. This change should also be 'undo-able'.

I've been thinking on adding functions to the document that update the database, much like in the mentioned comment, but this would put the document in charge of the database, not the record. (Technically it would still be the record, but just creating a record to write to the database doesn't feel good).
On the other hand I can just set the property on the record and save it, but how is the undo manager going to find out? And more important/complex, on undo, how are the actions going to get recorded for redo?

If it's any important: I'm using structs for my record types (for the more Swifty feel and solve uniqueness issues), so it makes no sense to register a record with the undo manager, as it will be a different record by the time it will undo/redo.

Do you have more experience with undo situations like these?

Thanks in advance.

Kind regards,

Remco Poelstra

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.0-beta
**Installation method:** manual
**Xcode version:** 11.5
**Swift version:** 5.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 10.15.4

**Comment by groue** [comment]
Hello @rpoelstra,

It's been a long time I've been playing with undo: I haven't learned much since the issue you are linking to.

I'm not sure I understand this sentence of yours, though:

> I've been thinking on adding functions to the document that update the database, much like in the mentioned comment, but this would put the document in charge of the database, not the record. (Technically it would still be the record, but just creating a record to write to the database doesn't feel good).

My "gut feeling" is that performing database changes through the document is probably the way to go. Only the document can handle both simple changes (such as updating the `enabled` property of one record) and complex changes (batch updates, complex inserts, etc.) in a consistent manner.

```swift
try document.setEnabled(true, forRecordId: 42)
try document.doSomeComplicatedStuff(name: "foo", height: 45)
```

I mean that when the app has to perform some modification, it's easier when there is a single rule which is : "grab the doc and ask it to perform the change".

From this simple rule:

- You can derive undo, since the doc has access to the UndoManager.
- You can hide the database (pool/queue) in the Document, preventing any other component of you app from performing changes that are not visible to the Document/UndoManager.
- You can have an equivalence between "database transaction" and "undoable action", which is (often) the desired granularity of undo. You get the guarantee that the UndoManager travels through a line of consistent database states (and crashes can't mess up with your db).

What makes you feel something different? Any theoretical, or practical problem? We can discuss both.

**Comment by rpoelstra** [comment]
Hi @groue,

This is indeed the setup I'm thinking to implement, but I'm feeling a bit uneasy for two reasons: The question you ask in 'GoodPracticesForDesigningRecordTypes': "who is saving books in the database?" has now to be answered with "it depends". It's either the record type itself, or the document, depending on what you do.
The second problem is that I want to integrate AppleScript support. This API (from a user perspective) normally follows an OO model, where properties are set on the objects and they do 'The Right Thing'. This contradicts with the requirement to ask the document to do the magic and have all records to be basically read-only. I can of course duplicate the model layer with a more object oriented design just for the script API, which would then call into the document. But this brings back the uniqueness problems and the need to keep these objects up to date with the database. The exact same problem I'm trying to prevent by using structs in the main model.

**Comment by groue** [comment]
> The question you ask in 'GoodPracticesForDesigningRecordTypes': "who is saving books in the database?" has now to be answered with "it depends". It's either the record type itself, or the document, depending on what you do.

First, thanks for having read this doc. I'm sorry the sentence about responsibility opens a door for misinterpretation.

Until I figure out a better wording, consider this snippet of code:

```swift
// 1. Open db transaction
try dbPool.write { db in
    // 2. Insert an Author
    let shakespeare = Author(name: "Shakespeare")
    try shakespeare.insert(db)
    // 3. Insert a Book
    try shakespeare.addBook(title: "Romeo & Juliet")
}
```

We have three distinct responsabilities here:

1. opening a database transaction (or generally speaking, accessing the database queue/pool and deciding what to do during this isolated database access).
2. inserting a row in the authors' table
3. inserting a row in the books' table

The snippet shows that:

- ✅ (1) something which is not an Author decides to access the database (it would be our Document in your application)
- ✅ (2) an instance of the Author type inserts into the author table.
- 🔴 (3) an instance of the Author type inserts into the book table.

The GoodPracticesForDesigningRecordTypes guide attempts at avoiding (3).

But (1) is normal. A single record instance is not able to understand the database as a whole, and thus can't decide when database transactions must be opened. This is covered with more details in the [How to Design Database Managers](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md#how-to-design-database-managers) chapter of the Good Practices guide.

I'll have to rewrite the responsibility paragraph in order to make this more clear.

---

> The second problem is that I want to integrate AppleScript support. This API (from a user perspective) normally follows an OO model, where properties are set on the objects and they do 'The Right Thing'. This contradicts with the requirement to ask the document to do the magic and have all records to be basically read-only. I can of course duplicate the model layer with a more object oriented design just for the script API, which would then call into the document.

OMG it's been even longer I haven't played with OSA and Apple Events 🤣

Let's play a thought experiment with Core Data. An simple NSManagedObject can indeed handle an Apple event, thanks to uniquing, Key-Value-Observation (KVO), and in-memory object graph.

- Uniquing make it sure the managed object is the only one that should handle the event.
- KVO, NSArrayController, etc allows views to get automatically refreshed.
- The managed object does not need to save its managed object context (which it does not know) in response to the Apple event.

With GRDB and record structs, we lose on all three:

- There can't be any "uniquing" for structs, so no record is ever the "natural" recipient for an event.
- There is no KVO, so the view can't update itself.
- Struct changes have to be persisted in the shadow database (but a record does not know its database pool)

Woot 😅 

Yes, I think the only available conclusion today is that Apple events have to be handled by the document as well.

**Comment by rpoelstra** [comment]
Thanks for your detailed answer.
It indeed seems that the document should have functions to handle all database access and have the records to be simple read-only containers. I might as well make all their properties 'let' constants.
I'll dive a bit deeper in the AppleScript interface on how I can best handle these properties with read-only structs. I'll report back, but it will take some considerable time.

**Comment by groue** [comment]
Thank you for asking! This is a topic which is not often addressed, with sharp angles, as you can see. I and other users will be very glad to read your follow-up. We may even derive some desirable changes or additions to the GRDB apis: but we'll only know after we have a reference implementation which handles all the warts that happen in real-life applications. Your open discussion is already a much welcomed contribution!

**Comment by groue** [comment]
> it will take some considerable time

So I'll close this issue. Just reopen at will!

**Comment by rpoelstra** [comment]
It took me less time than I expected, but it's quite doable to subclass the default script commands (even the intrinsic get and set).

From the `execute()` function it's possible to inspect the specifiers and check whether they are ones that should go to the database. If so, they can be decoded and handled at will, if not, `super`'s implementation can be called to handle all the rest.

Decoding the specifiers requires quite a lot of unreadable code, but it's certainly possible.

I haven't fully implemented it yet, but it seems to be working enough to look into the other architectural issues of converting to GRDB.
