### ISSUE TITLE
External storage of blobs

### ISSUE THREAD

**Issue by groue** [groue/GRDB.swift#79]
Quoting [SQLite documentation](https://www.sqlite.org/intern-v-extern-blob.html):

> If you have a database of large BLOBs, do you get better read performance when you store the complete BLOB content directly in the database or is it faster to store each BLOB in a separate file and store just the corresponding filename in the database?

How can we improve GRDB from this page? What does it take to provide robust support for external storage?

**Comment by xu460313557** [comment]
I also have same question too, seems [FMDB](https://github.com/ccgus/fmdb) can store NSMutableArray in Swift to use generic, hopes that GRDB can support it too.

**Comment by groue** [comment]
Hello @xu460313557,

GRDB can already store any valid value (Bool, Int, String, Data, Date, Swift enums, etc.). See documentation about [values](https://github.com/groue/GRDB.swift#values).

For complex structures like arrays and dictionaries, you can convert them to and from Data with [NSKeyedArchiver](https://developer.apple.com/documentation/foundation/nskeyedarchiver)/[NSKeyedUnarchiver](https://developer.apple.com/documentation/foundation/nskeyedunarchiver), or [JSONSerialization](https://developer.apple.com/documentation/foundation/jsonserialization), or any serialization technique you want to use.

This issue is about another topic entirely: the question is to avoid storing large data blobs in the database, but in external files instead. This may improve performance in some cases: see [Internal Versus External BLOBs in SQLite](https://www.sqlite.org/intern-v-extern-blob.html).

**Comment by groue** [comment]
Let's close this one. It seems that nobody needs this.

**Comment by pocketpixels** [comment]
Just found this via Google and just wanted to say I would definitely would love such a feature in GRDB. The feature being automatically storing large blobs of data in the filesystem, managed and referenced by GRDB (similar to Core Data's External Storage support, but hopefully more reliable). 
I am working with images and movies which tend to be way larger than 100KB (the threshold mentioned in the linked SQLite docs), so storing them directly in the database seems like a bad idea. Of course I can (and will) manage the files myself and store paths in GRDB, but a feature handling this automatically would be lovely.

**Comment by groue** [comment]
Hello @pocketpixels,

> Of course I can (and will) manage the files myself and store paths in GRDB, but a feature handling this automatically would be lovely.

Please share your techniques and the difficulties you have gone through when you're ready!

**Comment by pocketpixels** [comment]
Will do.

**Comment by BrianHung** [comment]
@pocketpixels Did you ever find a way to easily store images externally but also work with GRDB? Currently looking into migrating from SwiftData to GRDB after stubbing my toes on too many unsolved problems; SwiftData has an external storage flag which makes it easy to store blobs, and is the last thing I would need as a feature. Thanks!

**Comment by Jnosh** [comment]
@BrianHung It requires a bit more work than SwiftData but you can store external files by building on top of SQLite/GRDB.

At the most basic level you simply need to store some identifier you can later use to retrieve the file. 

For example, if you have a fixed (application private) folder where you store files (for a particular entity), you could use UUIDs to name the files and then store the UUID in the table referencing the file (optionally alongside a second column for the file type if you have multiple file types).

Most of the complexity is in providing similar reliability to data stored in the database itself.
SQLite (by default) ensures that transactions either fully succeed or otherwise fail but SQLite doesn't know about the external files so we can end up with dangling files or records referencing nonexistent files.

## Copy then insert

If you move/copy the file into place before inserting the record, yoz would need to at least remove the file again if the insertion transaction fails. But even doing so, an application or OS crash could leave you in a state where you added the file but not the DB record leading to a dangling file taking up disk space.

This can be mitigated by, for example, removing any files that don't have a corresponding DB record at application startup. That works but requires checking every single file at launch.

Copying the file during the transaction that inserts the record ends up being roughly equivalent to this case as well. It doesn't help fix this issue and just makes the write transaction a lot slower without any benefit.

## Insert then copy

Moving/copying the file after inserting the record can cause the opposite issue where the record was inserted but the application crashed before copying/moving the file into place. 

You would need to handle this by, for example, removing records without corresponding files, asking the user to supply the file again, recreating/redownloading a cached file, etc. Often this kind of check can be delayed until the file is actually needed and doesn't need to be done every time the application is launched.

Missing files might also be a condition you need to handle anyway. Files could in theory go missing at any time due to file system corruption (very unlikely) or a user modifying application private files (very unlikely on say iOS, unlikely on desktop). So if you have logic to handle this anyway, that might also be used to handle missing files due to crashes or logic issues.

## Using two transactions

If you want avoid both dangling and missing files due to crashes, you can achieve that by adding the record referencing the file over two transactions. This is a bit more complex but ensures that the file and record are either both present or both missing.

First you write a temporary entry referencing the file in a first transaction. Then you copy/move the file into place. And finally you perform a second transaction that creates the final record and removes the temporary record.

Crashing during the first transaction is harmless. If the second transaction commits succesfully the file must be available. And if the application crashes after the first transaction committed but before the second one did, the temporary record is available to clean up the dangling file.

This also requires cleaning up dangling files during application startup but using this approach you don't need to check every single file and only need to select any temporary records that still exist at launch (usually zero) and remove the corresponding file (if it exists) before removing the temporary record itself.

The temporary records can be stored in a dedicated table. Or you can reuse the table storing the final records by having some way to distinguish temporary and regular records. This can be as simple as a column storing a boolean value for this purpose.

**Comment by groue** [comment]
👍 Very excellent overview

I'll just remind that small images can probably fit directly in the database ([Internal Versus External BLOBs in SQLite](https://www.sqlite.org/intern-v-extern-blob.html)).

In many apps I've worked on, I've successfully applied the "Copy then insert" technique described above (including the startup cleaning).

**Comment by BrianHung** [comment]
Thanks for the extensive run-down on attaching external files to SQLite 😊 
I'll try the copy-then-insert approach. So far building with GRDB has been more enjoyable than SwiftData with the benefits of data portability!

**Comment by pocketpixels** [comment]
> @pocketpixels Did you ever find a way to easily store images externally but also work with GRDB?

Sorry, yes, I never followed up back then. Probably because I didn't feel like my implementation was particularly clean and principled. 

I also used the copy-then-insert approach, and checked for and deleted any orphaned files on app startup. 
I created a `DBManagedFile` `Record` subclass that had initializers that copied or moved files (or wrote a `Data` object) to the dedicated folder and represented it with a database entry in a dedicated table. And then had an associated `DBManagedFileManager` that did the orphan check on startup and also used a database observation to detect any deletions of `DBManagedFile` records and would delete the associated files. My implementation would keep all such file records in memory and diff it against observed new `fetchAll` request results to determine the deleted files. This of course wouldn't scale to huge file collections, and there probably is a better way of doing it. But it worked fine for my needs.

**Comment by pocketpixels** [comment]
Also yes, I would choose GRDB over SwiftData every time. After so many years of waiting for a new "Swift-ier" data persistance solution from Apple, I was pretty disappointed with what SwiftData ended up being.

**Comment by groue** [comment]
I can share a tip regarding database observation. SQLite does not detect changes in the file system, so no database observation tool will be automatically triggered if the app modifies a file.

A possible technique is to pretend that the database was modified with [`notifyChanges(in:)`](https://swiftpackageindex.com/groue/grdb.swift/documentation/grdb/database/notifychanges(in:)):

```swift
// Save the new player avatar
try avatarData.write(to: avatarURL, options: .atomic)

// Trigger all observations of the player table
try dbQueue.write { db in
    try db.notifyChanges(in: Player.all())
}
```
