### ISSUE TITLE
GRDB Checkpoints block on writes

### ISSUE THREAD

**Issue by charlesmchen-signal** [groue/GRDB.swift#793]
Hi @groue,

   Thanks again for all of the hard work on GRDB.

### The Desired Behavior

We're using `DatabasePool` & `DatabaseSnapshot` with:

```
        configuration.defaultTransactionKind = .immediate
        configuration.allowsUnsafeTransactions = true
```
We need to checkpoint our WAL without blocking (for long periods of time) on database writers. We're using a mixture of "passive" and "restart" checkpoints with a `busyMode` callback to timeout.  

SQLite checkpoints are designed to allow control over blocking behavior:

* "passive" checkpoints never block on database readers or writers - they abort immediately on conflict.

From https://www.sqlite.org/c3ref/wal_checkpoint_v2.html :
```
SQLITE_CHECKPOINT_PASSIVE 
Checkpoint as many frames as possible without waiting for any database readers or writers to finish, then sync the database file if all frames in the log were checkpointed. The busy-handler callback is never invoked in the SQLITE_CHECKPOINT_PASSIVE mode. On the other hand, passive mode might leave the checkpoint unfinished if there are concurrent readers or writers.
```

* "restart" checkpoints block on database writers, but the busy-handler can be used to limit how long they block for.

```
SQLITE_CHECKPOINT_FULL
This mode blocks (it invokes the busy-handler callback) until there is no database writer ...
SQLITE_CHECKPOINT_RESTART
This mode works the same way as SQLITE_CHECKPOINT_FULL with the addition that after checkpointing the log file it blocks (calls the busy-handler callback) until all readers are reading from the database file only. This ensures that the next writer will restart the log file from the beginning. Like SQLITE_CHECKPOINT_FULL, this mode blocks new database writer attempts while it is pending, but does not impede readers.
```

### The Issue

The problem is that `DatabasePool.checkpoint(...)` blocks on the writer's queue:

From: https://github.com/groue/GRDB.swift/blob/master/GRDB/Core/DatabasePool.swift#L181
```
    public func checkpoint(_ kind: Database.CheckpointMode = .passive) throws {
        try writer.sync { db in
            try db.checkpoint(kind)
        }
    }
```

This means that the `CheckpointMode` and `busyMode` callback don't matter much in terms of blocking - the checkpoint will block behind all writes instead of aborting as they should.

### Questions:

* Does `DatabasePool.checkpoint(...)` have to block on the writer's queue?
* We actually don't use `DatabasePool.checkpoint(...)` - we use `sqlite3_wal_checkpoint_v2()` within `DatabasePool.writeWithoutTransaction()` so that we can capture the `walSizePages` and `pagesCheckpointed` results.  `writeWithoutTransaction()` has the same problem - it blocks on the writers queue.

```
public func sqlite3_wal_checkpoint_v2(_ db: OpaquePointer!, _ zDb: UnsafePointer<Int8>!, _ eMode: Int32, _ pnLog: UnsafeMutablePointer<Int32>!, _ pnCkpt: UnsafeMutablePointer<Int32>!) -> Int32
```

**Comment by groue** [comment]
Hello @charlesmchen-signal, happy to see you again :-)

You have several questions.

> Does `DatabasePool.checkpoint(...)` have to block on the writer's queue? [...] `writeWithoutTransaction()` has the same problem - it blocks on the writers queue.

Indeed, all uses of a pool's writer connection are strictly **serialized** by GRDB, in a serial DispatchQueue.

This is not required by SQLite itself, which can support concurrent uses of a single database connection. But serializing database accesses vastly simplifies GRDB implementation, as well as user code, generally speaking.

The fact that all database accesses are protected by a serial DispatchQueue allows GRDB to open connections in the [Multi-thread](https://www.sqlite.org/threadsafe.html) mode:

> In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.

This mode disables internal SQLite mutexes, which means that it is *not an option* to lift the strict serialization of a database pool writer: this would be an SQLite misuse.

> SQLite checkpoints are designed to allow control over blocking behavior.

Sweet, you did spot that `DatabasePool.checkpoint(...)` misses the point :sweat_smile: Frankly, I have never used this method myself: this issue is a great reality check.

So you want to perform checkpoints without blocking your pool's writer. As explained above, the "Multi-thread" mode comes with a precondition which forbids non-blocking checkpoint from the pool's writer connection. This is our strongest constraint.

But we can use another connection!

```swift
let dbPool = try DatabasePool(path: dbPath)
let checkpointQueue = try DatabaseQueue(path: dbPath)

...

// Checkpoint without blocking the pool
checkpointQueue.writeWithoutTransaction { db in
    let code = sqlite3_wal_checkpoint_v2(db.sqliteConnection, ...)
    guard code == SQLITE_OK else {
        throw DatabaseError(resultCode: .init(rawValue: code), message: db.lastErrorMessage)
    }
}
```

I use a DatabaseQueue for the other connection, since there is no point using a full DatabasePool just for running checkpoints.

I use `sqlite3_wal_checkpoint_v2` since you want the `walSizePages` and `pagesCheckpointed` results.

Do you think this technique could solve your issue? If so, we'll see if it is possible to smooth the sharp corners out.

**Comment by groue** [comment]
> But we can use another connection!

The more I read https://www.sqlite.org/c3ref/wal_checkpoint_v2.html and try to put myself in your shoes, the more I think this is the way to go, since you may want to have a specific busy handler for checkpointing, different from the regular pool's writer.

**Comment by charlesmchen-signal** [comment]
@groue Thanks for the quick response.  Your suggestion seems viable - but I'm surprised that it is safe?  I thought it wasn't.  Are there are any risks or limitations around that?

* Your example code above suggests that we maintain the `DatabasePool` and `DatabaseQueue` at all times.  Is that right?
* Our database might used by several processes at a time (for example, the main app, a share extension, a notification service extension, etc.).  We'd probably only try to do checkpointing via the `DatabaseQueue` in the main app.

> you may want to have a specific busy handler for checkpointing

This is absolutely correct, we want different busy behavior (short timeouts) for checkpointing.

I'll try this suggestion today and follow up. Thanks again @groue

**Comment by groue** [comment]
Great, @charlesmchen-signal: we have a common setup to explore and validate before we clean things up.

> I'm surprised that it is safe? Are there are any risks or limitations around that?

The checkpointing documentation of SQLite explicitly talks about other readers and writers. For the checkpointing DatabaseQueue, the pool is just a bunch of other readers and writers. Also, I understand that the connection receiving SQLITE_BUSY is the checkpointing one. So the pool should not be affected.
And since you have external processes that access the db, I guess you're already using NSFileCoordinator, more or less a in https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md

I do not foresee problems with SQLite itself. Maybe application-level problems if we miss something. A wonderful opportunity to learn :-)

> Your example code above suggests that we maintain the DatabasePool and DatabaseQueue at all times. Is that right?

It suggests that we can use a distinct checkpointingQueue so that pool writes are not blocked :-) Now I had the same question as yours. I don't really know. Keeping an idle DatabaseQueue consumes no CPU and I/O, and consumes some RAM. It should exhibit reduced checkpointing latency since SQLite won't have to open a connection. Only measurement will tell you if it is a better solution than opening a new checkpointingQueue each time you want to perform a checkpoint.

>> you may want to have a specific busy handler for checkpointing
> This is absolutely correct, we want different busy behavior (short timeouts) for checkpointing.

It's good to have some confirmation that we are not heading in the wrong direction :-)

> I'll try this suggestion today and follow up.

Yes, please! You build the only app I know that pushes the lib to such height: your experience is invaluable, and supporting your use cases is very important to me 🤝

**Comment by charlesmchen-signal** [comment]
Hi @groue , so far your solution is working very well.  We're going to move ahead with it.  I'll report back to you if any problems arise.  Thanks for your timely help with this issue!  

> And since you have external processes that access the db, I guess you're already using NSFileCoordinator, more or less as in https://github.com/groue/GRDB.swift/blob/master/Documentation/SharingADatabase.md

No, we're not.  What is the reason to use `NSFileCoordinator`?  What specific problems does it avoid?

**Comment by groue** [comment]
Thanks for the feedback, @charlesmchen-signal 👍 

> What is the reason to use NSFileCoordinator? What specific problems does it avoid?

The goal is to prevent concurrent database opening, setup, and checks.

SQLite may hold locks during database opening ([source](https://www.sqlite.org/wal.html#sometimes_queries_return_sqlite_busy_in_wal_mode)):

> If the last connection to a database crashed, then the first new connection to open the database will start a recovery process. An exclusive lock is held during recovery. So if a third database connection tries to jump in and query while the second connection is running recovery, the third connection will get an SQLITE_BUSY error.

The busy handler may take care of this, but it is so hard to check. If `sqlite3_open_v2` returns SQLITE_BUSY, then we had no opportunity to setup the busy handler anyway. In doubt, file coordinators avoid this problem.

Applications perform database migrations as well, and you don't quite want them to run concurrently.

And you don't want migrations to be checked concurrently as well, due to the risk of peeking a look during the migration process. For example, without file coordinators, an app extension could witness the app in the middle of its migrations, and throw a "Database format is too old. Please open main app" error.

Now *you* run a widely deployed app, so you have a better sense of the actual probability of those errors to occur 😅 

---

Now, maybe we can draw conclusions about checkpoints:

`DatabasePool.checkpoint()` is not enough, because an app sometimes want to checkpoint from a DatabaseQueue.

This means that we should remove this method, and expose it in `Database` itself:

```swift
// Before
try dbPool.checkpoint()

// After
try dbPool.writeWithoutTransaction { db in
    try db.checkpoint()
}
```

Next, you have to call the raw `sqlite3_wal_checkpoint_v2` because the Swift `checkpoint` is not complete enough. Let's complete it!

Do you have other ideas?

**Comment by groue** [comment]
#795 was merged. I guess it closes this issue.
