### ISSUE TITLE
Change of behavior for non-existing columns on Xcode 12 beta 1

### ISSUE THREAD

**Issue by andersio** [groue/GRDB.swift#799]
### What did you do?

We have a query that does simply:

```swift
try pool.write { db in
  try Record.filter(Column("nonExisting") == "stub").deleteAll(in: db)
}
```

where the column `nonExisting` does not exist in the table schema.

### What did you expect to happen?
On Xcode 12 beta, it does throw an error with SQLite error code 1 (`SQLITE_ERROR`) with a clear message of "no such column `nonExisting`".

### What happened instead?
On Xcode 11.5, it seems SQLite (GRDB?) gracefully lets it through.

Could this possibly be caught when building against earlier iOS SDKs too? Been trying to research on whether SQlite has some sort of error checking modes that were previously disabled, but nothing seems relevant.

### Environment

**GRDB flavor(s):** GRDB with system SQLite
**GRDB version:** 5.0.0-beta3
**Installation method:** CocoaPods
**Xcode version:** Xcode 11.5 and Xcode 12 beta 1
**Swift version:** 5.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.5.5

**Comment by groue** [comment]
Hello @andersio,

You are witnessing the consequences of the ["Double-quoted String Literals Are Accepted"](https://sqlite.org/quirks.html#dblquote) SQLite misfeature.

GRDB generates the following SQL:

```sql
-- What GRDB sends to SQLite:
DELETE FROM "myRecord" WHERE "nonExisting" = 'stub'
```

The identifiers are quoted, so that it is possible to define records which are named "transaction", "table", and other SQL-reserved words.

Because of the misfeature, SQLite interprets undefined identifiers as... strings. The above request is interpreted as the valid SQL below:

```sql
-- What SQLite executes:
DELETE FROM myRecord WHERE 'nonExisting' = 'stub'
```

Starting SQLite 3.29.0, it is possible to remove this misfeature, so that such requests fail instead of executing *something*. GRDB does it automatically since GRDB 4.7.0.

Conclusion: on Xcode 12 beta, you are executing some code on a newer version of SQLite, above 3.29.0. This triggers the safety belt, and changes the behavior of non-existing columns.
