### ISSUE TITLE
Failed to create temp view

### ISSUE THREAD

**Issue by peterhoucll** [groue/GRDB.swift#808]
Hello, I use the following SQL to create a temporary view:
```swift
do {
	try dbPool?.write { db in
		let sql = """
                            create temp view if not exists vw_temp as
                                ...
                                ...
                                ...
                            """
		try db.execute(sql: sql)
	}
} catch let error {
	print(error)
}
```
The code runs normally without errors. But when I use vw_temp, Xcode  prompts: no such table: vw_temp

And if I remove "temp" and create a normal view, everything works fine.

Looking forward to your help, thank you.

**Comment by groue** [comment]
Hello @peterhoucll,

Thanks for the report. Would you please tell what you mean by "when I use vw_temp"? For example, provide a sample code that make it possible to reproduce the error you are experiencing. Thank you!

**Comment by peterhoucll** [comment]
Hello, thanks for your reply.

Similar to this:
```swift
do {
	try dbPool?.read { db in
		let sql = "select XXX from vw_temp where XXX"
		let cursor = try Row.fetchCursor(db, sql: sql)  //run  failed
		while let row = try cursor.next() {
			...
			...
			...
		}
	}
} catch let error {
	print(error)
}
```

**Comment by groue** [comment]
All right. Your trouble is that the temporary view was created by an SQLite connection which is not the same as the connection that tries to read from it.

Quoting [SQLite documentation](https://www.sqlite.org/lang_createview.html):

> If the "TEMP" or "TEMPORARY" keyword occurs in between "CREATE" and "VIEW" then the view that is created is only visible to the database connection that created it and is automatically deleted when the database connection is closed.

Your view was created by the "writer connection", and you try to use it from one of the several "reader connections". That's what DatabasePool is about: managing a *pool* of SQLite connections.

You have various options in order to fix your issue:

1. Make the view not temporary.
1. Use a DatabaseQueue instead of a DatabasePool (so that you use a single database connection).
2. Only access the `vw_temp` view from the writer connection only (avoid all `read` methods)
3. Use a DatabasePool, but create the temp view in all connections, as in the sample code below:

```swift
var configuration = Configuration()
configuration.prepareDatabase = { db in
    try db.execute(sql: "CREATE TEMP VIEW vw_temp AS SELECT * FROM player")
}
let dbPool = try DatabasePool(path: ..., configuration: configuration)
try! dbPool.write { db in
    try db.create(table: "player") { t in
        t.autoIncrementedPrimaryKey("id")
        t.column("name", .text).notNull()
        t.column("score", .integer).notNull()
    }
    try db.execute(sql: "INSERT INTO player (name, score) VALUES (?, ?)", arguments: ["Arthur", 1000])
    try db.execute(sql: "INSERT INTO player (name, score) VALUES (?, ?)", arguments: ["Barbara", 1000])
    
    let cursor = try Row.fetchCursor(db, sql: "SELECT name FROM vw_temp")
    while let row = try cursor.next() {
        print(row)
    }
}
try! dbPool.read { db in
    let cursor = try Row.fetchCursor(db, sql: "SELECT name FROM vw_temp")
    while let row = try cursor.next() {
        print(row)
    }
}
```

**Comment by peterhoucll** [comment]
Thank you for your help!

I chose the fourth option, the problem has been resolved, thank you.

**Comment by groue** [comment]
Happy GRDB!
