### ISSUE TITLE
GRDB Publishers + Combine Schedulers

### ISSUE THREAD

**Issue by Miiha** [groue/GRDB.swift#809]
### What did you do?

I tried to use the TestScheduler type form Pointfree's [Combine Schedulers Library](https://github.com/pointfreeco/combine-schedulers#testscheduler). I hooked a write publisher with the test scheduler this way:  

```swift
let scheduler = DispatchQueue.testScheduler
cancellable = dbQueue.writePublisher(receiveOn: scheduler) { db -> Player in
  let player = Player(id: 1, name: "foo", score: 1)
  try player.insert(db)
  return player
}.map(Result.success)
.catch { Just(.failure($0)) }
.print()
.sink {
  print($0)
}
scheduler.advance()
```

### What did you expect to happen?
I would expect the publisher to fulfil it's work when the scheduler is run.

### What happened instead?
Only a subscription is registered, but no values or completion is sent.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.0.0-beta.7
**Installation method:** SPM
**Xcode version:** 12.0
**Swift version:** 5.3
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.5

### Demo Project
[GRDBTestScheduler.zip](https://github.com/groue/GRDB.swift/files/4937208/GRDBTestScheduler.zip)
---
I noticed that in the unit tests for the combine publishers use a couple of `wait` calls.
Being able to write unit tests in that manner could really clean things up. 
My guess is that the database uses it's own queue, which is why nothing is scheduled on the test scheduler.
But might there be a way to still use the TestScheduler?

**Comment by groue** [comment]
Hello @Miiha,

GRDB Combine publishers are tested, and used everyday (at least by me), and do not exhibit any issue of this kind.

> I noticed that in the unit tests for the combine publishers use a couple of wait calls.

Yes, when I want to run tests that wait, I use XCTest expectations indeed.

> My guess is that the database uses it's own queue, which is why nothing is scheduled on the test scheduler.

I don't know.

> But might there be a way to still use the TestScheduler?

Ask the authors of TestScheduler, maybe?

Look, GRDB `writePublisher` [does not look that complicated](https://github.com/groue/GRDB.swift/blob/b9bb5147099c4bfa75e296668fa4f234af9075a5/GRDB/Core/DatabaseWriter.swift#L402-L417).

And yet, I had to workaround **Combine bugs**. There were fixed since iOS 13.0, but there are still devices that do not run on the latest iOS 13, and I don't want GRDB to misbehave on those devices.

I had to reimplement `Deferred { Future { ... } }` (under the name `OnDemandFuture`).

I had to reimplement `receive(on:)` (under the name `receiveValues(on:)`).

I ran tests *tens of thousands of times* until I got sure everything was just *properly scheduled* without any glitch, *ever*.

I'm not saying my code is bug-free. I just say it has less bugs than Combine, if you allow me some irony. And if you can exhibit some bug, I'll look at it, of course.

**Comment by Miiha** [comment]
Hi @groue, thanks for your reply. 
I am of course not 100% sure if I set up everything correctly. 
I see that there are a lot of obstacles with Combine you had to takle.
I will try to reach out to the authors of the Schedulers library and see if they can provide some thoughts.

Again, thank you for the detailed response.

**Comment by groue** [comment]
Thanks @Miiha. Yeah, I'm sorry I don't quite see yet if my help is needed.

I have an advice if you keep on using TestScheduler:

Since GRDB publishers are just asynchronous publishers that complete when the database has done its job, they shouldn't behave much differently than a plain `Just(stuff).delay(...)`. Maybe train with such basic publishers first?

**Comment by Miiha** [comment]
Hi @groue, I think you pointed me into the right direction.
A `TestScheduler` will perform scheduled work when asked to do so. 
In case of a `WritePublisher`, the scheduling happens after the database updated is fulfilled.
This is the reason I won't receive values when using `receive(on:)` and that's probably why one has to wait for the database to do it's asynchronous work.

Thanks again
