### ISSUE TITLE
Would you be interested in ActiveRecord style callbacks (like Rails)?

### ISSUE THREAD

**Issue by thieso2** [groue/GRDB.swift#815]
### What did you do?

I use GRDB and am really happy:-) And - coming from a Rails background - I sometimes miss having callbacks like the ones available in Ralis available (see https://guides.rubyonrails.org/active_record_callbacks.html).

I would love to contribute a patch that implements (starting with a subset of) those. I'm wondering if you would be interested in this as a contribution or if you have already decided against such a feature. 

And - if you like the idea, would you bundle this in a new Protocol, or add it to (Mutable)PersistableRecord? 

Thank you for GRDB!

**Comment by groue** [comment]
Hello @thieso2!

Thanks for asking. Could you please explain the use case you have in mind, and how [Customizing the Persistence Methods](https://github.com/groue/GRDB.swift/blob/master/README.md#customizing-the-persistence-methods) does not address it?

**Comment by thieso2** [comment]
I once read this section and was not really present to it when asking for this, sorry...

Basically (I believe) I can do everything I want with what GRDB already provides (maybe not the after_commit things). I'll play around with it and see where that gets me. I'll re-open this issue once (and only if I) have some code to share. 

Thank you!

**Comment by groue** [comment]
Thank you @thieso2!

Yes, I like it when suggestions like this are motivated, because they are not free:

- Callbacks create a mental burden on users (Should I override methods or use callbacks? Should I refactor my existing working app so that it uses the new hotness?)
- Callbacks come with a small but real performance hit
- Somebody will have to write documentation with inspiring sample code.

Finally... Callbacks belong to the notorious "Fat Model, Skinny Controller" way to architecture Rails apps. I'm not fond of this pattern at all, to be honest, and I really do not want to be one of its promoters.

But if you exhibit a use case that needs some polish, I'll be happy to discuss it with you. Maybe callbacks will help, maybe we'll find another way?
