### ISSUE TITLE
Custom Collations issue with eraseDatabaseOnSchemaChange

### ISSUE THREAD

**Issue by sctgcs** [groue/GRDB.swift#829]
### What did you do?

Created a new iOS project which includes a custom collation added to the shared DbPool object.
Set eraseDatabaseOnSchemaChange = true for development. 

### What did you expect to happen?

I expected the database would erase and migrate from scratch as usual.

### What happened instead?

The migrator raised an exception on the CREATE_TABLE which used the custom collation on the 2nd run.
First run was fine, database tables all created ok.
Second run with existing tables raised the exception. (There were NO schema changes)

Example:
2020-09-03 14:59:58.831127+0100 SFY Reports[919:327603] [logging] no such collation sequence: version_collation in "CREATE TABLE "reports" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "release_id" INTEGER NOT NULL UNIQUE, "company_id" INTEGER NOT NULL, "version" TEXT NOT NULL DEFAULT 0 COLLATE version_collation, "report_type_code" TEXT NOT NULL, "report_type_name" TEXT NOT NULL, "full_title" TEXT NOT NULL, "release_notes" TEXT NOT NULL, "live" BOOLEAN DEFAULT 0, "stored_at" DATETIME); CREATE INDEX "reports_on_company_id" ON "reports"("company_id")"

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 4.14.0
**Installation method:** SPM
**Xcode version:** 11.6
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15.6 (Catalina)

### Demo Project

Sorry, no demo at the moment.

**Comment by groue** [comment]
Hello @sctgcs,

Thanks for spotting this issue.

I suppose that your app 1) creates a DatabaseQueue/Pool instance, 2) adds a collation, and then 3) migrates the database.

Please try this other technique: 1) create a database configuration which adds the collation, 2) create the DatabaseQueue/Pool instance, and then 3) migrates the database:

```swift
let collation = ...
var config = Configuration()
config.prepareDatabase = { db in
    try db.add(collation: collation)
}
let dbQueue = try DatabaseQueue(path, configuration: config)
try migrator.migrate(dbQueue)
```

If I have a correct understanding of the failure, I expect this other technique to work. The `eraseDatabaseOnSchemaChange` option indeed looks for schema changes by opening another temporary database connection, which won't inherit custom collations unless they're added to the `prepareDatabase` configuration.

Please report if this fixes your issue. I will fix the API and change the documentation, so that the faulty setup is no longer possible, and no other GRDB user falls into the same trap.

**Comment by groue** [comment]
Closing in favor of #831

**Comment by sctgcs** [comment]
Thanks @groue; I can confirm that in my project, changing the place I add the collation to the configuration's prepareDatabase call fixes the issue. 

Best wishes for the  GRDB 5.0 release and thank you very much for all your hard work on this excellent SQLite wrapper.

**Comment by groue** [comment]
Good, @sctgcs! Thank you for your wishes. Don't miss the migration guide from GRDB 4 when GRDB 5 eventually leaves the beta stage :-)
