### ISSUE TITLE
Unable to build with custom sqlite and GRDB5 due to snapshot functions

### ISSUE THREAD

**Issue by benasher44** [groue/GRDB.swift#845]
### What did you do?

Attempt to upgrade from GRDB 4 to 5 and build.

### What did you expect to happen?

After some hacking (after all, we do have a custom sqlite setup), build with GRDB 5.

### What happened instead?

I'm not able to build due to issues related to the snapshots functionality, which I will explain.

GRDB introduced features that use the sqlite snapshots functions, which can be enabled with the `SQLITE_ENABLE_SNAPSHOT` preprocessor macro. We don't enable this macro in our sqlite build. However, it appears the sqlite amalgamation comes with the main struct type defined for snapshots in its header, even if you don't have this macro enabled, which leads to the first issue we're seeing: compiler complains of duplicate definition of the `sqlite3_snapshot` struct. This is easy enough to work around (see notes in the sample project)— we can do some hacking to namespace the struct defined in GRDB.

Once we do that though, we get a linker error because the final GRDB binary (not compiled with `SQLITE_ENABLE_SNAPSHOT`) references `sqlite3_snapshot_get`, `grdb_snapshot_free`, and `grdb_snapshot_free`. By not using `SQLITE_ENABLE_SNAPSHOT` in the sqlite build, those functions are compiled out of the sqlite binary. But, GRDB still references them in the final binary, so the linker errors.

#### Possible Solutions

1. We could enable `SQLITE_ENABLE_SNAPSHOT` on our end, but we'd prefer not to do that. I haven't studied the surface area of those APIs, or how they would impact our sqlite usage + required testing.
2. Some kind of patch to GRDB to also compile out the referenced functions when `SQLITE_ENABLE_SNAPSHOT` is not enabled?
3. Some other hacking on our end, which I haven't considered? Open to suggestions

Thanks in advance for your help and consideration!

### Environment

**GRDB flavor(s):** (GRDB, SQLCipher, Custom SQLite build?): GRDB + custom sqlite build/hackery in our Podfile
**GRDB version:** 5.0.1
**Installation method:** (CocoaPods, SPM, manual?) CocoaPods
**Xcode version:** 11.7
**Swift version:** 5.2
**Platform(s) running GRDB:** (iOS, macOS, watchOS?) iOS
**macOS version running Xcode:** 10.15.6

### Demo Project

https://github.com/benasher44/GRDB5SnapshotTest

In the Podfile, there are lines to un-comment to attempt to namespace the already-defined struct.

**Comment by groue** [comment]
Hello @benasher44,

We could change GRDB in order to make it work without SQLITE_ENABLE_SNAPSHOT.

This would not create any problem.The behavior of ValueObservation started from a DatabasePool will change in a way permitted by the documentation: it will always emit a duplicated first value, because it won't be able to prove that the database has not changed between the first fetch from a readonly SQLite connection, and the first access to the writer SQLite connection which allows to connect to the SQLite observation hooks. I say this so that you are aware of the potential impact on your app.

The difficulty of the SQLITE_ENABLE_SNAPSHOT  topic is that the sqlite3.h header shipped with Apple SDKs does not expose the feature - although they we can link against it. I could not witness any malfunction in the SDK versions I could test, and decided this was a just header bug, not the purposeful hiding of an experimental / incomplete / buggy feature.

In order to work around this, I had to use various techniques that I did not really care to package properly. This issue is an opportunity to have a second look at it. Thanks for the demo project, I'll have a look.

**Comment by benasher44** [comment]
Thanks— appreciate you having a look!

**Comment by groue** [comment]
#846 reveals that SQLITE_ENABLE_SNAPSHOT is considered private API on Mac Catalyst.

**Comment by groue** [comment]
@benasher44, GRDB 5.0.2 should fix your issue.

**Comment by benasher44** [comment]
Confirmed fixed. Thanks!

**Comment by gennaios** [comment]
Thank you for the fix. I am using as mentioned the newest sqlite version by including the sqlite3 pod. It now works with GRDB 5.
