### ISSUE TITLE
Creating a request for a custom Record type - I can't figure out how to build the request

### ISSUE THREAD

**Issue by d3mueller** [groue/GRDB.swift#863]
Hey, I've just started using this library and I really love it :D I've been trying out some things while working through the documentation (which is insanely thorough, it's awesome!) to get a basic understanding of everything and I have a question about Associations:

### What did you do?
I have three basic database tables, `story`, `timeline` and `event`. Each `timeline` belongs to at most one `story`, while `timeline` and `event` have a many-to-many relationship through the table `eventOwnership`. This is the migration for the database:

```swift
try db.create(table: "story", body: { table in
    table.autoIncrementedPrimaryKey("id")
    table.column("name", .text)
        // Sort by name by default
        .collate(.localizedCaseInsensitiveCompare)
        .notNull()
    table.column("description", .text)
        .notNull()
})

try db.create(table: "timeline", body: { table in
    table.autoIncrementedPrimaryKey("id")
    table.column("name", .text)
        .notNull()
        .collate(.localizedCaseInsensitiveCompare)
    table.column("description", .text)
        .notNull()
    table.column("storyId", .integer)
        .indexed()
        .references("story", onDelete: .cascade)
})

try db.create(table: "event", body: { table in
    table.autoIncrementedPrimaryKey("id")
    table.column("name", .text)
        .notNull()
    table.column("description", .text)
        .notNull()
    table.column("date", .date)
        .notNull()
})

try db.create(table: "eventOwnership", body: { table in
    table.primaryKey(["eventId", "owningTimelineId"])
    table.column("eventId", .integer)
        .notNull()
        .references("event", onDelete: .cascade)
    table.column("owningTimelineId", .integer)
        .notNull()
        .references("timeline", onDelete: .cascade)
        .indexed()
})
```

And these are the structs (I tried only including the relevant parts to keep it short):

```swift
public struct Story: Identifiable, Hashable {
    public var id: Int64?
    var name: String
    var description: String
}

extension Story: TableRecord {
    static let timelines = hasMany(Timeline.self)
    
    var timelines: QueryInterfaceRequest<Timeline> {
        request(for: Story.timelines)
    }
}

public struct Timeline: Identifiable, Hashable {
    public var id: Int64?
    var name: String
    var description: String
    var storyId: Int64?
}

extension Timeline: TableRecord {
    static let story = belongsTo(Story.self)
    static let eventOwnership = hasMany(EventOwnership.self)
    static let events = hasMany(Event.self, through: eventOwnership, using: EventOwnership.event)
    
    var story: QueryInterfaceRequest<Story> {
        request(for: Timeline.story)
    }
    
    var events: QueryInterfaceRequest<Event> {
        request(for: Timeline.events)
    }
}

public struct Event: Identifiable, Hashable {
    public var id: Int64?
    var date: Date
    var name: String
    var description: String
}

extension Event: TableRecord {
    static let eventOwnership = hasMany(EventOwnership.self)
    static let owningTimelines = hasMany(Timeline.self, through: eventOwnership, using: EventOwnership.owningTimeline, key: "owningTimelines")
    
    var owningTimelines: QueryInterfaceRequest<Timeline> {
        request(for: Event.owningTimelines)
    }
}

public struct EventOwnership: Hashable {
    var eventId: Int64?
    var owningTimelineId: Int64?
}

extension EventOwnership: TableRecord {
    static let event = belongsTo(Event.self)
    static let owningTimeline = belongsTo(Timeline.self)
}

```

I'm fiddling around with Associations and they are incredibly awesome :D. I'm currently trying to figure out how to create a specific request with a record type that should look something like this:

```swift
struct TimelineInfo: FetchableRecord, Decodable {
    var timeline: Timeline
    var eventInfos: [EventInfo] // This array contains all events and their owners (an owner is a timeline and the timeline's story)
}
```

Based on the `AssociationsBasics.md` page, I've successfully created the following request using the custom record type `EventInfo`:

```swift
struct EventInfo: FetchableRecord, Decodable {
    
    struct Owner: Decodable, Hashable {
        var timeline: Timeline
        var story: Story?
    }
    
    var event: Event
    var owners: [Owner]
    
    static func all() -> QueryInterfaceRequest<EventInfo> {
        Event.including(all: Event.owningTimelines
                            .including(optional: Timeline.story)
                            .forKey(CodingKeys.owners)
        )
        .asRequest(of: EventInfo.self)
    }
}
```

With this, I can easily grab all events and their corresponding list of owners:

```swift
try dbQueue.read { database in
    let eventInfos = try EventInfo.all().fetchAll(database)
}
```

This seems to return the correct values. However, I don't want to fetch all events. I only want those belonging to a specific timeline and I can't really figure out how to approach this properly.

I tried adding a static function to `TimelineInfo`, something like:

```swift
struct TimelineInfo: FetchableRecord, Decodable {
    var timeline: Timeline
    var eventInfos: [EventInfo]
    
    static func requestForTimeline(_ key: Int64) -> QueryInterfaceRequest<TimelineInfo> {
        Timeline.filter(key: key).including(.....)
        .asRequest(of: TimelineInfo.self)
    }
}
```

But I don't know how to build such a request. I tried recycling the code inside `EventInfo.all()` to create a similar request for `TimelineInfo`, but I can't access `EventInfo.CodingKeys` from outside the `EventInfo` struct, so I can't properly build that part of the request.

I would really appreciate help with this. I've been trying to figure it out for the last couple hours but my understanding of these things is not good enough :D. I also hope it's clear what I'm trying to achieve. I don't know most of the official terms for this library yet.

Thanks!

### Environment

**GRDB flavor(s):GRDB
**GRDB version: 5.0.3
**Installation method: SPM
**Xcode version: 12.2 beta 3
**Swift version:** Swift 5
**Platform(s) running GRDB: iOS
**macOS version running Xcode:** Mac OS Catalina 11.0.1 Beta 1

**Comment by groue** [comment]
Hello @d3mueller,

Thanks for the detailed information. It looks like your question is about the composition of requests. You know how to requests `EventInfo`, but you don't know how to request `[EventInfo]` nested inside `TimelineInfo`.

First of all, let's put aside the `all()` static functions. They nicely encapsulate requests, but when they hide too much of their inner guts, this encapsulation can turn into a hindrance.

So let's first build requests *that work*. On the way, we'll make our objects as transparent as they need to be, and break some encapsulation. Only after we have built our requests, we'll find new encapsulation boundaries.

Let's start with a transparent request for `EventInfo`:

```swift
struct EventInfo: Decodable, FetchableRecord {
    struct Owner: Decodable, Hashable {
        var timeline: Timeline
        var story: Story?
    }
    
    var event: Event
    var owners: [Owner]
    
    static let ownersKey = CodingKeys.owners.stringValue
}

let eventInfosRequest = Event
    .including(all: Event.owningTimelines
                .including(optional: Timeline.story)
                .forKey(EventInfo.ownersKey)
    )
    .asRequest(of: EventInfo.self)
```

And now let's build a transparent request for `TimelineInfo`:

```swift
struct TimelineInfo: Decodable, FetchableRecord {
    var timeline: Timeline
    var eventInfos: [EventInfo]
    
    static let eventInfosKey = CodingKeys.eventInfos.stringValue
}

let timelineInfosRequest = Timeline
    .including(all: Timeline.events
                .including(all: Event.owningTimelines
                            .including(optional: Timeline.story)
                            .forKey(EventInfo.ownersKey)
                )
                .forKey(TimelineInfo.eventInfosKey)
    )
    .asRequest(of: TimelineInfo.self)
```

The request for `TimelineInfo` can be altered, filtered, etc:

```swift
let timelineInfoRequest = Timeline
    .filter(key: 42) // <-
    .including(all: Timeline.events
                .including(all: Event.owningTimelines
                            .including(optional: Timeline.story)
                            .forKey(EventInfo.ownersKey)
                )
                .forKey(TimelineInfo.eventInfosKey)
    )
    .asRequest(of: TimelineInfo.self)
```

OK. We have reached a desirable step: we have requests that work 🎉

But on the way, we had to introduce two defects 😢

1. We expose some CodingKeys (which Swift synthesize as private types).
2. The code that requests `EventInfo` from `Event` is duplicated (`.including(all: Event.owningTimelines...)`).

So let's try to fix this!

---

First, let's encapsulate the requests of `EventInfo` from `Event`.

The solution I will guide you through will stricly distinguish two steps in the way we build requests. The first is the *structure* of the request. The second is the actual *decoding* of the request, when we fetch its values in a dedicated record type.

The two steps will partially overlap, because the coding keys of the decoding records are involved in the structure. But please bear with me.

Let's compare the requests for `EventInfo` and `TimelineInfo`, and exhibit the structure and decoding parts:

```swift
let eventInfosRequest = Event
    // structure
    .including(all: Event.owningTimelines
                .including(optional: Timeline.story)
                .forKey(EventInfo.ownersKey)
    )
    // decoding
    .asRequest(of: EventInfo.self)

let timelineInfosRequest = Timeline
    // structure
    .including(all: Timeline.events
                .including(all: Event.owningTimelines
                            .including(optional: Timeline.story)
                            .forKey(EventInfo.ownersKey)
                )
                .forKey(TimelineInfo.eventInfosKey)
    )
    // decoding
    .asRequest(of: TimelineInfo.self)
```

The shared code that turns `EventInfo` from `Event` is:

```swift
.including(all: Event.owningTimelines
            .including(optional: Timeline.story)
            .forKey(EventInfo.ownersKey)
)
```

It is called right on `Event` in the first request, and on `Timeline.events` on the second request.

**Extend `DerivableRequest` in order to encapsulate structure**
 
`Event` and `Timeline.events` don't have the same type. But `Event.all()` and `Timeline.events` share the same protocol, which is `DerivableRequest`. This protocol is where you can share structural code between record requests and associations. Let's give a try:

```swift
extension DerivableRequest where RowDecoder == Event {
    func withEventInfo() -> Self {
        including(all: Event.owningTimelines
                    .including(optional: Timeline.story)
                    .forKey(EventInfo.ownersKey)
        )
    }
}
```

The two requests for `EventInfo` and `TimelineInfo` can now be written as:

```swift
let eventInfosRequest2 = Event.all()
    .withEventInfo()
    .asRequest(of: EventInfo.self)

let timelineInfosRequest2 = Timeline
    .including(all: Timeline.events
                .withEventInfo()
                .forKey(TimelineInfo.eventInfosKey)
    )
    .asRequest(of: TimelineInfo.self)
```

We can do the same for `TimelineInfo`:

```swift
extension DerivableRequest where RowDecoder == Timeline {
    func withTimelineInfo() -> Self {
        including(all: Timeline.events
                    .withEventInfo()
                    .forKey(TimelineInfo.eventInfosKey)
        )
    }
}

let timelineInfosRequest3 = Timeline.all()
    .withTimelineInfo()
    .asRequest(of: TimelineInfo.self)
```

**Extend `QueryInterfaceRequest` in order to encapsulate decoding**

The above requests are better, but the structure and the decoding are too much decoupled. It's easy to forget how to decode, which type should feed `asRequest(of:)`.

So let's encapsulate decoding as well:

```swift
extension QueryInterfaceRequest where RowDecoder == Event {
    func asEventInfo() -> QueryInterfaceRequest<EventInfo> {
        withEventInfo().asRequest(of: EventInfo.self)
    }
}

let eventInfosRequest3 = Event.all().asEventInfo()

extension QueryInterfaceRequest where RowDecoder == Timeline {
    func asTimelineInfo() -> QueryInterfaceRequest<TimelineInfo> {
        withTimelineInfo().asRequest(of: TimelineInfo.self)
    }
}

let timelineInfosRequest4 = Timeline.all().asTimelineInfo()
```

Those requests are as versatile as other requests:

```swift
Event.asEventInfo().order(Column("date"))
Timeline.filter(key: 42).asTimelineInfo()
```

**Hide implementation details**

I suggest those `asEventInfo()` and `asTimelineInfo()` methods are the only ones that should be used by application code. Structure methods (`withEventInfo()` and `withTimelineInfo()`) and coding keys, should remain as private or fileprivate as possible and allowed by the language.

**Bonus: filtering events in TimelineInfo**

Our current implementation of `asTimelineInfo()` includes all events. You can't filter or sort them. Here is a possible solution:

```swift
extension DerivableRequest where RowDecoder == Timeline {
    func withTimelineInfo<A>(events: A) -> Self
    where A: AssociationToMany, A.OriginRowDecoder == Timeline, A.RowDecoder == Event
    {
        including(all: events
                    .withEventInfo()
                    .forKey(TimelineInfo.eventInfosKey)
        )
    }
}

extension QueryInterfaceRequest where RowDecoder == Timeline {
    func asTimelineInfo<A>(events: A) -> QueryInterfaceRequest<TimelineInfo>
    where A: AssociationToMany, A.OriginRowDecoder == Timeline, A.RowDecoder == Event
    {
        withTimelineInfo(events: events).asRequest(of: TimelineInfo.self)
    }
}

// Usage
let events = Timeline.events.order(Column("date"))
let timelineInfosRequest5 = Timeline
    .filter(key: 42)
    .asTimelineInfo(events: events)
```

---

That was a long journey, with a lot of extensions, maybe too many: we have pushed encapsulation to the extreme. We have a satisfying and versatile public api, but the inner guts are somewhat complex.

If there is something to remember from this answer, it is, in no particular order:

- GRDB wants you to distinguish structure from decoding.
- Always build requests that work first, and only after attempt at refactoring, if necessary.
- A little code duplication is a small code smell, compared to a cathedral of encapsulation that is difficult to understand and maintain.
- Test the results of your complex requests against sample data sets.

**Comment by d3mueller** [comment]
Thank you so much for this extremely detailed explanation! I really appreciate it! :)

I've worked through what you wrote and implemented everything, step by step, and it really helped me understand this concept of creating requests. This is exactly what I wanted to do :D

All of this is awesome, I'm really looking forward to digging deeper into the library. Thanks again for taking the time to write this :)

**Comment by groue** [comment]
You're welcome @d3mueller :-) Maybe you'll be able to help other users as well ;-) Happy GRDB!
