### ISSUE TITLE
pod install for 5.3.0 failed

### ISSUE THREAD

**Issue by askari01** [groue/GRDB.swift#909]
### What did you do?
pod 'GRDB.swift', '5.3.0'
followed by: pod install

### What did you expect to happen?

Pull GRDB 5.3.0

### What happened instead?

failed to find 5.3.0

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.3.0
**Installation method:** CocoaPods
**Xcode version:** 12.3
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** Big Sur

**Comment by groue** [comment]
Hello @askari01,

GRDB 5.3.0 installs fine with CocoaPods.

Please have a better look at the error messages returned by the `pod install` command. If you are looking for support about CocoaPods, will you please ask Google, StackOverflow, or the CocoaPods team instead?

**Comment by askari01** [comment]
thank you noticing it on Sunday but the default version is still 5.2.0 and if you specifically mention pod version to 5.3.0 it isn't  available. 
<img width="559" alt="Screenshot 2021-01-17 at 7 26 45 PM" src="https://user-images.githubusercontent.com/6830947/104845980-07270c80-58fa-11eb-936e-9e37c01b943e.png">

**Comment by groue** [comment]
I think you stopped reading the error message just a little bit too early, @askari01. Did you miss thee following lines?

> You have either:
> * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.

So please type the command that is suggested to you: "`pod repo update` or with `pod install --repo-update`."

And, in the future:

- Read the full error messages. They are here to let you understand what's wrong.
- Stop pasting screenshots. They won't show in Google results so that other users who have the same problem as yours have a chance to find an answer.
- Stop editing command output when you ask questions. It is such a *bad* idea to hide the information that can help others help you.
- Paste the full verbatim error messages.

You'll become a better online citizen, especially on Sundays.

**Comment by askari01** [comment]
sorry if you felt bad, no disrespect either. It was an issue at my end. But I also find your response bit harsh and rude. 
I updated my cocapod gem, also deleted pod-lock file which fixed it.

thanks
