### ISSUE TITLE
Using Combine to get All Changes from a Table

### ISSUE THREAD

**Issue by cliftonlabrum** [groue/GRDB.swift#919]
_Xcode 12.4, GRDB 5.3.0_

I'm new to SwiftUI, Combine, and GRDB. Previously I've been using Realm with AppKit/UIKit, but I stumbled across GRDB and was intrigued. It might be too complex for me, but I'm trying it out. 🙂 

My goal is to get Combine working with SwiftUI so I can see SQLite changes automatically in my views. I looked at the GRDB Combine example, but it got complex in a hurry and I couldn't follow it.

I have a record set up, my table created, and some sample data in the database. Here's an abbreviated version of the record definition:
```
struct Workspace: Codable, FetchableRecord, PersistableRecord, Identifiable {
  var id:String = UUID().uuidString
  var name: String
}
```
I want to know when any changes occur in my `workspace` table, so I'm trying to create an `ObservableObject` like this:
```
class WorkspaceObserver: ObservableObject {
  @Published var workspaces = [Workspace]()
  
  init(){
    
    let dbq = try! DatabaseQueue(path: "\(NSHomeDirectory())/Documents/MyDatabase.sqlite")
    let publisher = ValueObservation
        .tracking { db in
          self.workspaces = try Workspace.fetchAll(db)
          print(self.workspaces)
        }
        .publisher(in: dbq)
  }
}
```
And then my SwiftUI view looks like this:
```
struct WorkspaceView: View {
  @ObservedObject var observer = WorkspaceObserver()
  
  var body: some View {
    ScrollView{
      VStack(alignment: .center, spacing: 20){
        ForEach(observer.workspaces, id: \.id) { workspace in
          Text(workspace.name)
        }
      }.background(Color.blue)
    }
  }
}
```
My `WorkspaceObserver` gets initialized, but no data ever shows up. Is there any guidance you can give me to get a super-simple version of this working?

Thanks!

**Comment by groue** [comment]
Hello @cliftonlabrum,

I'm sorry the demo app was too complex. Maybe this issue will be useful in order to improve it.

The reason why you do not see anything is that your app does not keep the database connection open. The first sentence of the [ValueObservation Usage](https://github.com/groue/GRDB.swift/blob/master/README.md#valueobservation-usage) documentation chapter is:

> Make sure that a unique database connection is kept open during the whole duration of the observation.

Your `WorkspaceObserver` creates a `DatabaseQueue` and forgets it: the database queue is destroyed immediately, and the observation can't run.

Your solution is to make sure that your app keeps a single instance of `DatabaseQueue` open for the whole duration of the database usage. In applications that connect to a single database, this means that you need a to setup a shared connection, a singleton, some kind of global variable. *Do not* create several `DatabaseQueue` instances for a single database file. Not only this will allow observations to do their work, but you'll also avoid the SQLite errors that happen when multiple connections compete for database access.

**Comment by groue** [comment]
> The reason why you do not see anything is that your app does not keep the database connection open.

That's not the only reason. Look at:

```swift
  init(){
    
    let dbq = try! DatabaseQueue(path: "\(NSHomeDirectory())/Documents/MyDatabase.sqlite")
    let publisher = ValueObservation
        .tracking { db in
          self.workspaces = try Workspace.fetchAll(db)
          print(self.workspaces)
        }
        .publisher(in: dbq)
  }
```

This code is surely not you want, because the publisher is never subscribed.

You need to subscribe to the publisher, surely with the `sink` method, and set the `workspaces` property from there.

But now this is no longer about GRDB, this is about Combine and SwiftUI. GRDB builds regular publishers that behave like all other publishers. When you are able to feed a SwiftUI view with, for example, a [`Timer` publisher](https://developer.apple.com/documentation/foundation/timer/3329589-publish), you'll know how to feed a SwiftUI view with a GRDB publisher. You'll find Combine tutorials and help online.

**Comment by cliftonlabrum** [comment]
Thank you for your thorough reply! I'll dig into this some more and see if I can figure it out.
