### ISSUE TITLE
Question: What's the rough memory footprint of GRDB for a lightweight sql store? 

### ISSUE THREAD

**Issue by zrfrank** [groue/GRDB.swift#923]
### What did you do?

The motivation is that I have an app already make heavy use of CoreData + CloudKit with a synced store and multiple local stores, with persistent history enabled and multiple context, things get complicated quickly. 

I wish to spinout a local store from the current core data stack, which is used for bookkeeping local assets records. The store is lightweight that has a few tables, with each up-to 1 ~ 5k records.

Therefore, I'm wondering what's the rough performance cost, like a rough estimate of memory usage of GRDB, in a sense of a few MB, 10s MB, 100s MB.

As GRDB, by reading the documents, is very sophisticated. Therefore, I'm wondering that, generally speaking, does GRDB suitable for lightweight-use like running alongside a heavy CoreData stack?

Thanks!

**Comment by groue** [comment]
Hello @zrfrank,

> Therefore, I'm wondering what's the rough performance cost, like a rough estimate of memory usage of GRDB, in a sense of a few MB, 10s MB, 100s MB.

I don't know: you will have to measure it. GRDB keeps in memory:

- A few SQLite connections (1 for its `DatabaseQueue`, up to 6 for its `DatabasePool` in its default configuration)
- Caches for the database schema (informations about tables, etc), and frequently used database statements.

Unessential memory of SQLite and those caches can be reclaimed: see [Memory Management](https://github.com/groue/GRDB.swift/blob/master/README.md#memory-management).

Values fetched from the database are not cached by GRDB.

> As GRDB, by reading the documents, is very sophisticated. Therefore, I'm wondering that, generally speaking, does GRDB suitable for lightweight-use like running alongside a heavy CoreData stack?

This sophistication is much lighter than it appears. GRDB thinks that:

- Application code is easier to read when one can write `let players = try Player.fetchAll(db)` instead of building an SQLite statement, iterating its results, and build `Player` instances out of raw row values. So this tedious job is provided by the library.
- Demanding applications want to use advanced SQLite features (and this explains why the documentation is long).

That's about it. GRDB is a thin wrapper around SQLite, with a delicious (that's subjective) and performant (that's [measured](https://github.com/groue/GRDB.swift/wiki/Performance)) API. I do not expect its memory footprint to be very big, but I'd be happy to know if you notice something odd.

**Comment by zrfrank** [comment]
Thanks! It sounds promising.
