### ISSUE TITLE
Using ASC NULLS LAST with Association Aggregates

### ISSUE THREAD

**Issue by seowalex** [groue/GRDB.swift#939]
### What did you do?

I would like to sort using `ASC NULLS LAST` when using the `min(column)` and `max(column)` association aggregates.

### What did you expect to happen?

I expect to be able to do so.

### What happened instead?

There does not seem to be a way to do so.

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.5.0
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5.1
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 10.15

**Comment by groue** [comment]
Hello @seowalex,

One can not currently sort using an association aggregate. This feature is not implemented. Applying `desc` or `ascNullsLast` qualifiers is not even an option:

```swift
// NOT CURRENTLY POSSIBLE
// Teams ordered by the maximum score of their players
let request = Team.order(Team.players.max(Column("score")))
```

As a workaround, you can select the aggregate, so that it can be used as an ordering. Make sure your aggregate [has a name](https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#annotating-a-request-with-aggregates).

```swift
let request = Team
    .annotated(with: Team.players.max(Column("score")))
//                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ named 'maxPlayerScore' by default
    .order(sql: "maxPlayerScore ASC NULLS LAST")
```

When `order(sql:)` is a little too low-level for you, you can switch to a more verbose `SQLLiteral`-based solution:

```swift
let aggregateColumn = SQLLiteral("maxPlayerScore").sqlExpression
let request = Team
    .annotated(with: Team.players.max(Column("score")))
    .order(..., aggregateColumn.ascNullsLast, ...)
```

---

Implementing this feature is challenging.

Each call to the `order()` method *replaces* previously set orderings, and there is no way to *append* an ordering to a set of previously set orderings. As a consequence, the `order` method has to accept all ordering terms in a single shot.

Supporting association aggregates would ideally make the `order` method look like:

```swift
// IDEAL
Team.order(
    Column("a"),               // Column
    Column("b") + Column("c"), // SQLExpression
    Column("d").desc,          // SQLOrdering
    aggregate)                 // AssociationAggregate<Team>
```

The three first arguments currently conform to the `SQLOrderingTerm` protocol, which is able to drive the needed SQL generation, and `order()` accepts arrays of `SQLOrderingTerm`. I don't know how to redefine the signature of `order()` so that it also accepts generic association aggregates, while preserving type safety.

**Comment by seowalex** [comment]
Hi @groue,

Indeed, I have tried to select the aggregate as you have proposed, but it did not occur to me that you could specify the `ASC NULLS LAST` like so. Both the raw SQL and the SQLLiteral seem to work beautifully. Thanks so much!

As a tangent to the original question, if I would like to select the aggregate through the `DerivableRequest` protocol, is there a way to do so?

For example, might it be possible to do something like this?

```swift
extension DerivableRequest where RowDecoder == Team {
    annotated(with: Team.players.max(Column("score")))
        .order(sql: "maxPlayerScore ASC NULLS LAST")
}
```

**Comment by groue** [comment]
I'm happy the workaround works for you!

> As a tangent to the original question, if I would like to select the aggregate through the DerivableRequest protocol, is there a way to do so?

Yes, just upgrade to v5.6.0 😉

**Comment by seowalex** [comment]
Wow! I didn't expect the feature to be added so quickly. Using your library has been a joy so far, continue to keep up the good work!

**Comment by groue** [comment]
> > As a tangent to the original question, if I would like to select the aggregate through the DerivableRequest protocol, is there a way to do so?
> 
> Yes, just upgrade to v5.6.0 😉

Beware that when you extend an *association* with its own association aggregate (through `DerivableRequest` or directly), this association can only be used with `including(all:)`. See https://github.com/groue/GRDB.swift/blob/master/Documentation/AssociationsBasics.md#further-refinements-to-associations

**Comment by martindufort** [comment]
This was just what I was looking for. Thanks...
GRDB Pro Tip: Always search the issues section for a potential answer to your question. 99% it is answered in there.

**Comment by groue** [comment]
[I wrote](https://github.com/groue/GRDB.swift/issues/939#issuecomment-798382588):

> When `order(sql:)` is a little too low-level for you, you can switch to a more verbose [SQLLiteral](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md#sqlliteral)-based solution (in order to define a column which is independent from all tables involved in the request):
> 
> ```swift
> let aggregateColumn = SQLLiteral("maxPlayerScore").sqlExpression
> let request = Team
>     .annotated(with: Team.players.max(Column("score")))
>     .order(..., aggregateColumn.ascNullsLast, ...)
> ```

Since GRDB 5.18.0, you'll use a [detached column](https://github.com/groue/GRDB.swift/pull/1129) instead:

```swift
let aggregateColumn = Column("maxPlayerScore").detached
let request = Team
    .annotated(with: Team.players.max(Column("score")))
    .order(..., aggregateColumn.ascNullsLast, ...)
```

> Supporting association aggregates would ideally make the `order` method able to handle [a mix of columns and aggregates]

[Variadic Generics](https://forums.swift.org/t/variadic-generics/54511) will certainly help.
