### ISSUE TITLE
Must the model match the database field name? 

### ISSUE THREAD

**Issue by rakuyoMo** [groue/GRDB.swift#942]
### What did you do?

I have a model, like this:

```swift
struct GroupModel: Codable {
    let id: String
    let name: String
    let assets: [OtherModel]

    enum CodingKeys: String, CodingKey {
        case id     = "group_id"
        case name   = "group_name"
        case assets = "asset"
    }
}
```

I designed it to correspond to a table: `group`. But the group table only uses `id` and `name` two fields, no `asset` field.

The problem occurred when I performed the insert operation.

### What did you expect to happen?

I hope the insert operation is successful.

In other words, when I expect to perform an insert operation, I can ignore certain fields in the model and not insert the data of the field into the database.

### What happened instead?

The insert operation failed, and an error was reported:

```
table group has no column named asset in "INSERT INTO "asset_account_group" ("group_id", "group_name", "asset") VALUES (?,?,?)"
```

### Environment

**GRDB flavor(s):** GRDB
**GRDB version:** 5.5.0
**Installation method:** CocoaPods
**Xcode version:** 12.4
**Swift version:** 5.3.2
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.2.2

**Comment by rakuyoMo** [comment]
I thought about it carefully. If some fields in the model are ignored, some problems may also occur when searching?

**Comment by groue** [comment]
Hello @rakuyoMo,

You explicitly opt in for encoding `assets`, so your app gets what it is asking for.

Your options are:

- Do not encode `assets`. See "Choose Properties to Encode and Decode Using Coding Keys" in [Encoding and Decoding Custom Types ](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)

- Implement `Encodable.encode(to:)` so that it performs a customized encoding for the database, based on the [userInfo dictionary](https://github.com/groue/GRDB.swift/blob/master/README.md#the-userinfo-dictionary).

- Do not rely on `Encodable` for database encoding, and provide an explicit `EncodableRecord.encode(to:)` implementation instead (see [PersistableRecord Protocol](https://github.com/groue/GRDB.swift/blob/master/README.md#persistablerecord-protocol)).

Another option is to read the [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md) guide.

**Comment by rakuyoMo** [comment]
> Hello @rakuyoMo,
> 
> You explicitly opt in for encoding `assets`, so your app gets what it is asking for.
> 
> Your options are:
> 
> * Do not encode `assets`. See "Choose Properties to Encode and Decode Using Coding Keys" in [Encoding and Decoding Custom Types ](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)
> * Implement `Encodable.encode(to:)` so that it performs a customized encoding for the database, based on the [userInfo dictionary](https://github.com/groue/GRDB.swift/blob/master/README.md#the-userinfo-dictionary). This would allow you to encode `assets` in some coders, but not in the database.
> * Do not rely on `Encodable` for database encoding, and provide an explicit `EncodableRecord.encode(to:)` implementation instead (see [PersistableRecord Protocol](https://github.com/groue/GRDB.swift/blob/master/README.md#persistablerecord-protocol)).
> 
> Another option is to read the [Good Practices for Designing Record Types](https://github.com/groue/GRDB.swift/blob/master/Documentation/GoodPracticesForDesigningRecordTypes.md) guide, so that you do not store arrays of `OtherModel` in `GroupModel`.

Thank you very much for your reply, I finally chose option 3, which is very effective!

In fact, I still have a question. Maybe I should create a new issue, but I also want to try to ask a question here first: How can I insert multiple pieces of data at once? I now have a `[GroupModel]`. What I do now is to traverse the model array and perform an insert operation on each item in it. Is there any other way to accomplish this?

**Comment by groue** [comment]
> What I do now is to traverse the model array and perform an insert operation on each item in it.

So you know how to do it. SQLite has no batch insert operation anyway.

**Comment by rakuyoMo** [comment]
> > What I do now is to traverse the model array and perform an insert operation on each item in it.
> 
> So you know how to do it. SQLite has no batch insert operation anyway.

Okay, I know. Thanks again for your reply.

**Comment by groue** [comment]
You're welcome. When you have *a lot* of records to insert, and you look for best performance, see https://github.com/groue/GRDB.swift/issues/926#issuecomment-786089593
