### ISSUE TITLE
Embed subquery in CTE, and unpack json array via query interface

### ISSUE THREAD

**Issue by steipete** [groue/GRDB.swift#961]
Okay, this is a tricky one involving subqueries and CTEs:

I have a table that has a list of ids stored as json. (your Twitter friends). Since this changes over time there's multiple copies, the primary key is the fetch date. I need the list of latest friends unpacked as CTE. I'd love to formulate this in the query interface but didn't find a way to add custom SQL in the `from` part of the query.

The request uses a subquery. This one is easy enough to write:

```swift
let dateRequest = MemberEvent
    .all()
    .select(MemberEvent.Columns.createdAt)
    .filter(MemberEvent.Columns.userId == userId)
    .filter(MemberEvent.Columns.type == MemberEvent.EventType.following)
    .orderByCreationDate()
    .limit(1)

// returns: sql: SELECT "createdAt" FROM "memberEvent" WHERE ("userId" = ?) AND ("type" = ?) ORDER BY "createdAt" DESC LIMIT 1 arguments: [25401953, 1]
print(try! dateRequest.makePreparedRequest(db).statement)
// (related: I made SelectStatement: CustomStringConvertible, is that worth a PR?)
```

But now, how do I integrate this into custom sql, or write the second part with the query interface?

```swift
let followersCTE = CommonTableExpression(
    named: "friendIds",
    sql:"""
 SELECT
     "value" as "userId" FROM "memberEvent", json_each(memberEvent.addedIds)
 WHERE "createdAt" == ( // <- subquery should be here instead of writing it in sql
        SELECT
            createdAt
        FROM
            "memberEvent"
        WHERE ("userId" = ?)
        AND(memberEvent.type = ?)
    ORDER BY
        "createdAt" DESC
    LIMIT 1)
 ORDER BY
    "createdAt" DESC
""",
    arguments: [userId, MemberEvent.EventType.following])
```

Later on I use the followersCTE again with query interface:

```swift
Tweet
    .with(followersCTE)
    .filter(followersCTE.contains(Tweet.Columns.userId))
    // further filtering, but not relevant for the question
```
(This part was easy)

I got everything working but I'm not happy about the amount of manual sql.

So what I'd love to have:
1) How do I reference the subquery in my sql
2) One step further, can I replace most/all of the sql with the query interface?

Thanks for the help!

**Comment by groue** [comment]
Hello @steipete!

> But now, how do I integrate this into custom sql

You can embed subqueries with [SQL Interpolation](https://github.com/groue/GRDB.swift/blob/master/Documentation/SQLInterpolation.md):

```swift
let dateRequest = ...
let followersCTE = CommonTableExpression(
    named: "friendIds",
    literal: """
        SELECT
            "value" as "userId" FROM "memberEvent", json_each(memberEvent.addedIds)
        WHERE "createdAt" = (\(dateRequest)) -- There! Mind the enclosing parenthesis
        ORDER BY
            "createdAt" DESC
        """)
```

Note the `literal` parameter argument, instead of `sql`. This is how you can distinguish SQL interpolation based on the `SQL` literal, from raw SQL `String`.

> or write the second part with the query interface?

The `FROM "memberEvent", json_each(memberEvent.addedIds)` part is currently not expressible with the query interface: there's no api for `FROM table1, table2`. And TIL about `FROM table1, json_each(table1.column)` 🙂 

So... raw SQL remains your best friend here.

---

For extra robustness against future schema changes, SQL interpolation can help (but I'm always wondering if this is a good idea to give such advice, since this area is still somewhat exploratory, and I'm not fond of the readability):

```swift
extension MemberEvent {
    /// The request for added user ids in events whose creation date
    /// is equal to the `createdAt` expression
    static func userIds<E: SQLExpressible>(createdAt: E) -> SQLRequest<Int64> {
        """
        SELECT "value" AS "userId"
        FROM \(self), json_each(\(self).\(Columns.addedIds))
        WHERE \(Columns.createdAt) = \(createdAt)
        ORDER BY \(Columns.createdAt) DESC
        """
    }
}

let followersCTE = CommonTableExpression(
    named: "friendIds",
    request: MemberEvent.addedUserIds(createdAt: dateRequest))
```

In this above sample code, the `dateRequest` subquery is treated as an expression (`SQLExpressible` input). This allows `MemberEvent.addedUserIds(createdAt:)` to accept almost anything. It is also possible to force a subquery, with a `SQLSubqueryable` input (useful if you want to complete it with `UNION` or other operators):

<details>
    <summary>Force a subquery</summary>

```swift
extension MemberEvent {
    /// The request for added user ids in events whose creation date
    /// matches the `createdAt` subquery
    static func userIds<R: SQLSubqueryable>(createdAt: R) -> SQLRequest<Int64> {
        """
        SELECT "value" AS "userId"
        FROM \(self), json_each(\(self).\(Columns.addedIds))
        WHERE \(Columns.createdAt) = (\(createdAt))
        ORDER BY \(Columns.createdAt) DESC
        """
    }
}
```

</details>

---

Easing access to the [JSON1 Extension](https://www.sqlite.org/json1.html) is a fertile way forward. It just happens that I did not have any use for it yet. It is one area of SQLite that has a *wiiiiiide* range of uses and practices, and my lack of experience makes it difficult to expose JSON1 to Swift.

In such unsettled situations, we always have the support for raw SQL, with a few bridges to and from the query interface, as described above. We also have the "experimental" level of apis, which are not tied by semantic versioning, and makes it possible to move forward with a peaceful mind :-)

So I'll happily listen to your JSON1 experience :-)

**Comment by groue** [comment]
I have another way forward, in an experimental branch, which explores an entry point in the query interface without `TableRecord`:

```swift
// Full access to the query interface, no record type in sight
let tweetTable = Table("tweet")
let rows = try tweetTable.all()
    .filter(...)
    .orderByPrimaryKey()
    .fetchAll(db) // [Row]

// When one does not want to fetch raw rows
struct Tweet: FetchableRecord { ... }
let tweetTable = Table<Tweet>("tweet")
let tweets = try tweetTable...fetchAll(db) // [Tweet]
```

This means that being able to use `json_each(memberEvent.addedIds)` as a table is probably not too far away.

**Comment by steipete** [comment]
Thank you! Can confirm that your suggestion works great - I'll use `SQLSubqueryable` now.
