### ISSUE TITLE
`ESCAPE` clause on `LIKE` statements

### ISSUE THREAD

**Issue by dehesa** [groue/GRDB.swift#962]
Hi there. Do you support the SQLite [`ESCAPE` clause](https://sqlite.org/lang_expr.html) on `LIKE` statements?

I have been going through the docs, but I haven't been able to find anything. This is forcing me to write the whole statement in raw SQL. Previously:

```swift
try dbConnection.read { db in
    var query = CustomRecord.order(CustomRecord.Columns.isPinned.desc, CustomRecord.Columns.lastModifiedAt.desc)
    if let c = category {
        query = query.filter(CustomRecord.Columns.category == c)
    }

    if !term.isEmpty{  
        if term.contains(where: { $0 == "_" || $0 == "%" }) {
            // ESCAPE goes here
        } else {
            query = query.filter(CustomRecord.Columns.text.like("%\(term)%"))
        }
    }

    return try query.limit(50).fetchAll(db)
}
```

Now, there is a whole lot of String manipulation. In case there is no way to add `ESCAPE` through a nice GRDB interface, is there a way to add the raw SQL without having to resort to raw SQL for the whole statement?

### Environment

**GRDB flavor(s):** GRDB with SQLCipher
**GRDB version:** 5.3.0
**Installation method:** SPM
**Xcode version:** 12.4
**Swift version:** 5.3.2
**Platform(s) running GRDB:** macOS
**macOS version running Xcode:** 11.2.3

**Comment by groue** [comment]
Hello @dehesa,

The existing `like(_:)` method does not accept any escape character, you are right.

You can extend the query interface with the missing Swift APIs (until they are added to GRDB), so that you do not have to write your full queries as SQL. We'll inject small SQL snippets instead. The general technique is described in the [Adding support for missing SQL functions or operators](https://github.com/groue/GRDB.swift/blob/master/README.md#adding-support-for-missing-sql-functions-or-operators) chapter.

In our specific case, we want to complete the existing `like(_:)` method with a new `like(_:escape:)` method. Using the technique described above, and getting inspiration from the [declaration of the existing method](https://github.com/groue/GRDB.swift/blob/v5.7.4/GRDB/QueryInterface/SQL/SQLOperators.swift#L525-L534), we end up with:

```swift
// Paste this somewhere in your application
extension SQLSpecificExpressible {
    /// Returns a `LIKE ... ESCAPE ...` expression
    func like(_ pattern: SQLExpressible, escape: SQLExpressible) -> SQLExpression {
        SQL("\(self) LIKE \(pattern) ESCAPE \(escape)").sqlExpression
    }
}
```

Usage:

```swift
// All books with "10%" in the title
// SELECT * FROM book WHERE title LIKE '%10\%%' ESCAPE '\'
let books = try dbQueue.read { db in
    Book
        .filter(Column("title").like("%10\\%%", escape: "\\"))
        .fetchAll(db)
}
```

**Comment by dehesa** [comment]
That looks great @groue. Thank you. I will give it a go.

**Comment by dehesa** [comment]
@groue the `SQL` within the `SQLSpecifExpressible` in not found in scope. Did you mean something different?

**Comment by groue** [comment]
Ha, you're using GRDB 5.3. It may be time for an upgrade. Otherwise replace `SQL` with `SQLLiteral` (the latter was recently deprecated and renamed to `SQL`), this should work.

**Comment by dehesa** [comment]
That did it. Thank you. I will also try to update GRDB in the process.

**Comment by groue** [comment]
The next GRDB version will have built-in support for the `ESCAPE` clause. Thank you for the report, @dehesa!

**Comment by dehesa** [comment]
Thank you for the quick answer and being great all around :)
