### ISSUE TITLE
Support for Module Stability?

### ISSUE THREAD

**Issue by byohay** [groue/GRDB.swift#964]
We want to use GRDB without needing to re-compile it every time. That is, we want to create a binary framework once and use it. This has proven quite challenging, since once a library is compiled using one compiler version, it can't be used by applications compiled using other compiler versions.
That is, unless module stability is enabled. I tried to compile GRDB with module stability (And library evolution, as module stability depends on it), by adding the flag `BUILD_LIBRARY_FOR_DISTRIBUTION` to `xcodebuild`, but it doesn't compile without changing the code. And I wouldn't want to diverge from the mainline. 

Is this something that you considered supporting? It would save us a lot of build time.

**Comment by groue** [comment]
Hello @byohay,

`BUILD_LIBRARY_FOR_DISTRIBUTION` enables [Library Evolution](https://swift.org/blog/library-evolution/), which "allows developers of binary frameworks to make additive changes to the API of their framework while remaining binary compatible with previous versions."

If you read this document thoroughly, you'll see that:

- Enabling library Evolution is a fair amount of work
- ABI stability is much stronger than API stability. 

I will **not** promise that GRDB has reached ABI stability, and I will **not** start shipping precompiled binaries. This would create a significant maintenance burden, and basically kill the lib. I just do not have the skills and time required to foresee the *future* ABI needs of the library, and I do not want to start bumping the major version of the lib for any small change that has an unfortunate impact on the ABI.

However I do not want to prevent you from enabling library evolution on your side, and your suggestion is well appreciated 👍 

I will gladly welcome a pull request that:

1. Discusses, pounders and suggests changes.
2. Make it sure (with a test), that GRDB can be built with the library evolution flag (so that people who need it, like you, are always assured they can use `-enable-library-evolution` and `BUILD_LIBRARY_FOR_DISTRIBUTION` in the future).

Don't rush! This work may well impact performances, so you'll have to proceed with caution. It is possible that you stil need to maintain your own fork after this pull request has been merged (but with significantly less divergences from the upstream repository).

I'll help when needed!

**Comment by groue** [comment]
I did not say it clearly enough: this would be a **great** contribution. I and many other people would be very grateful. 💯

**Comment by steipete** [comment]
If I understand the request correctly, you don't need to ship those binaries - it's just good practice to enable BUILD_LIBRARY_FOR_DISTRIBUTION for external dependencies, or at least make sure they compile cleanly with this modification.

[I don't see a way to currently use SwiftPM for that](https://stackoverflow.com/questions/65556536/how-can-i-enable-abi-stability-for-a-swiftpm-package), but you can vendor the files into your own project and then enable Library Evolution - this should work without code modifications (other than removing your `import GRDB` because it's part of your main project now.)

So given that this this works and there's no general way to solve, I opt to close this ticket.

More generally and an advice to @byohay because also ship an SDK with Library Evolution enabled at http://pspdfkit.com/ - you want to have as few dependencies as possible for a module with Library Evolution, and you want to Vendor in any of these dependencies if you can't ditch it. We chose to not bother with SwiftPM for such a setup. (Binary integration with SwiftPM is still buggy and you have a ton of bugs waiting for you once you move to that)

**Comment by byohay** [comment]
@groue thanks for the elaborate answer! I understand at least superficially the effort needed to support library evolution. To tell the truth I didn't have high hopes because I knew what it entails.

The feature we really need is module stability though, but I'm not familiar with the technical details so I don't know if it can exist without library evolution.

**Comment by byohay** [comment]
@steipete not sure I understand, I just don't want to compile GRDB files every time we do a clean build of our projects. Vendoring the files into the projects will still require us to compile them if I understand correctly.

**Comment by steipete** [comment]
You need neither to solve the "we don't wanna recompile every time". Caching systems like Carthage or Buck already have caching logic that you can use. This requires that everyone uses the same Xcode version, but that's fairly easy to enforce inside a company.

Setting this up is quite some work, companies using that usually have a dedicated team just for build management and infra that's larger than your typical app team.
