### ISSUE TITLE
Feature Request: debounce/throttle ValueObservers

### ISSUE THREAD

**Issue by steipete** [groue/GRDB.swift#966]
In my current SwiftUI app, I listen to ~20 different queries in a model that all update the UI. So there's a large list of `@Published` for each value queried. Currently value observers fire immediately, as soon as the database is changed.

Imagine I am running a background-process that imports 50.000 rows in chunks every ~0.05 seconds. This results in the UI being extremely slow, as the value observer fires all the time, resulting in constant UI updates. 

This is neither needed nor wanted; what I am looking for is a "eventual consistent" value observer, that I can configure to debounce. In this example I'd likely set it to 0.3 seconds, so it still feels like the UI is updating in realtime, but the main thread no longer maxes out a CPU core.

Even worse, some value observers trigger on the write queue if they are marked as being non-deterministic, which delays the background import and is another case I absolutely want to avoid.

```swift
ValueObservation
    .trackingConstantRegion(fetchValue) {
		$0.throttle(for: 0.5, latest: false)
	} 
    .publisher(in: dbReader)
    .removeDuplicates()
	...

OR

ValueObservation
    .trackingConstantRegion(fetchValue, frequency: .throttle(0.3))
    .publisher(in: dbReader)
    .removeDuplicates()
	...

// Inside ValueObservation:
enum Frequency {
	case immediate, throttle(NSTimeInterval), debounce(NSTimeInterval)
```

The case with just an enum is likely easier, because what do we do if someone tries a more complex publisher in the block and schedulers also don't quite fit.

Alternative, a publisher that just informs of changes could also work and would allow utmost flexibility to combine different observers for more efficient updating.

[Good overview of throttle vs debounce](https://rhonabwy.com/2019/12/15/combine-throttle-and-debounce/)

**Comment by groue** [comment]
Hello @steipete,

This issue covers a large area, so we'll divide and conquer. Please give me a little time to prepare a few plans, and we'll discuss them.

**Comment by groue** [comment]
Hello again @steipete, I understand why you present this topic as a "debounce/throttle" issue, because, well, your app does not care very much about when the view is refreshed, as long as it is, eventually.

I frankly don't see this topic solved very quickly, even if your issue creates the opportunity to start addressing it. We're talking about back pressure, which is not precisely an easy topic.

But I'd like to help right now, with the current state of GRDB.

Maybe you'll better control database observation with [DatabaseRegionObservation](https://github.com/groue/GRDB.swift#databaseregionobservation). Unlike ValueObservation, which fetches fresh values when a transaction impacts the observed fetches, DatabaseRegionObservation notifies those transactions and does not fetch anything.

The events notified by DatabaseRegionObservation are a good candidate for throttling and debouncing. From those debounced notifications of impactful transactions, you'll be able to fetch:

```swift
// before
ValueObservation
    .tracking { db in ... }
    .publisher(in: dbPool)

// after
DatabaseRegionObservation
    .tracking(Tweet.all(), ...) // All tracked regions
    // All transactions that impact the tracked regions
    .publisher(in: dbPool)
    // Turn database connection into a Void event
    // that means "tracked regions were modified"
    .map { _ in }
    // Perform adequate throttling
    .throttle(...)
    // Insert initial event so that we perform an initial fetch
    .prepend(())
    // Fetch
    .map { 
        dbPool.readPublisher { db in ... }
    }
    .switchToLatest()
```

This is more involved. But it should do what you need.

**Comment by groue** [comment]
The proposed solution is, as far as I know, a correct answer.

I agree it is a lot of boilerplate. Also, it requires specifying the observed region twice (in the `DatabaseRegionObservation` creation, and in the fetching function given to `dbPool.readPublisher`).

Ideally, we'd just write:

```swift
let observation = ValueObservation
    .tracking { db in ... }
    .throttle(...)
```

This is a little tricky to do, because ValueObservation has actually _a lot_ of different behaviors. There are many code paths, depending on whether the observation runs on a DatabaseQueue or a DatabasePool, depending on its [scheduling](https://github.com/groue/GRDB.swift/blob/v5.18.0/README.md#valueobservation-scheduling), and depending on whether it observes a constant region or not (see [Specifying the Region Tracked by ValueObservation](https://github.com/groue/GRDB.swift/blob/v5.18.0/README.md#specifying-the-region-tracked-by-valueobservation) and [ValueObservation.trackingConstantRegion](https://github.com/groue/GRDB.swift/blob/v5.18.0/README.md#valueobservation-performance)).

I did spent some time thinking about this issue, but not enough to find a proper solution.

Keeping an issue open, in this repo, is the sign that somebody is working on it. In this case, it is not really true. So I'm closing this issue, with the "needs revisiting" label. I'd be happy to reopen it when possible.

**Comment by markst** [comment]
Hey! I landed here while trying to figure out if we can debounce `ValueObservation`.

I thought I’d piggyback on this issue instead of creating a new one.

We have a similar scenario where multiple views observe changes in our database through `ValueObservation`. Specifically, we persist the 'Play Progress' for certain episodes in our database table.

Previously, one challenge we faced was that the `ValueObservation` Combine publisher was being created when each view appeared, which led to numerous observers being created in a collection view, as there could be many episodes at once.

To optimize this, we’ve moved towards using a single `ValueObservation` that can be shared across multiple views.

Here's an example where by appending to our media items will recreate our publisher:
```swift
public init(provider: MediaPlayableStateProvider) {
    self.statePublisher = mediaItemsSubject
        .removeDuplicates()
        .flatMapLatest { provider.statePublishers(for: Array($0)) }
        .share(replay: 1)
        .eraseToAnyPublisher()
}
```

While we’re still working on further optimizations, the key question we’re grappling with is:  
**What are the trade-offs of using a `ValueObservation` per episode versus a single `ValueObservation` that observes multiple IDs and filters downstream?**

I’m curious about the performance and resource usage differences between these two approaches.

**Comment by groue** [comment]
Hello @markst,

_Keep your number of observations bounded._ For example, it's a bad idea to create one observation per row in a list. It should work, but I would not expect good performances as the size of the list grows.

For more information, see [ValueObservation Performance](https://swiftpackageindex.com/groue/grdb.swift/v6.29.2/documentation/grdb/valueobservation#ValueObservation-Performance).

See also [ValueObservation Scheduling](https://swiftpackageindex.com/groue/grdb.swift/v6.29.2/documentation/grdb/valueobservation#ValueObservation-Scheduling):

> By default, fresh values are fetched immediately after the database was changed. In particular, modifying the database on the main thread triggers a fetch on the main thread as well. To change this behavior, and guarantee that fresh values are never fetched from the main thread, [...]

**Comment by markst** [comment]
Thanks for response @groue . We've implemented `DatabaseRegionObservation` based on your advice.

I wonder if you have any thoughts about disabling `DatabaseRegionObservation` whilst app is in background?
Or would it be best to observe background mode and then recreate `DatabaseRegionObservation` when app is active?

**Comment by groue** [comment]
Hi @markst. Please next time ask this question in a new issue or discussion, because it is unrelated to the main topic (debounce/throttle). Questions and answers that are out of reach for other GRDB users are akin to private conversations, which are not included in the free support that is generously provided here.

To answer your question: if your app wants to disable observations whilst app is in background, this looks like something that is specific to your app. Your code can indeed observe app state and manage observations at will.

**Comment by markst** [comment]
Apologies; thought I was going to get in trouble if I made an issue!!
