### ISSUE TITLE
NSDate and NSDateComponents format

### ISSUE THREAD

**Issue by cfilipov** [groue/GRDB.swift#97]
Regarding the [Date and NSDateComponents](https://github.com/groue/GRDB.swift#nsdate-and-nsdatecomponents) section:

Is there a reason you selected the "YYYY-MM-DD HH:MM:SS.SSS" format as the default for inserting dates? I would have expected "YYYY-MM-DDTHH:MM:SS.SSSZ" to be more appropriate (inclusion of "T" and "Z"), since it's a more commonly used format. And generally, I think it's good practice to be explicit about time zone by either denoting it with "Z" or an offset. Would you be open to making `storageDateFormatter` a settable property somewhere to allow the user to override this without needing to create a custom value type for Date?

**Comment by groue** [comment]
Hello @cfilipov 

> Is there a reason you selected the "YYYY-MM-DD HH:MM:SS.SSS" format as the default for inserting dates?

In the UTC time zone. Yes, there is a reason. It's the one and only format that is:

- Comparable (`ORDER BY date` works)
- Comparable with the SQLite keyword `NOW` (`WHERE date > NOW` works)
- Able to feed SQLite date & time functions
- Precise enough

See https://www.sqlite.org/lang_datefunc.html for details.

> I would have expected "YYYY-MM-DDTHH:MM:SS.SSSZ" to be more appropriate (inclusion of "T" and "Z"), since it's a more commonly used format. And generally, I think it's good practice to be explicit about time zone by either denoting it with "Z" or an offset.

"YYYY-MM-DDTHH:MM:SS.SSSZ" is the ISO8601 format with time zone, a quite common interchange format indeed. It does not fit the requirements listed above, and this is why it has not been chosen.

There are two important keywords above: **time zone**, and **interchange**.

Let's start with interchange: it would have been surely handy if dates where stored as ISO8601 with time zone: one would just have to load the string representation in a date column, feed a JSON dictionary, and call it a day. But well, SQLite is not designed for interchange, it is designed for *storage*. This is an unfair trial :-)

Next, time zones. There is no support whatsoever for even the slightest notion of time zones in SQL, generally. Some databases support time zones ([PostgresSQL](https://www.postgresql.org/docs/current/static/datatype-datetime.html), for example), but I do wonder how well (or bad) they deal with the naturally evolving landscape of time zones that go beyond the trivial shifts like UTC+1. The [time zone database](https://www.iana.org/time-zones) was last updated one month ago, mind you :-)

Yet, we Swift and Objective-C programmers are pretty lucky, because our NSDate is documented as "encapsulat[ing] a single point in time, independent of any particular calendrical system or time zone." This means that the time-zone-free format of SQLite dates perfectly fits NSDate (when we assume the UTC time zone).

It also means that the time-zone-free format of SQLite dates perfectly fits NSDateComponents as well (when we don't want to assume any time zone, and can't use NSDate).

In another way: should SQLite support storing dates with time zones, we poor Swift developers would *lack* a value type that would encapsulate the full information.

All in all, we're in pretty good shape, despite the lack of time zones in SQLite.

> Would you be open to making storageDateFormatter a settable property somewhere to allow the user to override this without needing to create a custom value type for Date?

For all the reasons above, I'm strongly reluctant. People shoot themselves in the foot much too much easily.

**Comment by cfilipov** [comment]
> - Able to feed SQLite date & time functions
> - Comparable (ORDER BY date works)

This is true for every one of the date/time formats in your matrix (at least all the ones that include dates, I haven't tried with the time-only formats).

> - Precise enough

This is true for "YYYY-MM-DDTHH:MM:SS.SSS" and "YYYY-MM-DDTHH:MM:SS.SSSZ" as well.

> - Comparable with the SQLite keyword NOW (WHERE date > NOW works)

OK, this is a good reason. I never used "NOW" before, because I would typically init an `NSDate`, but if you were to do it directly in SQL this would be a big convenience. 

> "YYYY-MM-DDTHH:MM:SS.SSSZ" is the ISO8601 format with time zone, a quite common interchange format indeed. It does not fit the requirements listed above, and this is why it has not been chosen.

See my previous statements. Unless I'm missing something, this format is indeed comparable, all the SQLite date functions support it and it's just as precise. This is the format I have been using for some time.

All of the formats you listed are actually valid ISO 8601 date time formats. SQLite docs explicitly state this is the standard by which their date and time functions are based (though they only support a subset of it). So yes, it is an interchange format, and SQLite happened to choose this interchange format for their date/time support. 

My questions was: because there are several ways to format within this interchange standard, why did you choose that specific one as the default for writing. I think only your second bullet point is valid, but it's also a good enough reason on it's own so I'll use the format you suggest.

**Comment by groue** [comment]
> > - Comparable with the SQLite keyword NOW (WHERE date > NOW works)
> 
> OK, this is a good reason. I never used "NOW" before, because I would typically init an `NSDate`, but if you were to do it directly in SQL this would be a big convenience. 

Yes, I like to sweat details.

> My questions was: because there are several ways to format within this interchange standard, why did you choose that specific one as the default for writing. I think only your second bullet point is valid, but it's also a good enough reason on it's own so I'll use the format you suggest.

You're right, comparison with `now` was the final discriminant criteria. And as I see SQLite as a storage engine, not a network serialization tool, I had no trouble whatsoever ditching away the `T` and the `Z`, so that GRDB would remain a faithful SQLite companion.

**Comment by DamienPetrilli** [comment]
> See https://www.sqlite.org/lang_datefunc.html for details.

Hello!

I know this thread is very old but I have potentially the same need (storing the date in iso8601 for easier reading / debugging). I checked the link and couldn't find any limitation about storing the date in iso8601 format. They all seem to be equivalent.

> Formats 2 through 10 may be optionally followed by a timezone indicator of the form "[+-]HH:MM" or just "Z". The date and time functions use UTC or "zulu" time internally, and so the "Z" suffix is a no-op. Any non-zero "HH:MM" suffix is subtracted from the indicated date and time in order to compute zulu time. For example, all of the following time values are equivalent:
>
> 2013-10-07 08:23:19.120
2013-10-07T08:23:19.120Z
2013-10-07 04:23:19.120-04:00
2456572.84952685

The Modifiers sections in the link seems to describe some limitations but none are about the 8601 format. It's about special modifiers.

Are the limitations regarding iso8601 still valid? (7y later)

PS: 
- I tried to find the 2016 version in the revision history of the page but it goes only back to 2020-02-10. 
- I checked the changelog of SQLite and there is no mention of ISO 8601 since 2005 (but date and time functions have been improved multiple times since 2017)

May be this improvement changed everything?

https://www.sqlite.org/deterministic.html#dtexception

> Prior to SQLite 3.20.0 (2017-08-01) all date/time functions were always considered non-deterministic. The ability for date/time functions to be deterministic sometimes and non-deterministic at other times, depending on their arguments, was added for the **3.20.0 release**.

3.20.0 release notes
> The built-in [date and time functions](https://www.sqlite.org/lang_datefunc.html) have been enhanced so that they can be used in [CHECK constraints](https://www.sqlite.org/lang_createtable.html#ckconst), in [indexes on expressions](https://www.sqlite.org/expridx.html), and in the WHERE clauses of [partial indexes](https://www.sqlite.org/partialindex.html), provided that they do not use the 'now', 'localtime', or 'utc' keywords.

**Comment by groue** [comment]
Hello @DamienPetrilli.

> I have potentially the same need (storing the date in iso8601 for easier reading / debugging). 

Record types that conform to `Codable` can specify how their dates are encoded (see [Date and UUID Coding Strategies](https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-uuid-coding-strategies)):

```swift
struct Player: Codable, FetchableRecord, PersistableRecord, Identifiable {
    // Encodes and decodes `2023-02-15T08:14:54Z`
    // See other strategies for more options.
    static let databaseDateDecodingStrategy = DatabaseDateDecodingStrategy.iso8601
    static let databaseDateEncodingStrategy = DatabaseDateEncodingStrategy.iso8601
    var registrationDate: Date
}
```

When you don't use Codable, and for dates in query interface requests, you still have to perform manual date encoding and decoding - otherwise the default `YYYY-MM-DD HH:MM:SS.SSS` format applies:

```swift
let date: Date
let iso8601Date = formatter.string(from: date)
let request = Player.filter(Column("registrationDate") >= iso8601Date)
```

For the rationale behind the choice of `YYYY-MM-DD HH:MM:SS.SSS` as the default date format, see [Date](https://github.com/groue/GRDB.swift/blob/master/README.md#date).

Do you have other questions?

**Comment by DamienPetrilli** [comment]
Hello,

thanks for the reply. Yes, I already identify those changes but then I found this article stating that there were some limitations when you stored the data as iso8601 strings (cf below). Which is why I double checked if they were still valid.

So I guess the following is still true?

> In the UTC time zone. Yes, there is a reason. It's the one and only format that is:
> 
> Comparable (ORDER BY date works)
Comparable with the SQLite keyword NOW (WHERE date > NOW works)
Able to feed SQLite date & time functions
Precise enough

**Comment by groue** [comment]
This is still true, but there is a typo: read `CURRENT_TIMESTAMP` instead of `NOW`.

SQLite evaluates `CURRENT_TIMESTAMP` to a date string with a space character instead of a `T` between the date and the time. The default date format of GRDB is the same (with extra millisecond precision though), and allows users to perform comparisons with `CURRENT_TIMESTAMP`.

I tend to distinguish *storage formats* (whatever the database engine fosters) from 
*transport formats* (whatever the server api spec requires), and I do not try to merge them together. SQLite picked a format which is not ISO-8601, and added some support for ISO-8601 eventually. But ISO-8601 is not the preferred SQLite date format.
