### ISSUE TITLE
create temporary table not work

### ISSUE THREAD

**Issue by chunxige** [groue/GRDB.swift#978]
**GRDB version:**
 5.4.0
 
**Platform(s) running GRDB:** 
iOS

 `try dbPool.write { db in
                try db.create(table: "msPersonTagModel", temporary: true, body: { (tb) in
                    tb.column(MSPersonTagModel.CodingKeys.id.rawValue, .integer)
                    tb.column(MSPersonTagModel.CodingKeys.value.rawValue, .text)
                    tb.column(MSPersonTagModel.CodingKeys.isFilterApt.rawValue, .boolean)
                    tb.column(MSPersonTagModel.CodingKeys.isFilterAirline.rawValue, .boolean)
                })
            }

// next when i want to fetch datas ,it catch the error
var models: [MSPersonTagModel] = []
        do {
            models = try dbWriter.read { (db) in
                try MSPersonTagModel.fetchAll(db)
            }
        } catch {
            printLog("MSPersonTagModel 数据库里获取失败：\(error)")
        }

MSPersonTagModel 数据库里获取失败：SQLite error 1: no such table: msPersonTagModel - while executing `SELECT * FROM 

`

**Comment by groue** [comment]
Hello @chunxige,

A DatabasePool uses several SQLite connections: one for writes, and other ones for reads. This is how it can perform concurrent writes and reads.

A temporary table only exists in the SQLite connection it was created in. Other connections can not see it.

Since you created your temporary table in the writer connection, you can not access it from reader connections.

**Comment by groue** [comment]
I'm closing this issue since the reason for the error you see is fully described. Please reopen if you have further questions.
