### ISSUE TITLE
Fatal error: table has no unique index on column(s) score

### ISSUE THREAD

**Issue by garg204** [groue/GRDB.swift#982]
Thanks for the library.

Executing a fetch statement throws the following fatalError:
Fatal error: table player has no unique index on column(s) score

basically in my model both name and score are not unique. And I want to keep support to method passing filter keys from outside. It is 2 keys today "score" and "name", it can be variable number of filters. when I tried to run it . I am not sure what I am doing wrong and how can i achieve functionality to add multiple variable number of columns filter

func fetchAll(key: [String : GRDB.DatabaseValueConvertible?]?) {
 try? dbQueue?.read { db in
         let player =  try? Player.filter(key: key).fetchAll(db)
        print(player)
  }
}

fetchAll(key: ["score" : 100, "name": "Ankit"])

My model

struct Player: Codable, FetchableRecord, PersistableRecord {
    var id: Int64
    var name: String
    var score: Int
}

Environment
GRDB flavor(s): GRDB
GRDB version: 5.8.0
Installation method: Cocoapods
Xcode version: 12.2
Swift version: 5
Platform(s) running GRDB: iOS
macOS version running Xcode: 14.1

**Comment by groue** [comment]
Hello @garg204,

The work **key** has a very specific meaning in relational databases: a **key** must identify a single row in a table.

This is why GRDB ships with a `fetchOne(_:key:)` method which returns an optional: either the row for the given key exists, or not.

And this is why there is no `fetchAll(_:key:)` method which returns an array. No one expects that one key matches several rows.

The `filter(key:)` method is based on the same premise: it accepts a **key**.

Several kinds of key exist. There are primary keys, and secondary keys. Keys can be made of one single column, or several columns. A key is such an important concept in the relational model that RDBMS make sure no table contains two rows with the same key. Such **constraints** are expressed when the database table is created.

In the example below, the player table has three keys:

- A primary key `id`
- A secondary key `email`: no two players can share the same email
- A secondary key (`teamName`, `position`): there are never two players at the same position in a given team

```swift
try db.create(table: "player") { t in
    t.autoIncrementedPrimaryKey("id")
    t.column("score", .integer)
    t.column("name", .text)
    t.column("email", .text).unique()
    t.column("teamName", .text)
    t.column("position", .integer)
    t.uniqueKey(["teamName", "position"])
}
```

The GRDB methods that accept a key make sure that the database schema has a matching primary or secondary key, defined at the database level, in order to make sure your code does what it says it does. What would the code below do, if there are several players named "Ankit" with the score 100? Which one is picked? A random one? The one you expect? Or another one (a bug)?

```swift
if let player = try Player.fetchOne(key: ["score" : 100, "name": "Ankit"]) {
    // Use player
}
```

This is why you get this fatal error. It is a programmer error to tell GRDB that you use a (score, name) **key** when those columns are not a key (primary or secondary) in the database schema. It is a programmer error because such code would prevent programmers who know what a **key** is from understanding such code.

The fix is to add a unique index on the (score, name) columns, or to avoid using `key` for this pair:

```swift
let players = try Player
    .filter(Column("name") == "Ankil)
    .filter(Column("score") == 100)
    .fetchAll(db)
```

Your method could be written as:

```swift
extension Player {
    static func fetchAll(_ db: Database, columns: [String : GRDB.DatabaseValueConvertible?]) throws -> [Player] {
        var request = Player.all()
        for (key, value) in columns {
            request = request.filter(Column(key) == value)
        }
        return request.fetchAll(db)
    }
}

// All players named "Ankit" with score 100:
let players = try dbQueue.read { db in
    try Player.fetchAll(db, columns: ["score" : 100, "name": "Ankit"])
}
```

**Comment by garg204** [comment]
Hey @groue very nice explanation.  Thank you for clearing doubt!!

**Comment by groue** [comment]
You're welcome! Happy SQLite and GRDB!

**Comment by garg204** [comment]
Hey @groue I have one more doubt not related to above crash. Let's assume I am creating table first time. Should I need to run migration as well or not required for creating table first time.

Thanks in advance!!

**Comment by groue** [comment]
> Let's assume I am creating table first time. Should I need to run migration as well or not required for creating table first time.

If you use a DatabaseMigrator, then the recommended practice it to always run the migrator when the app boots. The object which is responsible for running a migration once and only once is the migrator. Applied migrations will not be run again. As your app evolves, and its database schema needs adjustments, add new migrations: they will run once, and only once. You never have to check if a table exists, or to use the `ifNotExists` modifier when you use a migrator.

Of course, if your database schema was defined *before* you started using a migrator, then the migrator has to be ready for both an empty schema, and a pre-populated database. Only then you have to worry about dealing with existing stuff.

But when you use a migrator from scratch, then you never have to think about this. Just define migrations, run your migrator, and you're good to go.

**Comment by garg204** [comment]
Thank you @groue  for clarifying. I have one more doubt. My model is like below.

struct Player: Codable, FetchableRecord, PersistableRecord {
    var id: Int64
    var name: String
    var score: Int
    var sentAt: Date = Date()
}

And I created a database schema like this 

      try? dbQueue?.write { db in
            try? db.create(table: "player") { table in
                table.autoIncrementedPrimaryKey("id")
                table.column("name", .text).notNull()
                table.column("score", .integer).notNull()
                table.column("sentAt", .datetime)
            }
        }

I got crash while writing value  "Fatal error: 'try!' expression unexpectedly raised an error: could not decode Date from database value". Can you suggest what I am doing wrong

**Comment by groue** [comment]
> I got crash while writing value "Fatal error: 'try!' expression unexpectedly raised an error: could not decode Date from database value". Can you suggest what I am doing wrong

Sure. Do not truncate the error message. It tells you which value was found in the database, and could not be decoded as a date.

Your fix is to fix the content of the database, or to stop decoding `Date`. Read https://github.com/groue/GRDB.swift/blob/master/README.md#date-and-datecomponents for more information about date support in GRDB.

> I have one more doubt.

Please stop adding comments in this issue which are not related to the title "Fatal error: table has no unique index...". This does not help users who look for **focused answers**. This does not help users who **search before asking**. Thank you.
