### ISSUE TITLE
GRDB doesn't compile with Xcode 13 beta 1

### ISSUE THREAD

**Issue by meeloo** [groue/GRDB.swift#984]
We use GRDB from the main branch with SPM. Upgrading to Xcode 13 beta 1 gives us the following error:
/Users/seb/build/Beam-eoqcbhvhucvnvceedotxvuevvuli/SourcePackages/checkouts/GRDB.swift/GRDB/Core/Database.swift:1602:10: Enum cases with associated values cannot be marked potentially unavailable with '@available'

**Comment by groue** [comment]
Hello @meeloo,

Thanks for reporting the issue, and welcome to the beta!

Users of Xcode 13 beta should use the [development](https://github.com/groue/GRDB.swift/tree/development) branch of GRDB.

This branch currently contains GRDB 5.8.0, plus the fix for the error you've seen.

It will also contain all future changes until the release of GRDB 5.9.0.

**Comment by meeloo** [comment]
Awesome, thanks!

**Comment by groue** [comment]
you're welcome, happy GRDB!

I'll keep this issue open as long as it is useful

**Comment by mhrakoto999** [comment]
Hi all,
GRDB 5.8.0 now compiles with Xcode 13 beta 4 !

**Comment by ManheimGreen** [comment]
Gwendal, hello again. GRDB is as excellent as ever. I return again to these remarkable cyberspaces to report that while manually-incorporated GRDB builds perfectly, manually-incorporated GRDBCustom does not build, with, on macOS 12 (beta 4) and Xcode 13 (beta 4), the following fatal error:

```
/Users/…/SQLiteCustom/src/configure:1:1: C compiler cannot create executables
```

Further, this fatal error further causes the following fatal error:

```
/Users/.../SQLiteCustom/GRDB.h:10:9: 'GRDB/sqlite3.h' file not found
```

...And of its attendant errors.

This issue is perfectly reproducible in a fresh project with GRDB (`GRDBCustom.xcodeproj`) incorporated according to the instructions found at [Custom SQLite Builds](https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md).

I would do more research into this, but my knowledge of the Xcode build process is essentially bupkis — almost literally nonexistent — and I would have no idea where even to begin. Hopefully this helps you, and do let me know if you need more information that I have errantly excluded.

**Comment by Patrik-svobodik** [comment]
Not sure if this is related but Profiling (and likely release) builds fail in 13b4 (build errors are classified under the GRDB tab)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25883885/128333996-362c2faf-3874-44b6-9088-56c3d92be01b.png">

**Comment by groue** [comment]
Beta 1 is no longer relevant
