### ISSUE TITLE
Reading from FileWrappers and Data

### ISSUE THREAD

**Issue by emorydunn** [groue/GRDB.swift#986]
I'm working on an app (now SwiftUI), but previously AppKit which uses package documents to store data. The Document API provides a FileWrapper with the contents of the document, which is great for `Codable`, however doesn't work so well for GRDB which needs a file path to open a database. 

I'm using the same basic logic as was suggested in #374, copying the data from the FileWrapper to a temp location and using that as the path for the database to either open directly or source to backup into an in-memory database. 

I'm wondering if it's possible to add support for opening an in-memory database from a `Data` object, removing the need to copy the database so many times when reading and writing to/from a FileWrapper. Especially with SwiftUI's Document types only providing FileWrappers for serialization it would be incredibly useful. 

Thank you in advance and for all the work that's gone into GRDB

**Comment by groue** [comment]
Hello @emorydunn,

I agree there are a lot of copies, and I'll trust you when you say SwiftUI makes it worse.
 
> I'm wondering if it's possible to add support for opening an in-memory database from a `Data` object.

SQLite does not describe anything directly related in https://www.sqlite.org/c3ref/open.html

Maybe a custom [VFS](https://www.sqlite.org/vfs.html) could help, but I've never played with such a low-level interface yet.

**Comment by emorydunn** [comment]
Using a VFS is way over my head, and probably more complex than opening documents really requires. Out of curiosity, if I submitted a PR with an init to handle the copy and backup, is that something you might consider adding, or do you feel it's best left as a user implementation?

**Comment by groue** [comment]
I guess I will, because good ideas are warmly welcomed. But you did not quite say what you have in mind, or I was not quite able to read between the lines. It looks like you have something simple in your head, a convenience api.

Maybe you could show a before/after, an example that truly reveals the advantages of your idea?

**Comment by emorydunn** [comment]
I thinking something along the lines of the two examples. One would create a in-memory database and the other would open a database from disk. 

```swift
extension DatabaseQueue {
    
    /// Opens an in-memory SQLite database.
    ///
    /// The contents of the FileWrapper are copied to a temporary location and then copied into the in-memory database.
    /// - Parameters:
    ///   - fileWrapper: A regular-file file wrapper
    ///   - tempFilename: The name of the temporary database file.
    convenience init(fileWrapper: FileWrapper, tempFilename: String) throws {
        self.init()
        
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(tempFilename)
        
        // Create a temp database
        try fileWrapper.write(to: tempURL, options: .atomic, originalContentsURL: nil)
        let source = try DatabaseQueue(path: tempURL.path)
        
        try source.backup(to: self)
    }
    
    /// Copies the contents of the FileWrapper and opens a database at the specified URL.
    ///
    /// The contents of the FileWrapper are copied to the specified location and then opened in-place. 
    /// - Parameters:
    ///   - fileWrapper: A regular-file file wrapper.
    ///   - tempFilename: The location to copy the file contents before opening.
    convenience init(fileWrapper: FileWrapper, tempURL: URL) throws {
        // Create a temp database
        try fileWrapper.write(to: tempURL, options: .atomic, originalContentsURL: nil)
        try self.init(path: tempURL.path)
    }
}
```

**Comment by groue** [comment]
Thank you @emorydunn!

All in all, I really appreciate your efforts, explorations, and work in progress. There are a few details that are worth addressing:

- Why the hard-coded path to `FileManager.default.temporaryDirectory` - could some users prefer another location?
- Why the `tempFilename` argument? If the goal is to use a unique name, then why not generate one? Indeed, what if there already exists a temporary file with the same name?
- Why a `tempFilename` here, and a `tempURL` there?
- What about users who prefer to use a scratch `DatabasePool` on disk, instead of a `DatabaseQueue`, so that they profit from the WAL mode, and enhanced multi-threaded database access?

All those questions make me think that there are just too many possible variations and tricky cases to handle. The best way to help users who have to deal with `FileWrapper` is sample code, not convenience initializers.

Eventually, I'd very favorably welcome a "How to use GRDB with FileWrapper" **tutorial** that describes a robust and simple scenario that users can extend would be the best way to help users who have to deal with `FileWrapper`.

This tutorial, based on your actual experience, would be a great contribution!

**Comment by emorydunn** [comment]
Those are all good questions, and while I can answer them for my own use case, I think you're right that there might be too many variations to do cleanly. 

I'd be happy to work on a tutorial and some sample code for working with FileWrappers and documents. 

Thank you so much for you help. I'll close this issue and open a PR when I have something ready for you to review.

**Comment by groue** [comment]
Thank you very much @emorydunn 👍
