### ISSUE TITLE
Feature Request: Avoid JSONRequiredError

### ISSUE THREAD

**Issue by pakko972** [groue/GRDB.swift#994]
The default Decodable support uses `JSONRequiredError` as marker errors that trigger JSON decoding.

It works, but the problem is that when one asks Xcode to breakpoint on Swift errors, one's life is miserable.

Can we avoid this? Maybe perform the decoding directly instead of throwing?

**Comment by groue** [comment]
Hello @pakko972,

The request is quite reasonable. Unfortunately, it is not possible to do it.

Foundation provides JSON support via `JSONEncoder` and `JSONDecoder` which are not encoders and decoders, but `TopLevelEncoder` and `TopLevelDecoder`.

Because of that, GRDB can not gracefully "switch" to JSON decoding/encoding _right in the middle_ of the decoding/encoding process. `JSONRequiredError`, on the other hand, allows to _fail and retry_.
