### ISSUE TITLE
Combine + MVVM help

### ISSUE THREAD

**Issue by GutteApps** [groue/GRDB.swift#996]
First, thank you for this wonderful and well documented package. 

### What did you do?

I'm implementing GRDB in my SwiftUI project. I like the  @Query properties used  in the demo application and wanted to use them in my project. However, my project is following the MVVM pattern and my models are referenced on view models which are observable class objects.  

Tried to change the demo project to look more like my project with the following (simplified)

```
class AppVM: ObservableObject {
    @Query(PlayerRequest(ordering: .byScore)) var players: [Player]
}

struct AppView: View {
    @StateObject var vm = AppVM()
    
    var body: some View {
            PlayerList(players: vm.players)
    }
}

@propertyWrapper
struct Query<Query: Queryable>: DynamicProperty {
    @Environment(\.appDatabase?.databaseReader) private var databaseReader: DatabaseReader?
    @StateObject private var core = Core()
    private var baseQuery: Query
    
    var wrappedValue: Query.Value {
        core.value ?? Query.defaultValue // error: Accessing StateObject's object without being installed on a View. This will create a new instance each time.
    }
    .
    .
   }
```

The players list is not populated and Im getting the following error: Accessing StateObject's object without being installed on a View. This will create a new instance each time.

I'v also tried making the **Core** object a singleton as suggested by some resources without success

**GRDB flavor(s):** GRDB
**GRDB version:**5.8.0
**Installation method:** SPM
**Xcode version:**12.5
**Swift version:** 5
**Platform(s) running GRDB:** iOS
**macOS version running Xcode:** 11.2

**Comment by groue** [comment]
Hello @GutteApps,

I'm not sure the `@Query` property wrapper that ships in the demo app can be used in a MVVM application.

This `Query` type is defined as a [DynamicProperty](https://developer.apple.com/documentation/swiftui/dynamicproperty), which is, quoting the doc: "an interface for a stored variable that updates an external property of a view." I won't say this sentence is crystal clear, but what _is_ clear is that dynamic properties are intended to be embedded in _views_.

When you embed such a `DynamicProperty` in an object that is not a SwiftUI View, such as your view model `AppVM`, I do not expect SwiftUI to auto-magically calls its `DynamicProperty.update()` method, and generally to make it work.

I think the error you see is just a consequence of this misuse

It's hard to blame you: the `@Query` demo code, which uses a `DynamicProperty`, a core `@StateObject`, and relies on their subtle integration with SwiftUI views and environment in order to work, is really not easy to grasp. See [Core Data and SwiftUI](https://davedelong.com/blog/2021/04/03/core-data-and-swiftui/) for the original inspiration.

---

Consider `@Query`, as it ships in the demo app, as a way to directly embed the database inside the views. In a way, it is an "anti-MVVM" tool ;-) Convenient, identical in spirit to the ready-made `@FetchRequest` property wrapper from Core Data, but against the strict separation of concerns that comes with MVVM.

Consider that the `DynamicProperty` and its inner `@StateObject` make it possible for a view to define its behavior *right from its own guts*, with an inner `@Query` property. The lifetime of the object instances that track the state of the view is fully managed by SwiftUI. SwiftUI decides when those objects are instantiated, and SwiftUI decides when they are deinited.

MVVM is quite different: it wants a view to be managed by some external object, its view model (usually an `ObservableObject` indeed). The lifetime management of the view model is *different*. It is usually NOT created by the view, NOT created by SwiftUI. It is created by your code, and explicitly given to the view: `PlayerList(viewModel: ...)` (or a variant of this pattern).

---

My advice is thus not to use `@Query` in your MVVM app, think twice before using `DynamicProperty` and `@StateObject` for implementing MVVM view models, and train yourself building MVVM SwiftUI apps without even thinking of GRDB at this stage.

When you feel better with MVVM in SwiftUI, it will be easy to feed your view models with a [GRDB Combine publisher](https://github.com/groue/GRDB.swift/blob/master/Documentation/Combine.md).

**Comment by groue** [comment]
Yeah, SwiftUI is _really hard_ when we want to apply "classical" architectural patterns 😅 Maybe we need to adapt a little bit.

A popular architectural framework of present days is [TCA](https://github.com/pointfreeco/swift-composable-architecture). I've never used it myself. It looks _very strict_. Maybe you'll feel at ease in this environment.

**Comment by GutteApps** [comment]
Thanks. I'm already feeling quite comfortable with SwiftUI and MVVM and I'm at the point where my project requires a db. I'll try the GRDB Combine publisher. TCA looks like it was heavily inspired by Redux which I always thought to be an overkill :)

**Comment by groue** [comment]
OK. I hope I didn't sound offensive by doubting your skills. So... yes : using plain good GRDB publishers should give you the most simple solution.

If some pattern emerges in your app, come back discuss what you have learned, it will help other users :-)
